### ISSUE TITLE
Fitur: Menambahkan fasilitas detai atau edit atau hapus pada penerima/sasaran program bantuan

### ISSUE THREAD

**Issue by Agus-Heriyanto** [eddieridwan/OpenSID#105]
![tampilan asli program](https://cloud.githubusercontent.com/assets/21340215/18094877/9efcbd34-6f07-11e6-9db2-0c1f11657e87.jpg)
![tambahan edit data program](https://cloud.githubusercontent.com/assets/21340215/18094887/b22a9f7a-6f07-11e6-8311-7bd37d74b7ab.jpg)

Tujuannya agar disaat ada kekeliruan input data bisa diganti atau dihapus karena fasilitas itu belum tersedia di menu bantuan yang fokus pada kolom penerima atau sasaran program.

**Comment by afri18** [comment]
gambarannya seperti input anggota keluarga dari data penduduk yg sudah di input, lebih aman, kalau menu edit mungkin hapus peserta aja, biasanya karna mati, pindah atau sudah tidak layak, seperti bantuan KIP > karna anak sekolahnya sudah tamat

**Comment by Agus-Heriyanto** [comment]
Ya mungkin perintah hapus aja agar bisa memperbaiki jika ada kelebihan data.

**Comment by eddieridwan** [comment]
Sudah ditambahkan fitur untuk hapus penerima sasaran program bantuan.

**Comment by afri18** [comment]
saya masih bingung, kenapa di program bantuan sasaran keluarga make data penduduk cigelam yg ada di sid awal nggak bisa ya ? apa saja data yg mesti diisi di opensid, mau pindah terganjal ini, saat disalin data saja nggak ada eror
kalau make data opensid atau import data bisa
