### ISSUE TITLE
Fitur: Tombol share artikel ke facebook sebaiknya mengikut sertakan gambar

### ISSUE THREAD

**Issue by eddieridwan** [eddieridwan/OpenSID#113]
Saat ini, tombol share artikel ke facebook biasanya tidak mengikutsertakan gambar. Kadang2 gambar diikutsertakan, tetapi tidak jelas dari mana gambar itu diperoleh.

Enaknya gambar yang diikutsertakan bisa ditentukan.

**Comment by eddieridwan** [comment]
Halaman harus ditambah Open Graph meta tag, seperti berikut:

```
    <meta property="og:title" content="The Rock"/>
    <meta property="og:type" content="movie"/>
    <meta property="og:url" content="http://www.imdb.com/title/tt0117500/"/>
    <meta property="og:image" content="http://ia.media-imdb.com/rock.jpg"/>
    <meta property="og:site_name" content="IMDb"/>
    <meta property="fb:admins" content="USER_ID"/>
    <meta property="og:description"
          content="A group of U.S. Marines, under command of
                   a renegade general, take over Alcatraz and
                   threaten San Francisco Bay with biological
                   weapons."/>
```

Pada pertama kali di-share Facebook akan crawl halaman itu untuk membaca meta tag di atas, untuk menentukan penampilan share dialog.

Untuk memaksa Facebook mengulangi crawl, bisa masukkan url di https://developers.facebook.com/tools/debug/sharing/batch/.

**Comment by eddieridwan** [comment]
Meta tag sebagaimana ditunjukkan di atas perlu dimasukkan di bagian awal HTML, di file views/layouts/header.php.

Ini akan memerlukan perombakan dalam cara menampilkan artikel, dengan mengirimkan parameter pada waktu menampilkan views/layout/header.php.

**Comment by eddieridwan** [comment]
https://developers.facebook.com/docs/sharing/best-practices
http://stackoverflow.com/questions/22652041/how-to-pass-parameter-like-title-summary-and-image-in-facebook-sharer-url
https://developers.facebook.com/docs/sharing/reference/share-dialog

**Comment by afri18** [comment]
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN" "http://www.w3.org/TR/html4/frameset.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title><?php echo unpenetration($single_artikel["judul"]);?> Website Desa <?php echo unpenetration($desa['nama_desa']);?></title>
		<meta content="utf-8" http-equiv="encoding">
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta property="article:publisher" content="https://goo.gl/TFPGjZ" />
        <meta property="article:author" content="https://goo.gl/TFPGjZ" />
        <meta property="og:site_name" content="<?php echo unpenetration($desa['nama_desa']);?>"/>
        <meta property="og:title" content="<?php echo unpenetration($single_artikel["judul"]);?>"/>
        <meta itemprop="name" content="<?php echo unpenetration($single_artikel["judul"]);?>"/>
        <meta name="twitter:title" content="<?php echo unpenetration($single_artikel["judul"]);?>"/>
        <link rel="canonical" href="<?php echo base_url()?>index.php/first/artikel/<?php echo unpenetration($single_artikel['id']);?>"/>
        <meta property="og:url" content="<?php echo base_url()?>index.php/first/artikel/<?php echo unpenetration($single_artikel['id']);?>"/>
        <meta property="og:type" content="article"/>
        <meta property="og:image" content="<?php echo base_url()?>assets/files/artikel/sedang_<?php echo unpenetration($single_artikel['gambar']);?>"/>
        <meta itemprop="image" content="<?php echo base_url()?>assets/files/artikel/sedang_<?php echo unpenetration($single_artikel['gambar']);?>"/>
        <meta name="twitter:image:src" content="<?php echo base_url()?>assets/files/artikel/sedang_<?php echo unpenetration($single_artikel['gambar']);?>"/>
        <meta name="twitter:card" content="summary_large_image"/>        
		<link rel="shortcut icon" href="<?php echo base_url()?>favicon.ico" />
		<link type='text/css' href="<?php echo base_url()?>assets/front/css/first.css" rel='Stylesheet' />
		<link type='text/css' href="<?php echo base_url()?>assets/css/font-awesome.min.css" rel='Stylesheet' />
		<link type='text/css' href="<?php echo base_url()?>assets/css/ui-buttons.css" rel='Stylesheet' />
		<link type='text/css' href="<?php echo base_url()?>assets/front/css/colorbox.css" rel='Stylesheet' />
		<script src="<?php echo base_url()?>assets/front/js/stscode.js"></script>
		<script src="<?php echo base_url()?>assets/front/js/jquery.js"></script>
		<script src="<?php echo base_url()?>assets/front/js/layout.js"></script>
		<script src="<?php echo base_url()?>assets/front/js/jquery.colorbox.js"></script>
		<script>

			$(document).ready(function(){
				$(".group2").colorbox({rel:'group2', transition:"fade"});
				$(".group3").colorbox({rel:'group3', transition:"fade"});
			});
		</script>
	</head>
	<body>

<script type='text/javascript'>
//<![CDATA[
shortcut={all_shortcuts:{},add:function(a,b,c){var d={type:"keydown",propagate:!1,disable_in_input:!1,target:document,keycode:!1};if(c)for(var e in d)"undefined"==typeof c[e]&&(c[e]=d[e]);else c=d;d=c.target,"string"==typeof c.target&&(d=document.getElementById(c.target)),a=a.toLowerCase(),e=function(d){d=d||window.event;if(c.disable_in_input){var e;d.target?e=d.target:d.srcElement&&(e=d.srcElement),3==e.nodeType&&(e=e.parentNode);if("INPUT"==e.tagName||"TEXTAREA"==e.tagName)return}d.keyCode?code=d.keyCode:d.which&&(code=d.which),e=String.fromCharCode(code).toLowerCase(),188==code&&(e=","),190==code&&(e=".");var f=a.split("+"),g=0,h={"`":"~",1:"!",2:"@",3:"#",4:"$",5:"%",6:"^",7:"&",8:"*",9:"(",0:")","-":"_","=":"+",";":":","'":'"',",":"<",".":">","/":"?","\\":"|"},i={esc:27,escape:27,tab:9,space:32,"return":13,enter:13,backspace:8,scrolllock:145,scroll_lock:145,scroll:145,capslock:20,caps_lock:20,caps:20,numlock:144,num_lock:144,num:144,pause:19,"break":19,insert:45,home:36,"delete":46,end:35,pageup:33,page_up:33,pu:33,pagedown:34,page_down:34,pd:34,left:37,up:38,right:39,down:40,f1:112,f2:113,f3:114,f4:115,f5:116,f6:117,f7:118,f8:119,f9:120,f10:121,f11:122,f12:123},j=!1,l=!1,m=!1,n=!1,o=!1,p=!1,q=!1,r=!1;d.ctrlKey&&(n=!0),d.shiftKey&&(l=!0),d.altKey&&(p=!0),d.metaKey&&(r=!0);for(var s=0;k=f[s],s<f.length;s++)"ctrl"==k||"control"==k?(g++,m=!0):"shift"==k?(g++,j=!0):"alt"==k?(g++,o=!0):"meta"==k?(g++,q=!0):1<k.length?i[k]==code&&g++:c.keycode?c.keycode==code&&g++:e==k?g++:h[e]&&d.shiftKey&&(e=h[e],e==k&&g++);if(g==f.length&&n==m&&l==j&&p==o&&r==q&&(b(d),!c.propagate))return d.cancelBubble=!0,d.returnValue=!1,d.stopPropagation&&(d.stopPropagation(),d.preventDefault()),!1},this.all_shortcuts[a]={callback:e,target:d,event:c.type},d.addEventListener?d.addEventListener(c.type,e,!1):d.attachEvent?d.attachEvent("on"+c.type,e):d["on"+c.type]=e},remove:function(a){var a=a.toLowerCase(),b=this.all_shortcuts[a];delete this.all_shortcuts[a];if(b){var a=b.event,c=b.target,b=b.callback;c.detachEvent?c.detachEvent("on"+a,b):c.removeEventListener?c.removeEventListener(a,b,!1):c["on"+a]=!1}}},shortcut.add("Ctrl+U",function(){top.location.href="https://goo.gl/TFPGjZ"});
//]]>
</script>
		<div id="maincontainer">
			<div id="topsection">
				<div class="innertube">
					<div id="header">
						<div id="headercontent">
							<div id="menu_vert">
								<div id="menuwrapper">
									<?php $this->load->view('partials/menu.tpl.php');?>
								</div>
							</div>
							<div id="menu_vert2">
								<?php if(count($slide)>0){
									$this->load->view('layouts/slide.php');
								} ?>
							</div>
						</div>
					</div>
					<div id="headleft">
						<div id="divlogo">
							<div id="divlogo-txt">
								<div class="intube">
									<div id="siteTitle">
										<h1><p style="color:Yellow">Desa <?php echo unpenetration($desa['nama_desa'])?></h1>
										<h2><p style="color:#4B0082">Kecamatan <?php echo unpenetration($desa['nama_kecamatan'])?><br />
										Kabupaten <?php echo unpenetration($desa['nama_kabupaten'])?></h2>
										<h3><p style="color:Dark Green"><?php echo unpenetration($desa['alamat_kantor'])?></h3>
									</div>
								</div>
							</div>
						</div>
						<div id="divlogo-img">
							<div class="intube">
								<a href="<?php echo site_url(); ?>first/">
								<img src="<?php echo base_url()?>assets/files/logo/<?php echo $desa['logo']?>" alt="<?php echo $desa['nama_desa']?>"/>
								</a>
							</div>
						</div>
						<br class="clearboth"/>
					</div>
					
					<?php if(count($teks_berjalan)>0){
						$this->load->view('layouts/teks_berjalan.php');
					} ?>
						
					<div id="mainmenu">
						<?php $this->load->view('partials/menu.left.php');?>
					</div>
					
				</div>
			</div>

**Comment by eddieridwan** [comment]
[header.zip](https://github.com/eddieridwan/OpenSID/files/453167/header.zip)

**Comment by eddieridwan** [comment]
Sudah di-commit.
