### ISSUE TITLE
database

### ISSUE THREAD

**Issue by afri18** [eddieridwan/OpenSID#115]
ternyata opensid dengan sid yg saya pakai database beda : 
1. datasurat
2 struktur tablepun ada pebedaan, contoh
![image](https://cloud.githubusercontent.com/assets/6611881/18224342/29d5ae9c-71fc-11e6-801d-25913ec28c62.png)
3. butuh kejelian lebih buat menggabungkannya

**Comment by eddieridwan** [comment]
Saya tadinya berasumsi, para pengoprek SID CRI tidak akan mengubah database, karena kalau sdh mengubah database, pindah aplikasi akan jauh lebih rumit -- ya, seperti anda alami.

Tapi sepertinya, pengoprek SID CRI leluasa mengubah database, sehingga sangat mungkin ada banyak versi database SID yang beredar, yang belum tentu saling kompatibel.

@afri18 , bisakah anda upload database SID CRI anda ke sini. Kosongkan data penduduk dsbnya, dan export ke .sql, saya hanya perlu strukturnya.

Saya mau mencoba mencari proses yang dapat membantu melaporkan perbedaan database.

**Comment by afri18** [comment]
sepertinya bukan di oprek bung eddie, setelah saya perhatikan perjalanan OPENSID terdapat penggabungan sid yg anda dapat di si.web.id dengan bung ari ya ? (saya lupa), pertanyaanya apakah saat penggabungan tersebut juga menggabungkan database ? setau saya yang di sid.web.id adlah versi terakhir, coba anda buka database dari sid.web.id dengan databaes bung ari (?)
versi yang d sid.web.id adalah yang resmi, sedangkan yg dipegang perorangan bisa jadi sudah tertinggal atau sudah di oprek (seperti punya saya).
Oprekan saya tetap mengacu ke SID dari sid.web.id
database punya saya lagi diproses/edit, kalau sudah selesai saya kirim

**Comment by afri18** [comment]
database nggak bisa di upload, padahal dah format zip, coba periksa jenis file yg bisa di input buat pengguna lain selain anda bung eddie ...

**Comment by eddieridwan** [comment]
Bisa coba memakai Chrome? Pengguna lain pada bisa. Tidak ada setting yang membatasi pengguna untuk upload.

**Comment by eddieridwan** [comment]
Versi sid.web.id saya unduh tgl 24 Mei 2016. Apakah ada rilis resmi baru sejak tgl itu? Kalau saya unduh lagi sekarang apakah akan sama atau berbeda?

Yang saya peroleh dari Andi Anwar pada tgl 30 Mei 2016 banyak sekali tambahan tabelnya dibanding yang dari sid.web.id, lihat di https://github.com/eddieridwan/OpenSID/blob/f939f066382d4bff8c3c079c86e1db2d2cc8816f/migrasi_0.3_ke_0.4.sql .

Menurut pengamatan saya, termasuk melihat versi yang diberikan pegiat lain waktu itu, versi sid.web.id jauh ketinggalan dibanding versi2 yang beredar.

**Comment by afri18** [comment]
![image](https://cloud.githubusercontent.com/assets/6611881/18226321/88e37f38-7231-11e6-979c-c74969083674.png)

**Comment by eddieridwan** [comment]
[datadesa.sql.zip](https://github.com/eddieridwan/OpenSID/files/453907/datadesa.sql.zip)

**Comment by afri18** [comment]
namanya aja yg diganti

**Comment by eddieridwan** [comment]
Saya kira karena itu. Github nge-cek apakah memang zip, dan menolak karena bukan format zip. Coba saja tes lagi utk yakin.
