### ISSUE TITLE
Bug: Penduduk yang status dasarnya pindah, mati atau hilang harusnya tidak dihitung sebagai jumlah anggota keluarga

### ISSUE THREAD

**Issue by eddieridwan** [eddieridwan/OpenSID#117]
Untuk penduduk yang mati,hilang atau pndah betul sudah tidak muncul di form kk, akan tetapi masih terhitung, bisa nggak untuk penduduk yang mati,hilang atau pindah tidak dihitung sebagai jumlah anggota keluarga lagi ??

**Comment by afri18** [comment]
info : di Kartu keluarga jumlah betul , di form kk menu > penduduk > kelaurga > jumlah anggota masih termasuk yg mati, hilang atau pindah

**Comment by eddieridwan** [comment]
Sudah di-commit.
