### ISSUE TITLE
Fitur: Laporan Keluarga Bulanan

### ISSUE THREAD

**Issue by afri18** [eddieridwan/OpenSID#118]
agar mengetahui juga perkembangan keluarga
![image](https://cloud.githubusercontent.com/assets/6611881/18249233/3763ad32-73a7-11e6-9356-81baf35f9542.png)

**Comment by eddieridwan** [comment]
@afri18 , di SID saya, kolom keluarga tidak ada. Coba upload script anda yang menampilkan laporan bulan keluarga tersebut.

**Comment by afri18** [comment]
itu tambahan bung Eddie, untuk mengetahui perkembangan keluarga
![image](https://cloud.githubusercontent.com/assets/6611881/18276985/0dd2b1d6-7477-11e6-8a70-b957e3a18a98.png)
 saya masih lom bisa kirim file zip di sini apa zip saya yg bermasalah
![image](https://cloud.githubusercontent.com/assets/6611881/18277403/9409bd84-7478-11e6-8bd8-faa797df6850.png)

**Comment by eddieridwan** [comment]
Bung @afri18 , bisa coba kirim ulang script bulannya ke sini, atau ke-inbox atau ke files di Facebook OpenSID? Saya akan coba terapkan fitur permintaan anda ini.

**Comment by eddieridwan** [comment]
Bung @afri18 , di kolom Keluarga > Laki2 dan Keluarga > Perempuan apakah yang dimaksud jumlah keluarga dengan Kepala Keluarga laki2/perempuan?

**Comment by eddieridwan** [comment]
Tambahkan tabel log_keluarga untuk mencatat keluarga yang ditambah dan dihapus. Saat ini tidak ada info untuk menentukan apakah keluarga baru itu dari penduduk baru, atau dari penduduk lepas yang sudah ada.

Di tabel log_bulanan, tambahkan kolom untuk mencatat jumlah keluarga berdasarkan jenis kelamin kepala keluarganya.

**Comment by afri18** [comment]
kalau tidak menambah kan table bisa nggak ??



Pada 22 September 2016 12.53, Eddie Ridwan <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
Tidak bisa, karena log_bulanan tidak menyimpan perubahan keluarga. Jadi harus tambah tabel untuk menyimpan peristiwa tambah/hapus keluarga.

**Comment by eddieridwan** [comment]
Sdh di-commit.

**Comment by afri18** [comment]
Okeh bung ngarti, pantesan susah
Pada tanggal 22 Sep 2016 14.22, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by afri18** [comment]
hasil akhir seperti ini, apa sudah dibenarkan lagi (unduh kemarin)
![image](https://cloud.githubusercontent.com/assets/6611881/18875790/705eaca8-84f1-11e6-93aa-60eeb9407ac7.png)

**Comment by eddieridwan** [comment]
@afri18 : Jumlah yang ditampilkan akan tergantung kapan fitur ini di-unduh. Karena _Keluarga Baru_ dan _Keluarga Pindah_ itu tercatat di _log_keluarga_ pada saat keluarga ditambah atau dihapus, maka apabila penambahan/penghapusan keluarga telah dilakukan sebelum fitur ini di-unduh, ya tidak akan terhitung.

Sedangkan jumlah _awal bulan_ dan _akhir bulan_ diambil dari log_bulanan yang diisi setiap kali menjalankan laporan berdasarkan data di tabel penduduk. 

Jadi untuk bulan pertama hasilnya bisa seperti yang anda alami. Untuk bulan2 berikutnya, karena tambah/hapus keluarga tercatat, jumlah perubahan keluarga akan ikut tampil.

**Perhatian.** 
>>>
Jumlah _awal bulan_ yang ditampilkan juga bisa tidak akurat, apabila _laporan bulanan_ tidak dilakukan pada akhir bulan yang lalu. Misalnya:
- pencetakan laporan bulanan dilakukan pada tanggal 25 Agustus
- pada tgl 26 Agustus, ada penduduk yang pindah/mati/hilang
>>>
Dalam hal ini, pada bulan berikutnya, September, jumlah _awal bulan_ untuk Agustus akan selisih 1 (satu) dari yang sebenarnya, karena log_bulanan untuk bulan itu tercatat pada tgl 25 Agustus.

Sayangnya ini adalah karena keterbatasan teknik yang diterapkan, yaitu log_bulanan dicatat pada waktu pengguna melakukan sesuatu. Untuk mengubah ini, agar dihitung secara otomatis oleh sistem pada tanggal tertentu (misalnya akhir bulan), memerlukan perangkat teknis tambahan.

Sementara itu, ya harus rajin untuk menjalankan laporan bulanan pada akhir setiap bulan.

**Comment by eddieridwan** [comment]
Info di atas telah ditambahkan di panduan di https://github.com/eddieridwan/OpenSID/wiki/Statistik-Kependudukan
