### ISSUE TITLE
bug: user operator

### ISSUE THREAD

**Issue by dedi2016** [eddieridwan/OpenSID#119]
jika saya menggunakan mode user hak operator, maka akan sign out sendiri jika ingin membuka map dan penduduk tab kelompok, apa ini hanya punya saya sendiri atau memang dibuat begitu? saya menggunakan openSID v0.9.1

**Comment by afri18** [comment]
itu hak administrator

**Comment by eddieridwan** [comment]
Pull request dari @batudaa
