### ISSUE TITLE
Bug: Peta Lokasi Kantor Desa tidak bisa kelihatan

### ISSUE THREAD

**Issue by suhadrian** [eddieridwan/OpenSID#121]
kenapa peta lokasi kantor desa tidak bisa muncul......?
![peta desa](https://cloud.githubusercontent.com/assets/20695005/18336438/d033f60c-75b9-11e6-83f2-5ff3b4c40fd0.jpg)

**Comment by eddieridwan** [comment]
Lampirkan database.sql dan folder desa anda.

**Comment by eddieridwan** [comment]
Setelah diperiksa, ternyata masalahnya disebabkan kolom2 berikut di tabel _config_ kosong:

1. _lat_
1. _lng_
1. _zoom_

Untuk memperbaiki, isi ketiga kolom dengan data koordinat _latitude_, _longitude_ yang valid, dan juga data _zoom_ peta, seperti contoh: berikut:

1. _lat_ : -8.488005310891758
2. _lng_ : 116.0406072534065
3. _zoom_: 19

Karena modul Administrasi saat ini tidak menyediakan fitur mengubah koordinat dalam situasi ini, perubahan dapat dilakukan langsung mempergunakan phpmyadmin.

**Comment by eddieridwan** [comment]
Perlu dilakukan perbaikan script, supaya data peta default dimasukkan ke tabel config pada saat membuat config desa baru.

**Comment by eddieridwan** [comment]
Sudah dicommit.
