### ISSUE TITLE
Bug: print surat

### ISSUE THREAD

**Issue by agustepe** [eddieridwan/OpenSID#123]
Erorr kita print surat wali dan wali hakim

**Comment by eddieridwan** [comment]
Surat export doc untuk surat wali dan wali hakim sudah dicommit di https://github.com/eddieridwan/OpenSID/commit/11c64c14210ec21c584a1b723d0cbd9b08ae8ef0

Tetapi versi cetak untuk surat2 ini tidak akan diperbaiki, karena akan tidak dipakai lagi.
