### ISSUE TITLE
Fitur: Tambahkan cek Kartu Keluarga di laman Profilku pada Layanan Mandiri

### ISSUE THREAD

**Issue by afri18** [eddieridwan/OpenSID#129]
sepeti koment di group opensid terkait "Layanan Mandiri" yang terpengaruh akibat verifikasi catpcha di komen artikel, sebaiknya diperbaiki dan ditambahkan menu upload dokumen sebagai dasar perubahan data tersebut.
Bisa nggak ya, saat klik Profilku juga ditambahkan tombol cek Kartu Keluarga, jadi nantinya warga tau datanya sudah valid atau belum untuk seluruh data keluarga, wah kalau ini bisa jelas Opensid nilainya plus.

**Comment by eddieridwan** [comment]
Sudah di-commit.

**Comment by afri18** [comment]
koreksi bung Eddie, saat klik cetak KK di layanan mandiri ternyata di bawa ke halaman siteman/login, ini saya coba saat keluar dari menu admin, kesimpulan, apabila halaman hom_desa tidak aktiv maka cetak KK dilayanan Mandiri dibawa ke halaman login/siteman

**Comment by eddieridwan** [comment]
Pindahkan pemanggilan cetak_kk untuk layanan mandiri ke controller first.php, dan memakai penanganan akses melalui login layanan mandiri , bukan login modul administrasi (siteman).

Sekalian buat function di keluarga_model untuk menyiapkan data cetak_kk yang bisa dipakai oleh cetak_kk baik dari layanan mandiri maupun dari laman Keluarga di modul admin.
