### ISSUE TITLE
Bug: Penambahan peserta kriteria keluarga di modul bantuan/program tidak muncul

### ISSUE THREAD

**Issue by afri18** [eddieridwan/OpenSID#130]
saat penambahan peserta dikriteria keluarga data (cari nama/nik disini) tidak muncul, kalau bisa menambahkannya seperti menu tambah keluarga dari penduduk yang terinput, juga ditambahkan baris untuk isi id Kartu Bantuan, di table program ada tapi belum difungsikan,
wah banyak issues,
memang butuh keahlian seperti bung Eddie, kemampuan ane terbatas

**Comment by eddieridwan** [comment]
@afri18 , Pada v0.10, penambahan peserta pada program dengan kriteria keluarga berjalan normal. Mohon dicoba ulang pada versi v0.10. Apabila masih bermasalah, harap lampirkan langkah yang diikuti dan tampilan layar menunjukkan error yang dialami.

**Comment by eddieridwan** [comment]
@afri18 Berikut ini tampilan layar dari v1.0. Bisa pilih keluarga, berfungsi normal. Apakah anda membuat oprekan pada versi OpenSID anda? Apakah sasaran peserta lainnya (misalnya Penduduk) berjalan normal?

![program-bantuan-kk](https://cloud.githubusercontent.com/assets/249563/18808908/93240cc6-82a1-11e6-8171-e80c64f44182.jpg)

**Comment by afri18** [comment]
![image](https://cloud.githubusercontent.com/assets/6611881/18809054/136e9e8c-829d-11e6-921f-4b2b5ec3b2e2.png)

**Comment by eddieridwan** [comment]
Bung @afri18 , di phpmyadmin, coba jalankan SQL ini:

```
SELECT k.no_kk as id,p.nama as nama,w.rt,w.rw,w.dusun FROM tweb_keluarga k
						LEFT JOIN tweb_penduduk p ON p.id=k.nik_kepala
						LEFT JOIN tweb_wil_clusterdesa w ON w.id=p.id_cluster
					WHERE 1
```

Hasil query ini yang ditampilkan di pilihan peserta keluarga. 

Apa hasil query ini di database anda? Kalau kosong, berarti ada yang tidak nyambung.

**Comment by eddieridwan** [comment]
@afri18 : apakah anda masih mengalami masalah ini, atau bisa ditutup?

**Comment by afri18** [comment]
belum saya coba lagi

**Comment by afri18** [comment]
saya coba gagal 
![image](https://cloud.githubusercontent.com/assets/6611881/20455562/70d28b4a-ae91-11e6-8331-6ddae21a6ac9.png)

**Comment by eddieridwan** [comment]
@afri18 : Apakah sudah dicoba dengan v1.5.1? Apakah sudah dibandingkan dengan demo di http://sid.bangundesa.info/index.php/program_bantuan?

**Comment by eddieridwan** [comment]
Ok, sudah ketemu masalahnya. Disebabkan oleh No. KK yang berisi "_" (misalnya "029_006"). Apakah mungkin ada nomor Kartu Keluarga seperti itu? Hapus karakter "_" di nomor KK tersebut dan coba lagi.

Kalau "_" itu memang harus merupakan bagian dari nomor KK, beritahu dasarnya dan kami akan coba cari solusinya.

**Comment by afri18** [comment]
betul bung, ada memang nomor kk berkarakter seperti itu, alasannya karna belum punya nomor KK baku, yang bersangkutan belum mengurus datanya, jadi sementara saya kasih no KK kayak gitu

**Comment by eddieridwan** [comment]
Supaya fiturnya jalan, coba ganti saja dulu no KK tersebut dengan menghapus karakter `"_"`.

**Comment by eddieridwan** [comment]
Ok, sudah diperbaiki. Sekarang daftar peserta sasaran keluarga bisa menampilkan daftar keluarga di mana ada no KK berisi karakter non-digit, seperti '_'. 

Sudah di-commit ke branch master.
