### ISSUE TITLE
Bug: Cetak biodata bisa ditampilkan walaupun pengguna layanan mandiri sudah logout

### ISSUE THREAD

**Issue by eddieridwan** [eddieridwan/OpenSID#131]
Langkah yang diikuti:

1. Di modul web, di widget Layanan Mandiri login sebagai pengguna layanan mandiri
1. Di laman Profilku, klik Cetak Biodata untuk menampilkan laporan biodata
1. Di widget Layanan Mandiri, klik tombol Keluar untuk logout
1. Di address bar browser, masukkan url untuk halaman biodata, seperti contoh ini: `http://localhost/OpenSID/index.php/first/cetak_biodata/1`

Laporan biodata akan ditampilkan walaupun sudah keluar. Seharusnya tidak ditampilkan.

**Comment by eddieridwan** [comment]
Sdh di-commit.

**Comment by afri18** [comment]
di saya langsung ketutup bing, saat penduduk/pengguna keluar

**Comment by eddieridwan** [comment]
Yakin? Coba masukkan url seperti ini di browser anda:
http://localhost/OpenSID/index.php/first/cetak_biodata/1

**Comment by afri18** [comment]
sudah saya coba di online tetap tertutup, begitu juga di local

**Comment by eddieridwan** [comment]
Ya, bagus. Memang sekarang di OpenSID seharusnya tertutup kalau pengguna tidak login. Kalau di SID CRI asli, bisa dibuka walaupun tidak login.

**Comment by afri18** [comment]
![image](https://cloud.githubusercontent.com/assets/6611881/18806479/571cc662-8258-11e6-8da4-08d7086bd031.png)
tidak bisa isi peserta kriteria keluarga
