### ISSUE TITLE
Bug: Tidak ada fitur untuk menghapus penduduk yang telah terdaftar untuk layanan mandiri

### ISSUE THREAD

**Issue by eddieridwan** [eddieridwan/OpenSID#133]
Langkah yang diikuti:

1. pergi ke laman Layanan Mandiri (klik Laporan > Layanan Mandiri)
1. daftarkan penduduk untuk layanan mandiri dengan menekan tombol Hasilkan Pin. Penduduk ini akan ditampilkan di tabel layanan mandiri

Tetapi tidak ada fitur untuk menghapus atau me-non aktifkan penduduk yang sudah terdaftar.

**Comment by eddieridwan** [comment]
Sudah di-commit.

**Comment by eddieridwan** [comment]
Fitur untuk me-non aktfikan penduduk tidak diterapkan. Menunggu adanya permintaan untuk fitur ini.

**Comment by ariandii** [comment]
Mohon ijin:
Permintaan fitur untuk me-nonaktifkan penduduk apakah bisa melalui komentar disini atau harus buat issues baru?

Jika bisa melalui komentar disini, saya berharap fitur tersebut dapat diterapkan atau mungkin semisal fitur secara otomatis nonaktif setelah kirim 2 atau 3 laporan dengan notifikasi di layanan mandiri. dan akan aktif kembali secara otomatis jika laporan tersebut sudah ditindaklanjuti oleh admin.

Atau ada laporan yang "bandel" sehingga akun tersebut perlu dinonaktifkan sementara.

Terima kasih.
