### ISSUE TITLE
Modul Cetak  Surat Keterangan Pindah Penduduk Tidak Menampilkan Jumlah Pengikut

### ISSUE THREAD

**Issue by siayi** [eddieridwan/OpenSID#14]
Ada masalah pada Modul Cetak  Surat Keterangan Pindah Penduduk,
1. Pada form Surat Keterangan Pindah Penduduk tidak bisa menampilkan data pengikut, padahal kolom isian Jumlah Pengikut sudah diisi >0 .
2. Ketika dicetak Jumlah Pengikut tertulis 0 orang, padahal saat mengisi pada form diisi 2 (>0)

![error sistem informasi desa](https://cloud.githubusercontent.com/assets/1229849/15647394/762526c0-268d-11e6-9354-af3990901ec4.png)

**Comment by eddieridwan** [comment]
Bung @siayi, bagaimana, apakah jurus gitnya sudah cukup mahir untuk bisa memperbaiki masalah ini dan mengirimkan solusinya melalui _pull request_ (https://help.github.com/articles/using-pull-requests/)?

Apabila perlu bantuan, beritahui kami. Dan kami kira, @batudaa juga bisa diminta bantuannya.

**Comment by siayi** [comment]
masih belum berhasil (dalam proses), baru Bab VIII di https://kelaskita.com/kelaskita/kelas/mengenal-git/  :+1:

**Comment by eddieridwan** [comment]
Diskusi _pull request_ di https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/opensid/tERY2bbBjnU.
Draft panduan di https://github.com/eddieridwan/OpenSID/wiki/Panduan-mengirimkan-perubahan-repo-OpenSID.

Selamat mencoba!
