### ISSUE TITLE
Bug: Fitur Excel di laporan kependudukan bulanan menampilkan halaman kosong

### ISSUE THREAD

**Issue by eddieridwan** [eddieridwan/OpenSID#145]
Langkah yang diikuti:
1. Pergi ke Statistik > Laporan Kependudukan Bulanan
2. Klik tombol Excel

Yang ditampilkan hanya halaman kosong.

**Comment by pandigresik** [comment]
saya coba di laptop local, gak ada masalah. File excel digenerate dengan baik

**Comment by eddieridwan** [comment]
Sudah dikerjakan.
