### ISSUE TITLE
Fitur : Penambahan menu Hapus, Edit, Cetak Ulang pada menu surat keluar

### ISSUE THREAD

**Issue by asepzhepots** [eddieridwan/OpenSID#147]
Agar lebih baik, rapi dan dapat digunakan kembali, sebaiknya dalam menu surat keluar ditambahkan fitur Hapus, Edit dan Cetak ulang surat, sehingga surat yang di anggap tidak terpakai atau ada kesalahan dapat diperbaiki ataupun di hilangkan

**Comment by eddieridwan** [comment]
Duplikat dari #102.

Hapus sebaiknya hanya dilakukan apabila memang surat dibuat sebagai contoh, percobaan atau keliru.

Fitur cetak sudah ada sebelumnya buat surat Export Doc.

Surat Keluar merupakan arsip surat. Surat yang ada di tabel ini adalah salinan dari surat yang telah dibuat dan sebaiknya tidak diubah. 

Kalau ada surat yang dianggap perlu diubah, maka surat tersebut perlu dibuat ulang mempergunakan proses pembuatan surat baru. Yaitu, fitur edit surat tidak konsisten dengan fungsi Surat Keluar sebagai arsip.

**Comment by eddieridwan** [comment]
#102 sudah di-commit.
