### ISSUE TITLE
Fitur: Kelola widget yang dibuat pengguna di folder desa

### ISSUE THREAD

**Issue by afri18** [eddieridwan/OpenSID#149]
1. Karna Opensid sangat mobil dalam perkembangannya bisa nggak file [side.right.php] di folder donjo-app\views\partials dimasukan ke dalam folder desa sebagai bagian dari stylesheets/tampilan web_desa, karna setiap kali realis ini sangat merepotkan.
lihat http://cigelam.desa.id/ 
tambah lagi ada beberapa fitur yang disesuaikan, wah sangat menyita waktu.
2. diberikan tombol dowload gambar/photo dibawah  ganti logo untuk disimpan di logo, tujuan agar file stylesh no 1 bisa diganti-ganti dengan catatan gambar yang tersimpan dengan judul yang sama dihapus dulu baru upload gambar baru

**Comment by eddieridwan** [comment]
@afri18 , mengapa anda tidak terapkan widget anda sebagai widget dinamis (customizable widget)?

Juga, usulan untuk bisa me-nonaktifkan widget statis sudah ada di #80. Apakah fitur ini yang anda butuhkan?

Atau apakah yang dibutuhkan termasuk kemampuan menentukan urutan semua widget, termasuk yang statis maupun dinamis?

**Comment by afri18** [comment]
yang dibutuhkan menurut kebutuhan, karna itu selera Administrator web artinya satu desa dengan desa lainnya (apalagi beda kabupaten) berbeda

**Comment by eddieridwan** [comment]
Solusi yang sedang diterapkan dijelaskan di #80. 

@afri18 , Satu issue sebaiknya hanya berisi satu masalah. Usulan anda yang no 2 dipindahkan ke issue tersendiri.

**Comment by eddieridwan** [comment]
Widget statis buatan pengguna sekarang disimpan di folder desa/widget. Sdh di-commt.
