### ISSUE TITLE
Fitur: Tampilkan statistik bantuan/program di menu web dan menu statistik

### ISSUE THREAD

**Issue by afri18** [eddieridwan/OpenSID#150]
Bisa nggak Bantuan/Program di tampilkan di halaman web menu
![image](https://cloud.githubusercontent.com/assets/6611881/18806503/1652ae66-8259-11e6-875f-e280293c0986.png)

juga di menu statistik
![image](https://cloud.githubusercontent.com/assets/6611881/18806522/a64eb17c-8259-11e6-9189-812881a1fca8.png)

**Comment by eddieridwan** [comment]
@afri18 , yang ditampilkan untuk suatu program bantuan apa? Daftar peserta? Statistik lainnya? Bisa berikan contoh statistik apa yang ingin ditampilkan untuk suatu program yang ada di desa anda?

**Comment by afri18** [comment]
di menu Bantuan sudah terisi, sekarang bagaimana menampilkan di statistik dan menu data desa submenu Bantuan1, Bantuan 2, dst
![image](https://cloud.githubusercontent.com/assets/6611881/18809023/10f4a29c-829c-11e6-8afe-62de2310b4d5.png)

**Comment by eddieridwan** [comment]
@afri18 Sesudah di-klik salah satu program bantuan, misalnya Bedah Rumah, apa yang ditampilkan? Jumlah keluarga? Tanggal? 

Coba berikan contoh tampilan statistik yang diinginkan untuk program bantuan KK dan program bantuan Penduduk.

**Comment by eddieridwan** [comment]
Untuk penampilan di menu web, tinggal ditambah keterangan cara mengakses statistik program bantuan di panduan https://github.com/eddieridwan/OpenSID/wiki/Artikel-Peragaan-Statistik
