### ISSUE TITLE
Fitur: Tambahkan kolom alamat di impor data penduduk

### ISSUE THREAD

**Issue by cakwidodo** [eddieridwan/OpenSID#154]
Pada data penduduk excel Setelah kolom dusun ditambah kolom untuk nama jalan atau perumahan (antara kolom dusun dg RW). Meskipun tidak terlihat di wilayah admistratif. Tp bisa dipanggil ketika cetak surat

**Comment by eddieridwan** [comment]
Bung @cakwidodo, apakah anda sudah memakai kolom <em>alamat_sekarang</em> dan <em>alamat_sebelumnya</em>? Kalau sudah, harap beri contoh pengisian ke dua kolom ini.

**Comment by Agus-Heriyanto** [comment]
Ya setuju dengna usul itu..dan bisa ditambahkan pada format imprt maupun export excel dengan iformasi lain yang berkaitan dengan identitas yang ada di info penduduk misalkan akseptor KB, status kehamilan dll. Mungkin untuk alamt spesifik jalan bisa masuk linknya ke alamat sekarang karena dulu pernah coba buat manual di alamt sekarang untuk nama jalan kemudian bisa terbaca saat pembuatan surat tertulis sebelum nama dusun.

**Comment by eddieridwan** [comment]
Usul untuk menambahkan semua data penduduk pada impor/ekspor data penduduk sudah terdaftar di #183. 

Usul ini khusus terbatas pada penambahan kolom alamat. Penambahan kolom alamat bermanfaat pada saat melakukan perbaikan data yang telah diimpor dari format BIP.

**Comment by eddieridwan** [comment]
Sdh dicommit ke master.

**Comment by cakwidodo** [comment]
saya selama inj hanya pakai input alamat tambahan pada surat, jadi gak masuk database
