### ISSUE TITLE
Bug: Cetak Biodata Layanan Mandiri Cetak hanya dapat cetak sendiri

### ISSUE THREAD

**Issue by markunyil** [eddieridwan/OpenSID#156]
ubah di /controllers/first.php
$data['penduduk'] = $this->penduduk_model->get_penduduk($id);
menjadi
$data['penduduk'] = $this->penduduk_model->get_penduduk($_SESSION['id']);

hanya dapat mencetak pada sesinya saja jika angka belakang diubah akan kembali pada page sesi.

function cetak_biodata ($id=''){
		if($_SESSION['mandiri']!=1){
			redirect('first');
			return;
		}
		$data['desa'] = $this->header_model->get_data();
		$data['penduduk'] = $this->penduduk_model->get_penduduk($_SESSION['id']);
		$this->load->view('sid/kependudukan/cetak_biodata',$data);
		
	}

**Comment by eddieridwan** [comment]
Langkah yang diikuti:

1. Login sebagai pengguna layanan mandiri
1. Klik _Cetak Biodata_ untuk menampilkan laporan biodata untuk pengguna
1. Lihat url, misalnya <br> `http://localhost:8080/OpenSID/index.php/first/cetak_biodata/100` 
1. Ganti url untuk menampilkan biodata penduduk lain, seperti <br> `http://localhost:8080/OpenSID/index.php/first/cetak_biodata/105`

Saat ini, biodata penduduk yang bukan pengguna yang login, bisa ditampilkan. Seharusnya tidak bisa.

**Comment by eddieridwan** [comment]
Sudah dicommit.

**Comment by markunyil** [comment]
Terimakasih, sebenarnya di SID saya juga sudah saya tambahahi layanan
mandiri bukan hanya untuk cetak bio data saja, surat-menyurat lain juga
bisa, masih saya coba trial dulu

**Comment by eddieridwan** [comment]
@markunyil: silakan membuat issue baru untuk tambahan anda, sekaligus lampirkan scriptnya. Atau sekalian saja buat _pull request_ di github.
