### ISSUE TITLE
Cara merubah huruf UPPERCASE menjadi hurup Capitalize

### ISSUE THREAD

**Issue by suhadrian** [eddieridwan/OpenSID#157]
bagaimana cara merubah huruf UPPERCASE pada cetak surat menjadi huruf Capitalize sehingga tampilan dalam surat tidak terkesan berantakan?
![surat](https://cloud.githubusercontent.com/assets/20695005/19069841/49871c86-8a5b-11e6-9802-d0b08747aad2.jpg)

**Comment by markunyil** [comment]
Untuk merubah huruf jadi Capitalize tinggal menambahkan code dimana kata atau kalimat yang mau di convert,
sebagai contoh untuk nama <?php echo  ucwords (strtolower(($penduduk['nama'])))?> karakter huruf dibuat lowercase dulu baru didepan perintah ucwords untuk membuat karakter capitalize. 
mungkin itu cara yang saya lakukan.

**Comment by markunyil** [comment]
<?php echo  ucwords (strtolower($penduduk['nama']))?>

**Comment by eddieridwan** [comment]
Sebagai penampilan _default_, kami akan ubah sesuai dengan usulan dari @suhadrian (Desa Gelangsar Lombok Barat). Yaitu, kecuali nama peminta surat dan nama penandatangan, semua data individu lain ditampilkan sebagai Title Case (huruf pertama memakai huruf besar).

Apabila pengguna ingin mengubah penampilan _default_ ini, perubahan ini dapat dilakukan di template RTF untuk masing-masing surat Export Doc (atau di file print_[jenis_surat].php yang disimpan di folder desa/surat/print untuk surat Cetak).

Perlu diingat, pengguna sebaiknya tidak mengubah file inti SID, karena akan tertimpa pada waktu mengupgrade OpenSID.

**Comment by eddieridwan** [comment]
Sdh di-commit.
