### ISSUE TITLE
#migrasi ke opensid

### ISSUE THREAD

**Issue by afri18** [eddieridwan/OpenSID#161]
Alham dulillah akhirnya web http://cigelam.desa.id/index.php/first berhasil saya miigrasi ke opensid, hanya saja untuk releas selanjutnya sebaiknya memberikan keterangan jenis file dan di folder mana yang harus diganti, agar nggak semuanya bung Eddie. karna kalau semuanya sangatlah repot

**Comment by eddieridwan** [comment]
Bung @afri18, bisa tolong jelaskan mengapa update ke rilis baru akan merepotkan? 

Kalau semua file/script ubahan sudah dimasukkan ke dalam folder _desa_, update dengan cara menggantikan semua file inti SID mudah saja. Semua yang di folder _desa_ aman dan tidak tertimpa.

Apakah anda masih ada perubahan script di file inti yang belum masuk ke folder _desa_? Mohon dirinci apa saja perubahan script yang anda lakukan yang masih ada di file inti SID, supaya saya bisa mengerti konfigurasi OpenSID apa lagi yang diperlukan.

Apakah anda sudah melihat petunjuk _Pindahkan File_ dan _Ulangi perubahan penampilan web_ di panduan https://github.com/eddieridwan/OpenSID/wiki/Panduan-Pindah-Dari-SID-CRI-ke-OpenSID?

**Comment by afri18** [comment]
Saya mengerti maksudnya, karna sid yg saya pake intinya d online jadi sangat repot bila setiap realeass mesti ganti seluruh scrept inti, usul agar setiap realeass memmberitahukan file apa aja yg d rubah/dganti, agar mudah dan tidak mengganggu file lainnya, dan ada beberapa setingan seperti form keluarga yg saya sesuaikan dengan kebutuhan

**Comment by eddieridwan** [comment]
Bung @afri18, setiap perubahan yang dilakukan kapan saja bisa anda periksa di github. Saya telah tambahkan petunjuk di https://github.com/eddieridwan/OpenSID/wiki/Panduan-Update-OpenSID bagaimana cara melihat perubahan yang dilakukan pada suatu rilis (lihat bagian _Melihat daftar file yang diubah pada rilis OpenSID_).

**Comment by eddieridwan** [comment]
Bung @afri18, bisakah anda jelaskan setingan apa yang anda sesuaikan di form keluarga? Apakah setingan ini bermanfaat juga untuk pengguna lainnya?

Maksudnya untuk melihat apakah OpenSID dapat menyediakan fitur untuk mengubah setingan supaya tidak perlu mengubah file inti (contohnya seperti yang telah dilakukan untuk widget di sidebar).

**Comment by afri18** [comment]
sebenarnya ini berkaitan dengan alamat > saya mencoba menerapkan alamat berisi dengan menambahkan alamat_sekarang, yang nantinya diikutkan dalam alamat tinggal dalam surat
![image](https://cloud.githubusercontent.com/assets/6611881/19234734/cbb896a6-8f17-11e6-8278-3058945f068a.png)
kalau ini form penduduk yang saya sesuaikan tapi alamat > alamat_sekarang lom muncul
![image](https://cloud.githubusercontent.com/assets/6611881/19235073/99bd9c12-8f19-11e6-8c4c-f49463738afd.png)

**Comment by eddieridwan** [comment]
Masalah penampilan alamat di halaman penduduk telah dipindahkan ke #174, sedangkan pertanyaan perubahan file telah dijawab di atas.
