### ISSUE TITLE
>>>>>>>>>>>> Link gambar wiki (panduan) -- arsip

### ISSUE THREAD

**Issue by eddieridwan** [eddieridwan/OpenSID#162]
<img width="1367" alt="ubah-data-peserta" src="https://user-images.githubusercontent.com/249563/28264906-79f8d7ea-6b30-11e7-9438-90475ae7159c.png">
<img width="890" alt="tambah-peserta-program-bantuan" src="https://user-images.githubusercontent.com/249563/28264907-79fa6182-6b30-11e7-881c-d20bea643816.png">

<img width="1320" alt="daftar-calon-pemilih" src="https://user-images.githubusercontent.com/249563/28258729-20638db6-6b16-11e7-9aaf-ce56443a32d5.png">

<img width="997" alt="pilihan-sumber-gambar-slider" src="https://user-images.githubusercontent.com/249563/28096711-3294d1d8-66ee-11e7-82d9-11970d1a3d4b.png">

<img width="1131" alt="setting_sinergitas_program" src="https://user-images.githubusercontent.com/249563/27818637-d7884cf8-60d9-11e7-8a46-c92fbe293fa7.png">
<img width="1006" alt="tombol-setting-widget" src="https://user-images.githubusercontent.com/249563/27818638-d7b9cb5c-60d9-11e7-8b54-2e24bc94a8ab.png">
<img width="1131" alt="widget-sinergitas-program" src="https://user-images.githubusercontent.com/249563/27818639-d7ce1364-60d9-11e7-8a2a-b5bc9e5241ef.png">

=========

![hosting-tidak-aman](https://user-images.githubusercontent.com/249563/27519999-93b75768-5a43-11e7-9601-94264f0e6ad8.jpg)

=======
<img width="1120" alt="daftar-bantuan-layanan-mandiri" src="https://user-images.githubusercontent.com/249563/27315197-93f235ea-55bb-11e7-9d7b-ae342e835e26.png">
![Uploading widget-layanan-mandiri.png…]()

======
<img width="1118" alt="navigasi-halaman-setting-aplikasi" src="https://user-images.githubusercontent.com/249563/27312815-11760306-55ae-11e7-9b9e-0c24d1ce944a.png">
<img width="1118" alt="navigasi-halaman-setting-aplikasi" src="https://user-images.githubusercontent.com/249563/27312815-11760306-55ae-11e7-9b9e-0c24d1ce944a.png">
======
<img width="956" alt="halaman-media-sosial" src="https://user-images.githubusercontent.com/249563/27309332-ae9a17ac-5596-11e7-8eac-6ce88b38fe3f.png">
<img width="956" alt="mengubah-tautan-media-sosial" src="https://user-images.githubusercontent.com/249563/27309333-ae9b1d96-5596-11e7-8dd4-a411e3e76495.png">
<img width="1118" alt="widget-menu-sosial-media" src="https://user-images.githubusercontent.com/249563/27309334-ae9be9c4-5596-11e7-9b13-f1fc7b4c13b1.png">

====
<img width="956" alt="form-isian-pemerintah-desa" src="https://user-images.githubusercontent.com/249563/27306661-c99d793e-5589-11e7-9cc9-4e682b506d81.png">
<img width="1147" alt="halaman-pemerintah-desa
" src="https://user-images.githubusercontent.com/249563/27306544-57005a9a-5589-11e7-8ee4-1bdb28296c26.png">
<img width="1144" alt="widget-aparatur-desa-2" src="https://user-images.githubusercontent.com/249563/27306545-57024684-5589-11e7-90b3-cfc602d09e83.png">

====

<img width="1034" alt="form-surat-baru" src="https://cloud.githubusercontent.com/assets/249563/26624260/b2e70116-4633-11e7-9d6a-44d6a17880b2.png">

<img width="1052" alt="penandatangan-surat" src="https://cloud.githubusercontent.com/assets/249563/26307942/6edb3a6e-3f3a-11e7-9695-c2fc4d8d0fda.png">

<img width="1052" alt="penandatangan-default" src="https://cloud.githubusercontent.com/assets/249563/26307702/449b6e28-3f39-11e7-84bb-3c64883e60b7.png">

<img width="1009" alt="aktif-nonaktifkan-modul" src="https://cloud.githubusercontent.com/assets/249563/25831925/ac186c98-34aa-11e7-870f-b3fe5788cd0d.png">
<img width="1009" alt="menu-pengaturan-modul" src="https://cloud.githubusercontent.com/assets/249563/25831926/ac197566-34aa-11e7-9a16-63d033298595.png">
<img width="1009" alt="tampilan-modul-setelah-dinonaktifkan" src="https://cloud.githubusercontent.com/assets/249563/25831927/ac1a9572-34aa-11e7-81bc-6bf5b7561698.png">
<img width="1009" alt="tombol-ubah-setting-modul" src="https://cloud.githubusercontent.com/assets/249563/25831928/ac1af440-34aa-11e7-9d25-02ea46ff5231.png">

<img width="1158" alt="contoh-tema-hadakewa" src="https://cloud.githubusercontent.com/assets/249563/25802599/4d72916a-3436-11e7-9798-bf7d28ba1520.png">
<img width="1110" alt="ubah-kategori-artikel" src="https://cloud.githubusercontent.com/assets/249563/25802600/4d73e7e0-3436-11e7-8c0b-870ee22d9b8e.png">

<img width="963" alt="geser-marker-kantor-desa" src="https://cloud.githubusercontent.com/assets/249563/25062968/10936134-221b-11e7-91fe-b1aff64abb11.png">

![lampiran-kosong](https://cloud.githubusercontent.com/assets/249563/25061510/7893d43c-21fb-11e7-8b14-3e6c26ce50de.jpg)

![upload-file-di-issue](https://cloud.githubusercontent.com/assets/249563/24045954/23b1b928-0b64-11e7-875d-42d14df0dce3.jpg)

Program bantuan

![contoh-id-peserta-program-bantuan](https://cloud.githubusercontent.com/assets/249563/23574647/732cf56e-00e5-11e7-8f2d-b94d5c635272.jpg)

![form-tambah-peserta-program](https://cloud.githubusercontent.com/assets/249563/22860414/1f57a1e2-f162-11e6-88de-30ce0ce0f32b.jpg)
![tombol-tambah-peserta-program](https://cloud.githubusercontent.com/assets/249563/22860415/1f711ad2-f162-11e6-8ed0-79aaa7eada0e.jpg)

Unduh pra-rilis
![unduh-versi-pra-rilis](https://cloud.githubusercontent.com/assets/249563/22858894/a5ed39d4-f12f-11e6-822b-883b10b251af.jpg)

Klasifikasi Surat
![form-surat-baru](https://cloud.githubusercontent.com/assets/249563/21760302/e3fda9ce-d6af-11e6-86de-c4b70f17c37c.jpg)

Migrasi
![migrasi-db](https://cloud.githubusercontent.com/assets/249563/21634690/2b44745e-d2ad-11e6-9519-c2ce1b482f1f.jpg)
![master-surat-dengan-lampiran](https://cloud.githubusercontent.com/assets/249563/21637022/2b40967a-d2b9-11e6-908b-d35331b3c707.jpg)
![surat-keluar-lampiran](https://cloud.githubusercontent.com/assets/249563/21637023/2bc1fad0-d2b9-11e6-9b39-fb9788c973e4.jpg)
![contoh-f-1 08](https://cloud.githubusercontent.com/assets/249563/21637258/3ab7dc34-d2ba-11e6-8359-c4e2396bea9d.jpg)

Kosongkan DB
![kosongkan-db](https://cloud.githubusercontent.com/assets/249563/21410273/8bfd211c-c833-11e6-8b78-e38ac8d9d7b0.jpg)

Konversi sid304
![konversi-sid304](https://cloud.githubusercontent.com/assets/249563/19690649/9390128c-9afb-11e6-84dc-4542cd3a079b.jpg)

**Comment by eddieridwan** [comment]
Update OpenSID

![perubahan-di-commit](https://cloud.githubusercontent.com/assets/249563/19220838/4038cd48-8e69-11e6-8aac-41e8b5471704.jpg)
![daftar-commit-untuk-rilis](https://cloud.githubusercontent.com/assets/249563/19220839/40685fd6-8e69-11e6-975c-ee97f5ec64e4.jpg)
![tombol-lihat-commit](https://cloud.githubusercontent.com/assets/249563/19220841/409170d8-8e69-11e6-9bea-9c8cd772c154.jpg)
![rilis-opensid](https://cloud.githubusercontent.com/assets/249563/19220949/e0aa7d06-8e6b-11e6-969e-da486368a2f5.jpg)

**Comment by eddieridwan** [comment]
BIP

![impor-bip](https://cloud.githubusercontent.com/assets/249563/19303651/1788bfd6-909c-11e6-853a-1a771a03fe03.jpg)

**Comment by eddieridwan** [comment]
Menu

![tombol-naik-turun-menu-statis](https://cloud.githubusercontent.com/assets/249563/20339157/aad11f04-ac3f-11e6-9d62-0b5765153388.jpg)
![tombol-tampilkan-submenu-statis](https://cloud.githubusercontent.com/assets/249563/20339158/aaf5b878-ac3f-11e6-99bf-a4a5ec08be43.jpg)

![menu-statis-web](https://cloud.githubusercontent.com/assets/249563/20339584/1a24f144-ac42-11e6-84e6-d92c26cb2469.jpg)

**Comment by eddieridwan** [comment]
Error upgrade
![error-belum-migrasi](https://cloud.githubusercontent.com/assets/249563/20457895/c505ee0a-aefa-11e6-9e3e-bc59b0f02307.jpg)

**Comment by eddieridwan** [comment]
Config
![contoh-setting-config](https://cloud.githubusercontent.com/assets/249563/20505139/e9465e6a-b0af-11e6-9d17-3a2575edb40d.jpg)

**Comment by eddieridwan** [comment]
Icon modul admin
![database](https://cloud.githubusercontent.com/assets/249563/20507180/0e30ebec-b0be-11e6-9cd8-ab50bf457774.png)
![go-home-5](https://cloud.githubusercontent.com/assets/249563/20508921/e51814b8-b0c9-11e6-81ff-0e2ff92036f5.png)
![preferences-contact-list](https://cloud.githubusercontent.com/assets/249563/20508943/07540d16-b0ca-11e6-9255-9b4317079794.png)
![applications-office-5](https://cloud.githubusercontent.com/assets/249563/20508959/1ea8167e-b0ca-11e6-9f60-4306d899b750.png)
![analysis](https://cloud.githubusercontent.com/assets/249563/20508969/2d640c4a-b0ca-11e6-9e92-5fa12e9c2bf9.png)
![program](https://cloud.githubusercontent.com/assets/249563/20508977/3baa7db6-b0ca-11e6-913f-8a7ae7352cc0.png)
![persil](https://cloud.githubusercontent.com/assets/249563/20508991/4d9d046c-b0ca-11e6-9be6-a9043b8b2734.png)
![plan](https://cloud.githubusercontent.com/assets/249563/20508992/4dd7e30c-b0ca-11e6-8441-c193d4125dd7.png)
![gis](https://cloud.githubusercontent.com/assets/249563/20509002/5b255558-b0ca-11e6-89a6-11981c205cff.png)
![mail-send-receive](https://cloud.githubusercontent.com/assets/249563/20509017/6f087492-b0ca-11e6-8cdc-a886f70f2b5d.png)
![system-users](https://cloud.githubusercontent.com/assets/249563/20509021/7bd8113c-b0ca-11e6-962f-92c079df42a9.png)
![message-news](https://cloud.githubusercontent.com/assets/249563/20509030/88a1e2f8-b0ca-11e6-912d-1b2416b8654e.png)
![mail-reply-all](https://cloud.githubusercontent.com/assets/249563/20509036/952ff172-b0ca-11e6-970c-e880307dcd9d.png)




![ekspor-format-impor-excel](https://cloud.githubusercontent.com/assets/249563/20508254/284c3bce-b0c5-11e6-8009-dd673fdfdee9.jpg)

**Comment by eddieridwan** [comment]
![tombol-edit-wiki](https://cloud.githubusercontent.com/assets/249563/20545837/4a41cc06-b176-11e6-84b6-09f8cb8e82ff.jpg)

![daftar-revisi-wiki](https://cloud.githubusercontent.com/assets/249563/20546222/c82bff2c-b178-11e6-9e50-40b565523988.jpg)
![tombol-lihat-revisi-wiki](https://cloud.githubusercontent.com/assets/249563/20546221/c82b5f18-b178-11e6-9e1d-65d01b48f107.jpg)
![preview-gambar-wiki](https://cloud.githubusercontent.com/assets/249563/20546224/c82e3b02-b178-11e6-9f6c-ec58e08e303a.jpg)
![script-gambar-wiki-80-persen](https://cloud.githubusercontent.com/assets/249563/20546220/c82b78a4-b178-11e6-9aeb-59591161f79c.jpg)
![upload-gambar-wiki](https://cloud.githubusercontent.com/assets/249563/20546225/c82ebd70-b178-11e6-8715-e78d8f37b33e.jpg)
![simpan-suntingan-wiki](https://cloud.githubusercontent.com/assets/249563/20546223/c82d62fe-b178-11e6-877c-00b644d0a0e6.jpg)
![tampilan-preview-wiki](https://cloud.githubusercontent.com/assets/249563/20546226/c85a25fa-b178-11e6-89ce-7b4bda54329c.jpg)
![sunting-halaman-pakai-markdown](https://cloud.githubusercontent.com/assets/249563/20546227/c85d8c2c-b178-11e6-9d59-28818ad73b6b.jpg)

**Comment by eddieridwan** [comment]
![tanya-jawab-update-1](https://cloud.githubusercontent.com/assets/249563/20549936/8a34bb42-b195-11e6-818b-338268f3c826.jpg)

**Comment by eddieridwan** [comment]
v1.5
![tampilan-sebutan-jorong](https://cloud.githubusercontent.com/assets/249563/20827952/2e7654ba-b8c9-11e6-8c87-27633e972756.jpg)

**Comment by buchary** [comment]
![peta desa](https://cloud.githubusercontent.com/assets/20512335/20911605/e2c4e10c-bba3-11e6-84d0-2dddc458ab93.jpg)

**Comment by eddieridwan** [comment]
Program bantuan
![menu-web-statistik-program-bantuan](https://cloud.githubusercontent.com/assets/249563/21008719/8557c81c-bd75-11e6-9c71-6814d2dd0661.jpg)
![tabel-program-bantuan](https://cloud.githubusercontent.com/assets/249563/21008720/855c5e9a-bd75-11e6-89c5-fa69259c3022.jpg)

**Comment by buchary** [comment]
![logo desa](https://cloud.githubusercontent.com/assets/20512335/21547540/b4f141e0-ce21-11e6-8117-7eeb73f57ceb.jpg)

**Comment by Dedi83** [comment]
![cetak surat](https://cloud.githubusercontent.com/assets/19701605/23361386/0414331a-fd23-11e6-8686-251a33b9af19.png)

**Comment by Dedi83** [comment]
![cetak surat](https://cloud.githubusercontent.com/assets/19701605/23361604/0a094232-fd24-11e6-8ab3-510a6377d877.png)

**Comment by TAHTA24** [comment]
![1](https://cloud.githubusercontent.com/assets/22760871/24071086/562f333e-0c05-11e7-9bb3-ce6901138ef6.png)
![2](https://cloud.githubusercontent.com/assets/22760871/24071087/563faee4-0c05-11e7-8479-3509d9574a86.png)
![3](https://cloud.githubusercontent.com/assets/22760871/24071088/564472b2-0c05-11e7-9ec5-c345c0b62df0.png)
![4](https://cloud.githubusercontent.com/assets/22760871/24071089/564dd0dc-0c05-11e7-81da-4964bde43b1c.png)

**Comment by aliftara** [comment]
![plan-lokasi](https://user-images.githubusercontent.com/34668262/35547765-a5e7b318-05ad-11e8-983d-de742036ce1e.png)

**Comment by ariandii** [comment]
![1](https://user-images.githubusercontent.com/46939846/52827705-90bf7580-30f8-11e9-82ff-1cd071ca27e4.png)
![2](https://user-images.githubusercontent.com/46939846/52827706-90bf7580-30f8-11e9-953d-60ea6b000950.png)
![3](https://user-images.githubusercontent.com/46939846/52827707-91580c00-30f8-11e9-9208-7a1ab75d25d1.png)
![4](https://user-images.githubusercontent.com/46939846/52827709-91580c00-30f8-11e9-8136-8c19a6ee2fb0.png)
![5](https://user-images.githubusercontent.com/46939846/52827710-91f0a280-30f8-11e9-8837-77592ff96c52.png)
![6](https://user-images.githubusercontent.com/46939846/52827711-91f0a280-30f8-11e9-8780-ca644f10292e.png)
![7](https://user-images.githubusercontent.com/46939846/52827712-91f0a280-30f8-11e9-952a-2bdace09b8c9.png)
![8](https://user-images.githubusercontent.com/46939846/52827715-92893900-30f8-11e9-93b0-0a1ff641271a.png)
![9-i](https://user-images.githubusercontent.com/46939846/52827717-92893900-30f8-11e9-98be-3c09604c04fb.png)
![9-s](https://user-images.githubusercontent.com/46939846/52827718-92893900-30f8-11e9-974d-68b2926b765f.png)
![10](https://user-images.githubusercontent.com/46939846/52827719-9321cf80-30f8-11e9-8b5d-f5d7eb347c8d.png)
![11](https://user-images.githubusercontent.com/46939846/52827720-93ba6600-30f8-11e9-8ede-8216358a154e.png)
![12](https://user-images.githubusercontent.com/46939846/52827721-93ba6600-30f8-11e9-9551-d13ab2005bae.png)
![13](https://user-images.githubusercontent.com/46939846/52827722-9452fc80-30f8-11e9-9b92-05411207476e.png)
![14](https://user-images.githubusercontent.com/46939846/52827723-9452fc80-30f8-11e9-8328-5198c95b5c68.png)
![15](https://user-images.githubusercontent.com/46939846/52827724-94eb9300-30f8-11e9-8abd-e1b0609bd19b.png)
![16](https://user-images.githubusercontent.com/46939846/52827726-94eb9300-30f8-11e9-8214-4cf33fbe969e.png)

**Comment by mizwaruddin** [comment]
![pengguna_2](https://user-images.githubusercontent.com/39736008/97130022-dd36d180-1772-11eb-85d0-2a126dd534e4.png)

**Comment by mizwaruddin** [comment]
![pengguna_3](https://user-images.githubusercontent.com/39736008/97130168-3141b600-1773-11eb-95e2-c5dcd301cd7c.png)

**Comment by mizwaruddin** [comment]
![pengguna_4](https://user-images.githubusercontent.com/39736008/97139462-23009380-178d-11eb-8653-c257a7cb8c0d.png)

**Comment by mizwaruddin** [comment]
![pengguna_5](https://user-images.githubusercontent.com/39736008/97139581-6b1fb600-178d-11eb-9560-a1d9ef15c64b.png)

**Comment by mizwaruddin** [comment]
![pengguna_6](https://user-images.githubusercontent.com/39736008/97143876-12a0e680-1796-11eb-8a36-36217e399206.png)

**Comment by mizwaruddin** [comment]
![pengguna_7](https://user-images.githubusercontent.com/39736008/97143958-36fcc300-1796-11eb-9f61-897bcb8079c3.png)

**Comment by mizwaruddin** [comment]
![pengguna_8](https://user-images.githubusercontent.com/39736008/97144866-cf477780-1797-11eb-8168-79f3185de9c1.png)

**Comment by mizwaruddin** [comment]
![pengguna_9](https://user-images.githubusercontent.com/39736008/97145923-94deda00-1799-11eb-84ab-7286db968617.png)

**Comment by mizwaruddin** [comment]
![pengguna_10](https://user-images.githubusercontent.com/39736008/97147093-8a254480-179b-11eb-8cab-5d800a7956fd.png)

**Comment by mizwaruddin** [comment]
![pengguna_11](https://user-images.githubusercontent.com/39736008/97147137-9c9f7e00-179b-11eb-8ea8-f41b9c71411e.png)

**Comment by mizwaruddin** [comment]
![qr_1](https://user-images.githubusercontent.com/39736008/97186963-88c43e00-17d4-11eb-9955-13c1e6a6e712.png)

**Comment by mizwaruddin** [comment]
![qr_2](https://user-images.githubusercontent.com/39736008/97189093-cf1a9c80-17d6-11eb-832f-97011e9ae7b8.png)

**Comment by mizwaruddin** [comment]
![qr_3](https://user-images.githubusercontent.com/39736008/97190542-6b916e80-17d8-11eb-8017-6f29b3dbd662.png)

**Comment by mizwaruddin** [comment]
![identitas_1](https://user-images.githubusercontent.com/39736008/97192967-0d19bf80-17db-11eb-9426-696cf296907c.png)

**Comment by mizwaruddin** [comment]
![ubah_2](https://user-images.githubusercontent.com/39736008/97197215-f4f86f00-17df-11eb-98d0-9abaa984dfa6.png)

**Comment by mizwaruddin** [comment]
![ubah_4](https://user-images.githubusercontent.com/39736008/97203291-2f193f00-17e7-11eb-945b-938218520a85.png)

**Comment by mizwaruddin** [comment]
![ubah_5](https://user-images.githubusercontent.com/39736008/97205058-802a3280-17e9-11eb-9027-c12ebb530c1f.png)

**Comment by mizwaruddin** [comment]
![ubah_3](https://user-images.githubusercontent.com/39736008/97206323-23c81280-17eb-11eb-85fa-62f6b23e538e.png)

**Comment by mizwaruddin** [comment]
![ubah_6](https://user-images.githubusercontent.com/39736008/97206446-53771a80-17eb-11eb-8890-03862f94dcf1.png)

**Comment by mizwaruddin** [comment]
![ubah_7](https://user-images.githubusercontent.com/39736008/97206628-8f11e480-17eb-11eb-8037-f74c68180226.png)

**Comment by mizwaruddin** [comment]
![ubah_8](https://user-images.githubusercontent.com/39736008/97245739-47607c80-182e-11eb-9f8f-1498a0c67f4f.png)

**Comment by mizwaruddin** [comment]
![ubah_9](https://user-images.githubusercontent.com/39736008/97247319-04080d00-1832-11eb-861c-0cc013b7fb77.png)

**Comment by mizwaruddin** [comment]
![ubah_10](https://user-images.githubusercontent.com/39736008/97247475-577a5b00-1832-11eb-94af-c0d481c62070.png)

**Comment by mizwaruddin** [comment]
![ubah_11](https://user-images.githubusercontent.com/39736008/97247577-88f32680-1832-11eb-9623-e58888eb9521.png)

**Comment by mizwaruddin** [comment]
![ubah_12](https://user-images.githubusercontent.com/39736008/97249795-26e8f000-1837-11eb-90f0-d2afc82520dd.png)

**Comment by mizwaruddin** [comment]
![ubah_13](https://user-images.githubusercontent.com/39736008/97250105-d02fe600-1837-11eb-8916-e6708605fb52.png)

**Comment by mizwaruddin** [comment]
![ubah_14](https://user-images.githubusercontent.com/39736008/97250212-138a5480-1838-11eb-9b9e-e1774e3ae45a.png)

**Comment by mizwaruddin** [comment]
![administratif_1](https://user-images.githubusercontent.com/39736008/97302591-e071b080-188b-11eb-825f-dd9f485d6ea1.png)

**Comment by mizwaruddin** [comment]
![administratif_2](https://user-images.githubusercontent.com/39736008/97303209-b10f7380-188c-11eb-9e58-b91dea4d5ffa.png)

**Comment by mizwaruddin** [comment]
![administratif_3](https://user-images.githubusercontent.com/39736008/97303533-16fbfb00-188d-11eb-895d-03f613b39143.png)

**Comment by mizwaruddin** [comment]
![administratif_4](https://user-images.githubusercontent.com/39736008/97303956-ac978a80-188d-11eb-8ddf-24373516a529.png)

**Comment by mizwaruddin** [comment]
![administratif_5](https://user-images.githubusercontent.com/39736008/97304096-df418300-188d-11eb-9f0b-97459106891d.png)

**Comment by mizwaruddin** [comment]
![administratif_6](https://user-images.githubusercontent.com/39736008/97304289-1d3ea700-188e-11eb-9925-674b7010b5c5.png)

**Comment by mizwaruddin** [comment]
![administratif_7](https://user-images.githubusercontent.com/39736008/97304464-5545ea00-188e-11eb-866c-eecf52936595.png)

**Comment by mizwaruddin** [comment]
![administratif_8](https://user-images.githubusercontent.com/39736008/97304702-afdf4600-188e-11eb-85ea-71b6d4da0566.png)

**Comment by mizwaruddin** [comment]
![rw_1](https://user-images.githubusercontent.com/39736008/97319700-b4602a80-189f-11eb-87e3-af57882ce46b.png)

**Comment by mizwaruddin** [comment]
![rw_2](https://user-images.githubusercontent.com/39736008/97319916-e70a2300-189f-11eb-97c2-b17c217e537c.png)

**Comment by mizwaruddin** [comment]
![rw_3](https://user-images.githubusercontent.com/39736008/97320305-3cdecb00-18a0-11eb-985b-eaae5125d007.png)

**Comment by mizwaruddin** [comment]
![rw_4](https://user-images.githubusercontent.com/39736008/97320401-554ee580-18a0-11eb-88dd-af2ac89b1a94.png)

**Comment by mizwaruddin** [comment]
![rw_5](https://user-images.githubusercontent.com/39736008/97320619-90e9af80-18a0-11eb-9e02-9d15962f73b4.png)

**Comment by mizwaruddin** [comment]
![rw_6](https://user-images.githubusercontent.com/39736008/97320697-a6f77000-18a0-11eb-9b2d-02c6d21a7844.png)

**Comment by mizwaruddin** [comment]
![rt_1](https://user-images.githubusercontent.com/39736008/97320893-dc9c5900-18a0-11eb-8de1-50dd02c58845.jpg)

**Comment by mizwaruddin** [comment]
![rt_3](https://user-images.githubusercontent.com/39736008/97321148-25541200-18a1-11eb-825a-e8d1bfe21395.png)

**Comment by mizwaruddin** [comment]
![rt_4](https://user-images.githubusercontent.com/39736008/97321253-41f04a00-18a1-11eb-9052-e59618a01529.png)

**Comment by mizwaruddin** [comment]
![rt_5](https://user-images.githubusercontent.com/39736008/97321533-909de400-18a1-11eb-9801-07b4b7c1cf9c.png)

**Comment by mizwaruddin** [comment]
![rt_6](https://user-images.githubusercontent.com/39736008/97321604-a4e1e100-18a1-11eb-9023-c0db3021ab3d.png)

**Comment by mizwaruddin** [comment]
![cetak_1](https://user-images.githubusercontent.com/39736008/97324242-33576200-18a4-11eb-928c-917a8660b033.png)

**Comment by mizwaruddin** [comment]
![cetak_2](https://user-images.githubusercontent.com/39736008/97325393-84b42100-18a5-11eb-88c1-92102eccf438.png)

**Comment by mizwaruddin** [comment]
![cetak_3](https://user-images.githubusercontent.com/39736008/97325550-b3ca9280-18a5-11eb-9f5e-ae4814d16885.png)

**Comment by mizwaruddin** [comment]
![pemdes_1](https://user-images.githubusercontent.com/39736008/97395726-21170b80-1918-11eb-95f6-8edd97d6932e.png)

**Comment by mizwaruddin** [comment]
![pemdes_2](https://user-images.githubusercontent.com/39736008/97395896-8a971a00-1918-11eb-88dd-c65a654d8a57.png)

**Comment by mizwaruddin** [comment]
![pemdes_3](https://user-images.githubusercontent.com/39736008/97395967-b31f1400-1918-11eb-8d97-80d0d73eed7d.png)

**Comment by mizwaruddin** [comment]
![pemdes_4](https://user-images.githubusercontent.com/39736008/97396128-085b2580-1919-11eb-815b-77728ea3b446.png)

**Comment by mizwaruddin** [comment]
![pemdes_5](https://user-images.githubusercontent.com/39736008/97396278-4fe1b180-1919-11eb-9839-3cd659eebc6d.png)

**Comment by mizwaruddin** [comment]
![pemdes_6](https://user-images.githubusercontent.com/39736008/97397167-380b2d00-191b-11eb-9bea-afe15125f918.png)

**Comment by mizwaruddin** [comment]
![pemdes_7](https://user-images.githubusercontent.com/39736008/97397254-6a1c8f00-191b-11eb-8977-d70ac3882613.png)

**Comment by mizwaruddin** [comment]
![pemdes_8](https://user-images.githubusercontent.com/39736008/97397395-b5cf3880-191b-11eb-91c2-749cbb7e45d3.png)

**Comment by mizwaruddin** [comment]
![pemdes_9](https://user-images.githubusercontent.com/39736008/97397594-33934400-191c-11eb-80f2-817786d9e938.png)

**Comment by mizwaruddin** [comment]
![pemdes_10](https://user-images.githubusercontent.com/39736008/97397713-81a84780-191c-11eb-9752-d54a6a704d99.png)

**Comment by mizwaruddin** [comment]
![pemdes_11](https://user-images.githubusercontent.com/39736008/97397776-a00e4300-191c-11eb-8743-e6053259bcb6.png)

**Comment by mizwaruddin** [comment]
![pemdes_12](https://user-images.githubusercontent.com/39736008/97397907-dea3fd80-191c-11eb-8d13-58c4cd61755b.png)

**Comment by mizwaruddin** [comment]
![pemdes_13](https://user-images.githubusercontent.com/39736008/97398227-65f17100-191d-11eb-8e03-abc297a2c86d.png)

**Comment by mizwaruddin** [comment]
![pemdes_15](https://user-images.githubusercontent.com/39736008/97398315-91745b80-191d-11eb-846c-514c00d513cb.png)

**Comment by mizwaruddin** [comment]
![pemdes_16](https://user-images.githubusercontent.com/39736008/97398386-bd8fdc80-191d-11eb-920a-7c183a6e7e11.png)
