### ISSUE TITLE
Bug: Pada rincian rumah tangga, kepala rumah tangga di judul berbeda dengan di daftar anggota

### ISSUE THREAD

**Issue by afri18** [eddieridwan/OpenSID#163]
kenapa saat klik detail di daftar rumah tangga nggak sinkron ya ???
![image](https://cloud.githubusercontent.com/assets/6611881/19235769/e3bd5682-8f1d-11e6-8852-ae35f84fdc3d.png)

**Comment by eddieridwan** [comment]
Bung @afri18 , bisa tolong jelaskan penggunaan fitur _Rumah Tangga_. Apa bedanya dengan _Keluarga_? Karena di panduan CRI tidak ditemukan penjelasan.

**Comment by afri18** [comment]
Rumah Tangga bisa disebut suatu rumah utuh/besar, didalamnya bisa terdapat 2 bahkan lebih kepala keluarga
jadi Rumah Tangga adalah yang memasak/dapur sendiri, didalamnya bisa terdapat 2 atau lebih kepala keluarga (kartu keluarga)

**Comment by eddieridwan** [comment]
@afri18:

1. apakah harus suatu keluarga (sebagaimana tertera di kartu keluarga) secara keseluruhan menjadi anggota suatu rumah tangga, atau bolehkan hanya sebagian  dari keluarga itu? Sepertinya harus keseluruhan, karena kalau hanya sebagian, alamat di kartu keluarga tidak lagi berlaku bagi keluarga itu -- benar?
2. haruskah salah satu kepala keluarga yang menjadi kepala rumah tangga, atau bolehkah siapa saja dari anggota rumah tangga menjadi kepala rumah tangga?

**Comment by eddieridwan** [comment]
@afri18 bisa berikan contoh praktis penggunaan data rumah tangga? Apakah hanya laporan cetak dan excel yang ada di laman Rumah Tangga?

**Comment by eddieridwan** [comment]
Sdh dicommit.

**Comment by afri18** [comment]
apakah poin ini sudah di mengerti ?? karna sudah di tutup
Rumah tangga (rumah besar) bisa terdiri dari beberapa Kartu Keluarga dan kepala rumah tangganya adalah yang pertama atau yg tua atau yang menanggung biaya dapur

**Comment by eddieridwan** [comment]
1. Jadi rumah tangga terdiri dari Keluarga, bukan perorangan seperti fitur Tambah RT saat ini? Apakah sistem perlu diubah supaya hanya memperlihatkan Keluarga pada waktu Tambah Rumah Tangga dan Tambah Anggota RT?
1. Saat ini siapa saja bisa dipilih sebagai kepala rumah tangga. Apakah sistem perlu membatasi pada kepala keluarga atau boleh siapa saja?
1. Apakah perlu fitur untuk mengubah rumah tangga? Sekarang tidak ada. Apanya yang perlu diubah (ganti kepala RT, hapus KK)?

Silakan membuat issue baru (terpisah) untuk masing-masing tugas, apabila memang diperlukan.

**Comment by afri18** [comment]
fiturnya nggak usah di ubah, ug jadi permasalahan saat klik detail satu Rumah Tangga nggak singkron dengan judul di atas : 
![image](https://cloud.githubusercontent.com/assets/6611881/20459378/d1b32de2-aef1-11e6-989d-cfde01692ad3.png)

![image](https://cloud.githubusercontent.com/assets/6611881/20459398/8041ca4e-aef2-11e6-84da-aa8226dd1db0.png)

**Comment by eddieridwan** [comment]
Seperti bisa dilihat di atas, error itu sudah diperbaiki di cabang master (makanya issue ini sudah ditutup). 

Tetapi, apabila pendapat anda betul mengenai fungsi Rumah Tangga dan kaitannya dengan Keluarga, maka fitur Tambah Rumah Tangga dan Tambah Anggota RT yg sekarang ada salah dan akan membuat pengguna baru bingung. Kita ingin agar fitur ini sejelas mungkin bagi pengguna baru dan mengurangi kemungkinan mereka membuat kesalahan.

Jadi pertanyaan berikut masih berlaku:

1. apakah sebaiknya Tambah Rumah Tangga dan Tambah Anggota RT menyediakan pilihan Keluarga dan bukan Penduduk?
1. apakah kepala RT sebaiknya dibatasi pada kepala Keluarga?
1. Apakah perlu fitur untuk mengubah rumah tangga? Sekarang tidak ada. Apanya yang perlu diubah (ganti kepala RT, hapus KK)?

**Comment by afri18** [comment]
Jawab : 
1. Tambah Anggota Rumah Tangga sbaiknya tetap penduduk, bisa aja anggota kk sudah terpisah cuma belom memperbarui kartu keluarga
2. kepala Rumah Tangga bisa aja anggota dalam kartu keluarga (keluarga) jadi sebaiknya jangan dibatasi hanya kepala keluarga
3. yang sangat dibutuhkan ganti kepala Rumah tangga, bila Kepala Rumah Tangga Wafat/Pindah
salut buat BUNG EDDIE sangat cepat responnya, menjadikan OPENSID lebih KOMPLIT buat DESA
