### ISSUE TITLE
Fitur: Mengeluarkan surat untuk pemohon non_warga/penduduk

### ISSUE THREAD

**Issue by afri18** [eddieridwan/OpenSID#164]
Untuk sesuatu keperluan kadang ada yg bukan penduduk mohon dibuatkan surat keterangan domisili usaha, saya coba tapi nggak konek saat cetak maupun export , mohon bantuan
![image](https://cloud.githubusercontent.com/assets/6611881/19238168/71c7d784-8f2a-11e6-91db-54f1baca87a9.png)

**Comment by eddieridwan** [comment]
@afri18 Apakah mendapat error seperti di bawah ini? Ini disebabkan pencetakan surat perlu NIK pemohon surat. Harap konfirmasi dan saya bisa coba mencari jalan untuk support surat di mana pemohonnya non-warga.

![surat-non-warga](https://cloud.githubusercontent.com/assets/249563/19339498/4f82746c-9156-11e6-9cea-a53b07b6fd06.jpg)

**Comment by afri18** [comment]
tobol cetak dan export tidak jalan alias blank target, padahal file sudah disiapkan

**Comment by akbar12** [comment]
tidak ada pesan error mungkin karena aplikasi berjalan pada 'production mode'.
Issue ini akan saya kerjakan.

**Comment by eddieridwan** [comment]
Kalau bisa mohon fokus pada surat export doc dulu. Di controller surat.php, pencetakan surat export doc diatur di _function doc()_. Seperti terlihat di situ, saat ini ada asumsi selalu ada id penduduk yang dikirim dari form isian surat, seperti 

```
		$id = $_POST['nik'];
		// surat_persetujuan_mempelai id-nya suami atau istri
		if (!$id) $id = $_POST['id_suami'];
		if (!$id) $id = $_POST['id_istri'];
```
Jadi kalau tidak ada nik/id penduduk, perlu diubah, termasuk penyesuain di surat_model.php dan surat_keluar_model.php.

**Comment by akbar12** [comment]
@eddieridwan Baik, maksudnya saya juga kerjakan yg export (issue ini).  Nanti saya kabari lagi setelah eksplorasi fitur ini.

**Comment by eddieridwan** [comment]
Bung @afri18, mohon lampirkan script form dan template rtf untuk surat contoh anda, supaya bung @akbar12 mempunyai surat nyata untuk dicoba.

**Comment by afri18** [comment]
nggak bisa muat disini bisa bung @akbar12  kirim email, karna zip saya nggak bisa masuk di sini

**Comment by eddieridwan** [comment]
@akbar12, sesudah menerima file dari bung Syahfri, sebaiknya dilampirkan di sini.

**Comment by akbar13** [comment]
Maaf saya switch ke akun ini ya, saya kelupaan akun yg di atas itu akun kantor.

Baik, kirimkan saja ke akbar.syahdamar@gmail.com @afri18 @eddieridwan

**Comment by akbar13** [comment]
Halo mas @afri18 , saya tunggu template suratnya ya...

**Comment by eddieridwan** [comment]
[surat_domisili_usaha_non_warga.zip](https://github.com/eddieridwan/OpenSID/files/752167/surat_domisili_usaha_non_warga.zip)

**Comment by afri18** [comment]
tetap nggak bisa saya inbok di fb aja

**Comment by eddieridwan** [comment]
[surat_domisili_usaha_non_warga rtf.zip](https://github.com/eddieridwan/OpenSID/files/752819/surat_domisili_usaha_non_warga.rtf.zip)

**Comment by akbar13** [comment]
terimakasih @eddieridwan

**Comment by eddieridwan** [comment]
Sudah sampai mana bung @akbar13 ? Kalau ada yang tidak jelas, silakan bertanya.

**Comment by akbar13** [comment]
@eddieridwan saya sudah menambah data master surat, dan sedang menyesuaikan script form yg diberi mas @afri18 dengan program SID.

**Comment by afri18** [comment]
![image](https://cloud.githubusercontent.com/assets/6611881/22786730/5eb46b2a-ef0c-11e6-9474-5d1874658790.png)

**Comment by akbar13** [comment]
Bisa-bisa saja mas @afri18 , kalo saya tergantung persetujuan mas @eddieridwan saja.

**Comment by akbar13** [comment]
mas @eddieridwan data orang yg non warga ini mau disimpan di tabel `tweb_penduduk` dan dibedakan dengan warga melalui kolom `status` atau mau dibuatkan tabel baru?

**Comment by akbar13** [comment]
mas @eddieridwan data orang yg non warga ini mau disimpan di tabel `tweb_penduduk` dan dibedakan dengan warga melalui kolom `status` atau mau dibuatkan tabel baru? menurut saya dibuatkan tabel baru mungkin jadi solusi yg paling praktis.

**Comment by afri18** [comment]
bung @akbar13 , datanya jangan disimpan karna orangnya tidak tinggal dalam desa, dia hanya mempunyai usaha/toko/warung saja
untuk penduduk tidak tetap memang seharusnya bisa dilayani administrasinya, cuma di SID saat ini tidak bisa

**Comment by eddieridwan** [comment]
Bung @akbar13, beberapa pertimbangan:

1. data orang pemohon non-warga tidak perlu disimpan di tabel tersendiri
1. tetapi surat yang dihasilkan tetap harus bisa masuk arsip dan ditampilkan di tabel _Surat Keluar_.. Untuk itu perlu ada info siapa pemohon surat. Salah satu kemungkinan adalah menambah kolom di tabel _log_surat_ untuk menyimpan nama pemohon, dan info ini ditampilkan di daftar surat keluar apabila kolom _id_penduduk_ kosong (karena bukan warga).
1. bahwa suatu surat adalah untuk pemohon non-warga bisa terdeteksi apabila $_POST tidak berisi nik, id_suami atau id_istri (jadi sepertinya tidak perlu ada tombol khusus). Kalau sudah terdeteksi penanganan pencetakan surat export doc akan berbeda dengan yang berbasis data penduduk. Dalam hal surat pemohon non-warga, data yang ditampilkan di surat adalah data yang terkumpul di form surat.

**Comment by akbar13** [comment]
![2017-02-13-22-20-localhost](https://cloud.githubusercontent.com/assets/24959380/22889866/26ec04ee-f23d-11e6-9c54-7b08753e2197.png)
![2017-02-13-22-20-localhost 1](https://cloud.githubusercontent.com/assets/24959380/22889878/2d466096-f23d-11e6-87ea-225de2d6a6d3.png)
![2017-02-13-22-37-localhost](https://cloud.githubusercontent.com/assets/24959380/22889885/332d15f4-f23d-11e6-9897-ed1adf1cc9d3.png)

mas @afri18 Form dan Cetak Surat sudah berfungsi. Silahkan dikoreksi melalui gambar screenshot di atas.
mas @eddieridwan Log surat keluar sudah disesuaikan dengan melakukan penambahan field nama pemohon non warga pada table log_surat dan sedikit modifikasi surat_keluar_model. masih perlu sedikit penyesuaian pada tampilan list surat keluar.

**Comment by eddieridwan** [comment]
@akbar13 maaf baru lihat. Bagus. Sepertinya surat ini bermanfaat untuk semua desa, jadi mungkin ada baiknya kalau kita tambahkan pada surat sistem. Yaitu bagian dari file inti, bukan di folder desa. 

Dengan demikian, entri untuk surat ini perlu ada di tabel tweb_surat_format. Untuk menerapkan itu, perlu ditambahkan migrasi baru di file donjo-app/models/database_model.php untuk insert row untuk surat ini.

Nanti kalau sudah di-acc oleh bung @afri18, dan anda sudah lakukan testing (jangan lupa rebase dulu ke branch master -- yang sudah berubah), silakan buat pull request.

**Comment by eddieridwan** [comment]
Bung @akbar13, sudah lama tidak ada kabar. Sudah sampai di mana? Ada yang bisa di-merge?

**Comment by akbar13** [comment]
Oh halo mas @eddieridwan .. maaf beberapa waktu yg lalu saya masih banyak perkerjaan di kantor, ini saya mau mulai lagi. Saya usahakan minggu ini/minggu depan pull request.

**Comment by eddieridwan** [comment]
@akbar13, apa kabar? Apakah sudah sempat membuat pull request?

**Comment by dadannurman** [comment]
Para Master mohon maaf saya lancang,
Surat Keterangan kepemilikan tanah non warga juga membutuhkan Format surat ini.
Apakah sudah ada solusinya master?

**Comment by eddieridwan** [comment]
@akbar12 @akbar13 : sudah lama tidak ada kabar. Apakah akan meneruskan penerapan issue ini?

**Comment by eddieridwan** [comment]
Ok, karena sudah terlalu lama, kami kerjakan issue ini.
Sudah dicommit ke master.
