### ISSUE TITLE
Bug: Surat Export Doc tidak menampilkan surat pada instalasi online

### ISSUE THREAD

**Issue by afri18** [eddieridwan/OpenSID#168]
kenapa waktu surat saya buat online di tombol export nggak mau mengunduh/download ya ???
kalau di ofline lancar jaya
apa temen yang memakai opensid secara online mengalami ini ??

**Comment by batudaa** [comment]
Sudah diperiksa lokasi pada LOKASI_SURAT_EXPORT_DESA bisa ditulisi atau tidak?

Default 'desa/surat/export/'

**Comment by afri18** [comment]
itu di file mana ?? disaya yg ofline lancar kode tombol exportnya : 
<?php if (SuratExport($url)) { ?><button type="button" onclick="$('#'+'validasi').attr('action','<?php echo $form_action2?>');$('#'+'validasi').submit();" class="uibutton confirm"><span class="ui-icon ui-icon-document">&nbsp;</span>Export Doc</button><?php } ?>
cuma yg di online gagal url terbaca : 
http://cigelam.desa.id/index.php/surat/doc/surat_ket_penduduk

**Comment by eddieridwan** [comment]
Check folder _desa/arsip_ sudah dibuat di htdocs online. Folder ini tempat menyimpan surat yang dihasilkan oleh proses export doc.

**Comment by afri18** [comment]
betul bung eddieridwan , ternyata terunduh di folder desa/arsip, pertanyaan selanjutnya kenapa nggak bisa langsung terbuka ya ?? padahal saat memakai sid 3.04 cri berjalan mulus, mohon solusi

**Comment by eddieridwan** [comment]
@afri18 , di folder online _desa/arsip_ nama file yang tersimpan apa saja?
Di laman Cetak Surat > Surat Keluar, apakah suratnya bisa diunduh dari situ?

Apakah suratnya terunduh ke folder (misalnya folder _downloads_) di komputer anda? Kadang2 suratnya terunduh sebagai file dan tidak terbuka langsung. Kalau ini terjadi, buka saja file ini untuk dicetak.

**Comment by afri18** [comment]
semua jenis surat yg pernah dicoba export via online tersimpan di online desa/arsip, yang lancar saat export format KK rtf langsung terbuka, ini folder cpanel online
![image](https://cloud.githubusercontent.com/assets/6611881/19476343/d576c3ba-9562-11e6-8230-5d1fe3c864b5.png)

hanya surat belum ketemu. tidak bisa di unduh dari halaman Surat Keluar, karna tidak terbaca, kalau yang offline terbaca.
setingan untuk semua browser untuk unduhan/download file rtf/doc langsung membuka saat selesai mengunduh, dan ini tidak terjadi kecuali offline

**Comment by eddieridwan** [comment]
Apakah di halaman Surat Keluar, tombol cetak/unduk tampak, seperti terlihat di gambar berikut. Apa yang terjadi saat tombol itu di-klik?

![surat-keluar](https://cloud.githubusercontent.com/assets/249563/19515988/7463550a-962c-11e6-8c39-22cd47964d22.jpg)

**Comment by eddieridwan** [comment]
Kalau bisa, juga perlihatkan isi tabel _log_surat_. Di phpmyadmin, tampilkan tabel log_surat, terus lihat seluruh isi tabel dengan menekan tautan seperti terlihat di gambar berikut. Yang ingin dilihat adalah isi kolom _nama_surat_.

![surat-keluar-2](https://cloud.githubusercontent.com/assets/249563/19516850/a8c815b6-9630-11e6-883f-e05541a40de5.jpg)

**Comment by afri18** [comment]
kosong di log_surat>nama surat
![image](https://cloud.githubusercontent.com/assets/6611881/19586022/7b4c7cb6-977b-11e6-9dd1-7939a6e568f1.png)

tidak satupun yg bisa diunduh ulang surat export doc
![image](https://cloud.githubusercontent.com/assets/6611881/19586049/b4deb48a-977b-11e6-8f7e-177a81043884.png)

mohon petunjuk selanjutnya, karna surat doc nggak bisa di export/diunduh, anehnya untuk kartu keluarga doc/export lancar jaya

**Comment by eddieridwan** [comment]
Tampaknya nama surat tidak terrekam di tabel log_surat.

Ada tiga script yang berperan:

1. donjo-app/controllers/surat.php
1. donjo-app/models/surat_model.php
1. donjo-app/models/surat_keluar_model.php

Apakah anda membuat perubahan pada file-file ini?

Untuk melacak masalahnya, perlu memasukkan baris debugging sebagai berikut:

1. di file donjo-app/controllers/surat.php tambahkan baris error_log sebagai berikut:
```
	function doc($url=''){
		$format = $this->surat_model->get_surat($url);
		$f = $format['id'];
		$g=$_POST['pamong'];
		$u=$_SESSION['user'];
		$z=$_POST['nomor'];

		$id = $_POST['nik'];
		// surat_persetujuan_mempelai id-nya suami atau istri
		if (!$id) $id = $_POST['id_suami'];
		if (!$id) $id = $_POST['id_istri'];
		$sql = "SELECT nik FROM tweb_penduduk WHERE id=?";
		$query = $this->db->query($sql,$id);
		$hasil  = $query->row_array();
		$nik = $hasil['nik'];

		$nama_surat = $this->surat_keluar_model->nama_surat_arsip($url, $nik, $z);
		error_log("Nama surat 1: $nama_surat\n", 3, "php.log"); // <---- tambah baris ini
		$this->surat_model->coba($url, $nama_surat);
		error_log("Nama surat 2: $nama_surat\n", 3, "php.log"); // <---- tambah baris ini
		$this->surat_keluar_model->log_surat($f,$id,$g,$u,$z,$nama_surat);

	}
```

1. di file donjo-app/models/surat_keluar_model.php tambahkan baris error_log sebagai berikut:
```
	function log_surat($f=0,$id='',$g='',$u='',$z='', $nama_surat){

		$data['id_pend']=$id;

			$sql   = "SELECT id FROM tweb_surat_format WHERE url_surat = ?";
			$query = $this->db->query($sql,$f);
			if($query->num_rows() > 0){
				$pam=$query->row_array();
				$data['id_format_surat']=$pam['id'];
			}else{
				$data['id_format_surat'] = $f;
			}

			$sql   = "SELECT pamong_id FROM tweb_desa_pamong WHERE pamong_nama = ?";
			$query = $this->db->query($sql,$g);
			if($query->num_rows() > 0){
				$pam=$query->row_array();
				$data['id_pamong']=$pam['pamong_id'];
			}else{
				$data['id_pamong'] = 1;
			}


		if($data['id_pamong']=='')
			$data['id_pamong'] = 1;

		$data['id_user']=$u;
		$data['bulan']=date('m');
		$data['tahun']=date('Y');
		$data['no_surat']=$z;
		$data['nama_surat']=$nama_surat;
		error_log("Nama surat 3: $nama_surat\n", 3, "php.log"); //<---- Tambah baris ini
		//print_r($data);
		$this->db->insert('log_surat',$data);

	}
```

Export beberapa surat, dengan berbeda jenis surat, NIK dan nomor surat. Setelah itu, harap laporkan isi file _php.log_ (ada di folder root).

**Comment by afri18** [comment]
sudah di coba tapi tetap tidak bisa, malah table log surat sudah saya kosongkan, begitu juga arsipnya, herannya untuk export doc kk bisa .

**Comment by eddieridwan** [comment]
@afri18 , Isi php.log anda tidak konsisten dengan penulisan php.log yg diperlukan di atas:

```
Nama surat 1: surat_ket_penduduk_3275111604780005_2016-10-30_412.rtf
Nama surat 1: surat_ket_penduduk_3275111604780005_2016-10-30_412.rtf
Nama surat 3: 
Nama surat 1: surat_ket_penduduk_3275111604780005_2016-10-30_412.rtf
Nama surat 1: surat_ket_usaha_3275111604780005_2016-10-30_412.rtf
```
Supaya saya bisa bantu melacak masalahnya, harap kirimkan secara utuh/lengkap ketiga file berikut (yang di server online): 

1. donjo-app/controllers/surat.php
1. donjo-app/models/surat_model.php
1. donjo-app/models/surat_keluar_model.php

Nanti saya akan tambahkan baris2 penulisan php.log untuk dijalankan pada server online anda, supaya lebih jelas mengapa nama surat tidak direkam di log_surat.

[php.zip](https://github.com/eddieridwan/OpenSID/files/582958/php.zip)

**Comment by afri18** [comment]
saya inbok di fb, zip tetap nggak bisa

**Comment by afri18** [comment]
saya masih belom bisa export doc online

**Comment by eddieridwan** [comment]
@afri18 , coba ganti ketiga file dengan file pengganti di bawah. Cetak beberapa surat export-doc dan kirimkan php.log.

[donjo_app_cpanel_pengganti.zip](https://github.com/eddieridwan/OpenSID/files/596348/donjo_app_cpanel_pengganti.zip)

**Comment by afri18** [comment]
![Uploading image.png…]()
hsil php log di cpanel
Nama surat 1: surat_ket_penduduk_3214121610670005_2016-11-19_561.rtf
Nama surat 1: surat_ket_catatan_kriminal_3214121610670005_2016-11-19_221.rtf
Nama surat 1: surat_ket_usaha_3214121610670005_2016-11-19_301.rtf

**Comment by afri18** [comment]
hsil php log di cpanel
Nama surat 1: surat_ket_penduduk_3214121610670005_2016-11-19_561.rtf
Nama surat 1: surat_ket_catatan_kriminal_3214121610670005_2016-11-19_221.rtf
Nama surat 1: surat_ket_usaha_3214121610670005_2016-11-19_301.rtf

**Comment by eddieridwan** [comment]
File php.log bisa di-upload dgn mengganti namanya menjadi php.log.txt.

O/S di hosting anda apa: Windows atau Unix, versi apa persisnya?
Sepertinya ada masalah pada waktu menjalankan exec(). Tampaknya _hang_ dan tidak kembali. Tergantung versi O/S anda nanti dicoba buat pendekatan lain.

[php.log.txt](https://github.com/eddieridwan/OpenSID/files/601696/php.log.txt)

**Comment by eddieridwan** [comment]
Oke, coba ganti lagi dengan file terlampir di bawah.
Sekarang dicoba dengan ada timeout pada waktu menjalankan proses O/S supaya dipaksa selesai sesudah 5 detik.
Tolong kirimkan php.log (rename dulu menjadi php.log.txt) sesudah mencoba beberapa surat.

[donjo_app_cpanel_pengganti2.zip](https://github.com/eddieridwan/OpenSID/files/601736/donjo_app_cpanel_pengganti2.zip)

**Comment by afri18** [comment]
tetap nggak bisa, pesan php.log : 
Nama surat 1: surat_ket_penduduk_3275111604780005_2016-11-20_562.rtf
cmd: libreoffice --headless --norestore --convert-to pdf --outdir /home/cigelamdesa/public_html/desa/arsip/ /home/cigelamdesa/public_html/desa/arsip/surat_ket_penduduk_3275111604780005_2016-11-20_562.rtf
Nama surat 1: surat_ket_catatan_kriminal_3275111604780005_2016-11-20_563.rtf
cmd: libreoffice --headless --norestore --convert-to pdf --outdir /home/cigelamdesa/public_html/desa/arsip/ /home/cigelamdesa/public_html/desa/arsip/surat_ket_catatan_kriminal_3275111604780005_2016-11-20_563.rtf
Nama surat 1: surat_ket_usaha_3275111604780005_2016-11-20_564.rtf
cmd: libreoffice --headless --norestore --convert-to pdf --outdir /home/cigelamdesa/public_html/desa/arsip/ /home/cigelamdesa/public_html/desa/arsip/surat_ket_usaha_3275111604780005_2016-11-20_564.rtf

**Comment by afri18** [comment]
![image](https://cloud.githubusercontent.com/assets/6611881/20459346/51f9c026-aef0-11e6-966c-816315d52f9b.png)
herannya untuk export Kartu Keluarga doc lancar ...

**Comment by eddieridwan** [comment]
Operating system di hosting apa? Linux versi apa?

**Comment by afri18** [comment]
lihatnya dari mana ya ? saya lom pernah periksa ..

**Comment by eddieridwan** [comment]
Di cpanel halaman muka.

![cpanel_stats](https://cloud.githubusercontent.com/assets/249563/20459492/f6bada8c-af27-11e6-91a1-8dc8c0a9917a.jpg)

**Comment by afri18** [comment]
![image](https://cloud.githubusercontent.com/assets/6611881/20459752/d1c87a72-aeff-11e6-8ce7-c1911e31478b.png)
ini bukan

**Comment by eddieridwan** [comment]
@afri18 Hostingnya di mana? Sepertinya cpanel hosting anda tidak mengizinkan function php exec(), dan prosesnya mati pada saat memanggil exec(). Untuk menangani kemungkinan ini, coba ganti lagi ketiga file menggunakan file pengganti terlampir.

Coba cetak 3 surat, dan kirimkan file _sid.log_ (ganti nama dari _php.log_).

[donjo_app_cpanel_pengganti3.zip](https://github.com/eddieridwan/OpenSID/files/614073/donjo_app_cpanel_pengganti3.zip)

**Comment by afri18** [comment]
Nama surat 1: surat_ket_penduduk_3275111604780005_2016-11-29_302.rtf
cmd: libreoffice --headless --norestore --convert-to pdf --outdir /home/cigelamdesa/public_html/desa/arsip/ /home/cigelamdesa/public_html/desa/arsip/surat_ket_penduduk_3275111604780005_2016-11-29_302.rtf
Nama surat 1: surat_ket_catatan_kriminal_3275111604780005_2016-11-29_303.rtf
cmd: libreoffice --headless --norestore --convert-to pdf --outdir /home/cigelamdesa/public_html/desa/arsip/ /home/cigelamdesa/public_html/desa/arsip/surat_ket_catatan_kriminal_3275111604780005_2016-11-29_303.rtf
Nama surat 1: surat_ket_usaha_3275111604780005_2016-11-29_304.rtf
cmd: libreoffice --headless --norestore --convert-to pdf --outdir /home/cigelamdesa/public_html/desa/arsip/ /home/cigelamdesa/public_html/desa/arsip/surat_ket_usaha_3275111604780005_2016-11-29_304.rtf

**Comment by eddieridwan** [comment]
Ok, sepertinya hosting anda sama sekali ngambek pada saat menjalankan exec() -- bahkan tidak menerbitkan exception. 

Ini, coba solusi lainnya, di mana langkah itu dilewati sama sekali. Tapi anda harus pastikan di file desa/config/config.php setting $config['libreoffice_path'] tidak ada.

Yang diganti satu file saja: donjo-app/models/surat_model.php.
 Kali ini tidak pakai log file. Laporkan apa hasilnya.

Hosting anda di mana? Kalau di dapurhosting tidak ada masalah.

[surat_model.php.txt](https://github.com/eddieridwan/OpenSID/files/620050/surat_model.php.txt)

**Comment by eddieridwan** [comment]
Solusi di atas berhasil, karena tidak berusaha menjalankan libreoffice apabila tidak ada setting konfigurasinya. Sdh dicommit.

**Comment by afri18** [comment]
saya dah coba update ke 1.5 juga berhasil menjalankan export doc
