### ISSUE TITLE
Bug: OpenSID mengimport tanggal aa/bb/cccc sebagai mm/dd/yyyy bukan dd/mm/yyyy

### ISSUE THREAD

**Issue by syaifudin9** [eddieridwan/OpenSID#169]
Saar import data penduduk dri excel, setelah dilihat kok Kalkulasi umur banyak yang salah padhl di sidcri normal? Apakah ini bug?

**Comment by eddieridwan** [comment]
Bung @syaifudin9, sepertinya sebabnya format tanggal lahir di file excel anda (lihat di bawah) memakai format aa/bb/cccc (bagai garing), yang di-interpretasikan oleh PHP sebagai bln/hari/tahun (format tanggal Amerika/Eropa) -- dan bukan hari/bln/tahun.

Anda bisa mengubah format tanggal anda menjadi aa-bb-cccc (pakai strip), dan akan di-baca sebagai hari-bln-tahun (format tanggal Inggris/Asia).

Untuk solusi jangka panjang, issue ini adalah untuk mengubah OpenSID supaya bisa mengimport tanggal dalam format hari/bln/tahun.

![tanggal-lahir-cri](https://cloud.githubusercontent.com/assets/249563/19416815/d826de8e-93cc-11e6-932c-3fe82e2ba04b.jpg)

**Comment by syaifudin9** [comment]
Nunggu release baru, hehehhe soalnya ngganti ke aa-bb-cccc ga bisa dioffice 2016. Terima kasih

**Comment by eddieridwan** [comment]
Import excel sudah mengenali format dd-mm-yyyy sejak v0.10
