### ISSUE TITLE
Fitur: Tampilkan alamat keluarga di laporan penduduk

### ISSUE THREAD

**Issue by eddieridwan** [eddieridwan/OpenSID#174]
Dari @afri18:

sebenarnya ini berkaitan dengan alamat > saya mencoba menerapkan alamat berisi dengan menambahkan alamat_sekarang, yang nantinya diikutkan dalam alamat tinggal dalam surat
![image](https://cloud.githubusercontent.com/assets/6611881/19234734/cbb896a6-8f17-11e6-8278-3058945f068a.png)
kalau ini form penduduk yang saya sesuaikan tapi alamat > alamat_sekarang lom muncul
![image](https://cloud.githubusercontent.com/assets/6611881/19235073/99bd9c12-8f19-11e6-8c4c-f49463738afd.png)

**Comment by eddieridwan** [comment]
Laman penduduk menampilkan berbagai kolom data penduduk, dan untuk tampilan yang sudah ada tidak ada lagi tempat untuk menampilkan alamat keluarga, kecuali dengan menggantikan data yang sudah ada. 

Kami (moderator) beranggapan belum ada alasan yang kuat untuk menggantikan data yang ada. Karena itu, alamat keluarga tidak akan ditambahkan pada laman penduduk. Alih-alih kami akan tambahkan alamat keluarga di laporan biodata penduduk.

**Comment by afri18** [comment]
yang saya maksud bagai mana menimbulkan alamat di table tweb_keluarga timbul dalam format alamat tinggal dalam surat, jadi alamat dalam surat terdiri dari >alamat[tweb_keluarga]rt,rw,dusun [tweb_penduduk]

**Comment by eddieridwan** [comment]
Sudah dicommit. Penampilan alamat keluarga di surat dimasukkan pada issue terpisah.
