### ISSUE TITLE
Mengubah Title di Website

### ISSUE THREAD

**Issue by buchary** [eddieridwan/OpenSID#175]
Bagaimana cara mengubah title di Website seperti di karangbajo.. Tampak seperti gambar berikut:
![mengubah title](https://cloud.githubusercontent.com/assets/20512335/19752858/eec2d2a6-9c32-11e6-8378-7e74f07d137f.png)

**Comment by eddieridwan** [comment]
Kalau sekadar mengubah icon yang ditampilkan, ganti saja file favicon.ico (di folder root) dengan gambar lain. Namanya harus _favicon.ico_ dan ukurannya bisa 32x32 or 16x16 pixel.

**Comment by buchary** [comment]
Kalau kita ubah, apakah akan berpengaruh pada saat kita update pak Eddie??

**Comment by buchary** [comment]
Untuk Mengubah title.. Misalnya Desa Senggigi ke Website Desa Senggigi.. Caranya bagaimana pak Eddie?

**Comment by eddieridwan** [comment]
Mengubah _favicon.ico_ di folder root akan tertimpa pada waktu mengupdate OpenSID. Jadi perlu ditambahkan fitur untuk mengupload icon pengganti, untuk disimpan di folder desa. Untuk mencegah pembuatan subfolder baru, kami akan letakkan di folder _desa/logo_.

Karena file .ico mempunyai format khusus, diperlukan library php untuk membuatnya. Kami akan coba pakai https://github.com/chrisbliss18/php-ico.
