### ISSUE TITLE
Fitur: Tambahkan tombol share WA di laman artikel

### ISSUE THREAD

**Issue by eddieridwan** [eddieridwan/OpenSID#176]
Script dari Dwi Asih Wahyu Saptoto.

[artikel (1).php.zip](https://github.com/eddieridwan/OpenSID/files/559762/artikel.1.php.zip)

**Comment by eddieridwan** [comment]
Perlu upgrade font-awesome dari v3.2.1 ke v4.

**Comment by metalab25** [comment]
issue ini sudah bisa diterapkan bung @eddieridwan

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #505.
