### ISSUE TITLE
Fitur: Sediakan cara untuk mengubah urutan menu dan submenu

### ISSUE THREAD

**Issue by syaifudin9** [eddieridwan/OpenSID#177]
Bagaimana caranya mengubah struktur menu dari no 6 menjadi nomer 2
![img_20161030_112827](https://cloud.githubusercontent.com/assets/22818831/19834491/42884804-9e94-11e6-8d7e-483ef61c1c79.jpg)

**Comment by syaifudin9** [comment]
![photogrid_1477801987696](https://cloud.githubusercontent.com/assets/22818831/19834502/afbc4736-9e94-11e6-8b1e-ac82b479a5dd.jpg)
Agar menu no 5 artikel umum berada dekat dengan berita desa?

**Comment by eddieridwan** [comment]
Ada dua kelompok menu:

1. Menu atas, yang diatur mempergunakan tabel menu
1. Menu utama, yang diatur mempergunakan tabel kategori

Masing-masing mempunyai sub-menu, yang juga perlu bisa diubah urutannya.

**Comment by eddieridwan** [comment]
Untuk menerapkan ini, perlu ditambah kolom _urut_ pada tabel _menu_.

Tabel _kategori_ sudah mempunyai kolom _urut_, tetapi tidak jelas dipakai untuk apa. Sekarang dipakai untuk menangani urutan penampilan menu utama.

**Comment by eddieridwan** [comment]
Sudah dicommit.
