### ISSUE TITLE
Fitur : pada cetak surat ada fasilitas rekap surat keluar, mohon dibuatkan juga bagaimana mengarsip surat2 masuk

### ISSUE THREAD

**Issue by syaifudin9** [eddieridwan/OpenSID#178]
Mohon ditambahkan fitur untuk mengarsip surat2 masuk, klo bisa juga ada cetakblembar disposisu

**Comment by eddieridwan** [comment]
@syaifudin9 @tahta24

Harap jelaskan rincian kolom/info apa yang akan direkam untuk surat masuk. Beri contoh surat masuk dan kolom/info yang direkam untuk surat masuk tersebut.

Lampirkan seperti apa lembar disposisi yang diperlukan.

**Comment by eddieridwan** [comment]
AGENDA SURAT MASUK dan KELUAR sesuai PERATURAN MENTERI DALAM NEGERI REPUBLIK INDONESIA NOMOR 47 TAHUN 2016
TENTANG ADMINISTRASI PEMERINTAHAN DESA

![agenda-surat-masuk](https://user-images.githubusercontent.com/249563/28498305-8c8ac3f8-6fdd-11e7-9e23-7e5a7afce84a.jpg)

Petunjuk pengisiannya:

![petunjuk-agenda-surat-masuk](https://user-images.githubusercontent.com/249563/28498307-9698e014-6fdd-11e7-9559-7be7551b91fd.jpg)

**Comment by eddieridwan** [comment]
Contoh disposisi sesuai PERATURAN MENTERI DALAM NEGERI  NOMOR	: 3 TAHUN 2005  TANGGAL	: 3 JANUARI 2005

[DISPOSISI.docx.zip](https://github.com/eddieridwan/OpenSID/files/1167988/DISPOSISI.docx.zip)

![microsoft word - disposisi page1](https://user-images.githubusercontent.com/249563/28498333-1e9a330a-6fde-11e7-8874-c74ae1578136.jpg)
![microsoft word - disposisi page2](https://user-images.githubusercontent.com/249563/28498334-1e9cf40a-6fde-11e7-9290-a00b2ad37ad1.jpg)

**Comment by MUHAMMADRANGSEL** [comment]
Dan juga tambahkan fasilitas upload dokumen surat masuknya shgga sewaktu dicari suratnya tinggal di cari di Aplikasi

**Comment by MUHAMMADRANGSEL** [comment]
Dokumen yang saya maksud hasil scan atau foto surat masuknya

**Comment by eddieridwan** [comment]
Info tambahan dari @syaifudin9 

Lembar disposisi surat masuk:
![lembar-disposisi-surat-masuk](https://user-images.githubusercontent.com/249563/28506034-bbb6ceb8-706b-11e7-91bb-aced6b4a087c.jpg)

Contoh yang telah diisi:
![contoh-disposisi-surat-masuk](https://user-images.githubusercontent.com/249563/28506050-cb3ee7bc-706b-11e7-9bbd-0bbc0588f8c8.jpg)

Semua surat disimpan di arsip, seperti ini:
![map-agenda-surat-masuk](https://user-images.githubusercontent.com/249563/28506059-d655f2d0-706b-11e7-8511-d89b5194f2a2.jpg)

Kalo di dinas perpustakaan memakai map gantung sesuai kode surat:
![kode-surat-utk-map-arsip](https://user-images.githubusercontent.com/249563/28506066-e792f174-706b-11e7-83c6-34f5b8bf86cc.jpg)

**Comment by eddieridwan** [comment]
Daftar petugas di bagian _Disposisi Kepada_ di _Lembar Disposisi_ bisa berbeda untuk setiap desa. _Kawil_ adalah singkatan _Kepala Kewilayahan_ yang menggantikan istilah dulu _Kepala Dusun_. Ini diatur di Permendagri nomor 84 tahun 2015 TENTANG SUSUNAN ORGANISASI DAN TATA KERJA PEMERINTAH DESA.

[Permendagri-Nomor-84-Tahun-2015-Susunan-Organisasi-dan-Tata-Kerja-Pemerintah-Desa.pdf](https://github.com/eddieridwan/OpenSID/files/1169113/Permendagri-Nomor-84-Tahun-2015-Susunan-Organisasi-dan-Tata-Kerja-Pemerintah-Desa.pdf)

**Comment by afri18** [comment]
usul
![image](https://user-images.githubusercontent.com/6611881/28573521-22064ebe-7175-11e7-96a2-f69746c0a1f3.png)
sekalian dibuatkan dokumentasi SK Kades/Perdes isinya > tanggal-no sk-tentang-sasaran

**Comment by MUHAMMADRANGSEL** [comment]
mantap mas syafri itu juga mau saya usulkan

Pada tanggal 25 Jul 2017 20:11, "Syafri" <notifications@github.com> menulis:

usul
[image: image]
<https://user-images.githubusercontent.com/6611881/28573521-22064ebe-7175-11e7-96a2-f69746c0a1f3.png>
sekalian dibuatkan dokumentasi SK Kades/Perdes isinya > tanggal-no
sk-tentang-sasaran

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/eddieridwan/OpenSID/issues/178#issuecomment-317732338>,
or mute the thread

**Comment by MUHAMMADRANGSEL** [comment]
Sesuai dgn aturan dan saran dr DPMD Kabupaten untuk register surat keluar
satu tuk semua jenis surat keluar baik surat keterangan maupun surat keluar
ke instansi

Pada tanggal 25 Jul 2017 22:02, "MUHAMMAD SPD" <muhammadrangsel@gmail.com>
menulis:

**Comment by eddieridwan** [comment]
Modul surat masuk sudah dicommit ke master. Terbatas pada fitur dasar berdasarkan permintaan awal, termasuk laporan agenda surat masuk dan lembar disposisi.

Permintaan susulan yang perlu dibuatkan issue baru:

1. Filter untuk surat masuk dinas/resmi
2. Kelola surat keluar non-layanan
3. Kelola SK Kades/Perdes

Masing2 permintaan di atas perlu dibuatkan issuenya sendiri-sendiri.

@syaifudin9 @MUHAMMADRANGSEL @afri18
