### ISSUE TITLE
Tidak ada info kenapa import excel gagal

### ISSUE THREAD

**Issue by eddieridwan** [eddieridwan/OpenSID#18]
Kalau import gagal, yang diberitahu hanya bahwa prosesnya gagal, tetapi tidak ada info yang menjelaskan sebab kegagalan. Lebih mudah melacak kesalahan data import apabila sistem memberi info sebab kegagalan.

**Comment by siayi** [comment]
Informasi gagal import data , belum cukup informatif bagi pengguna.

**Comment by siayi** [comment]
selain itu ketika import excel dengan jumlah data besar pun #23 , dispaly error pun kuran tepat, karena yang muncul tipe file yang salah, padahal tipe file sudah sesuai petunjuk dan aturan data.

**Comment by eddieridwan** [comment]
Sudah diperbaiki di v0.8. Buat issue baru apabila ada masalah spesifik yang ditemukan.

**Comment by siayi** [comment]
sudah dijajal,, mantap
