### ISSUE TITLE
Keterangan akseptor KB seperti jenis cacat di identitas penduduk dan ditampilkan di statistik

### ISSUE THREAD

**Issue by Agus-Heriyanto** [eddieridwan/OpenSID#180]
Ini dimaksudkan agar banyak informasi yang didapat dari desa kepesertaan KB apakah menggunakan pil. spiral, suntikan atau yang lain dan secara komulatifnya bisa terlihat di data statistik yang menggunakan KB dan tidak, jadi bisa mempermudah desa dalam melakukan identifikasi.
![kb](https://cloud.githubusercontent.com/assets/21340215/19837501/fdef8524-9ef5-11e6-8033-a64b5cb5cad4.jpg)

**Comment by lemahayu** [comment]
untuk penambahannya fitur KBnya mohon dishare pak supaya bisa diaplikasikan...

**Comment by eddieridwan** [comment]
@lemahayu , metoda OpenSID bukan 'sharing' seperti yang banyak dipraktekkan pegiat SID lainnya. Karena, seperti dijelaskan di https://github.com/eddieridwan/OpenSID/wiki/Tanya-Jawab-Install-dan-Update, cara 'patching' menimbulkan kerancuan script. 

Metoda OpenSID adalah menerapkan setiap fitur yang diperlukan, seperti _informasi KB_ langsung sebagai fitur di rilis OpenSID resmi. Kapan fitur ini bisa diterapkan? Tergantung prioritas dan adanya pegiat OpenSID yang berminat/bersedia untuk menerapkannya. Prioritas ditentukan oleh banyaknya pengguna/pegiat yang meminta/menanyakan suatu fitur. 

Anda juga bisa menyatakan suatu tugas merupakan prioritas bagi anda dengan memberi jempol, seperti terlihat di gambar berikut.

![beri-jempol-pada-issue](https://cloud.githubusercontent.com/assets/249563/20609231/9bd20ec2-b2ee-11e6-9f05-5ea28a4131f5.jpg)

**Comment by eddieridwan** [comment]
@Agus-Heriyanto , siapa saja yang boleh menjadi akseptor KB? Perempuan saja? Ada batas umur? Ada batas status kawin? 

Persisnya apa daftar cara KB? Pengguna boleh memilih semua atau hanya satu?

- pil
- spiral
- suntikan
- lainnya?

**Comment by eddieridwan** [comment]
Jawaban dari @Agus-Heriyanto : 

1. Desa sering dimintai data tkait jumlah pengguna KB y memang identik dg perempuan.Kalo umur mungkin ngikuti dr identitas penduduk y sdh drekam dan tentu sdh menikah
2. Jenis kb diatas perlu mjd pilihan dan ditambh pilihan lainnya
3. Sy pikir u 1 plihan jenis kb y digunakan saat ini
4. Ini data masukan dr beberapa desa agar desa punya gmbran u mbuat perencanaan dluar fisik
5. Sy pikir scr umum lbh baik dan ada pilihan dr prog pemerintah ato y lain
6. Statistik y lgsg muncul jmlh pengguna kb sesuai jenis y dpilih..mgkin bs di gabung di menu statistik sid.

**Comment by eddieridwan** [comment]
Bagaimana dengan laki-laki yang sudah vasektomi dan penggunaan kondom? Tidak dianggap sebagai akseptor KB? Karena dalam hal ini istrinya tidak perlu kb -- sehingga kalau kb pria tidak tercatat, apakah statistiknya nanti kurang lengkap?

Atau, apakah cara KB seperti vasektomi dan kondom biasanya dicatat pada perempuan, walaupun yang menggunakan adalah laki-laki? Perlu acuan yang menjelaskan pendataan akseptor KB yang baku.

**Comment by eddieridwan** [comment]
Dari: https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=9&cad=rja&uact=8&ved=0ahUKEwjS2eKt8MnQAhUEJpQKHRO6AxYQFghbMAg&url=http%3A%2F%2Frepository.fisip-untirta.ac.id%2F379%2F1%2FKOM%2520-%2520PERAN%2520PENYULUH%2520KELUARGA%2520BERENCANA%2520(PKB)%2520DI%2520KECAMATAN%2520KASEMEN%2C%2520KOTA%2520SERANG.pdf&usg=AFQjCNHnMLPcXfb1H4FuLuMcIcj7OEP8wA&sig2=iGH2p9pUuNdZoXr4RtBJ_A&bvm=bv.139782543,d.c2I
 
![daftar-cara-kb-1](https://cloud.githubusercontent.com/assets/249563/20652003/05adc3ea-b556-11e6-948d-484039d1398e.jpg)

**Comment by eddieridwan** [comment]
![daftar-cara-kb-2](https://cloud.githubusercontent.com/assets/249563/20652029/a7efa6f0-b556-11e6-8cf6-d92111fb9b7d.jpg)



Dari laporan berikut:
[buletin-kespro.pdf](https://github.com/eddieridwan/OpenSID/files/615069/buletin-kespro.pdf)

**Comment by eddieridwan** [comment]
![daftar-cara-kb-3](https://cloud.githubusercontent.com/assets/249563/20652118/42ba59e0-b558-11e6-9c3a-0df6e7d45e72.jpg)

Sumber:
[laporan-akhir-evaluasi-28-jan-2__20110512125342__3040__1.pdf](https://github.com/eddieridwan/OpenSID/files/615078/laporan-akhir-evaluasi-28-jan-2__20110512125342__3040__1.pdf)

**Comment by eddieridwan** [comment]
![daftar-cara-kb-4](https://cloud.githubusercontent.com/assets/249563/20652139/8b6885c2-b558-11e6-8024-89d796ddcd77.jpg)

Sumber:
[bab1.pdf](https://github.com/eddieridwan/OpenSID/files/615081/bab1.pdf)

**Comment by eddieridwan** [comment]
Berdasarkan acuan di atas, yang akan diterapkan adalah pilihan Alat Kontrasepsi:

* Intrauterine Device (IUD)
* Metoda Operasi Wanita (MOW)
* Metoda Operasi Pria (MOP)
* Implan
* Suntik
* Pil
* Kondom

**Comment by eddieridwan** [comment]
Ketemu Survei Demografi dan Kesehatan Indonesia, yang sepertinya menjadi acuan dalam bidang KB. Daftar lengkap alat/cara KB. Tetapi, terpikir yang dimaksud dengan 'akseptor KB' mungkin terbatas pada yang memakai alat kontrasepsi -- sehingga cara tradisional (sanggama terputus, pantang berkala) tidak termasuk sebagai bagian dari 'akseptor KB'. Ok, sementara ini daftar di SID kita batasi pada alat kontrasepsi, dan tidak termasuk cara tradisional.

![daftar-cara-kb-5](https://cloud.githubusercontent.com/assets/249563/20705685/cfd6605e-b688-11e6-8692-b7e26595bdfd.jpg)

[SDKI-2012.pdf](https://github.com/eddieridwan/OpenSID/files/618670/SDKI-2012.pdf)

**Comment by lemahayu** [comment]
mohon pencerahan untuk Data Akseptor KB ketika diaktifkan pada Menu Data Desa di website ketika diklik yang muncul malah Data Demografi Berdasar.....terimakasih....

**Comment by eddieridwan** [comment]
@lemahayu : OpenSID versi berapa? Harap lampirkan tampilan layar supaya lebih mudah dilacak. Juga coba bandingkan dengan situs demo di http://sid.bangundesa.info/index.php/statistik/index/16.
