### ISSUE TITLE
Bug: Akte dan Tanggal pernikahan penduduk tidak muncuk di edit dan tambahkan informasi punya buku nikah lalu muncukan di statistik

### ISSUE THREAD

**Issue by Agus-Heriyanto** [eddieridwan/OpenSID#181]
Ini dimaksudkan agar desa mengetahui keluarga yang belum memiliki buku nikah..jadi desa bisa mengarahkan APBDes untuk kegiatan agar keluarga punya buku  nikah.
![punya buku nikah](https://cloud.githubusercontent.com/assets/21340215/19837606/10f2983a-9ef8-11e6-858d-0065d0855925.jpg)

**Comment by eddieridwan** [comment]
@Agus-Heriyanto , apabila ada Akta Perkawinan, apakah bisa buat asumsi juga ada Buku Nikah?

**Comment by Agus-Heriyanto** [comment]
Mksd nya bs dmunculkan keterangan sbelum akte pkawinan..apakah ada buku nikah ato tidak dan ada muncul dstatiskik brp keluarga y tidak punya buku nikah.Ini u mendorong desa dlm melihat masy y msh belum tertib administrasi shg ada upaya desa melalui perencanan dan penganggarannya mengadakn prog agar masy mmpunyai buku nikah.Kalo misalkn ckp dg akte pkawinan,mugkin bs dmunculk dstatistik jg.Bgitu bung edi..

Terkirim dari Samsung Mobile

-------- Pesan asli --------
Dari: Eddie Ridwan <notifications@github.com> 
Tanggal: 02/11/2016  18:13  (GMT+08:00) 
Ke: eddieridwan/OpenSID <OpenSID@noreply.github.com> 
Cc: Agus-Heriyanto <agus.heriyanto.s.pt@gmail.com>,Mention <mention@noreply.github.com> 
Subjek: Re: [eddieridwan/OpenSID] Akte dan Tanggal pernikahan penduduk tidak muncuk di edit dan tambahkan informasi punya buku nikah lalu muncukan di statistik (#181) 
 
@Agus-Heriyanto , apabila ada Akta Perkawinan, apakah bisa buat asumsi juga ada Buku Nikah?

**Comment by eddieridwan** [comment]
Pada v1.3, kolom akta_perkawinan dipakai untuk menyimpan nomor akta nikah (buku nikah) bagi warga muslim and untuk menyimpan nomor akta perkawinan bagi warga non-muslim.
