### ISSUE TITLE
Konversi dari data BIP 2016 ke Format import seperti BIP 2012 yang warna hijau kuning

### ISSUE THREAD

**Issue by Agus-Heriyanto** [eddieridwan/OpenSID#184]
Ini Contoh BIP 2016 di Lombok Tengah
[AIK DAREQ - Copy.xlsx](https://github.com/eddieridwan/OpenSID/files/560577/AIK.DAREQ.-.Copy.xlsx)

**Comment by eddieridwan** [comment]
@Agus-Heriyanto, lebih sederhana ya? Tidak ada status kawin, status e-KTP, nama ayah, no akte lahir. Betul begitu?

**Comment by eddieridwan** [comment]
@Agus-Heriyanto , Issue ini untuk import langsung ke database atau konversi berkas excel?

**Comment by eddieridwan** [comment]
Karena impor BIP 2016 sudah diterapkan #192, dan juga sudah disediakan fitur untuk export dalam format yang bisa di-import excel, #142, sekarang tidak diperlukan lagi fitur untuk konversi BIP 2016 ke format import excel.
