### ISSUE TITLE
Penomoran Surat

### ISSUE THREAD

**Issue by asepzhepots** [eddieridwan/OpenSID#186]
Agar lebih baik format penomoran surat dapat di custom, karena disetiap desa format surat berbeda-beda, contoh : 147/028/2016 (Jenis Surat/Nomor Surat/ Tahun) ada juga yang mengguanakan format 028/147/X/2016 ( Nomor Surat/Jenis Surat/Bulan/Tahun)

**Comment by eddieridwan** [comment]
@asepzhepots , Di form surat, pengisian nomor surat bebas, tidak dibatasi. Jadi format nomor surat yang berbeda-beda tidak masalah.

**Comment by eddieridwan** [comment]
@asepzhepots, karena tidak ada tanggapan susulan dari anda, saya akan tutup issue ini. Apabila ada permintaan/masalah lain sehubungan dengan nomor surat, silakan dibuka lagi atau buat issue baru.
