### ISSUE TITLE
#form_isian

### ISSUE THREAD

**Issue by afri18** [eddieridwan/OpenSID#196]
setelah saya cermati sebaiknya form isian untuk : 
1. Tambah data Keluarga Baru (/keluarga/form/0/1)
2. Tambah data penduduk karna pendatang (penduduk/form)
3. Tambah data penduduk karna lahir (keluarga/form_a/1/0/2242)
untuk data isian individunya samakan saja biar satu kali kerja
contoh untuk data pendidikan sedang di tempuh hanya ada di form penduduk pendatang di yang lainnya tidak ada

**Comment by eddieridwan** [comment]
Dibuatkan satu file yang berisi semua isian biodata penduduk, _penduduk_form_isian.php, yang di-include di ketiga tempat tersebut di atas.

Dengan cara ini, isian, urutan dan peristilahan akan tampak sama pada ketiga kegunaan tersebut.

**Comment by eddieridwan** [comment]
Sudah dicommit.

**Comment by afri18** [comment]
![image](https://cloud.githubusercontent.com/assets/6611881/20394450/205ee5ee-ad12-11e6-9bb8-164da4e0facd.png)

**Comment by eddieridwan** [comment]
@afri18 , maksudnya apa? Kurang lebar, terlalu lebar? Pada browser saya tampak seperti berikut. Panjangnya 'pendidikan sedang ditempuh' lebih panjang karena ada pilihan yang panjang. Tetapi kalau dilihat daftar pilihannya, memang agak aneh --- tetapi itulah yang diperoleh dari SID 3.04 dulu. Apakah daftar itu yang ingin anda ubah?

![form-isian-penduduk](https://cloud.githubusercontent.com/assets/249563/20411687/65ec4262-ad87-11e6-837c-98c72ce61636.jpg)

**Comment by afri18** [comment]
pilihan tidak timbul di form tersebut > penambahan anggota keluarga dari kelahiran

**Comment by eddieridwan** [comment]
Menurut anda, apa pengertian 'Pendidikan sedang ditempuh'? Mengapa hanya pada waktu menambah anggota keluarga dari kelahiran? Bukankah kolom ini berlaku untuk semua penduduk -- misalnya pilihannya termasuk 'Sedang S-1/Sederajat' yang jelas bukan untuk yang baru lahir?

**Comment by afri18** [comment]
kalau tidak diisi nantinya kedetek di statistik pendidikan belum ditempuh belum mengisi, ini maksudnya biar kita tidak kerja dua kali jadi langsung diisi (istilahnya langsung disensus)
