### ISSUE TITLE
Fitur: Tombol naikkan/turunkan menu hanya untuk administrator

### ISSUE THREAD

**Issue by afri18** [eddieridwan/OpenSID#198]
seharusnya kewenangan administrator web aja, biar user yg lain nggak gonta ganti sembarangan
![image](https://cloud.githubusercontent.com/assets/6611881/20395889/06f4d0f0-ad17-11e6-8639-84e7e082aa38.png)

**Comment by eddieridwan** [comment]
@afri18 , dengan demikian, menurut anda apakah semua fitur berikut hanya boleh dilakukan oleh administrator?:

1. naikkan/turunkan menu
1. ubah menu
1. hapus menu
1. kunci menu
1. tambah menu

Jadi peran Operator apa saja?

**Comment by eddieridwan** [comment]
@afri18 , ok sudah di-commit. Tetapi hanya untuk fitur naikkan/turnkan menu. Untuk yang lainnya, sebaiknya dilakukan review menyeluruh mengenai hak-hak masing jenis pengguna, untuk menentukan secara rinci apa yang boleh dilakukan oleh masing-masing jenis pengguna. 

Sepertinya pekerjaan untuk menerapkan fitur _authorisation_ ini cukup besar (karena banyaknya fitur di SID), dan perlu dilihat sejauh mana manfaatnya. Maksudnya, ada berapa desa yang secara nyata/aktif mempunyai user dengan hak selain administrator?

**Comment by afri18** [comment]
saya sangat setuju untuk pengaturan yang berhubungan dengan tampilan web atau menu hanya bisa dilakukan oleh administrator/admin utama
