### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by arzaddin** [eddieridwan/OpenSID#201]
Buka halaman database malah blank, error di log:
PHP Fatal error:  Can't use method return value in write context in ...../opensid/donjo-app/models/import_model.php on line 365

Upgrade ke PHP7 muncul error gini:
PHP Fatal error:  Uncaught Error: Call to undefined function mysql_pconnect() in ...../opensid/donjo-sys/database/drivers/mysql/mysql_driver.php:91

**Comment by eddieridwan** [comment]
Harap lihat panduan install di https://github.com/eddieridwan/OpenSID/wiki/Panduan-Install-OpenSID. Di situ dijelaskan, SID/OpenSID memerlukan PHP 5.x, dan yang biasa dipakai PHP 5.5 atau 5.6.

**Comment by eddieridwan** [comment]
@arzaddin , apakah sudah dicoba lagi dengan versi PHP 5.x?

**Comment by batudaa** [comment]
Kalau pake versi 5.3 bisa pake branch yang baru saja saya pull request.

**Comment by batudaa** [comment]
Untuk php7 juga sudah saya pull request. 
Tunggu saja kalau nanti di gabung ke master. Kalau tidak lolos gabung, tinggal bikin saja branch sendiri,,,, ;)
