### ISSUE TITLE
Fitur: Mengganti sebutan 'dusun' dengan kata lain

### ISSUE THREAD

**Issue by lemahayu** [eddieridwan/OpenSID#202]
Desa saya sudah tidak memakai dusun lagi, tapi memakai blok dan kepala dusun juga tidak ada adanya kepala blok....disetiap blok yang ada terdapat dua jabatan yaitu kepala blok dan ketua RW yang membedakan hanya fungsinya kalau kepala blok masuk jajaran pamong desa sedangkan RW tidak...terimakasih

**Comment by eddieridwan** [comment]
Desa anda di mana? Apakah sebutan _blok_ juga dipakai di desa lainnya sebagai pengganti _dusun_? Dan apakah dikenal oleh Disdukcapil setempat?

**Comment by lemahayu** [comment]
desa lemahayu kecamatan kertasemaya kabupaten indramayu jawa barat, kalau untuk 13 desa diwilayah kecamatan saya pakainya blok semua, untuk data disdukcapil dalam data bip berformat excel pada lajur dusun datanya kosong yang ada hanya data pada lajur alamat.

**Comment by lemahayu** [comment]
yang membingungkan dalam administrasi wilayah didesa saya kepala blok itu ada 3 tapi dalam alamat ada sub bloknya contohnya dalam wilayah blok pelem ada blok kedokan bajing, blok kayu duwur dan blok siadan, jadi ketika saya coba import data sering terjadi error dikarenakan terjadi tumpang tindih rw dan rt.

**Comment by lemahayu** [comment]
contohnya warga yang ada di wilayah blok pelem dalam data BIP ada yang alamatnya blok kayu duwur rt 02 rw 01, ada lagi yang alamatnya blok kedokan bajing rt 01 rw 01, dari situ terlihat ada 2 sub blok dengan satu rw hanya berbeda rt.

**Comment by lemahayu** [comment]
data wilayah desa saya 
1. Blok Pelem 
sub blok : blok kedokan bajing, blok siadan, blok kayu duwur, blok jondol gading
2. blok anyar (tidak memiliki sub blok)
3. blok mundu
sub blok : blok tumaritis, blok siadan
disitu ada dua sub blok yang masuk dalam dua wilayah blok yaitu blok siadan yang membedakanya pada rt dan rw nya, yang masuk blok pelem rt 09 rw 01 yang masuk blok mundu rt 01 rw 03

**Comment by eddieridwan** [comment]
Sepertinya cukup rumit hirarki wilayah di Kecamatan Kertasemaya! Bagaimana dengan kecamatan lainnya di Kabupaten Indramaya -- memakai _blok_ juga?

SID mengenal tiga tingkat wilayah: dusun, rw, rt. Untuk menambah satu lagi, seperti sub-blok, akan lumayan susah. Terlebih lagi, sepertinya penggunaan sub-blok di tempat anda tidak konsisten, yaitu tidak merupakan bagian dari struktur hirarkis murni.

Yang bisa saya usulkan:

1. sub-blok biar direkam di kolom _alamat_ saja, mengikuti penggunaan kolom _alamat_ lainnya untuk menyimpan nama jalan atau nama kompleks perumahan.
1. menggunakan kolom dusun untuk menyimpan nama _blok_
1. menambah fitur di OpenSID untuk bisa menggantikan sebutan _dusun_ menjadi kata lain, seperti _blok_.  Dengan penggantian ini, penampilan layar aplikasi dan surat/laporan akan menampilkan _blok_ bukan _dusun_.

**Comment by eddieridwan** [comment]
Di daerah lain juga dipakai sebutan yang berbeda untuk wilayah _dusun_.  Saya tahu di Sumatera Barat, _desa_ disebut _nagari_, dan _dusun_ disebut _jorong_. Jadi fitur untuk bisa menggantikan sebutan _dusun_ mungkin juga bermanfaat bagi daerah lain seperti Sumatera Barat.

**Comment by lemahayu** [comment]
Terimakasih Pak Eddie atas pencerahannya, ditunggu fitur blok di OpenSIDnya...

**Comment by eddieridwan** [comment]
Haha.. OpenSID bukan aplikasi saya --- melainkan milik bersama semua pengguna dan pegiat SID.

**Comment by lemahayu** [comment]
Betul Pak Eddie, bahasanya saya ganti  dimohon bantuannya kiranya Pak Eddie dan seluruh pengguna dan pengiat SID yang bisa menambahkan fitur pengganti dusun dengan blok, karena saya sangat awam dalam hal pembuatan pemograman dan aplikasi....

**Comment by lemahayu** [comment]
Terimakasih banyak Pak Eddie untuk updatenya....
