### ISSUE TITLE
#artikel_hotline

### ISSUE THREAD

**Issue by afri18** [eddieridwan/OpenSID#204]
alangkah baiknya artikel hotline saat ditampilkan tidak memuat seluruh isi artike (kecuali pendek/satu paragraf) kecuali setelah diklik judulnya, baru terbaca semua.
Usulnya artikel Hotline hanya menampilkan satu paragraf aja ini bertujuan agar artikel yang panjang tidak membuat tampilan web menjadi enak dilihat karna seimbang.

**Comment by eddieridwan** [comment]
Duplikat #354.
