### ISSUE TITLE
#realis

### ISSUE THREAD

**Issue by afri18** [eddieridwan/OpenSID#217]
perubahan yang sudah dilakukan tidak dibarengi dengan hasil cetak/print, contoh laporan bulanan penduduk hasil cetak masih yang lama, laporan keluarga belum disertakan, begitu juga dengan perubahan yang lain, saya coba hasillya masih yg lama

**Comment by eddieridwan** [comment]
Rilis 1.5? Apakah upgrade dilakukan dengan mengganti keseluruhan script seperti panduan https://github.com/eddieridwan/OpenSID/wiki/Panduan-Update-OpenSID?

Beri contoh laporan yang masih yang lama. Beri tampilan layar.

**Comment by eddieridwan** [comment]
@afri18 , apakah masalah ini sudah diperiksa lagi? Kalau masih ada masalah harap berikan contoh spesifik dan screenshot.

**Comment by afri18** [comment]
laporan penduduk bulanan
![image](https://cloud.githubusercontent.com/assets/6611881/20956998/d07a741c-bc7f-11e6-930f-dfee129757e3.png)
juga yg lain dan untuk export excelnya eroor

**Comment by eddieridwan** [comment]
@afri18 : Apakah yang dimaksud judulnya ada tulisan 'Kampung' atau masalah lain? Kalau tulisan 'Kampung', itu ditentukan oleh setting di desa/config/config.php, seperti dijelaskan di https://github.com/eddieridwan/OpenSID/wiki/Panduan-Konfigurasi-Aplikasi. 

Kalau yang dimaksud belum adanya perkembangan keluarga di fitur cetak laporan penduduk bulanan, masalah ini sudah lama didaftarkan di https://github.com/eddieridwan/OpenSID/issues/144.

Mengenai export excelnya, masalah itu juga sudah lama terdaftar di https://github.com/eddieridwan/OpenSID/issues/145. Sayang belum ada yang sempat memperbaiki.

Kalau masalah lain, mohon dijelaskan persisnya apa masalahnya. Maaf, karena tidak langsung terlihat oleh saya apa masalahnya.

**Comment by eddieridwan** [comment]
Hal-hal yang dibahas di issue ini telah dikerjakan pada issue lain dan sudah di-commit ke master.
