### ISSUE TITLE
Fitur: Terapkan surat permohonan pindah WNI F.1-25

### ISSUE THREAD

**Issue by eddieridwan** [eddieridwan/OpenSID#218]
@aero123

Surat ini sering diminta, dan dibanyak desa masih diisi secara manual.

![formulir permohonan pindah wni f-1 25](https://cloud.githubusercontent.com/assets/19701605/20640226/9699a790-b40a-11e6-8407-0f443d2e14fe.jpg)

**Comment by eddieridwan** [comment]
@aero123, ada pertanyaan. 

Sesudah membuat surat pindah seperti ini, apakah status keluarga yang bersangkutan perlu diubah sesuai dengan isi surat? Atau, apakah status keluarga diubah hanya berdasarkan permintaan/info terpisah dari warga yang bersangkutan (yaitu tidak terkait surat permohonan pindah)?

**Comment by aero123** [comment]
status keluarga yang bersangkutan otomatis berubah sesuai dengan isi surat bung eddieridwan, contoh : yang pindah hannya kepala keluarga, maka keluarga yang tidak ikut akan menjadi kepala keluarga.

**Comment by eddieridwan** [comment]
Belum bisa persis seperti blanko dari Disdukcapil. Tapi dirlis dulu, nanti dicoba lagi pada rilis ke depan.
