### ISSUE TITLE
Bug : Alamat sebelumnya tidak berubah padahal sudah menepati KK baru dengan alamat yg berbeda dgn sebelumnya

### ISSUE THREAD

**Issue by misterditho** [eddieridwan/OpenSID#220]
alamat ybs tidak berubah saat menempati KK baru.

![bug sid 1](https://cloud.githubusercontent.com/assets/24251912/20999033/75057404-bd44-11e6-97f9-721e41c5409b.jpg)

**Comment by eddieridwan** [comment]
Masalahnya saat ini id_cluster, yang menentukan dusun/rw/rt keluarga ada di tabel penduduk pada data kepala keluarganya. Jadi, fungsi id_cluster di table tweb_penduduk dua:

1. alamat keluarga apabila penduduk tersebut adalah kepala keluarga
1. alamat penduduk apabila penduduk tersebut penduduk lepas

Sedangkan pada penduduk yang bukan kepala keluarga dan juga bukan penduduk lepas, id_cluster seharusnya tidak dipakai.

Untuk membuat lebih jelas dan sederhana, id_cluster untuk keluarga perlu diletakkan di tabel tweb_keluarga. Pada migrasi awal, id_cluster setiap kepala keluarga perlu dipindahkan ke id_cluster di data keluarganya di tweb_keluarga.

**Comment by misterditho** [comment]
siap, terimakasih atas penjelasannya.
