### ISSUE TITLE
Munculkan detail nama" dan alamat penerima bantuan

### ISSUE THREAD

**Issue by TAHTA24** [eddieridwan/OpenSID#221]
Klw bisa, kita bisa melihat nama" dan alamat penerima raskin, PKH, Bedah rumah dan BLSM

**Comment by eddieridwan** [comment]
Bagaimana kalau program Raskin/BLSM/PKH/Bedah Rumah yang ada di fitur Ubah Data KK kita gabung saja dengan modul Program Bantuan?

Dengan demikian, penampilan peserta program Raskin/BLSM/PKH/Bedah Rumah tersedia secara otomatis di modul Program Bantuan (dan juga statistiknya). Pendekatan ini konsisten -- jadi tidak melihat program bantuan keluarga di dua tempat seperti sekarang.

**Comment by eddieridwan** [comment]
**Klemens Kwaman**: Itu ide bagus skali mas....biar dng pengabungan itu kita bisa melihat dalam 1 KK brapa jenis bantuan yg didapat untuk mnghindari KKN dalm pemberian bantuan.....shingga pada saat mmberikan bantuan trjadi pemrataan kepada warga yg mmbtuhkan....

**Muhammad Djalil:** kalau bisa ikut juga data bpjs

**Syafri**: Bagus, tambahkan no id kartu program bantuan agar mengetahui doc yg d pegang warga

**Si Aditya**: ijin menambahkan, agar pendataan lebih akurat sebaiknya memang penerima bantuan didata perseorangan,,
saya setuju program Raskin/BLSM/PKH/Bedah Rumah yang ada di fitur Ubah Data KK digabung dalam modul Program Bantuan, krn akan memudahkan pendataan penduduk yg menerima bantuan dan bantuan yang diterima pun bisa lebih dari 1dan perlu ditambahkan juga pada Rincian/Informasi Biodata Penduduk untuk kolom mengenai Bantuan-Bantuan yang diterima, dan juga memungkinkan pada Ubah Data Penduduk bisa ditambahkan menu perubahan Bantuan yang diterima sesuai dengan jenis Bantuan pada Modul Program Bantuan.

Di Modul Program Bantuan pada Daftar Peserta Program agar menambahkan informasi no KK dan Satus Hub Keluarga dlm KKnya pada semua jenis sasaran program baik itu Perseorangan, KK, Rumah Tangga, Organisasi dll, hal ini bermaksud pada saat rekapitulasi kita semua bisa melihat penerima berasal dr KK mana dan statusx apa.

Perubahan sesuai usul diatas tentunya juga akan berimbas pada modul Statistik/Statistik Keluarga, diharapkan nantinya modul Statistik/Statistik Keluarga terisi sesuai jenis Program Bantuan pada Modul Program Bantuan.

lebih kurangnya mohon maaf.. mungkin bisa ditambahkan dengan teman2 yang lain.
