### ISSUE TITLE
Fitur: Tambahkan nomor kartu peserta program bantuan

### ISSUE THREAD

**Issue by afri18** [eddieridwan/OpenSID#223]
untuk penambahan kriteria keluarga sudah okeh, agar realis akan datang sekaligus saya usulkan 
1. untuk penambahan peserta sebaiknya jangan langsug simpan saat klik nik/nama/no_kk tapi ditambahkan tombol simpan, jadi kita tahu alamat dan orang sudah sesuai untuk mengurangi kesalahan.
2. tambahkan kolom di tabel [program_peserta] untuk no_ id_kartu > peserta program untuk mengetahui dokumen yang dipegang warga, jadi kita bisa entri/masukan dulu no tersebut baru simpan
3. tampilan statistik yang bagus seperti usia rentan, lebih rinci

**Comment by eddieridwan** [comment]
Bung @afri18, anda telah menambahkan tiga (3) masalah dalam issue ini. Sebaiknya, untuk memudahkan pengelolaan penerapan, dibuat issue terpisah untuk masing2 masalah.

Karena yang menerapkan pada saat ini masih satu orang saja, ya dilakukan satu2... kalau terpisah bisa dikomentari/diterapkan/ditutup sendiri2. Nantipun, kalau sudah ada lebih banyak orang yang membantu menerapkan, bisa saja masing2 issue dilakukan oleh orang yang berbeda -- sehingga alur penerapannya sendiri2.

Ok, ini info untuk anda pada saat menambahkan issue lainnya. Supaya mengikuti 'best practice' pengelolaan aplikasi.

**Comment by eddieridwan** [comment]
Issue ini untuk usulan (2) di atas: tambahkan kolom di tabel [program_peserta] untuk no_ id_kartu > peserta program untuk mengetahui dokumen yang dipegang warga, jadi kita bisa entri/masukan dulu no tersebut baru simpan.

Issue (1) dipisah ke #228

**Comment by eddieridwan** [comment]
Sdh di-commit ke master.
