### ISSUE TITLE
perbedaan cetak langsung dan export doc pada surat keterangan 

### ISSUE THREAD

**Issue by Jhiban-Khang** [eddieridwan/OpenSID#226]
perbedaan cetak langsung dan export doc pada surat keterangan , nama pemohon tidak muncul

**Comment by eddieridwan** [comment]
OpenSID tidak akan memperbaiki lagi surat cetak langsung, karena tidak bisa diubah dgn mudah oleh pengguna. Dan juga utk menghindari perbedaan antara surat cetak langsung dgn export doc, diusulkan utk menghapus fitur cetak langsung.

Biar surat export doc saja yang dikembangkan, lebih fleksibel dan lebih mudah disesuaikan oleh desa.

**Comment by dadannurman** [comment]
mas @eddieridwan bagaimana cara menghapus menu cetak langsung pada surat? mohon solusinya

**Comment by eddieridwan** [comment]
Untuk surat sistem, tombol cetak langsung tidak bisa dihapus.

Untuk surat yang dibuat pengguna, tombol cetak langsung bisa dihapus. Silakan lihat panduan https://github.com/eddieridwan/OpenSID/wiki/Mengelola-Master-Surat, di bagian _Menambah Surat Baru_.
