### ISSUE TITLE
Chart Statistik Error

### ISSUE THREAD

**Issue by siayi** [eddieridwan/OpenSID#227]
Chart Statistik pada halaman administrasi (backend) tidak menampilkan data chart, apakah fungsi ini belum ditambahkan?
Screenshoot error sebagai berikut:

![chart statistik error](https://cloud.githubusercontent.com/assets/1229849/21258065/ec5443c2-c3ad-11e6-8aec-11c661297378.png)

**Comment by eddieridwan** [comment]
Ada file yang terhapus pada waktu membersihkan file yang tidak terpakai.

Telah dikembalikan file: penduduk_graph.php dan penduduk_pie.php.

**Comment by eddieridwan** [comment]
@siayi , bisa diunduh dari master. Karena sudah ada perubahan struktur database, perlu jalankan Database > Migrasi DB SID 3.04.

**Comment by siayi** [comment]
terima kasih pak @eddieridwan masalah teratasi (solved) sesuai petunjuk di atas.
![chart solved](https://cloud.githubusercontent.com/assets/1229849/21286009/ef1674ea-c47a-11e6-898c-a1d1ebaa668d.png)

**Comment by eddieridwan** [comment]
Bung @siayi , download master lagi -- menu kirinya sudah diperbaiki -- yang di atas ternyata salah. Karena SID asli pakai copy/paste sehingga perlu diubah dibeberapa tempat. Sekarang sudah dibenahi supaya script menu kiri ada di satu tempat saja.
