### ISSUE TITLE
Import excel gagal apabila jumlah data terlalu besar

### ISSUE THREAD

**Issue by eddieridwan** [eddieridwan/OpenSID#23]
Di alami oleh  @siayi di http://sid.bangundesa.info/index.php/siteman, pada waktu Database > Import Excel.    

Ketika import data dg jmlh baris data 6, ukuran file < 2M --> sukses import.
Tetapi ketika import data dengan ukuran file > 2MB, ada error : Data Gagal disimpan

Perlu dilacak kenapa hal ini terjadi. Apabila ada keterbatasan ukuran file, perlu ditambahkan informasi hal itu. Dan diberikan cara alternatif untuk mengimport data yang banyak.

**Comment by eddieridwan** [comment]
Bung @siayi, import yang gagal itu dari file excel dengan jumlah baris berapa?

**Comment by siayi** [comment]
8416

**Comment by eddieridwan** [comment]
Setelah dilacak, masalah ada pada batasan ukuran file yang bisa diupload dan batas waktu melakukan upload. Setting yang menentukan batasan ini ada di php.ini. Setting yang perlu disesuaikan adalah:

- post_max_size
- upload_max_filesize
- max_input_time
- max_execution_time

Setting ini mudah diubah pada komputer lokal. Tetapi di server hosting, setting ini memerlukan bantuan admin, dan belum tentu disetujui, karena akan mempengaruhi pemakai lain.

Batas ukuran file default biasanya 2M.

**Comment by eddieridwan** [comment]
Sebaiknya pada waktu akan melakukan Import Excel, sistem memeriksa setting _upload_max_filesize_ dan ukuran file yang akan diupload. Apabila ukuran file yang akan diupload melebihi _upload_max_filesize_, tampilkan informasi error tersebut pada pengguna.

**Comment by eddieridwan** [comment]
Penampilan error ukuran file unggahan terlalu besar, sudah dicommit.

**Comment by eddieridwan** [comment]
Di rilis v0.8.

**Comment by siayi** [comment]
mantap (y)

**Comment by hasanlq69** [comment]
izin bertanya, misal import excel/csv nya harus data yg valid isinya bukan data yang asal2an barisnya kolomnya membuat validasi spt itu gmna ya caranya? terimakasih
