### ISSUE TITLE
Error Query Database di Model Penduduk

### ISSUE THREAD

**Issue by ghost** [eddieridwan/OpenSID#230]
Pertama install ada error Query jika masuk di bagian penduduk 

`LEFT JOIN tweb_wil_clusterdesa a ON d.id_cluster = a.id` 

seharusnya

`LEFT JOIN tweb_wil_clusterdesa a ON d.id = a.id`

karena di tabel `tweb_wil_clusterdesa` tidak ada `id_cluster`

kemudian  dibagian `pic_helper.php` ada error pada bagian 

`define (MIME_TYPE_DOKUMEN, serialize (array(...` dibeberapa versi php tanpa singel quote tetap berjalan, tetapai di beberapa lagi tidak, apaa tidak seharunya menggunakan singel quote seperti 

`define ('MIME_TYPE_DOKUMEN', serialize (array(....`

**Comment by eddieridwan** [comment]
Lihat comment di pull request untuk issue ini.

**Comment by batudaa** [comment]
**define** tanpa quote akan tetap jalan, dan akan dianggap menggunakan quote.
Apabila _error notice_ aktif, maka akan menampilkan notice. Tapi tetap akan jalan.

Di production, OpenSID menonaktifkan semua error_reporting.

**Comment by eddieridwan** [comment]
Perubahan define sudah dicommit ke master.
