### ISSUE TITLE
Bug: Sorting pada Master Surat Error

### ISSUE THREAD

**Issue by siayi** [eddieridwan/OpenSID#232]
Pada Modul **Master Surat** ketika melakukan sorting pada kolom **Nama Surat** dan **Kode Surat** tampil pesan error sebagai berikut:

**Nama Surat** :
```
A Database Error Occurred

Error Number: 1054

Unknown column 'u.pertanyaan' in 'order clause'

SELECT u.* FROM tweb_surat_format u WHERE 1 ORDER BY u.pertanyaan LIMIT 0,20

Filename: /var/www/html/OpenSID/models/surat_master_model.php

Line Number: 114
```

**Kode Surat** : 

```
A Database Error Occurred

Error Number: 1054

Unknown column 'u.id_kategori' in 'order clause'

SELECT u.* FROM tweb_surat_format u WHERE 1 ORDER BY u.id_kategori LIMIT 0,20

Filename: /var/www/html/OpenSID/models/surat_master_model.php

Line Number: 114

```

Di bawah ini gambar error di maksud:
![error fitur sorting pada master surat](https://cloud.githubusercontent.com/assets/1229849/21416414/5617d8a0-c845-11e6-96f0-f283643952a8.png)

**Comment by eddieridwan** [comment]
Ok, sudah diperbaiki. Sepertinya developer aslinya copy/paste saja tanpa melakukan testing.
