### ISSUE TITLE
Error di menu penduduk OpenSID v 1.7

### ISSUE THREAD

**Issue by aero123** [eddieridwan/OpenSID#233]
jika di akses menu penduduk maka akan keluar error seperti ini
![gambar11](https://cloud.githubusercontent.com/assets/19701605/21422918/c9db4e8a-c86c-11e6-993a-4eebd829b439.jpg)

**Comment by eddieridwan** [comment]
Harap lihat posting di https://www.facebook.com/groups/OpenSID/ mengenai ini. Error ini terjadi karena mengambil script dari branch master dan bukan dari rilis resmi di https://github.com/eddieridwan/OpenSID/releases. Sering di branch master contoh data awal belum di-update dengan perubahan struktur database yang dibutuhkan.

Solusinya:
1. Unduh dari rilis resmi dan impor contoh data awalnya,
2. Atau navigasi ke Database > Migrasi DB SID 3.04 dan klik tombol migrasi di laman itu.
