### ISSUE TITLE
Bug pada peta Desa

### ISSUE THREAD

**Issue by metalab25** [eddieridwan/OpenSID#234]
saya mencoba untuk update data lokasi desa namun setelah saya tetapkan map marker pada lokasi desa dan saya simpan peta lokasi desa pada frontpage tetap tidak terupdate.... mohon bantuannya

**Comment by lynggo** [comment]
belum solved ya ini

**Comment by MUHAMMADRANGSEL** [comment]
Baca Panduan tuk mendapatkan google-api di wiki

**Comment by MUHAMMADRANGSEL** [comment]
Ini sudah bisa, mohon ditutup issuenya mas eddie
