### ISSUE TITLE
Fitur: Tampilkan Statistik Akte Kelahiran

### ISSUE THREAD

**Issue by metalab25** [eddieridwan/OpenSID#235]
Sesuai dengan permintaan dari pengguna OpenSID di desa Hadakewa mohon di munculkan statistik Akte Kelahiran agar bisa di pantau anak mana yg blum memiliki...krn kdang ada ketidak sdaran dri ortu akan akta kelahiran anakx......

**Comment by eddieridwan** [comment]
Sdh dicommit ke master.
