### ISSUE TITLE
Setelah import penduduk RT, RW dan Dusun tidak terbaca

### ISSUE THREAD

**Issue by cakwidodo** [eddieridwan/OpenSID#237]
setelah import data penduduk .xls rt, rw dan dusun tidak terbaca (bisa di check lagi) hal ini terjadi pada operasi windows

**Comment by eddieridwan** [comment]
Harap jelaskan:

1. Import excel atau BIP?
2. Errornya seperti apa -- apakah proses impor ada error, atau sukses tapi rt/rw/dusun kosong?
3. Lampirkan contoh data (beberapa baris) yang diimpor.
4. OpenSID versi berapa?

**Comment by cakwidodo** [comment]
[contoh data penduduk latihan.zip](https://github.com/eddieridwan/OpenSID/files/678660/contoh.data.penduduk.latihan.zip)
pada versi 1.7

**Comment by eddieridwan** [comment]
Masalah impor tidak merekam id_cluster (dusun,rw,rt) keluarga sudah diperbaiki dan sudah dicommit ke cabang master.
