### ISSUE TITLE
eror opensid_1.7

### ISSUE THREAD

**Issue by afri18** [eddieridwan/OpenSID#238]
saat klik data penduduk eror, kenapa ya ?? padahal database selalu di update, apa opensid_1.7 ada database yg perlu disesuaikan/update ???
![image](https://cloud.githubusercontent.com/assets/6611881/21562005/fd48b0a6-cea6-11e6-903c-f62fbd012b4e.png)

**Comment by eddieridwan** [comment]
Hal ini sudah ditanyakan di grup FB beberapa kali. Di bagian bawah catatan rilis di https://github.com/eddieridwan/OpenSID/releases dijelaskan adanya perubahan struktur database dan juga dijelaskan apa yang perlu dilakukan untuk migrasi database.

**Comment by afri18** [comment]
yang saya tanyakan apakah releas 1.7 ada database nya ? kenapa saat di unduh tidak ikut ??

**Comment by afri18** [comment]
database terakhir 1.5 direaleas 1.6 sudah tidak ada update database buat pengguna lama, saat realeas 1.7 terjadi eror buaka menu penduduk, ini yg saya alami bung, yadinya aman sampai relas 1.6

**Comment by eddieridwan** [comment]
@afri18 , Ya, memang 1.5 versi terakhir yg ada file migrasi_xxx.sql secara terpisah. 

Ini karena fitur Database > Migrasi DB SID 3.04 juga berisi script sql untuk melakukan migrasi yang diperlukan. Jadi daripada duplikasi, sekarang pada waktu update tinggal menjalankan Migrasi DB SID 3.04 untuk mengubah struktur database yang diperlukan. Dan proses ini berlaku untuk upgrade dari versi berapa saja, karena fitur Migrasi DB SID 3.04 berisi script migrasi untuk semua versi.

Mudah2an penjelesan ini membantu. Mungkin nama fitur Migrasi DB SID 3.04 perlu diganti, karena dapat digunakan untuk migrasi update, bukan saja untuk konversi database SID 3.04.

**Comment by afri18** [comment]
justru itu juga eror juga bung, 
![image](https://cloud.githubusercontent.com/assets/6611881/21574638/09512ce8-cf29-11e6-8d87-064c3a55e819.png)

**Comment by eddieridwan** [comment]
Itu karena di database anda ada lebih dari satu surat dengan kode surat '470.1.11'. Seharusnya kode surat unik; setiap surat perlu memiliki kode_surat yang berbeda.

Ubah kode surat yang sama supaya berbeda (di Cetak Surat > Master Surat); setelah itu coba jalankan lagi Migrasi DB.

**Comment by afri18** [comment]
okeh bung bisa, karna menurut saya kode surat adalah kode yang menunjukan jenis surat, jadi ada beberapa surat yg kodenya sama, contoh keterangan penduduk dengan surat domisili, menurut saya itu jenis surat yang sama, karna menerangkan tentang penduduk, itu yang saya ketahui dengan pengkodean surat. jadi kode surat bukan menunjukan id surat tertentu melainkan jenis surat, contoh lagi surat SKCK dengan ijin keramaian itu kodenya/jenisnya merupakan surat pengantar kepolisian biasanya sama

**Comment by eddieridwan** [comment]
Ok, bisa saja untuk menunjukkan jenis surat; tinggal ditambahkan nomor urut
untuk membedakan surat yang sejenis.

2016-12-31 14:08 GMT+11:00 Syafri <notifications@github.com>:

**Comment by afri18** [comment]
setelah saya coba, surat tambahan yg saya edit jadi tidak berfungsi, padahal direleas sebelumnya masih berjalan

**Comment by eddieridwan** [comment]
Apa errornya? Surat cetak langsung atau export doc?

**Comment by afri18** [comment]
ma'af bung edi, ternyata saya yang kurang teliti, folder surat di folder desa belom saya aktifkan, hanya saja kalau bisa kode surat saat migrasi atau update database jangan dirubah, karna cukup repot entri ulangnya,

**Comment by eddieridwan** [comment]
Ok, kode surat tidak akan diupdate pada migrasi, karena memang dapat diubah oleh pengguna, walaupun untuk surat yang merupakan bagian dari rilis inti.
