### ISSUE TITLE
#surat pindah

### ISSUE THREAD

**Issue by afri18** [eddieridwan/OpenSID#242]
![image](https://cloud.githubusercontent.com/assets/6611881/21576574/b0572004-cf67-11e6-9e72-6df04d542616.png)

**Comment by aero123** [comment]
Kalo menurut saya pribadi gausah ditambahi bung afri, karena format tersebut sudah merujuk pada formulir disdukcapil, dikhawatirkan nanti kalo ada tambahan pada formulir tersebut tidak diterima di instansi terkait. mohon koreksinnya bagi temen" yang lain, (dikarenakan mungkin tidak menjadi masalah bagi daerah lain)

**Comment by afri18** [comment]
D surat pindah disduk juga ada pilihan tersebut, yg artinya no kk d hapus karna tidak ada anggota kelurga yg tinggal

**Comment by eddieridwan** [comment]
Ya, pilihan _Tidak Ada Anggota Keluarga Yang Ditinggal_ ada pada F1-08, tetapi tidak ada pada blanko F1 pindah lainnya.

**Comment by afri18** [comment]
pilihan Tidak Ada Anggota Keluarga Yang Ditinggal sebaiknya selalu disertakan, sebagai kontrol buat desa tentang keberadaan anggota suatu keluarga, sebagai acuan apa no kk tersebut masih dipakai atau harus diganti (diganti otomatis bila yg pindah kepala keluarga oleh disduk)

**Comment by eddieridwan** [comment]
Sudah dirilis v1.8.
