### ISSUE TITLE
Perbaikan Title Page

### ISSUE THREAD

**Issue by keylaeff** [eddieridwan/OpenSID#243]
saran kedepan nya, dimohon untuk memperhatikan/memperbaiki title page pada opensid trsebut, saya lihat untuk title page nya masih belum unique tiap page nya. kecuali single page karena title mengambil judul postingan. hal ini akan berguna jika ada user yang ingin meng-online-kan opensid tersebut. jika hasil index, title seo baik. maka akan membantu promosi opensid itu sendiri agar dikenal banyak orang melalui search engine.
ex : homepage : <title> Sistem Informasi Desa ..... </title>
static page : <title> judul halaman static - Sistem Informasi Desa ..... </title>
archive page : <title> Judul Archive - Sistem Informasi Desa ..... </title>
category page : <title> judul kategori - Sistem Informasi Desa ..... </title>
search result page : <title> judul kueri hasil pencarian - Sistem Informasi Desa ..... </title>

mungkin itu saran dari saya, ada kurang lebih nya saat mohon maaf. terimakasih

**Comment by eddieridwan** [comment]
@keylaeff : terima kasih, saran yang baik. 

Apabila anda berminat, silakan juga sekaligus menerapkan usulan anda -- buat saja pull request.

Kami memang sangat harapkan ada teman2 programmer/developer yang dapat membantu pengembangan OpenSID -- karena walaupun bermanfaat sekali bagi desa2, seperti anda lihat sendiri ada banyak perbaikan yang bisa dilakukan.

Terima kasih atas perhatiannya.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
