### ISSUE TITLE
DATA RT-RW TIDAK MUNCUL PADA HASIL EXPORT DAN CETAK 

### ISSUE THREAD

**Issue by Jhiban-Khang** [eddieridwan/OpenSID#244]
data DUSUN, RT, RW tidak muncul pada saat ditampilkan, di export dan di cetak.

**Comment by eddieridwan** [comment]
@Jhiban-Khang, apakah ini di halaman Penduduk? Apakah di tabel penduduk tampil data Dusun, RT dan RW?

**Comment by eddieridwan** [comment]
@Jhiban-Khang : pada waktu melaporkan issue, harap menjelaskan:

1. versi OpenSID ditemukannya masalah
1. langkah yang dilakukan sebelum ketemu masalah
1. sebaiknya melampirkan tampilan layar errornya

**Comment by lemahayu** [comment]
pada export doc bukan tidak muncul Rt dan Rw hanya posisinya yang terbalik, kalau bisa nama dusun atau blok dulu baru Rt dan Rw dan kalau bisa Bloknya tercantum tidak hanya nama bloknya saja seperti digambar dibawah ini yang dilingkari warna merah.
![format export](https://cloud.githubusercontent.com/assets/22955154/21959595/6d7e31c6-dafe-11e6-9a8b-b56831bfcffc.JPG)

**Comment by MUHAMMADRANGSEL** [comment]
Itu dirubah di cetak atau print suratnyq

**Comment by eddieridwan** [comment]
Ditutup karena RT/RW muncul. Urutan penampilan bisa diubah di template surat.
