### ISSUE TITLE
Bug: gagal export exel pada rumah tangga

### ISSUE THREAD

**Issue by Jhiban-Khang** [eddieridwan/OpenSID#245]
gagal export exel pada rumah tangga, tidak muncul apa-apa setelah cetak exel pada rumah tangga

**Comment by pandigresik** [comment]
pada file donjo-app/views/sid/kependudukan/rtm-excel.php baris pertama 
`<?php php` 
rubah menjadi 
`<?php`

**Comment by eddieridwan** [comment]
Pull request https://github.com/eddieridwan/OpenSID/pull/393 sudah di-merge ke master.
