### ISSUE TITLE
404 Page Not Found , pada halaman rumah tangga, sortir dusun

### ISSUE THREAD

**Issue by Jhiban-Khang** [eddieridwan/OpenSID#246]
error 404 pada halaman, kependudukan, rumah tangga, filter dusun

**Comment by eddieridwan** [comment]
@Jhiban-Khang : pada waktu melaporkan issue, harap menjelaskan:

1. versi OpenSID ditemukannya masalah
1. langkah yang dilakukan sebelum ketemu masalah
1. sebaiknya melampirkan tampilan layar errornya

**Comment by eddieridwan** [comment]
Sdh dicommit ke master.
