### ISSUE TITLE
tambah anggota untuk kelompok tidak ada,

### ISSUE THREAD

**Issue by Jhiban-Khang** [eddieridwan/OpenSID#247]
menu tambah anggota kelompok tertentu tidak ada,

**Comment by metalab25** [comment]
itu di menu apa ?

**Comment by eddieridwan** [comment]
@Jhiban-Khang Maksudnya fitur ini?

![tombol-tambah-anggota-kelompok](https://cloud.githubusercontent.com/assets/249563/22859639/c2368466-f147-11e6-9170-579b66a01c83.jpg)

**Comment by eddieridwan** [comment]
Sepertinya yang diperlukan adalah panduan untuk menu _Kelompok_.

Kami akan tutup issue ini. Silakan buka lagi jika ada perbaikan spesifik yang diinginkan.
