### ISSUE TITLE
informasi yang disajikan dari file export maupun import excel bisa lebih banyak

### ISSUE THREAD

**Issue by Agus-Heriyanto** [eddieridwan/OpenSID#248]
Adanya penambahan kolom untuk untk file excel yang export maupun import terkait identitas yang tersajikan di biodata pendudk misalkan kolom akseptor KB, status kehamilan dsb karena jika desa ingin mengumpulkan data terlebih dahulu lwt excel maka akan banyak informasi dari identitas penduduk yang langsung tersaji dan tidak megisi secara manual lagi karena mengisi manual membutuhkan waktu yang lama.Begitu juga dengan hasil export menampilkan data yang sama sehingga jika ingin dilengkapi maka desa hanya menambahakan data yang belum terisi untuk diimport kemudian
[import data konsultasi.xlsx](https://github.com/eddieridwan/OpenSID/files/683641/import.data.konsultasi.xlsx)
[import data konsultasi.xlsx](https://github.com/eddieridwan/OpenSID/files/683648/import.data.konsultasi.xlsx)

**Comment by MUHAMMADRANGSEL** [comment]
Isue ini sudah dikerjakan sharusnya perku diclosed mas eddie

**Comment by eddieridwan** [comment]
Sudah dikerjakan di #587.
