### ISSUE TITLE
Bug: kode_surat masih unik, padahal sebagai klasifikasi surat tidak harus unik untuk surat

### ISSUE THREAD

**Issue by afri18** [eddieridwan/OpenSID#249]
masih ditemukan eror saat migrasi database di Opensid_1.8
![image](https://cloud.githubusercontent.com/assets/6611881/21671018/2fef1c18-d34b-11e6-9e2f-8e7eb4f53e38.png)

**Comment by eddieridwan** [comment]
Ini adalah karena walaupun kode surat tidak diubah pada saat migrasi, kolom kode surat harus unik, karena berfungsi sebagai id.

Jadi dalam kasus anda, seperti diusulkan sebelumnya, anda dapat dengan mudah menambahkan nomor urut pada 'kategori' surat supaya menjadi unik (misalnya 470.1.15.1, 470.1.15.2, dstnya), sehingga info kategori masih ada.

Alternatif lain, kita bisa tambahkan kolom baru di tabel tweb_surat_format yang bisa dipakai untuk merekam kategori surat.

**Comment by afri18** [comment]
sebaiknya kode surat jangan dijadikan id surat, kalau memang dibutuhkan id surat tambahkan aja di kolom baru

**Comment by eddieridwan** [comment]
Istilah 'kode surat' biasanya bermakna ID. Kalau mau kita bisa ubah kolom yang ada menjadi 'kategori' atau 'jenis' (supaya jelas kegunaannya -- isi kolom tidak diusik) dan tambahkan kolom baru bernama 'kode surat' untuk dipakai sebagai id.

**Comment by afri18** [comment]
coba lihat pengkodean surat, kadang judul surat tidak sama tapi kodenya sama, pernah kita bahas tenyang ini, seperti surat pengantar kawin (surat jenis N1 sampai N7, sepengetahuan saya kodenya sama tentang pengantar kawin)

**Comment by eddieridwan** [comment]
Ini sebenarnya masalah pengertian istilah. Istilah apa yang dipakai untuk menyebut "F-1.25", "F-1.08" atau "N1" yang secara unik menentukan suatu blanko/format? Apakah "F-1.25" disebut "kode" blanko atau apakah ada istilah lain yang digunakan?

**Comment by eddieridwan** [comment]
Sebagai perbandingan, pada SHDK misalnya, bukankan "kode"-nya seperti 01/02/dstnya harus unik?

**Comment by afri18** [comment]
pengertian yg saya tau kode surat adalah jenis surat karna kalau tentang kepolisian kode umumnya 330 jenis surat penduduk 470 kalau ID JUDUL SURAT  itu sesuatu yg berbeda

**Comment by eddieridwan** [comment]
Ok, penggunaan istilah "kode" memang tidak konsisten. Penggunaan 'kode' untuk menyebut 'F-1.03' yang unik saya kira lebih konsisten dengan pengertian teknis istilah 'kode' (seperti 'kode' Agama atau 'kode' SHDK dsbnya yang nota bene unik).

Tetapi, tampaknya penggunaan sebutan **'kode surat'** sudah terlanjur umum digunakan sebagai singkatan dari **'kode jenis surat'**. 

Bagaimana kalau kita ganti nama kolom _kode_surat_ menjadi _kode_jenis_surat_, dan tambahkan kolom baru _id_surat_?


![kode-surat-1](https://cloud.githubusercontent.com/assets/249563/21674362/842a0690-d381-11e6-8d4b-a634e71371ed.jpg)
![kode-surat-2](https://cloud.githubusercontent.com/assets/249563/21674363/842d3cd4-d381-11e6-93fb-cdcab484e1ad.jpg)
![kode-surat-3](https://cloud.githubusercontent.com/assets/249563/21674364/8430668e-d381-11e6-8cd3-b0d44a0034c7.jpg)

**Comment by andanwar** [comment]
Apakah ada yg bisa sesuaikan dengan format Cianjur pak,

**Comment by eddieridwan** [comment]
@afri18 itu contoh 'kode klasifikasi arsip', yaitu 'klasifikasi'-nya yang diberi kode, bukan 'surat'-nya. Yaitu, 'jenis surat'-nya yang diberi kode, bukan 'surat'-nya. Suratnya sendiri kalau diberi kode, ya harusnya unik. 

Sama dengan di perpustakaan, kode serupa yang digunakan adalah 'kode klasifiikasi buku' bukan 'kode buku'.

![kode_klasifikasi_buku](https://cloud.githubusercontent.com/assets/249563/21678414/babd322a-d392-11e6-8d82-1cc5b27774c9.jpg)

**Comment by afri18** [comment]
![image](https://cloud.githubusercontent.com/assets/6611881/21684618/03bd9386-d391-11e6-958f-e650b22d85c7.png)

**Comment by afri18** [comment]
kalau meng arsipkan ya sesuai kode surat yang tertera, akan lebih mudah, tidak perlu membuka/menghafal pengarsipan

**Comment by afri18** [comment]
https://docs.google.com/file/d/0B5oOxjjjp5iDMFJJSy1Oa0c1ZE0/view

**Comment by eddieridwan** [comment]
@afri18 apakah itu Kode Klasifikasi Surat yang baku, atau yang banyak digunakan di desa? Kalau iya, kita bisa tambahkan pada SID.

Jadi setuju kita pakai istilah "kode klasifikasi surat" atau disingkat "klasifikasi"?

**Comment by eddieridwan** [comment]
Sdh dicommit.

**Comment by afri18** [comment]
Dah sesuai ketentuan srt dinas

**Comment by afri18** [comment]
Dah sesuai ketentuan dinas, kalau desa bisa adanya klasifikasi global, mungkin ketidak tauan, misal, untk kepolisian ambil mudahnya 331, nggak make klasifikasi ditail

**Comment by afri18** [comment]
Dah sesuai ketentuan surt dinas, kalau desa bisa adanya klasifikasi global, mungkin ketidak tauan, misal, untk kepolisian ambil mudahnya 331, nggak make klasifikasi ditail

**Comment by Isharayafawi** [comment]
Assalamualaikum,, kepanjangan dari Huruf "N" (N1) itu apa yah??? yang tau mohon pencerahanx
