### ISSUE TITLE
Bug pembuatan artikel baru

### ISSUE THREAD

**Issue by metalab25** [eddieridwan/OpenSID#253]
Pada saat pembuatan artikel baru sukses dan tampil pada Front-End web namun pada saat mau baca lengkap artikelnya data tidak ditemukan dan waktu mau edit artikelnya juga kosong.
Saya cek di DB pada table artikel juga data artikel tersebut tidak ada.
padahal kalo di offline itu tidak ada masalah namun mengapa kalo OpenSID ini di onlinekan terjadi masalah seperti itu

OpenSID V.1.7

**Comment by eddieridwan** [comment]
Sudah coba di demo sid.bangundesa.info untuk melihat apakah masalah anda juga ditemukan di v1.8?

Jadi judul artikel ada, tapi isi artikel kosong? Kalau di-edit ulang apakah tetap isi artikel tidak tersimpan?

**Comment by metalab25** [comment]
kalau edit artikel judul dan isi artikel kosong, saya juga cek di db didalam table artikel, artikel tersebut tidak ada

**Comment by eddieridwan** [comment]
Sudah coba di demo sid.bangundesa.info untuk memasukkan artikel anda? Untuk melihat apakah masalah anda juga ditemukan di v1.8?

Mungkin coba instal OpenSID online lagi? Sekalian upgrade ke v1.8.

**Comment by metalab25** [comment]
setelah saya update ke 1.8 akhirnya tidak ada masalah lagi
