### ISSUE TITLE
Bug: Pilihan pendidikan sedang ditempuh tidak tampil di form isian keluarga baru

### ISSUE THREAD

**Issue by afri18** [eddieridwan/OpenSID#254]
pilihan di Pendidikan sedang di Tempuh tidak muncul, begitu juga dengan form tambah data keluarga
![image](https://cloud.githubusercontent.com/assets/6611881/21926181/35fff7e4-d9b3-11e6-96bf-9bb8fb018c3f.png)

**Comment by metalab25** [comment]
sepertinya ada kesalahan pada database anda, sebab pada field tersebut datanya mengambil dari isi tabel database tweb_penduduk_pendidikan
Silahkan periksa kembali database anda.
Terimakasih

**Comment by afri18** [comment]
metalab25 itu hanya berlaku di form tambah keluarga dan tambah data anggota keluarga, sedangkan di tambah penduduk lancarjaya, kalaulah anda sarankan diperiksa database apanya yg diperiksa ? mohon saran yang detail

**Comment by eddieridwan** [comment]
Sdh diperbaik dan dicommit.

**Comment by afri18** [comment]
untuk tambah keluarga sudah jalan untuk tambah anggota keluarga belum tampil
![image](https://cloud.githubusercontent.com/assets/6611881/22054473/58031fa0-dd88-11e6-8f5f-1160ae726e80.png)

**Comment by eddieridwan** [comment]
Ok, pilihan pendidikan sedang ditempuh sudah tampil di form tambah anggota keluarga.

**Comment by afri18** [comment]
okeh bung eddie sekarang dah jalan
kalau saya hanya bisa koreksi aja moga sid makin berkembang
