### ISSUE TITLE
Fitur: Supaya tabel Log Penduduk bisa diurut berdasarkan Tanggal Peristiwa

### ISSUE THREAD

**Issue by afri18** [eddieridwan/OpenSID#255]
agar memudahkan koreksi dan pencarian sebaiknya form di penduduk_log diurutkan berdasarkan tanggal peristiwa, yang paling atas tanggal peristiwa terbaru
![image](https://cloud.githubusercontent.com/assets/6611881/21926789/ce9298fc-d9b5-11e6-9f1b-d7bbe8081e08.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.

**Comment by afri18** [comment]
makin mantaab ini bung eddie
