### ISSUE TITLE
Usul: Supaya database antar versi bisa seragam

### ISSUE THREAD

**Issue by afri18** [eddieridwan/OpenSID#256]
pada database contoh saya perhatikan ada 84 table, sedangkan di sid yg saya pakai terkoreksi 85 table, setelah dimigrasi ke opensid1.8 atau 1.9 table jumlahnya jadi tidak beraturan, kadang saat migrasi 79 kadang 74 ada solusi agar database bisa seragam ???
contoh database awal ada 84 table
![image](https://cloud.githubusercontent.com/assets/6611881/21929076/213e519e-d9c1-11e6-973d-c4d7a6829e2b.png)
setelah migrasi terkoreksi 79 table
![image](https://cloud.githubusercontent.com/assets/6611881/21929143/77859e72-d9c1-11e6-8ec5-4579ff493603.png)

**Comment by metalab25** [comment]
sepertinya di OpenSID V.1.8 sudah menghilangkan fitur Migrasi DB dari SID-CRi ke OpenSID, jadi saran saya ada kalau mau "Migrasi" dari SID-CRI ke OpenSID gunakan dulu OpenSID versi 1.7 dan jalankan migrasi DB SID baru setelah sukses anda update ke versi OpenSID versi 1.8 lalu jalankan lagi Migrasi DB OpenSID.
Terimakasih

**Comment by afri18** [comment]
metalab25 , database yg saya pakai sudah opensid terakhir opensid1.6 , epengetahuan saya di opensid1.7 tidak tersedia migrasi database khusus secara terpisah, sudah digabung dimenu Migrasi DB dari SID-CRi ke OpenSID. pengertian yang saya dapat adalah migrasi kedatabase ini adalah migrasi dari database jenis apa saja, mungkin bung eddie bisa menjelaskan

**Comment by metalab25** [comment]
diatas anda sebutkan bahwa "sedangkan di sid yg saya pakai terkoreksi 85 table" jadi saya berasumsi bahwa anda menggunkan SID-CRI.
Itu dibawah saya ambilkan sedikit dari changelog rilis OpenSID 1.7

> Rilis ini memerlukan perubahan struktur database. Apabila meng-upgrade (yaitu bukan install baru), struktur database perlu diubah dengan menjalankan fitur Database > Migrasi DB SID 3.04. Fitur migrasi ini melakukan perubahan database yang diperlukan.

**Comment by eddieridwan** [comment]
@afri18 : pada suatu rilis, struktur database mungkin berubah, tergantung fitur/perbaikan apa yang diterapkan pada rilis tersebut. Jadi ada rilis di mana jumlah tabel bertambah, misalnya pada v1.1, karena diperlukan tabel untuk mengelola widget.

 Jumlah tabel bisa juga berkurang. Misalanya pada v1.9 yang akan dirilis hari Kamis yang akan datang (v1.9 belum dirilis; yang di master adalah pre-1.9), jumlah tabel berkurang, karena beberapa tabel yang tidak digunakan lagi (seperti ref_jamkesmas, ref_raskin -- yang sudah digabungkan pada program bantuan) sebaiknya dihapus. Tabel/script yang tidak dipakai sebaiknya dihapus, supaya tidak membingungkan programmer yang mengembangkan OpenSID.

Singkatnya, struktur database OpenSID akan terus berkembang tergantung kebutuhan, sehingga mungkin saja pada versi lainnya jumlah tabel akan berubah lagi.

**Comment by eddieridwan** [comment]
@metalab25 , @afri18 : mengenai Migrasi DB, di beberapa posting di FB sudah dijelaskan bahwa yang dulu namanya _Migrasi DB SID 3.04_ sekarang diganti namanya menjadi _Migrasi DB_, karena fitur ini digunakan untuk mengubah struktur database ke struktur database terkini --- dan ini berlaku untuk semua database, baik database yang berasal dari instalasi SID 3.04 CRI ataupun database dari versi OpenSID yang lalu.

Penjelasan ini juga ada di panduan, di:

1. https://github.com/eddieridwan/OpenSID/wiki/Panduan-Administrasi-Database
1. https://github.com/eddieridwan/OpenSID/wiki/Panduan-Pindah-Dari-SID-CRI-ke-OpenSID

Harap teman2, sebagai senior OpenSID, rajin2 membaca panduan dan juga rajin mengembangkan dan memperbaiki panduan.

**Comment by afri18** [comment]
maksudnya adalah agar database contoh dengan database yg sudah migrasi jumlah table/strukturnya nya sama, ini penting bagi pengguna lama (yg sudah ada datanya), jadi sebagai koreksi/perbandingan apakah migrasi sukses atau tidak dengan melihat/membandingkan dengan databasecontoh

**Comment by eddieridwan** [comment]
@afri18 , sekadar info: database contoh biasanya hanya diupdate pada waktu akan rilis resmi. Di cabang master, misalnya kalau versi 'pre-1.9', menunjukkan versi ini belum dirilis. Ingat rilis resmi hanya versi yang tampil di https://github.com/eddieridwan/OpenSID/releases. 

Di cabang master, yang belum dirilis resmi, struktur database masih bisa berubah, tergantung fitur/perbaikan apa lagi yang diterapkan sebelum dirilis resmi. Karena itu, terlalu dini untuk membuat database contoh.

Singkatnya: kalau memakai versi yang belum dirilis resmi, yaitu yang ada tulisan 'post-xxx' atau 'pre-xxx', database contoh belum tentu cocok dengan fitur Migrasi DB. Yang rilis resmi di https://github.com/eddieridwan/OpenSID/releases diusahakan agar struktur database contoh sesuai dengan Migrasi DB.

**Comment by eddieridwan** [comment]
Apabila ingin melihat secara rinci apa yang diubah pada setiap migrasi, silakan buka saja berkas donjo-app/models/database_model.php. Misalnya untuk melihat migrasi dari versi 1.8 ke 1.9 sampai saat ini (karena belum dirilis) cari saja di fungsi migrasi_18_ke_19().
