### ISSUE TITLE
Mohon ditambahkan data bantuan di layanan mandiri

### ISSUE THREAD

**Issue by metalab25** [eddieridwan/OpenSID#257]
Mohon ditambahkan data Bantuan bagi penduduk/keluarga di dalam layanan mandiri.
Jadi Penduduk/Keluarga bisa mengetahui Bantuan apa saja yang didapatkan oleh warga itu sendiri apa bila warga tersebut login melalui Layanan Mandiri.
![2017-01-14 2](https://cloud.githubusercontent.com/assets/19917739/21942354/b5eea0fa-da07-11e6-81c3-5dfb9e9dc0bb.jpg)

Terimakasih

**Comment by eddieridwan** [comment]
Duplikat #443
