### ISSUE TITLE
Bug: input keluarga baru dusun/rw/rt kelurga tdk muncul

### ISSUE THREAD

**Issue by desahadakewa** [eddieridwan/OpenSID#262]
keluarga»»»tamabah data baru»»> semua kolom di isi dan saat disimpan data berhasil disimpan hanya saja alamat keluarga tersebut tidak ada.. sehingga saya melakukan pindah penduduk dalam desa untuk mendapatkan alamat. apakah ini kesalahan penginputan data saya atau .....??? mks..salam desa hadakewa.

**Comment by eddieridwan** [comment]
Kolom alamat berhasil disimpan, tetapi id_cluster (dusun, rw, rt) tidak.

**Comment by eddieridwan** [comment]
Sdh dicommit ke master.
