### ISSUE TITLE
Tidak Merubah Logo Desa dan Logo User

### ISSUE THREAD

**Issue by BorneoStg86** [eddieridwan/OpenSID#263]
Kira" apa ya om penyebabnya tidak bisa diganti logo desa sama logo user admin?
padahal sudah di upload, ttp aja ga bisa...#solusinya om

**Comment by metalab25** [comment]
apa folder desa-contoh sudah di rename menjadi desa ????

**Comment by eddieridwan** [comment]
Silakan lihat panduan di https://github.com/eddieridwan/OpenSID/wiki/Tanya-Jawab-Install-dan-Update dan langkah (3) di https://github.com/eddieridwan/OpenSID/wiki/Panduan-Install-OpenSID.
