### ISSUE TITLE
Mengganti sebutan 'kabupaten' dengan 'kota'

### ISSUE THREAD

**Issue by ariefprabowo81** [eddieridwan/OpenSID#266]
![kabupaten](https://cloud.githubusercontent.com/assets/25439726/22628391/dbafe212-ec05-11e6-9e4e-c58fea3ddb79.jpg)
selamat siang pak eddi, saya kebetulan bekerja di kelurahan kampung dalam kota pekanbaru. kemarin saya browsing2 dan kebetulan menemukan OpenSID ini. kemudia saya uji coba dulu programnya untuk di RT perumahan saya (kebetulan juga saya ketua RT) sebelum saya gunakan untuk di kantor. Overall, programnya sangat bagus,lengkap, dan sangat membantu sekali.

ada beberapa usul dan pertanyaan sekitar OpenSID ini :

1. apakah OpenSID ini hanya untuk pemerintahan kabupaten saja? karena di tempat saya sudah tidak ada lagi desa apalagi dusun. saya sudah coba utk mengganti kata 'desa' menjadi 'kelurahan' dan sudah berhasil. hanya saja masih ada kata dusun yang tidak bisa saya hilangkan.

2. di dalam identitas kelurahan/desa ada 'nama kabupaten'. saya sudah untuk menggantinya cuma belum berhasil. mohon petunjuk nya.

mungkin untuk sementara itu saja yang saya tanyakan. atas perhatiannya diucapkan terima kasih.

**Comment by pandigresik** [comment]
pada donjo-app/config/sid_ini.php tambahkan config sebutan_kabupatan sehingga menjadi seperti ini
`$config['sebutan_desa'] = 'kelurahan';
$config['sebutan_dusun'] = 'dusun';
$config['login_title'] = 'OpenSID';
$config['admin_title'] = 'Sistem Informasi Desa';
$config['sebutan_kabupaten'] = 'kota';`

kemudian pada donjo-app/views/home/konfigurasi_form.php
pada baris ke 40 `<th>Nama Kabupaten</th>`
ubah menjadi `<th>Nama <?php echo ucwords(config_item('sebutan_desa'))?></th>`

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
