### ISSUE TITLE
Dropdown Format Import Excel yang keluar tulisan bukan ID nya

### ISSUE THREAD

**Issue by ariefprabowo81** [eddieridwan/OpenSID#267]
![format import](https://cloud.githubusercontent.com/assets/25439726/22557200/5dbfc414-e99c-11e6-8fb9-8cfd41ce4651.jpg)

format import excel ketika ingin mengisi kolom agama, pendidikan yang keluar tulisannya bukan ID 1 atau 2 atau 3. mohon bantuannya.

trims

**Comment by eddieridwan** [comment]
Terima kasih telah melaporkan. Sudah diperbaiki, dan dicommit ke cabang master. Dapat diunduh dari https://github.com/eddieridwan/OpenSID/. Klik tombol hijau _Clone or download_, terus klik _Download ZIP_.
