### ISSUE TITLE
statistik wilayah

### ISSUE THREAD

**Issue by afri18** [eddieridwan/OpenSID#268]
di status FB ada yang menanyakan ketidak singkronan data statistik wilayah denga data yg di tampilkan ini saya periksa baik di web saya sendiri maupun di web sid.bangundesa memang terjadi kesalahan link bung Eddie menyarankan silahkan baca petunjuk, lalu diberikan linknya yang jadi masalah adalah link tersebut sepengetahuan saya adalah link statis/tetap/bawaan sid saya sendiri luput menyadari sejak opensid versi berapa ini terjadi , saya coba menyamakan lansung dari table tetap nggak bisa, kesimpulan kemungkinan ada php yg dirubah, mohon koreksi ulang menu statistik wilayah, kalau bisa tampilan mulai dari Dusun > Jumlah Rw > Jumlah RT > jumlah penduduk
![image](https://cloud.githubusercontent.com/assets/6611881/22628075/d2c45cd8-ebff-11e6-9b00-5bc300d30933.png)

**Comment by eddieridwan** [comment]
Seperti dijelaskan di https://github.com/eddieridwan/OpenSID/wiki/Menu-Peragaan-Statistik (lihat daftar _Peragaan Statistik Yang Tersedia_), untuk menampilkan Data Demografi Berdasar Populasi Per Wilayah ganti link menu statis yang bersangkutan menjadi _wilayah_. Sebagai contoh di situs demo di http://sid.bangundesa.info, menu Data Wilayah Administratif sudah di-edit dan sekarang menampilkan statistik yang diinginkan.

Tidak ada script yang perlu diperbaiki. Hanya menu saja yang perlu di-edit. 

Di cabang master di https://github.com/eddieridwan/OpenSID contoh_data_awal_20170204.sql sekarang sudah diperbaiki, sehingga pemula yang mengimpor contoh data awal menampilkan statistik yang benar. 

![link-statistik-data-wilayah](https://cloud.githubusercontent.com/assets/249563/22629535/d50ca41c-ec4c-11e6-9571-acc250798599.jpg)

**Comment by afri18** [comment]
ternyata mesti ketik " wilayah " baru muncul

**Comment by eddieridwan** [comment]
Apabila panduan di https://github.com/eddieridwan/OpenSID/wiki/Menu-Peragaan-Statistik kurang jelas, silakan diperbaiki.
