### ISSUE TITLE
Bug: Missing image /assets/images/gis/point/face-embarrassed.png

### ISSUE THREAD

**Issue by cafeiklan** [eddieridwan/OpenSID#278]
![2017-02-12_124934](https://cloud.githubusercontent.com/assets/1905469/22859978/19ec22e0-f122-11e6-818d-b48681cbd6de.jpg)

**Comment by cafeiklan** [comment]
Cari di sid 3.04 kok gak nemu

**Comment by MUHAMMADRANGSEL** [comment]
Di SID 3.10 tempatnya ada

**Comment by MUHAMMADRANGSEL** [comment]
Di SID 3.10 tempatnya ada

**Comment by cafeiklan** [comment]
kok gak ketemu ya mas, saya ada branch SID 3.10, apa mungkin branch nya kurang lengkap 
https://github.com/cafeiklan/opensid/tree/original-SID-3.10/assets/images/gis/point

**Comment by eddieridwan** [comment]
Bagaimana @cafeiklan, anda bisa selesaikan issue ini?

**Comment by MUHAMMADRANGSEL** [comment]
Nanti saya kirimkan mas eddie

Pada tanggal 17 Mar 2017 03:05, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by MUHAMMADRANGSEL** [comment]
masalahnya di
![tangkapan layar 2017-03-19 22 17 38](https://cloud.githubusercontent.com/assets/25834335/24082173/b4c8e478-0cf3-11e7-8107-d5e95a53a2b5.png)
Solusinya

di foldes gis dan icon kalau saya periksa yang belum lengkap folder icon 
 saya kirimkan folder images yang gis dan icon nya lengkap di group setelah itu coba tekan tombol migrasi dan dicoba

**Comment by eddieridwan** [comment]
Selain tidak ada icon yang dicari, ternyata OpenSID juga kekurangan tabel gis_simbol yang ada di 3.10. Perlu ditambahkan migrasi untuk membuat tabel ini dan mengisi semua icon. Ambil sql-nya dari file sid.sql di 3.10.

**Comment by eddieridwan** [comment]
Sdh dicommit ke master.
