### ISSUE TITLE
Bug: program_bantuan/detail

### ISSUE THREAD

**Issue by cafeiklan** [eddieridwan/OpenSID#279]
![2017-02-12_125645](https://cloud.githubusercontent.com/assets/1905469/22860009/d4dc9562-f122-11e6-9664-9d47f597e5ba.jpg)

Unknown column 'p.no_id_kartu' in 'field list'

**Comment by eddieridwan** [comment]
Seperti dijelaskan pada posting di FB, jangan lupa menjalankan Database > Migrasi untuk mengubah struktur database.
