### ISSUE TITLE
TODO: Error not found /index.php/rtm/dusun

### ISSUE THREAD

**Issue by cafeiklan** [eddieridwan/OpenSID#280]
![2017-02-12_132542](https://cloud.githubusercontent.com/assets/1905469/22860138/ec07071e-f126-11e6-823d-e4137f919c22.jpg)

Fix err Not Found

**Comment by cafeiklan** [comment]
Fixed #286

**Comment by cafeiklan** [comment]
Belum fix untuk /rtm/dusun

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
