### ISSUE TITLE
membuat slide header

### ISSUE THREAD

**Issue by metalab25** [eddieridwan/OpenSID#287]
Berikut contoh isi file Slide Headernya dengan nama file slide1.php

`<html lang="en">
<head>
  <link type='text/css' href="<?php echo base_url()?>desa/css/desa-web.css" rel='Stylesheet' />
  <link type='text/css' href="<?php echo base_url()?>desa/css/desa-default.css" rel='Stylesheet' />
 <link type='text/css' href="<?php echo base_url()?>desa/css/slider.css" rel='Stylesheet' />
  
  
  <script type="text/javascript" src="<?php echo base_url()?>desa/js/jquery-3.1.1.min.js"></script>
  <script type="text/javascript" src="<?php echo base_url()?>desa/js/jquery.cycle2.min.js"></script>
  
<style type="text/css">
</style>
</head>  
<body>
<div class="cycle-slideshow">
    <span class="cycle-prev"><img src="<?php echo base_url()?>desa/css/images/back_button.png" alt="Back"></span> 
    <span class="cycle-next"><img src="<?php echo base_url()?>desa/css/images/next_button.png" alt="Next"></span>
    <span class="cycle-pager"></span>  
	<img src="<?php echo base_url()?>desa/slide/slide_besar_01.jpg" alt="Logo dan kata kata">
	<img src="<?php echo base_url()?>desa/slide/slide_besar_08.jpg" alt="Panatai Hadakewa">
    <img src="<?php echo base_url()?>desa/slide/slide_besar_06.jpg" alt="Papan Kantor Desa">
	<img src="<?php echo base_url()?>desa/slide/slide_besar_07.jpg" alt="Kantor Desa">
	<img src="<?php echo base_url()?>desa/slide/slide_besar_05.jpg" alt="Rapat Batas Desa">
	<img src="<?php echo base_url()?>desa/slide/slide_besar_03.jpg" alt="Seremoni Lubang Kali">
	<img src="<?php echo base_url()?>desa/slide/slide_besar_04.jpg" alt="Kegiatan Tim Siaga Bencana">
	 
</div>
</body>
</html> `

load file slide1.php di file contents.php yang ada di folder view/partial

if(count($slide)>0){
									$this->load->view('layouts/slide1.php');
}

letakan posisinya diatas headline

**Comment by cafeiklan** [comment]
ini knp tidak di pull request sj ya?

**Comment by metalab25** [comment]
saya ge ngerti caranya om

**Comment by eddieridwan** [comment]
[slide_header.zip](https://github.com/eddieridwan/OpenSID/files/776138/slide_header.zip)

**Comment by TAHTA24** [comment]
Issue sy dikerjakan jg yah mas eddie ridwan 
Penambahan tanggal dan nama kepala desa pada laporan kependudukan bulanan
![screenshot_20170317-232723](https://cloud.githubusercontent.com/assets/22760871/24068840/d9b3323c-0bd3-11e7-84bb-f43069d719f6.png)
![laporan bulanan](https://cloud.githubusercontent.com/assets/22760871/24068846/1af0b530-0bd4-11e7-9f0c-3ab53639791a.png)

**Comment by eddieridwan** [comment]
Tambahkan sebagai bagian dari modul Galeri. Suatu album dapat ditampilkan di slider. Semua foto di album tersebut akan ditampilkan di slider.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
