### ISSUE TITLE
menghilangkan index.php

### ISSUE THREAD

**Issue by metalab25** [eddieridwan/OpenSID#288]
Buat file .htaccess di root opensid dan berikut ini isinya
`RewriteEngine on
RewriteCond $1 !^(index\.php|resources|robots\.txt)
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php/$1 [L,QSA]`

lalu edit file config.php yang ada di folder donjo-app/config/ 
ubah $config['index_page'] = 'index.php'; menjadi $config['index_page'] = '';

**Comment by batudaa** [comment]
Untuk hal seperti ini mungkin bisa dikemas dalam bentuk panduan dan kirim ke wikinya [OpenSID](https://github.com/eddieridwan/OpenSID/wiki) ketimbang menjadi issue.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master. Lihat penjelasan penerapan di https://github.com/eddieridwan/OpenSID/pull/328. Fitur ini tidak langsung dapat digunakan, karena tergantung konfigurasi apache --- apakah mengizinkan penggunaan .htaccess atau tidak.
