### ISSUE TITLE
Bug: Error setelah impor data analisis

### ISSUE THREAD

**Issue by eddieridwan** [eddieridwan/OpenSID#290]
Laporan dari Rarang Selatan:

"menu analisis setelah selesai import analis selalu muncul layar seperti di bawah ini"

![error-import-analisis](https://cloud.githubusercontent.com/assets/249563/22967909/3c50ee30-f3cd-11e6-88ea-1696f6c38666.png)

**Comment by eddieridwan** [comment]
Masalah ini kemungkinan besar disebabkan versi SID 3.04 yang digunakan sebagai versi awal OpenSID memang belum lengkap -- terutama pada modul Analisis. Mudah2an dengan adanya script SID 3.10 kita dapat menyerap penyempurnaan modul Analisis yang sepertinya sudah dilakukan, termasuk kelengkapan database (masalah di atas menunjukkan adanya kolom yang belum dibuat).

**Comment by metalab25** [comment]
saya tidak tau ini solusi dari permasalahannya apa bukan
kalo saya tinggal menambahkan kolom kode_jawaban pada tabel "analis_parameter" melalui phpmyadmin dan error pun tidak muncul lagi

**Comment by eddieridwan** [comment]
Sdh disesuaikan dengan SID 3.10. Impor analisis sudah berhasil dijalankan.
Sdh dicommit ke master.
