### ISSUE TITLE
Nomor Kartu Keluarga

### ISSUE THREAD

**Issue by afri18** [eddieridwan/OpenSID#291]
bila penduduk meninggal/pindah/hilang sebaiknya nomor kartu keluarga dan nama Kepala Keluarga langsung tercatat di table log_penduduk, alasannya : 
bila nomor kartu keluarga/kepala keluarga berubah kita masih bisa melihat asal usul penduduk yang meninggal/pindah/hilang tersebut
karna saya mengalami begitu kepala keluarga/nomor KK berubah maka tidak bisa lagi kita melihat asal penduduk yang meninggal/pindah/hilang tersebut karna yg ada di table log_penduduk tersebut hanya id keluarga dan id penduduk dalam sistem

**Comment by eddieridwan** [comment]
Sdh dicommit ke master.
