### ISSUE TITLE
Fitur (SID 3.10): Format surat bisa diaktif/non-aktifkan

### ISSUE THREAD

**Issue by eddieridwan** [eddieridwan/OpenSID#292]
Hanya surat yang aktif yang ditampilkan di menu Cetak Surat > Cetak Surat.

![disable-master-surat](https://cloud.githubusercontent.com/assets/249563/22992765/8dae87d0-f425-11e6-8d4e-28a70ac869e1.png)

**Comment by eddieridwan** [comment]
Sdh dicommit ke master.

**Comment by Dedi83** [comment]
![non aktifkan surat01](https://cloud.githubusercontent.com/assets/19701605/23367604/65094556-fd3d-11e6-9009-58981cd96e93.png)
![non aktifkan surat02](https://cloud.githubusercontent.com/assets/19701605/23367607/656c7bb2-fd3d-11e6-8202-6ff755c4fef3.png)
![non aktifkan surat03](https://cloud.githubusercontent.com/assets/19701605/23367605/655062a6-fd3d-11e6-8c6a-e06a6c045ecc.png)
![non aktifkan surat04](https://cloud.githubusercontent.com/assets/19701605/23367606/65619fb2-fd3d-11e6-9548-ee016c3ed77b.png)
