### ISSUE TITLE
NIP sekdes yang di struktur pemerintah desa tertulis otomatis dalam surat

### ISSUE THREAD

**Issue by Agus-Heriyanto** [eddieridwan/OpenSID#296]
Masih banyak desa sekdenya dari kalangan PNS jadi untuk mempermudah penulisan secara otomatis untuk NIP sekdes langsung tertera di dalam surat.Hal ini juga bisa dimanfaatkan jika open SID dipergunakan oleh kelurahan karena saat ini Kami lagi coba membantu beberapa kelurahan untuk penerapan Open SID.Terima Kasih.
![nip sekdes](https://cloud.githubusercontent.com/assets/21340215/23010059/70248b7c-f454-11e6-92f9-564066a84743.jpg)

**Comment by MUHAMMADRANGSEL** [comment]
Kalau rarang selatan sdh ok sprti itu utk NIP otomatis dicetak maupun exportnya

**Comment by prihantosimbah** [comment]
Bisa saja hal ini di lakukan..

**Comment by eddieridwan** [comment]
Sdh dicommit ke master. 

Untuk melihat penggunaannya di form, buat surat baru dan lihat cara menambahkan blok pilihan pamong di form surat baru itu.

Di template .rtf, kode isian untuk menampilkan NIP pamong adalah [pamong_nip].

**Comment by metalab25** [comment]
NIP tidak muncul apabila surat di eksekusi dengan mode cetak
