### ISSUE TITLE
Kode jawaban pada tabel analis_parameter

### ISSUE THREAD

**Issue by metalab25** [eddieridwan/OpenSID#297]
Selamat siang.

Langsung aja deh. untuk kode_jawaban pada analis_parameter belum tersedia sedangkan pada saat pembuatan Analis Parameter terdapat input/post ke kode_jawaban jadi mohon untuk ditambahkan kolom tersebut.

Kalo saya pribadi sih sudah menambahkan namun untuk pengguna lain yang mengerti akan kesulitan.
Terimakasih.

Salam
Happy

![analis_parameter](https://cloud.githubusercontent.com/assets/19917739/23007644/add32f92-f444-11e6-9727-eb7e23204283.png)
![kode_jawaban](https://cloud.githubusercontent.com/assets/19917739/23007647/b4cca904-f444-11e6-8b0b-47ab56d548dc.png)

**Comment by metalab25** [comment]
Sepertinya duplicate issue ini silahkan di merger aja bung dengan yang sudah ada

**Comment by eddieridwan** [comment]
Duplikat dari #290
