### ISSUE TITLE
Menu analisis di OpenSID perlu penyesuaian dgn SID 3.10 CRI 

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#299]
Analisis OpenSID
![image](https://cloud.githubusercontent.com/assets/25834335/23049871/84bca824-f4f1-11e6-8812-4cfc40e343d6.png)
Analisis SID 3.10 CRI
![image](https://cloud.githubusercontent.com/assets/25834335/23049794/10d80822-f4f1-11e6-80bb-25e69eeb87b7.png)

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL , apa saja yang perlu disesuaikan?

**Comment by eddieridwan** [comment]
Sdh dicommit ke master.
