### ISSUE TITLE
Menu Persil OpenSID perlu penyesuaian dengan Persil SID 3.10 CRI

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#300]
Persil OpenSID
![image](https://cloud.githubusercontent.com/assets/25834335/23049927/d210a1ca-f4f1-11e6-9901-6886671f04ec.png)

Persil SID 3.10 CRI
![image](https://cloud.githubusercontent.com/assets/25834335/23049939/e360e5d4-f4f1-11e6-9642-3392e063824c.png)

OpenSID masih ada masalah di Menu Pendataan Persil tambah data (Manual) nama pemilik persil tidak tampil sedangkan di SID 3.10 CRI nama pemilik persil tampil

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
