### ISSUE TITLE
Tampilan Peta di Menu Peta error

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#301]
![image](https://cloud.githubusercontent.com/assets/25834335/23050024/64e148c4-f4f2-11e6-948d-ff59db71405c.png)

**Comment by eddieridwan** [comment]
Ini disebabkan Google API key belum terpasang, lihat https://github.com/eddieridwan/OpenSID/wiki/Memasang-Google-API-Key.

Untuk lihat fitur ini berjalan normal, lihat situs demo http://sid.bangundesa.info/index.php/gis
