### ISSUE TITLE
Pengaturan Manajemen Modul SID 3.10 CRI bisa aktif dan dinonaktifkan sedangkan OpenSID tidak

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#302]
![image](https://cloud.githubusercontent.com/assets/25834335/23050138/0e1b6e7e-f4f3-11e6-9eec-02a4fdf70ce1.png)

salah satu tujuannya supaya bisa memunculkan menu yang sudah bisa dikembangkan sedangkan yang belum bisa dinonaktifkan seperti Menu Plan masih belum bisa dikembangkan oleh Pemerintah Desa

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
