### ISSUE TITLE
Laporan Penduduk Bulanan Cetak excel

### ISSUE THREAD

**Issue by afri18** [eddieridwan/OpenSID#304]
untuk menu cetak excel di menu Statistik > Laporan bulanan masih eror kalau bisa dibuat seperti ini : 
http://cigelam.desa.id/index.php/first/artikel/198

**Comment by MUHAMMADRANGSEL** [comment]
<<<<<Issue 304 telah ditemukan Solusinya>>>>
Masalah untuk menu cetak excel di menu Statistik > Laporan bulanan masih eror/blank seperti ini :
![image](https://cloud.githubusercontent.com/assets/25834335/24302535/8e4a0aa2-10e5-11e7-9ba7-1a2b1d2bfe14.png)
Solusinya sudah bisa di temukan.
saya gunakan scrip <<<bulanan_excel>>> yang di SID 3.10 alhamdulillah sudah bisa. _cuma saya tidak tau dimana scrip yang di OpenSID ada kurang atau tidak balance shingga error._
File tersebut terletak di donjo-app/views/statistik/laporan/bulanan_excel.php. 
Hasilnya seperti ini :
![image](https://cloud.githubusercontent.com/assets/25834335/24302595/c3fda9d8-10e5-11e7-8103-db87ac87107c.png)

**Comment by eddieridwan** [comment]
@afri18 apakah yang diinginkan itu download dalam format excel atau pdf?
Kalau contoh anda di http://cigelam.desa.id/index.php/first/artikel/198, sepertinya itu laporan pdf.

**Comment by MUHAMMADRANGSEL** [comment]
Seperti yg sdh saya sampaikan mas eddie ketika kita klik cetak lapor bulan excel hasilnya blank,,, dan mgkin disamping blank yg diinginkan mas syafri formatnya seperti yg ia posting

**Comment by eddieridwan** [comment]
Mengerti, tapi apakah sebaiknya hasilnya .xls atau .pdf.

**Comment by MUHAMMADRANGSEL** [comment]
excel mas

Pada tanggal 7 Apr 2017 15:05, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
![lampid_201703](https://cloud.githubusercontent.com/assets/249563/24825978/c6bd664a-1c7f-11e7-88f5-e86d9e5f34d9.jpg)

**Comment by MUHAMMADRANGSEL** [comment]
Pas banget mas eddie

Pada tanggal 8 Apr 2017 12:21, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
Perlu ditangani:

1. Keluarga yang boleh dihapus hanya yang tidak ada kepala keluarga, karena tidak akan tercatat di laporan bulanan.
1. Kalau kepala keluarga pecah dari KK, apa yang dilaporkan di laporan bulanan keluarga? Yaitu dilaporkan di baris mana, sebagai apa?
1. log_penduduk dari bulan2 sebelumnya tidak boleh dihapus, karena sudah dilaporkan
1. Kalau penduduk hilang->hidup, mati->hidup, pindah->hidup dalam bulan sedang berjalan (misalnya karena keliru) tidak perlu penanganan khusus. Tapi bila berbeda bulan, perlu penanganan khusus supaya laporan perkembangan penduduk menunjukkan penambahan yang betul dari laporan bulan sebelumnya

**Comment by eddieridwan** [comment]
Sudah dicommit ke master. Hal2 yang masih perlu perhatian dicatat di https://github.com/eddieridwan/OpenSID/wiki/Statistik-Kependudukan, di bagian _Keterbatasan Lainnya_.

**Comment by afri18** [comment]
waduh ane lama nggak buka, terkendala koneksi, ma'af ya rekan2
sebaik nya excel, kalau yg diweb itu buat publikasi dan laporan ane print jadi pdf

**Comment by metalab25** [comment]
ternyata kasus ini masih terjadi di OpenSID versi local (offline), memang kalo versi Onlinenya tidak ada masalah dan saya sudah mencobanya sendiri.
Ini akan jadi kendala bagi desa" pengguna opensid yang belum memiliki opensid online.
@eddieridwan , mohon ditinjau kembali issue ini

**Comment by eddieridwan** [comment]
@metalab25 tidak ada masalah offline maupun online. Masalah ini sudah lama diperbaiki. Harap coba lagi dan periksa apakah telah terinstal dgn benar.

**Comment by metalab25** [comment]
saya sudah periksa berulang" bahkan berkali" install ulang sampai saya install ulang xampp tetap blank. bukan saya aja yang mengalami tapi desa kedung sigit mengalami juga. awalnya desa kedung sigit yang kasih info ke saya lalu saya coba dan yang saya dapatkan sama seperti yang desa kedung sigit alami

**Comment by metalab25** [comment]
di facebook pun saya info dan ada yang berkomentar mengalami hal yang sama

**Comment by MUHAMMADRANGSEL** [comment]
Betul sekali saya saja sampai skrg blm bisa

Pada tanggal 7 Mei 2017 17:12, "Happy" <notifications@github.com> menulis:

**Comment by metalab25** [comment]
wah ternyata masalah yang dibilang sudah terselesaikan malah banyak yang menyampaikan masih bermasalah

**Comment by MUHAMMADRANGSEL** [comment]
ya mas happy, shgg saya pakai scrip 1.12 untuk laporan bulanannya

Pada tanggal 7 Mei 2017 17:53, "Happy" <notifications@github.com> menulis:

**Comment by metalab25** [comment]
file apa yang digunakan om Rarang

**Comment by MUHAMMADRANGSEL** [comment]
Folder laporan yg ada dj donjo-app/views/laporan

Semua scripnya saya copy

Pada tanggal 7 Mei 2017 18:02, "Happy" <notifications@github.com> menulis:
