### ISSUE TITLE
Seharusnya tdk ada pilihan hubungan 'anak' bagi anggota keluarga yang kepala keluarganya belum kawin

### ISSUE THREAD

**Issue by TAHTA24** [eddieridwan/OpenSID#306]
Maaf sblmx sekedar saran sj. 
Pertama: Untuk kepala keluarga yg statusnya blm kawin seharusnya jika menambahkan anggota keluarga maka pilihan status pada comman buttonnya itu sebagai anak dihilangkan sj krn tdk mungkin status blm kawin tapi punya anak.
Yg kedua : NIK tdk boleh ganda. Krn prnah sy coba input Nik yg sama tetap tersimpan.

**Comment by eddieridwan** [comment]
NIK tdk boleh ganda sudah diterapkan di #345.

**Comment by eddieridwan** [comment]
@TAHTA24 , mungkin tidak sesederhana itu. Menurut logika itu, jika belum kawin, hubungan keluarga berikut juga tidak berlaku:
- menantu
- cucu
- mertua
- suami/istri
- kepala keluarga

Bahkan, hubungan 'kepala keluarga' tidak berlaku pada waktu menambah anggota terlepas dari status kawin, karena sudah ada kepala keluarga dan hanya boleh ada satu.

Betul?

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
