### ISSUE TITLE
Dokumen Pengesahan di Menu Analisis Gagal Upload Berkas Form Pendataan

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#308]
![image](https://cloud.githubusercontent.com/assets/25834335/23130753/3d5374e2-f7ba-11e6-8cd3-e89a650c94d3.png)

![image](https://cloud.githubusercontent.com/assets/25834335/23130778/4dd0d800-f7ba-11e6-809c-e7543f0e0ac7.png)

hasilnya Blank seperti ini
![image](https://cloud.githubusercontent.com/assets/25834335/23130799/626837e0-f7ba-11e6-8181-dfefbf60f1d3.png)

Sekedar Info Kalau di SID CRI sudah Bisa dengan Tampilan seperi dibawah ini
![image](https://cloud.githubusercontent.com/assets/25834335/23130882/b13bcbe8-f7ba-11e6-8933-b8a3278d5b81.png)

![image](https://cloud.githubusercontent.com/assets/25834335/23130912/c1fd802a-f7ba-11e6-8b6b-c45f3588e4a4.png)

hasilnya
![image](https://cloud.githubusercontent.com/assets/25834335/23130953/d94a7b52-f7ba-11e6-8cef-ff1a4752902e.png)

**Comment by eddieridwan** [comment]
Sdh dicommit ke master.
