### ISSUE TITLE
Paging di halaman web tidak akurat

### ISSUE THREAD

**Issue by batudaa** [eddieridwan/OpenSID#31]
Pindah page (termasuk next dan back) di daftar artikel untuk menu berdasarkan nama kategori, selalu pindah ke menu Beranda.

**Comment by pandigresik** [comment]
sudah dilakukan permintaan PR https://github.com/eddieridwan/OpenSID/pull/396

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
