### ISSUE TITLE
Log surat keluar bisa duplikat

### ISSUE THREAD

**Issue by cafeiklan** [eddieridwan/OpenSID#316]
![2017-02-24_072213](https://cloud.githubusercontent.com/assets/1905469/23285154/1ba1de24-fa62-11e6-855a-71bb03af22e6.png)

**Comment by eddieridwan** [comment]
@cafeiklan, sebenarnya log itu tidak duplikat, karena timestampnya (kolom tanggal) berbeda. Ini menunjukkan pengguna mencetak surat yang sama berkali-kali, mungkin setiap kali dengan melakukan perubahan pengisian data di form surat yang bersangkutan.

Yang perlu kita pertimbangkan, apakah ini sesuatu yang bermanfaat atau tidak? Apakah pengguna ingin tahu (di laman Surat Keluar) setiap kali surat ini dicetak?

Mungkin yang bisa kita gunakan sebagai patokan adalah dengan melihat apakah surat yang diunduh dari masing2 entri di Surat Keluar berbeda atau sama. 

Kalau kita lihat dari function di _surat_keluar_model.php_:

```
	function nama_surat_arsip($url,$nik,$nomor){
		// Nama surat untuk surat keterangan di mana NIK = 1234567890123456 dan
		// nomor surat = 503/V.58.IV.135/III pada tanggal 27 Juli 2016 akan seperti ini:
		// surat_ket_pengantar_1234567890123456_2016-07-27_503-V.58.IV.135-III.rtf
		$nomor_surat = str_replace("'", '', $nomor);
		$nomor_surat = preg_replace('/[^a-zA-Z0-9.	]/', '-', $nomor_surat);
		$nama_surat = $url."_".$nik."_".date("Y-m-d")."_".$nomor_surat.".rtf";
		return $nama_surat;
	}
```
kita lihat bahwa untuk surat bagi seorang pemohon (NIK), dengan jenis surat dan nomor surat yang sama, surat yang dihasilkan akan menimpa surat serupa pada tanggal yang sama. Yaitu, pada setiap hari hanya ada satu salinan surat yang disimpan di arsip.

Jadi, apabila kita ingin mengurangi entri di log_surat, mungkin kita bisa batasi hanya satu entri untuk setiap salinan surat yang tersimpan di arsip. Dengan cara ini, timestamp (kolom tanggal) yang tampil di Surat Keluar akan menunjukkan tanggal/jam terakhir surat itu dicetak, tetapi tidak menunjukkan percobaan cetak lainnya yang dilakukan.

Bagaimana kalau surat yang sama dicetak lagi pada hari berikutnya? Dalam hal ini akan ada versi lain dari surat itu yang tersimpan di arsip. Dan saya kira sebaiknya ada entri juga di log surat untuk versi surat ini.

**Comment by cafeiklan** [comment]
> sebenarnya log itu tidak duplikat, karena timestampnya (kolom tanggal) berbeda. Ini menunjukkan pengguna mencetak surat yang sama berkali-kali, mungkin setiap kali dengan melakukan perubahan pengisian data di form surat yang bersangkutan.

om @eddieridwan, yg saya maksudnya dengan patch ini , yakni log berulang adalah dengan data yg sama, coba amati fungsi yg sama buat, jadi ketika datanya sama, akan dianggap duplikat, tetapi jika tidak, maka tidak, misal nama suratnya dirubah atau keperuannya di rubah.

untk mengimbangi patch ini, timestamp pada field tanggal harusnya diganti on update curent timestamp

**Comment by eddieridwan** [comment]
Sudah dicommit ke master, dengan perubahan mengikuti komentar di atas mengenai menyesuaikan entri di log_surat dengan file surat yang tersimpan di arsip.
