### ISSUE TITLE
Perbaikan kelengkapan kepemilikan dokumen

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#321]
1. Gambar yg diupload ukurannya terbatas
2. File yg diupload muncul di menu admin web/dokumen sdgkan sid 3.10 tidak
Mohon diperbaiki sblm dirilis

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL:

1. Ukuran file yang bisa diupload tergantung setting php.ini, bukan aplikasinya. Lihat solusinya di https://github.com/eddieridwan/OpenSID/wiki/Error-Import-Excel

**Comment by eddieridwan** [comment]
Item (2) sudah dicommit ke master.
