### ISSUE TITLE
Fitur: Bisa upload berbagai jenis dokumen pada Menu Admin Web > Dokumen 

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#322]
Maslahnya tdk bisa mengupload jenis fle rar, exe sedangkan sid 3.10 ready. 
Mhn bantuannya krn saya sdh coba tp tdk bisa3

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL, pada menu yang mana dan OpenSID versi berapa? Bisa tampilkan screenshotnya?

**Comment by eddieridwan** [comment]
Maksudnya di Admin Web > Dokumen?

Apakah memang file seperti itu mau diupload ke web? Kegunaannya apa untuk urusan administrasi kantor desa?

**Comment by eddieridwan** [comment]
Format arsip seperti .zip, .rar bisa dimengerti dan bisa ditambahkan. 

Tetapi apa contoh file .exe yang ingin disimpan?

**Comment by MUHAMMADRANGSEL** [comment]
Aplikasi atau sejenisnya lah mas eddie tp yg terpenting berbentuk rar

**Comment by eddieridwan** [comment]
Ok, sudah dicommit ke master. Sekarang selain file dokumen (pdf, excel, msword dll), bisa juga upload file gambar (jpg, png, dll) dan juga file format arsip (zip, rar). Apabila perlu mengunggah file jenis lain, bisa dicompress dulu ke dalam .zip atau .rar.
