### ISSUE TITLE
Biodata Penduduk Tidak Terekam

### ISSUE THREAD

**Issue by Topohudoyo** [eddieridwan/OpenSID#325]
Sekilas info buat saya menemukan masalah ketika mempelajari untuk menggunakan opensid, yakni untuk cetak biodata Penduduk pada kolom pendidikan tidak terekam isiannya. itu terjadi baik di opensid yang off-line,  maupun online (Demo Open SID). mohon jadi perhatian temen-temen semua..salam tp.

![biodata opensid](https://cloud.githubusercontent.com/assets/25343964/23401069/f377a2f6-fdd8-11e6-860e-83eb837c458c.JPG)

**Comment by eddieridwan** [comment]
@Topohudoyo, sepertinya cetakan biodata penduduk ini perlu ditata ulang. Apakah ada data lain yang juga belum ditampilkan? Apakah datanya lebih baik dikelompokkan? Dari pada menambah satu info ini saja, lebih baik sekalian diperbaiki tuntas.

Mungkin anda dapat memulai membuat usulan tampilan cetakan biodata baru -- dan koordinasi pembahasan dengan anggota forum https://www.facebook.com/groups/OpenSID/ lainnya.

**Comment by eddieridwan** [comment]
Karena tidak ada tambahan info, tambahkan data pendidikan saja.
Untuk perbaikan lainnya, perlu membuat issue baru.

Sudah dicommit ke master.
