### ISSUE TITLE
Penambahan Nama dan alamat di Program Bantuan

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#326]
Mengingat banyaknya masyarakat yg mendapatkan berupa bantuan KIS, KIP, PKH dan lainnya identitas yg tertera di KK dgn di Kartu Bantuan Beda 100% seperti Nama, TTL, NIK Alamat shgg untuk lebih mantap dan jelasnya masyarakat yg mana yg mendapatkan program perlu ditambahkan Nama, NIK, Alamat seeuwi dgn di Kartu yg didapatkan kalau untuk ID kartu sdh ok banget

**Comment by MUHAMMADRANGSEL** [comment]
Alasannya kenapa ini penting penambahan Kolom seperti Nama, NIK, tempat tgl lahir, alamat krn Identitas di Kartu Keluarga dan di Kartu Bantuan yg diterima 99% beda

**Comment by MUHAMMADRANGSEL** [comment]
Ini perlu segera di ditambahkan mas eddie dan kawan2 programer

**Comment by eddieridwan** [comment]
Untuk program bantuan sasaran penduduk (perorangan) atau juga sasaran lainnya (keluarga, rumah tangga, kelompok)?

**Comment by MUHAMMADRANGSEL** [comment]
Yang kebanyakan perorangan mas Seperti Kartu Indonesia Sehat, Kartu Indonesia Pintar, dan untuk keluarga juga mas eddie sprt Kartu Keluarga Sejahtera. Dua2 nya mas eddie

**Comment by eddieridwan** [comment]
Untuk sasaran Keluarga, data ID siapa yang direkam? Data Kepala Keluarga?

**Comment by MUHAMMADRANGSEL** [comment]
Kepala keluarga bersama anggotanya sprt kartu KKS

**Comment by MUHAMMADRANGSEL** [comment]
Mengingat kami sedang ada pendataan terkait dgn masyarakat yg mendapatkan bantuan2, mas eddie untuk issue ini kami mohon di buatkan shgg bisa kami manfaatkan maksimal krn 99% beda nama dan lqinnya dgn di kartu keluarga

**Comment by MUHAMMADRANGSEL** [comment]
Penambahan kolom diantaranya 1. Kolom Nama sesuai kartu 2. Tempat ttl lahir sesuai kartu 3. NIK sesuai kartu 4. Alamat sesuai dgn kartu

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL bagaimana, apakah panduan Analisis sudah dibuat?

**Comment by MUHAMMADRANGSEL** [comment]
tggl saya masukkan ke github mas, namun jauh dr kurang mhn dilengkapi nanti

Pada tanggal 15 Apr 2017 20:41, "Eddie Ridwan" <notifications@github.com>
menulis:

@MUHAMMADRANGSEL <https://github.com/MUHAMMADRANGSEL> bagaimana, apakah
panduan Analisis sudah dibuat?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/eddieridwan/OpenSID/issues/326#issuecomment-294294114>,
or mute the thread

**Comment by MUHAMMADRANGSEL** [comment]
Panduan analisisnya sdh dibuat mas. Bisa dicek

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL , sdh dicommit ke master. Silakan ujicoba di versi pra-rilis. Jangan lupa Migrasi DB.

**Comment by MUHAMMADRANGSEL** [comment]
Ok siap mas eddie

**Comment by dadannurman** [comment]
Mohon maaf mas @eddieridwan setelah saya lakukan perubahan sesuai petunjuk,
saya coba input "Identitas di Kartu Peserta"

![capture123](https://cloud.githubusercontent.com/assets/28327817/26041591/2dbd4d20-3958-11e7-90d4-ccfb61df39aa.PNG)

setelah klik simpan muncul eror

![capture1234](https://cloud.githubusercontent.com/assets/28327817/26041606/41cb30a2-3958-11e7-94f0-8b611afdca42.PNG)

Mohon solusinya master

**Comment by MUHAMMADRANGSEL** [comment]
Silqhkan pakai yg asli OpenSID bukan Tampilan website hqdakewa, saya bisa

Pada tanggal 15 Mei 2017 10:21, "DadanNurman" <notifications@github.com>
menulis:

**Comment by dadannurman** [comment]
Terimakasih banyak agan @MUHAMMADRANGSEL

**Comment by eddieridwan** [comment]
Issue ini sdh ditutup. Jika bertanya, sebaiknya di Forum FB.
