### ISSUE TITLE
Cetak dan Export ke Excel

### ISSUE THREAD

**Issue by batudaa** [eddieridwan/OpenSID#33]
Cetak dan Export ke Excel di data Penduduk Gagal. Cetak memberikan halaman kosong dan untuk excel memberikan pesan 'File not found'.

**Comment by eddieridwan** [comment]
@batudaa , kami coba di OpenSID v0.7, dan kedua fungsi cetak dan export ke Excel di data Penduduk berjalan normal. Apakah issue ini bisa ditutup?

**Comment by eddieridwan** [comment]
Anggap issue ini sudah tidak bermasalah lagi.
