### ISSUE TITLE
PENDUDUK PENDATANG DAN PENDUDUK TIDAK TETAP TIDAK TAMPIL DI FROM SURAT

### ISSUE THREAD

**Issue by CIJERUK** [eddieridwan/OpenSID#330]
penduduk pendatang dan penduduk tidak tetap tidak tampil nik/namanya di from surat....
di from surat hanya bisa keluar NIK/NAMAnya untuk penduduk Tetap saja...

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
