### ISSUE TITLE
OpenSID bisa berjalan dengan baik di WebServer OpenLiteSpeed Linux

### ISSUE THREAD

**Issue by lynggo** [eddieridwan/OpenSID#332]
Alhamdulillah bisa jalan juga di webserver kenceng OpenLiteSpeed

Cara install OpenLiteSpeed di Linux

http://open.litespeedtech.com/mediawiki/index.php/Help:Installation

**Comment by lynggo** [comment]
Untuk rewrite rule nya :

RewriteCond $1  ^(index\.php|resources|robots\.txt) 
RewriteCond %{REQUEST_FILENAME} !-f 
RewriteCond %{REQUEST_FILENAME} !-d 
RewriteRule ^(.*)$ index.php/$1 [L,QSA]

Supaya bisa SEO

**Comment by batudaa** [comment]
Kalau jalan dengan baik mestinya tidak masuk issue. Kalau ada masalah menyangkut fitur aplikasi barulah masuk issue.

Untuk hal seperti ini mungkin bisa dikemas dalam bentuk panduan dan kirim ke wikinya [OpenSID](https://github.com/eddieridwan/OpenSID/wiki).

**Comment by eddieridwan** [comment]
@lynggo , seperti dijelaskan oleh @batudaa , silakan buat panduannya. Lihat di laman https://github.com/eddieridwan/OpenSID/wiki/Panduan-Install-OpenSID, di _Daftar Bacaan_, di situ ada tautan ke panduan install server bukan XAMPP. Mungkin panduan anda juga bisa ditambahkan di situ.

Silakan bahas langsung di forum FB https://www.facebook.com/groups/OpenSID/, yang lebih cocok untuk diskusi ini.
