### ISSUE TITLE
BUG: Kartu rtm error

### ISSUE THREAD

**Issue by cafeiklan** [eddieridwan/OpenSID#334]
![image](https://cloud.githubusercontent.com/assets/1905469/23585037/504e3b78-01a5-11e7-9d25-c196f336e06a.png)

![image](https://cloud.githubusercontent.com/assets/1905469/23585042/5a36d0b4-01a5-11e7-9e18-53e59d991145.png)

Tombol kartu rtm > erro

![image](https://cloud.githubusercontent.com/assets/1905469/23585028/20d6f0ce-01a5-11e7-94d1-5ef2f1424db5.png)

**Comment by eddieridwan** [comment]
Sudah dilaporkan sebelumnya di #258.
