### ISSUE TITLE
Error saat pilih dokumen lampiran (Cetak Surat)

### ISSUE THREAD

**Issue by metalab25** [eddieridwan/OpenSID#335]
Saya coba membuat membuat Surat Keterangan Usaha (hanya sebatas coba") namun pada saat pilih dokumen pada daftar dokumen halaman menjadi error

![2017-03-05](https://cloud.githubusercontent.com/assets/19917739/23586532/05758a66-01d2-11e7-8864-50d705eaa2ee.png)
![2017-03-05 1](https://cloud.githubusercontent.com/assets/19917739/23586554/7d62587e-01d2-11e7-8384-335199b7b5f0.png)
![2017-03-05 2](https://cloud.githubusercontent.com/assets/19917739/23586585/21e8c054-01d3-11e7-9bd2-2e8409342a98.png)
![2017-03-05 3](https://cloud.githubusercontent.com/assets/19917739/23586595/48aed9ee-01d3-11e7-86d6-41fdc9e47020.png)
![2017-03-05 4](https://cloud.githubusercontent.com/assets/19917739/23586601/6023ee84-01d3-11e7-8f36-9a622066d791.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
