### ISSUE TITLE
eror

### ISSUE THREAD

**Issue by TAHTA24** [eddieridwan/OpenSID#344]
Eror jika plih menu penduduk-rumah tangga trus pilih berdasarkan dusun.

**Comment by eddieridwan** [comment]
Ini sudah dilaporkan sebelumnya, https://github.com/eddieridwan/OpenSID/issues/280 dan sudah dikerjakan.

Biasakan memeriksa issue sebelum melaporkan yang baru, menjaga-jaga tidak duplikat.
