### ISSUE TITLE
Penambahan tgl & nama kepala desa pd laporan bulanan

### ISSUE THREAD

**Issue by TAHTA24** [eddieridwan/OpenSID#348]
Perlu ditambahkan tgl & nama kepala desa (perangkat desa) pada laporan kependudukan bulanan krn didesa sy stiap bulan membuat laporan tersebut tetapi permintaan dr pihak kecamatan harus ada yg bertanda tangan dbawah apakah kepala desa ataukah perangkat desa.
![screenshot_20170317-232723](https://cloud.githubusercontent.com/assets/22760871/24050503/f628cc48-0b69-11e7-9a70-3e40b2852aa9.png)

**Comment by TAHTA24** [comment]
Penting

**Comment by eddieridwan** [comment]
@TAHTA24 , untuk membantu programmer, harap sediakan konsep tulisan/letak tanggal/nama perangkat desa (lampirkan gambar laporan).

Apakah selalu kepala desa, atau apakah pengguna bisa memilih perangkat desa mana yang menandatangani?

**Comment by eddieridwan** [comment]
Saat ini penampilan laporan di laman Statistik > Laporan Kependudukan Bulanan (ada kolom Keluarga) berbeda dengan hasil cetak Statistik > Laporan Kependudukan Bulanan > Cetak (tidak ada kolom Keluarga).

Apakah perlu (sebaiknya) disamakan? Judul kolom mana yang akan dipakai (tampilan layar atau tampilan cetak)?

**Comment by TAHTA24** [comment]
Mas eddie ridwan sy blm tw menambahkan gambar dsini

**Comment by TAHTA24** [comment]
Klw bisa samakan sj antara tampilan cetak dgn tampilan layar spy lbh konsisten.klw bs tampilkan jg per dusun. Dan yg tanda tangan kepala desa bisa jg diganti" perangkat desa yg lain..

**Comment by TAHTA24** [comment]
Klw didesaku mas eddie sy ketik ulang di excel kemudian sy liat jumlahx sj. Krn klw mw dcetak langsung tdk bs terlalu lebar jg tdk dimuat dikertas ukuran F4.

**Comment by YokaYunanda** [comment]
Bisa tolong diupload contoh data dokumenya bpk? Supaya kita tau attribut apa saja yang diperlukan

**Comment by TAHTA24** [comment]
Mas yoka yunanda sy blm tw cara upload file/gambar di issue. Gmn carax mas?

**Comment by YokaYunanda** [comment]
Caranya sedikit ribet:
1. buka http://imgur.com/upload
2. upload gambarnya disana
3. paste kan url gambarnya di comment git hub sini

**Comment by eddieridwan** [comment]
@tahta24, @yokayunanda: untuk unggah file (termasuk gambar) ke issue mudah saja.

![upload-file-di-issue](https://cloud.githubusercontent.com/assets/249563/24045484/a29e4e88-0b62-11e7-81d3-415a3aea944f.jpg)

**Comment by TAHTA24** [comment]
![laporan bulanan](https://cloud.githubusercontent.com/assets/22760871/24049457/0b8e4e8a-0b67-11e7-8d51-28770f1836bf.png)
Kaya gini laporan bulanan didesa saya mas.

**Comment by eddieridwan** [comment]
@TAHTA24, sudah dicommit ke master. Silakan unduh versi pra-rilis dari https://github.com/eddieridwan/OpenSID dan ujicoba. Beritahu apabila ada yang perlu diperbaiki.

**Comment by TAHTA24** [comment]
Gmn yah cara uji cobax mas eddie?

**Comment by eddieridwan** [comment]
@TAHTA24, Lihat panduan https://github.com/eddieridwan/OpenSID/wiki/Unduh-script-OpenSID, bagian _Unduh versi pra-rilis_.

**Comment by TAHTA24** [comment]
Sdh mantap mas eddie tp klw bs di laporan kelompok rentan jg dtambahkan. Untuk mengantisipasi sj kedepannya syp tw aja ada permintaan lg dr bpk camat disini setelah sy perkenalkan openSID kepadanya.

**Comment by eddieridwan** [comment]
Untuk kelompok rentan, silakan buat issue baru. Issue ini sekarang akan ditutup.

Selamat sukses menyebarluaskan OpenSID.
