### ISSUE TITLE
penambahan kolom import excel data penduduk

### ISSUE THREAD

**Issue by widodoari** [eddieridwan/OpenSID#349]
Penambahan kolom data (akta lahir, No. Paspor, akta nikah dan tanggal, akta cerai dan tanggal)  pada (FormatImportExcel.xls) 
![issue](https://cloud.githubusercontent.com/assets/13248793/23887161/a87c5550-08b2-11e7-80da-2ee20932bfcd.jpg)

**Comment by metalab25** [comment]
wah issue bagus nih

**Comment by prihantosimbah** [comment]
![image](https://cloud.githubusercontent.com/assets/22185813/24025992/aae8aa74-0af0-11e7-88ca-f34fdad99190.png)

butuh masukan untuk kesepakatan...

**Comment by Topohudoyo** [comment]
Bisa tuh di di penuhi tapi tidak semua harus harus di masukan dalam format import excel karena bukan data statis biarlah pengisiannya sebagai bagian dari kegiatan mutasi kependudukan desa.

**Comment by MUHAMMADRANGSEL** [comment]
Mantap kalau itu bisa dilakukan maka akan mempermudah operator dan pemerintah desa untuk mempercepat proses memasukkan data kedalam aplikasi. OpenSID memang luar biasa

**Comment by MUHAMMADRANGSEL** [comment]
setelah saya otak atik alhamdulillah sekarang sudah bisa import semua data sesuai dengan form penduduk isian  terdiri dari akta lahir, No. Paspor, akta nikah dan tanggal, akta cerai dan tanggal dan yang lainnya
[Menambahkan Data Import.zip](https://github.com/eddieridwan/OpenSID/files/1236818/Menambahkan.Data.Import.zip)

**Comment by MUHAMMADRANGSEL** [comment]
Mohon dikoreksi dan disesuaikan lagi mas eddie

**Comment by MUHAMMADRANGSEL** [comment]
mudah2an mas widodoari bisa terbantukan dn segera di masukkan di comit

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
