### ISSUE TITLE
Bug: Logo tidak tampil di hosting online apabila nama filenya mengandung spasi

### ISSUE THREAD

**Issue by eddieridwan** [eddieridwan/OpenSID#350]
Di hosting, apabila mengunggah logo dengan nama file seperti 'logo kab kp.PNG', yang berisi spasi, logo tersebut tidak tampil. File logonya berhasil diunggah ke folder desa/logo, tetapi tidak bisa ditemukan oleh aplikasinya.

Masalah ini dilaporkan oleh pengguna Facebook Topo Hudoyo.

**Comment by cafeiklan** [comment]
sepertinya lebih bagus nama file logo diganti menjadi logo.ext saja om @eddieridwan

**Comment by eddieridwan** [comment]
@cafeiklan, nama file tersimpan sebaiknya tetap seperti aslinya, supaya pengguna tahu asal file logo tersebut. Hanya mungkin spasi di nama file diganti dengan karakter netral, seperti '-'. 

Bagaimana, anda bisa terapkan?

**Comment by cafeiklan** [comment]
Sudah om @eddieridwan

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
