### ISSUE TITLE
Batasi tampilan artikel utama menjadi satu paragraf, dengan tautan untuk melihat selengkapnya

### ISSUE THREAD

**Issue by afri18** [eddieridwan/OpenSID#354]
untuk artikel yang diklik menjadi headline (artikel utama) sebaiknya dibatasi tampilannya (default) satu paragraf, selanjutnya beri keterangan baca selengkapnya seperti artikel yg tidak headline, jadi artikel utama akan tampil utuh bila diklik judul atau selengkapnya.
Tujuan agar tampilan web stabil (panjangnya sama) tidak terpengaruh bila artikel headline (utama) panjang atau pendek.

**Comment by eddieridwan** [comment]
Sediakan `function potong_teks($teks, $panjang)` untuk memotong teks sesuai kebutuhan.
Tampilkan artikel utama dengan panjang 700 karakter.
Karena view _partials/content.php_ persis sama pada tema _default_ dan _hadakewa_, sekarang tema _hadakewa_ cukup menggunakan _default/partials/content.php_ dan tidak menduplikasi berkas ini.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
