### ISSUE TITLE
Tampilan Hasil Analisis di menu font end tidak tampil

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#355]
Pendataan di Menu analisis SID 3.10
![image](https://cloud.githubusercontent.com/assets/25834335/24069661/de48b400-0bdf-11e7-9f7c-0501537b50e0.png)

Hasil Pendataan 
![image](https://cloud.githubusercontent.com/assets/25834335/24069659/bcb5155e-0bdf-11e7-91f1-88af6417db23.png)

![image](https://cloud.githubusercontent.com/assets/25834335/24069665/fcf084d2-0bdf-11e7-90a6-2864da653b26.png)

sedangkan di OpenSID
![image](https://cloud.githubusercontent.com/assets/25834335/24069674/13511df4-0be0-11e7-8daa-5df8c6124f7d.png)

Hasil Pendataan
![image](https://cloud.githubusercontent.com/assets/25834335/24069683/3e542dc0-0be0-11e7-988a-127d518ff328.png)

yang muncul
![image](https://cloud.githubusercontent.com/assets/25834335/24069690/5d14e510-0be0-11e7-99dc-8b915ee27d52.png)

Mohon bantuan temen2 programer spy Fasilitas yang ada di SID 3.10 CRI semua lengkap di OpenSID

**Comment by MUHAMMADRANGSEL** [comment]
Panduan Menua Analisis


[Menu Analisis.docx](https://github.com/eddieridwan/OpenSID/files/853945/Menu.Analisis.docx)

**Comment by MUHAMMADRANGSEL** [comment]
[Uploading 2015-01-Panduan-Penggunaan-Aplikasi-SID-3.04_v1.pdf…]()

**Comment by eddieridwan** [comment]
Bung @MUHAMMADRANGSEL, tidak perlu takut, langsung saja masukkan me panduan. Kalau bisa buat issue, pasti bisa panduan. Tanya saja kalau terbentur masalah. Tapi coba dulu, ya. Trims.

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL saya coba unduh file _Menu Analisis.docx_ anda, tetapi selalu tidak berhasil (error -Forbidden). Tolong anda unggah ulang, mungkin coba menggunakan versi .doc?

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL , bisa kirim contoh data analisis untuk dicoba?

**Comment by MUHAMMADRANGSEL** [comment]
yg saya pakai ppls2 yg berbentuk excel itu yg jadi pertanyaannya mas

Pada tanggal 7 Apr 2017 06:20, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
Saya impor ppls2.xls yang tersedia di sid3.10, tapi di sid3.10 tampil halaman kosong. Apakah anda isi data tambahan?

![analisis-sid3 10](https://cloud.githubusercontent.com/assets/249563/24779366/085dd0aa-1b84-11e7-9196-955d7916d47f.jpg)

**Comment by MUHAMMADRANGSEL** [comment]
Itu yg saya pakai mas eddie

Pada tanggal 7 Apr 2017 07:02, "MUHAMMAD SPD" <muhammadrangsel@gmail.com>
menulis:

**Comment by MUHAMMADRANGSEL** [comment]
SUdah mas isi semua pertanyaan per keluarga/penduduk di input data

Pada tanggal 7 Apr 2017 07:28, "MUHAMMAD SPD" <muhammadrangsel@gmail.com>
menulis:

**Comment by MUHAMMADRANGSEL** [comment]
Saya hanya isi item pertanyaanya mas dan tampilkan agregasi data hanya itu
mas

Pada tanggal 7 Apr 2017 07:29, "MUHAMMAD SPD" <muhammadrangsel@gmail.com>
menulis:

SUdah mas isi semua pertanyaan per keluarga/penduduk di input data

Pada tanggal 7 Apr 2017 07:28, "MUHAMMAD SPD" <muhammadrangsel@gmail.com>
menulis:

**Comment by eddieridwan** [comment]
Ok, sudah ketemu. Masing2 indikator yg akan ditampilkan harus dibuat 'publik', baru bisa tampil di modul web.

**Comment by eddieridwan** [comment]
Karena itulah perlu panduan. Modul Analisis sukar digunakan tanpa mengerti apa/mengapa/ bagaimana.... bukan hanya sekadar klik saja...

**Comment by MUHAMMADRANGSEL** [comment]
siap mas eddie saya akan berusaha maksimal untuk buatkan panduaanya sebisa
saya mas yg penting tampilan analisisnya bisa tampil dulu

Pada tanggal 7 Apr 2017 07:37, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by MUHAMMADRANGSEL** [comment]
dan kebetulann kami sdh pelatihqn carq membuat analisis mas eddie jd udah
ada ilmu sdkit

Pada tanggal 7 Apr 2017 07:41, "MUHAMMAD SPD" <muhammadrangsel@gmail.com>
menulis:

**Comment by eddieridwan** [comment]
Sdh dicommit ke master.
