### ISSUE TITLE
Perubahan penampilan view dan cetak Keluarga dan Penduduk

### ISSUE THREAD

**Issue by eddieridwan** [eddieridwan/OpenSID#356]
Usulan @MUHAMMADRANGSEL .

**Comment by eddieridwan** [comment]
[Perubahan Tampilan Cetak dan Viewnya view-sid-kependudukan.zip](https://github.com/eddieridwan/OpenSID/files/853025/Perubahan.Tampilan.Cetak.dan.Viewnya.view-sid-kependudukan.zip)

**Comment by MUHAMMADRANGSEL** [comment]
Perubahan Scrip tersebut sengaja saya rubah sesuai dengan keperluan di Pemerintah Desa Rarang Selatan 
Adapun Scrip yang sudah saya rubah ada 7 Scrip seperti gambar di bawah ini
![image](https://cloud.githubusercontent.com/assets/25834335/24079410/f92ea952-0cb9-11e7-8ce1-4fb4b668b7a2.png)

1. ajax_edit_nokk Perubahannya seperti gambar dibawah ini
    ![image](https://cloud.githubusercontent.com/assets/25834335/24079426/5303e546-0cba-11e7-9c3d-63cf92c70155.png)

2. kartu_keluarga hasil perubahannya
![image](https://cloud.githubusercontent.com/assets/25834335/24079460/220c187c-0cbb-11e7-876a-2c20ae4e87df.png)

3. cetak_kk hasil perubahannya
![image](https://cloud.githubusercontent.com/assets/25834335/24079469/5cb34018-0cbb-11e7-8c25-8b096ad92893.png)

4. keluarga
![image](https://cloud.githubusercontent.com/assets/25834335/24079473/80a0e070-0cbb-11e7-9df6-dc98e7fc5e9e.png)

5. keluarga_print
![image](https://cloud.githubusercontent.com/assets/25834335/24079480/99b0f866-0cbb-11e7-874c-105d74548adc.png)

6. penduduk
![image](https://cloud.githubusercontent.com/assets/25834335/24079485/a8470ab4-0cbb-11e7-8d48-113db4128305.png)

7. penduduk_print
![image](https://cloud.githubusercontent.com/assets/25834335/24079488/bb010114-0cbb-11e7-9eed-f6eef991c826.png)

Catatan : Teman2 bisa membandingkannya sebelum perubahan spy kelihatan perubahan dari sebelum perubahannya. mungkin untuk menjelaskan lebih rinci saya tidak bisa

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL di penduduk_print saya ganti urutan RT/RW/Dusun menjadi RW/RT/Dusun supaya konsisten dengan tampilan layar Penduduk dan view/cetak Keluarga.

**Comment by MUHAMMADRANGSEL** [comment]
Lebih baik dirubah di viewnya mas eddie

Pada tanggal 19 Mar 2017 07:38, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by afri18** [comment]
kalau menurut saya nggak pas kalau dusun dibelakang rw dan rt , karna secara wilayah dusun terdiri dari rw, rw terdiri dari rt, itu yg umum, memang ada beberapa desa nggak make rw atau sebaliknya, dan ada juga yg nggak make rt atau rw.
kalau menurut saya jangan dirubah, kalau dirubah, baca tentang wilayah desa, desa terdiri dari dusun>rw>rt>keluarga/rumah tangga>indifidu

**Comment by eddieridwan** [comment]
Di BIP 2012/2016, urutannya Dusun, RT/RW.

**Comment by afri18** [comment]
![image](https://cloud.githubusercontent.com/assets/6611881/24081352/9f06e914-0ce4-11e7-9783-1df4f2dcfcac.png)
ini alasan saya suka format ini
untuk penduduk kita langsung tahu/lihat data inti > nik,nama,nokk,sex,umur,alamat [dusun,rt,rw] 
untuk keluarga sama langsung data inti, jadi data inti tetap terkontrol
kalau mau tau yg lain baru klik untuk edit atau lihat doang

**Comment by prihantosimbah** [comment]
Di beberapa tempat ada format Dusun, RT, RW seperti di tempat kami..

**Comment by Agus-Heriyanto** [comment]
Menurut Saya untuk urutan  itu ditetapkan saja dari Dsun dulu baru RT/RW.Untuk kelengkapan data penduduk dan keluarga yang di print out atau disimpan dalam bentuk soft file dengan menyertakan lebih banyak data...bagi Saya bagus juga karena lebih banyak merangkum data identitas pendudk dan keuarga meski mau ditampilakan atau tidak ga masalah tapi waktu print out semua datanya tersedia.Langkah  ini juga bisa membantu jika ada pihak yang berkeptingan terhadap data tersebut maka akan lebih lengkap bisa diperoleh.
Untuk golongan darah sebaiknya tidak dihilangkan karena itu sangat membantu desa dalam mengidentifikasi gol darah warganya jika sewaktu2 membutuhkan darah....

**Comment by MUHAMMADRANGSEL** [comment]
Gol. Darah tdk dihapus dan ketika ada instansi yg meminta data spy data yg tercantum di KK semua bisa diprint... Mas agus herianto.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
