### ISSUE TITLE
Sesuaikan tampilan kartu keluarga dengan cetak kartu keluarga

### ISSUE THREAD

**Issue by eddieridwan** [eddieridwan/OpenSID#358]
Usulan @muhammadrangsel.

2. kartu_keluarga hasil perubahannya, dengan tambahan tanda tangan Kepala Keluarga dan Kepala Desa, sesuai dengan hasil cetak Kartu Keluarga.
![image](https://cloud.githubusercontent.com/assets/25834335/24079460/220c187c-0cbb-11e7-876a-2c20ae4e87df.png)

3. cetak_kk hasil perubahannya, di mana penampilannya diperbaiki sedikit (hilangkan baris kosong)
![image](https://cloud.githubusercontent.com/assets/25834335/24079469/5cb34018-0cbb-11e7-8c25-8b096ad92893.png)

**Comment by eddieridwan** [comment]
Untuk (3) di atas, kami juga menghapus baris 'Tanggal cetak', karena tanggal cetak sudah ada di tanda tangan kepala desa.

Perubahan ini sudah dicommit ke master.

**Comment by MUHAMMADRANGSEL** [comment]
Mantap mas eddie, mas eddie memang luar biasa... Saya kepingin belajar bhasa php
