### ISSUE TITLE
Merubah Tampilan penulisan Alamat di Cetak Surat

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#359]
Tampilan Penulisan Alamat di setiap Cetak Surat spy seragam 
Contoh penulisannya sekarang : MONTONG BAGIK RT 000 RW - Dusun Dasan Bagik Desa Rarang Selatan
Sedangkan yang diinginkan seperti ini : Montong Bagik RT 001 RW - Dusun Dasan Bagik Desa Rarang Selatan

**Comment by MUHAMMADRANGSEL** [comment]
Mohon Bantuan temen2 programer, saya sdh coba otak atik tp tetep belum bisa

**Comment by afri18** [comment]
di saya dah pas
![image](https://cloud.githubusercontent.com/assets/6611881/24104518/f7284932-0db4-11e7-9f5f-6decf771ee45.png)

**Comment by MUHAMMADRANGSEL** [comment]
Yang cetak langsung mas syafri, yang itu export nya

**Comment by MUHAMMADRANGSEL** [comment]
![image](https://cloud.githubusercontent.com/assets/25834335/24127436/3895b2cc-0e07-11e7-8051-013a9303a72f.png)

Penulisan Alamatnya seharusnya sperti ini supaya kelihatan lebih rapi di surat cetak langsung : **Montong Bagik RT. 003 RW. - Dusun Dasan Bagik Desa Rarang Selatan Kecamatan Terara Kabupaten Lombok Timur**

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL, seperti dijelaskan di https://github.com/eddieridwan/OpenSID/wiki/Panduan-Mencetak-Surat, OpenSID tidak akan memperbaiki surat cetak langsung pada rilis resmi. Tidak dianjurkan desa menggunakan dua versi surat, dan juga terlalu banyak prioritas lain. 

Walaupun demikian, fitur ini tetap aktif untuk pengguna yang bersedia untuk mengoprek sendiri. Untuk kasus anda, coba lihat penggunaan fungsi PHP ini: 

`ucwords(strtolower([data-kolom-anda]));`
