### ISSUE TITLE
Di Cetak Surat Hubungan Keluarga tidak Muncul

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#360]
![image](https://cloud.githubusercontent.com/assets/25834335/24127180/5c596412-0e05-11e7-9fe7-8e2ce0093de5.png)

dan solusinya sudah bisa saya temukan 
pada baris 135 -152 belum ada *LEFT JOIN tweb_penduduk_hubungan hb ON u.kk_level = hb.id )* sehingga saya tambahkan
dan hasilnya
![image](https://cloud.githubusercontent.com/assets/25834335/24127320/33f3e2e4-0e06-11e7-8c35-cfd4e462763a.png)

**Comment by eddieridwan** [comment]
Bung @MUHAMMADRANGSEL, untuk bisa digunakan, file scriptnya perlu dimasukkan ke .zip, baru di upload ke issue. Kalau seperti di atas tidak bisa digunakan.

**Comment by MUHAMMADRANGSEL** [comment]
udah saya kirimkan lewat mesenjer, sudah saya coba tidak bisa mas eddie

**Comment by MUHAMMADRANGSEL** [comment]
tidak ada yang tidak bisa mas eddie selama kita mau dan berusaha, sebenarnya saya terinspirasi dengan mas eddie dan teman2 yang lain

**Comment by eddieridwan** [comment]
Errornya apa pada waktu coba upload file .zip?

**Comment by MUHAMMADRANGSEL** [comment]
Ya pada waktu uploadx mas eddie

**Comment by eddieridwan** [comment]
Error messagenya persisnya apa? Pakai Chrome atau Firefox? OS anda apa?

**Comment by MUHAMMADRANGSEL** [comment]
Pakai chrome

**Comment by eddieridwan** [comment]
Coba pakai IE. Lampirkan screenshot kalau ada error. Windows 7, 8 atau 10?

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL jangan mau kalah... coba upload .zip menggunakan browser IE (Internet Explorer). Kami tunggu hasilnya.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
