### ISSUE TITLE
galeri foto

### ISSUE THREAD

**Issue by afri18** [eddieridwan/OpenSID#361]
aneh rasanya bila album galeri foto lebih dari 10 tapi yg muncul cuma 6 album mohon dirubah tampilannya tidak terbatas seperti arsip artikel, karna pernah diprotes album yg saya upload tidak muncul, sementara saya rubah tampilan jadi 18 
![image](https://cloud.githubusercontent.com/assets/6611881/24212305/89409e70-0f61-11e7-8fde-1d7837c4570f.png)

**Comment by eddieridwan** [comment]
@cafeiklan @batudaa @Erkajp : sudah lama tidak ada kabar dari teman2. Mudah2an sudah tidak terlalu sibuk, dan dapat kembali meluangkan waktu untuk kontribusi pada OpenSID.

Apakah ada yang sempat mengerjakan issue ini?

**Comment by afri18** [comment]
saya lom brani rubah, takut salah nanti malah berantakan, kalau di local nekad wae

**Comment by eddieridwan** [comment]
Sudah ditambahkan paging oleh @batudaa.
Sudah dicommit ke master.
