### ISSUE TITLE
masih galeri

### ISSUE THREAD

**Issue by afri18** [eddieridwan/OpenSID#362]
kalau bisa gambar yang tampil di widget galeri hanya gambar judul album saja
![image](https://cloud.githubusercontent.com/assets/6611881/24212469/07f85bf4-0f62-11e7-9828-fc5692374265.png)

**Comment by eddieridwan** [comment]
Sudah diterapkan @batudaa .
Sudah dicommit ke master

**Comment by afri18** [comment]
usahakan yg tampil hanya gambar judul album saja

**Comment by eddieridwan** [comment]
@afri18 Ya sudah. Sekarang @batudaa telah menerapkan membatasi 4 judul album maks, dipilih secara acak.
Sudah di master.
