### ISSUE TITLE
surat pengantar nikah

### ISSUE THREAD

**Issue by afri18** [eddieridwan/OpenSID#365]
ini format kua yg saya pake
nantinya bung @eddieridwan  tolong di revisi bila calon mempelai wanita dengan pria dalam satu desa, saya nggak bisa/ngarti edit surat_model nya
![n1_n7](https://cloud.githubusercontent.com/assets/6611881/24342969/3b47dcd4-12ee-11e7-8ec4-dafde1ccc227.png)
zip nggak masuk padah sudah make IE

**Comment by samsulmaarif** [comment]
@afri18 yang dimaksud zip gak masuk itu gak bisa upload di sini? mungkin file-nya bisa diupload ke google drive, lalu dikasih link ke sini... 

gambar itu gak kebaca tulisannya....

**Comment by MUHAMMADRANGSEL** [comment]
Saya jg sudah memakai itu dan skrg sedang saya gabung N-1, N-2 dan N-4 menjadi satu sekali isi tiga file ini langsung dprint bersamaan.

**Comment by MUHAMMADRANGSEL** [comment]
Mas eddie mohon pencerahwn untuk mengganti / menjadi , di tampilan print export semua surat seperti : Dasan Bunut/12 Juni 1998 menjadi Dasan Bunut, 12 Juni 1998..

**Comment by MUHAMMADRANGSEL** [comment]
Alhamdulillah N1,N2 dan N4 sdh bisa digabung jadi sAtu

**Comment by afri18** [comment]
ini pernah saya upload bisa di gabung

**Comment by prihantosimbah** [comment]
bisa dishare filenya bung safri, bung muhammad? saya pikir akan sangat berguna bagi desa-desa yg lain..

**Comment by afri18** [comment]
sudah ada di bung eddie

**Comment by eddieridwan** [comment]
[perbaikan-atau-penmbahan-surat-N1-_N7-dan-numpang-nikah.zip](https://github.com/eddieridwan/OpenSID/files/921714/perbaikan-atau-penmbahan-surat-N1-_N7-dan-numpang-nikah.zip)

![lima-surat-sekaligus](https://cloud.githubusercontent.com/assets/249563/25037691/ecd96690-213d-11e7-9ece-274e07e2fb4f.png)

![n1-n7](https://cloud.githubusercontent.com/assets/249563/25037692/ecef0306-213d-11e7-9072-fb8af8f715bd.png)

**Comment by eddieridwan** [comment]
surat_ket_nikah telah dicommit ke master. Form ini menghasilkan semua surat N-1 s/d N-7 sekaligus untuk calon pasangan pria dan wanita.

![surat nikah - daftar surat](https://cloud.githubusercontent.com/assets/249563/26273105/166bd61a-3d6c-11e7-9b1d-dccdca43b6aa.jpg)

**Comment by eddieridwan** [comment]
Eko Exsa menemukan acuan ini yang mungkin bisa lebih memperjelas aturan surat nikah:

http://wz-thf.blogspot.co.id/2014/10/prosedur-tata-cara-mengurus-surat-nikah.html

**Comment by eddieridwan** [comment]
Blanko N-1 s/d N-7, Lampiran KMA No.298 Tahun 2003:

[Surat nikah N1-N6.pdf](https://github.com/eddieridwan/OpenSID/files/612318/Surat.nikah.N1-N6.pdf)

**Comment by afri18** [comment]
https://drive.google.com/file/d/0B86LdSFWCXwObk1QZzNOR2hDQUk/view?usp=sharing

**Comment by eddieridwan** [comment]
@afri18 sudah diterapkan di master. Tinggal digunakan dan jika ada yg perlu diperbaiki, ya seperti biasa buat issue baru.
