### ISSUE TITLE
Sediakan kode isian tambahan untuk surat export doc dari data konfigurasi desa

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#369]
Butuh Penyesuaian **DATA DARI KONFIGURASI DESA** setelah adanya penambahan email desa, website desa, telpon desa dan nip kepala desa di surat_model.php untuk memunculkan alamat lengkap desa di Export Surat.

**Comment by MUHAMMADRANGSEL** [comment]
![tangkapan layar 2017-04-02 20 16 25](https://cloud.githubusercontent.com/assets/25834335/24587486/dca1e30c-17e1-11e7-99bb-f9887bd10b75.png)

**Comment by eddieridwan** [comment]
Sediakan kode isian berikut:

[nama_kepala_desa]
[nip_kepala_desa]
[email_desa]
[telepon_desa]
[website_desa]

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
