### ISSUE TITLE
Hapus file yang tidak digunakan

### ISSUE THREAD

**Issue by eddieridwan** [eddieridwan/OpenSID#370]
Beberapa file yang sepertinya tidak digunakan lagi:

1. donjo-app/views/partials/admin.tpl.php
1. donjo-app/controllers/laporan_perubahan.php
1. donjo-app/views/laporan/perubahan_print.php
1. donjo-app/views/laporan/perubahan.php
1. donjo-app/views/statistik/laporan/perubahan.php
1. donjo-app/views/statistik/laporan/perubahan_print.php
1. donjo-app/views/partials/artikel-x.php
 
Cek dulu apakah sekarang digunakan di SID 3.10. Jika tidak, hapus saja.

**Comment by MUHAMMADRANGSEL** [comment]
Di SID 3.10 ttep pakai

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL , masih ada tidak selalu berarti digunakan. Apakah ada tampilan layar/menu yang mengakses script tersebut? Semua script di atas tidak bisa diakses dari menu yang ada.

**Comment by eddieridwan** [comment]
Cek di SID 3.10

1. donjo-app/views/partials/admin.tpl.php (tidak dipakai)
1. donjo-app/controllers/laporan_perubahan.php (tidak diakses dari tampilan atau menu)
1. donjo-app/views/laporan/perubahan_print.php (tidak dipakai)
1. donjo-app/views/laporan/perubahan.php (tidak diakses dari tampilan atau menu)
1. donjo-app/views/statistik/laporan/perubahan.php (tidak dipakai)
1. donjo-app/views/statistik/laporan/perubahan_print.php (tidak dipakai)
1. donjo-app/views/partials/artikel-x.php (tidak dipakai)

Akan dihapus, karena juga tidak dipakai di SID 3.10.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
