### ISSUE TITLE
erorr waktu tambah anggota keluarga

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#372]
erorr waktu tambah anggota keluarga melalui menu keluarga
![image](https://cloud.githubusercontent.com/assets/25834335/24642284/8d65cf6a-1930-11e7-8b51-0b23e453cac1.png)

![image](https://cloud.githubusercontent.com/assets/25834335/24642298/a4d10cd2-1930-11e7-8e5f-7d28e103ca14.png)

waktu mau simpan terjadi error seperti gambar dibawah ini 👍 
![image](https://cloud.githubusercontent.com/assets/25834335/24642319/c0fde452-1930-11e7-9bbb-688165645d35.png)

dan cara Kb tidak muncul
![image](https://cloud.githubusercontent.com/assets/25834335/24642529/0b904554-1932-11e7-9ea2-d812f74f648d.png)
mohon perbaikan

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
