### ISSUE TITLE
Tambah data keluarga melalui menu keluarga error lg

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#375]
Setelah pecah KK dan mau tambah data dari penduduk yang sudah terinput (dari data pecah KK tersebut) tampilan NIK kepala keluarga tidak muncul seperti gambar dibawah ini
![image](https://cloud.githubusercontent.com/assets/25834335/24692437/2d326de6-1a03-11e7-93cc-5ba9f3ad5476.png)

**Comment by MUHAMMADRANGSEL** [comment]
Maslahnya di penulisan nama tidak, contoh SA'AT jadi pejulisaannya harus seperti ini SAAT

**Comment by eddieridwan** [comment]
Perbaiki supaya nama seperti Ma'aruf atau Sa'at tidak membuat Tambah Data Keluarga error.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
