### ISSUE TITLE
Menu peta blank 

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#378]
1.Fitur menu peta di pra 1.13 hasilnyq blank
2. Mau cetak perkembqngan penduduk blank kalau excel hasilnya kosong

**Comment by eddieridwan** [comment]
Bisa jelaskan "2. Mau cetak perkembqngan penduduk blank kalau excel hasilnya kosong"? 
Bisa lampirkan screen shotnya?

**Comment by eddieridwan** [comment]
Fitur menu sudah diperbaiki di master.

**Comment by MUHAMMADRANGSEL** [comment]
Membuka bwoser baru tp blank tdk ada yg muncul, terus kalau excel didownload berhasil cuma tdk ada tulisan sedikitpun

**Comment by MUHAMMADRANGSEL** [comment]
Kalau di sid.banguninfo cetak perkembangan sdh ok, sdgkan hasil downloads excel hanya judulnya saja yg ada

**Comment by eddieridwan** [comment]
Ini hasil download excel dari sid.bangundesa.info. Normal. Apakah sudah jalankan Database > Migrasi DB?

[Laporan_bulanan_10_04_2017.xls.zip](https://github.com/eddieridwan/OpenSID/files/909826/Laporan_bulanan_10_04_2017.xls.zip)

**Comment by eddieridwan** [comment]
Sepertinya ada data yang tidak terduga di database anda. Bisa kirim backup database anda ke inbox, nanti saya lihat?

**Comment by MUHAMMADRANGSEL** [comment]
Siap mas sambil mas lihatkan saya dilaporan penduduk ada yg tdk balance

Pada tanggal 11 Apr 2017 04:23, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL , sudah saya coba dengan data anda. Normal saja, lihat hasil cetak dan excel di bawah. Mungkin coba install ulang. Tapi hapus dulu semua file di folder htdocs, **KECUALI** folder _desa_.

![rarang-cetak](https://cloud.githubusercontent.com/assets/249563/24892094/2cead43e-1ece-11e7-9017-1f0327e26ffe.jpg)
[Laporan_bulanan_11_04_2017.xls.zip](https://github.com/eddieridwan/OpenSID/files/912062/Laporan_bulanan_11_04_2017.xls.zip)

**Comment by MUHAMMADRANGSEL** [comment]
Siap mas eddie, coba cek kan saya dilapor bulan tahun 2012 kok ada yang
muncul sdgkqn saya mulai bulan oktober pakai aplikasi ini, dimana
maslahnya...

Pada tanggal 11 Apr 2017 10:49, "Eddie Ridwan" <notifications@github.com>
menulis:

@MUHAMMADRANGSEL <https://github.com/MUHAMMADRANGSEL> , sudah saya coba
dengan data anda. Normal saja, lihat hasil cetak dan excel di bawah.
Mungkin coba install ulang. Tapi hapus dulu semua file di folder htdocs,
*KECUALI* folder *desa*.

[image: rarang-cetak]
<https://cloud.githubusercontent.com/assets/249563/24892094/2cead43e-1ece-11e7-9017-1f0327e26ffe.jpg>
Laporan_bulanan_11_04_2017.xls.zip
<https://github.com/eddieridwan/OpenSID/files/912062/Laporan_bulanan_11_04_2017.xls.zip>

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/eddieridwan/OpenSID/issues/378#issuecomment-293142124>,
or mute the thread

**Comment by eddieridwan** [comment]
Adanya laporan 2012 kemungkinan besar karena anda tidak kosongkan dulu semua contoh data awal sebelum mengisi data desa anda. Contoh awal berisi data di tabel log_bulanan dan log_penduduk. Mungkin data ini yang ditampilkan.

Anda bisa saja hapus baris data lama dari log_bulanan dan log_penduduk secara langsung menggunakan phpmyadmin. Tentunya dengan berhati-hati, supaya data yang betul tidak ikut terhapus.

**Comment by MUHAMMADRANGSEL** [comment]
Oooo gitu ya mas, jadi masalahnya di log penduduk dgn di log bulanan

Pada tanggal 11 Apr 2017 12:26, "Eddie Ridwan" <notifications@github.com>
menulis:

Adanya laporan 2012 kemungkinan besar karena anda tidak kosongkan dulu
semua contoh data awal sebelum mengisi data desa anda. Contoh awal berisi
data di tabel log_bulanan dan log_penduduk. Mungkin data ini yang
ditampilkan.

Anda bisa saja hapus baris data lama dari log_bulanan dan log_penduduk
secara langsung menggunakan phpmyadmin. Tentunya dengan berhati-hati,
supaya data yang betul tidak ikut terhapus.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/eddieridwan/OpenSID/issues/378#issuecomment-293153571>,
or mute the thread

**Comment by eddieridwan** [comment]
Seperti sudah dikatakan di atas, silakan baca dengan cermat penjelasan di https://github.com/eddieridwan/OpenSID/wiki/Statistik-Kependudukan. Peran log_bulanan dan log_penduduk dijelaskan di situ.

**Comment by MUHAMMADRANGSEL** [comment]
tetap tdk bisa dicetak mas eddie, saya instal dan pakai database v.1.13 jg
tdk bisa

Pada tanggal 11 Apr 2017 13:13, "MUHAMMAD SPD" <muhammadrangsel@gmail.com>
menulis:

**Comment by MUHAMMADRANGSEL** [comment]
Apa scripnya yg digithub tdk sama dgn di sid.bangundesa.info

Pada tanggal 11 Apr 2017 22:26, "MUHAMMAD SPD" <muhammadrangsel@gmail.com>
menulis:

tetap tdk bisa dicetak mas eddie, saya instal dan pakai database v.1.13 jg
tdk bisa

Pada tanggal 11 Apr 2017 13:13, "MUHAMMAD SPD" <muhammadrangsel@gmail.com>
menulis:

**Comment by eddieridwan** [comment]
Untuk melacak masalahnya, coba ganti file index.php di folder htdocs dengan file di bawah. Laporkan error yang ditampilkan.

[index.php.zip](https://github.com/eddieridwan/OpenSID/files/915006/index.php.zip)

**Comment by MUHAMMADRANGSEL** [comment]
Tetap tdk bisa mas eddie apa mungkin xampp, yg tdk mendukung...????

Pada tanggal 12 Apr 2017 07:16, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by MUHAMMADRANGSEL** [comment]
dan yg membuat saya binggung di versi 1.13 kok saya mengalami masalah ini
sdgkan yg versi kemarin sampqi versi 1.12 lancar dan aman mas eddie,,,,
kalau bisa data base yg saya kirimkan kemarin mas perbaiki dan mhn
dikirimkan kembali,,   mhn maaf sebelumya dan trima kasih

Pada tanggal 12 Apr 2017 21:58, "MUHAMMAD SPD" <muhammadrangsel@gmail.com>
menulis:

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL **Anda belum jawab: PHP versi berapa? Tampilkan versi PHP menggunakan http://localhost/info.php.**

Juga coba ganti donjo-app/views/laporan/tabel_bulanan.php dengan file terlampir.

[tabel_bulanan.php.zip](https://github.com/eddieridwan/OpenSID/files/917799/tabel_bulanan.php.zip)

**Comment by MUHAMMADRANGSEL** [comment]
siap mas eddie, nanti tiqng coba

Pada tanggal 13 Apr 2017 03:43, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by MUHAMMADRANGSEL** [comment]
apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.5.37

Pada tanggal 13 Apr 2017 06:22, "MUHAMMAD SPD" <muhammadrangsel@gmail.com>
menulis:

**Comment by MUHAMMADRANGSEL** [comment]
saya instal ulang dan memakai rilis 1.13 mas eddie tetap hasilnyq blank di
laporan penduduk

Pada tanggal 14 Apr 2017 18:24, "MUHAMMAD SPD" <muhammadrangsel@gmail.com>
menulis:

apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.5.37

Pada tanggal 13 Apr 2017 06:22, "MUHAMMAD SPD" <muhammadrangsel@gmail.com>
menulis:
