### ISSUE TITLE
Bug: Tombol Kartu RTM  pada menu Rumah Tangga error

### ISSUE THREAD

**Issue by metalab25** [eddieridwan/OpenSID#38]
pada saat lihat rincian data Rumah Tangga button "Kartu rtm" mengarahkan ke "/sid/penduduk/kartu_rtm.php" namun file tersebut tidak ada.
sepertinya itu bug asli dari SID CRI sebab saya coba pake SID dari CRI juga seperti itu

**Comment by eddieridwan** [comment]
Duplikat #258. Tutup yang ini.
