### ISSUE TITLE
Tampilan Web

### ISSUE THREAD

**Issue by matangjaneng** [eddieridwan/OpenSID#380]
Mohon ditambah beberapa opsi tampilan web, terimakasih

**Comment by MUHAMMADRANGSEL** [comment]
Sperti apa penambahannya????

**Comment by eddieridwan** [comment]
@matangjaneng , membuat issue harus rinci & spesifik. Lihat panduan https://github.com/eddieridwan/OpenSID/wiki/Pengelolaan-Masalah-dan-Permintaan-Perbaikan-SID, bagian _Memberi Prioritas Pada Issue_.

Jika ingin diskusi umum, lakukan di Facebook di https://www.facebook.com/groups/OpenSID/.

Kalau yang anda maksud adalah untuk menyediakan pilihan 'theme' untuk penampilan web, lihat panduan https://github.com/eddieridwan/OpenSID/wiki/Mengubah-Penampilan-Web. Silakan membuat folder desa/css untuk penampilan alternatif dan kirimkan untuk di-share.

**Comment by eddieridwan** [comment]
Tutup issue ini, karena tidak ada susulan permintaan spesifik.
