### ISSUE TITLE
BUG: error UI Layout Intialization Error pada modul Admin

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#384]
setelah kali pindah ke menu dan sub menu selalu muncil kalimat seperti gambar dibawah ini
![image](https://cloud.githubusercontent.com/assets/25834335/25060049/a99de434-21bd-11e7-8141-7c5db9c93328.png)

ini terjadi di pasca 1.13

**Comment by eddieridwan** [comment]
Sdh dicommit ke master.
