### ISSUE TITLE
kasus sama >>> error UI Layout Intialization Error pada menu plan dan gis (peta) 

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#385]
![image](https://cloud.githubusercontent.com/assets/25834335/25063157/3268fda0-2207-11e7-9de8-a446ed2dd4ec.png)

![image](https://cloud.githubusercontent.com/assets/25834335/25063197/27c7e7b6-2208-11e7-9bea-da6caec831a7.png)

di menu dan sub menu yang lain sudah ok, tinggal di menu plan dan gis saja

**Comment by eddieridwan** [comment]
Sdh dicommit ke master.

**Comment by MUHAMMADRANGSEL** [comment]
Terima kasih banyak mas eddie

Pada tanggal 15 Apr 2017 18:38, "Eddie Ridwan" <notifications@github.com>
menulis:
