### ISSUE TITLE
Mohon untuk dibuatkan Widget Foto Slide Aparatur Desa

### ISSUE THREAD

**Issue by metalab25** [eddieridwan/OpenSID#387]
Mohon untuk dibuatkan widget foto aparatur desa (kalo bisa statik jadi tinggal upload foto-fotonya saja)

berikut scriptnya (terlampir)
[aparatur_desa.txt](https://github.com/eddieridwan/OpenSID/files/924155/aparatur_desa.txt)
![2017-01-30 1](https://cloud.githubusercontent.com/assets/19917739/25069932/a5f4ea8a-22c1-11e7-89c7-0997c2f8bf85.png)

                                        `

**Comment by eddieridwan** [comment]
Simpan, ubah dan tampilkan foto aparatur desa di menu _SID Home > Pemerintah Desa_. Tambah widget aparatur desa. Tampilkan foto aparatur desa di widget aparatur desa.

Sudah dicommit ke master.

**Comment by eddieridwan** [comment]
Gunakan jquery cycle2 (bukan bootstrap cycle) supaya konsisten dengan slider dan teks berjalan.
