### ISSUE TITLE
Mohon dibuatkan widget untuk Sinergi Program

### ISSUE THREAD

**Issue by metalab25** [eddieridwan/OpenSID#388]
Mohon dibuatkan widget untuk Sinergi Program (kalo bisa statik jadi tinggal upload gambarya danURL tujuannya saja)

Berikut scriptnya (terlampir) 
[sinergi_program.txt](https://github.com/eddieridwan/OpenSID/files/924171/sinergi_program.txt)
![2017-04-16 2](https://cloud.githubusercontent.com/assets/19917739/25069962/768959ba-22c2-11e7-9c45-639ab9550570.png)

**Comment by Agus-Heriyanto** [comment]
Kalo bisa bersinergi juga dengan aplikasi offline sehingga bisa ditampilkan jadi online seperti siskiudes.....![sinergi](https://cloud.githubusercontent.com/assets/21340215/25113480/5d806f12-242a-11e7-9572-e6f4367879c0.png)

**Comment by Agus-Heriyanto** [comment]
Web desa cigelan....mas syafri....Ayo dong mas syafri dibagi sriptnya juga.....Mkasi...

**Comment by eddieridwan** [comment]
Widget Program Sinergitas dari bung Parso Widodo: 
[widget.zip](https://github.com/eddieridwan/OpenSID/files/1100828/widget.zip)

**Comment by eddieridwan** [comment]
Contoh widget Sinergitas Program.

Isi widget:

- terdiri dari baris2, yang berisi gambar yang jika di-klik akan navigasi ke situs terkait
- setiap baris bisa terdiri dari 1, 2 atau 3 gambar.

<img width="1112" alt="contoh-sinergitas-program" src="https://user-images.githubusercontent.com/249563/27524352-964f8bd8-5a77-11e7-9ecd-f88f13b07ef2.png">

**Comment by eddieridwan** [comment]
Gunakan contoh animasi gambar sinergitas_program dari http://cigelam.desa.id/.

Simpan setting widget sinergitas_program di kolom _setting_ di tabel _widget_ dalam format _json_.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
