### ISSUE TITLE
Ubah Background

### ISSUE THREAD

**Issue by arisugiyana** [eddieridwan/OpenSID#389]
cara ubah tampilan website, bagaimana ya. saya pakai webdesa secara online. terimakasih

**Comment by batudaa** [comment]
Jangan lupa baca wiki
https://github.com/eddieridwan/OpenSID/wiki/Mengubah-Penampilan-Web

**Comment by arisugiyana** [comment]
terima kasih tapi saya tidak menginstal SID di komputer

**Comment by eddieridwan** [comment]
Daftar issue ini digunakan untuk melaporkan masalah atau usulan/permintaan perbaikan OpenSID. Jika hanya ingin tahu cara menggunakan OpenSID, sebaiknya bertanya di https://www.facebook.com/groups/OpenSID/.

Apabila pertanyaan anda tidak ada kaitannya dengan OpenSID, di sini bukan tempatnya.
