### ISSUE TITLE
Header Desa dengan alamat dan website

### ISSUE THREAD

**Issue by metalab25** [eddieridwan/OpenSID#397]
Bung Eddie atau para programer opensid lainnya, saya ada melakukan perubahan pada file inti untuk merubah left menu (top menu) dan melakukan perubahan untuk menampilkan telepon, website dan email pada top header frontend hingga menjadi seperti di gambar
![2017-04-26 4](https://cloud.githubusercontent.com/assets/19917739/25443320/16351f48-2ada-11e7-99e6-dffa668b8021.png)
Perubahan - perubahan yang saya lakukan ada di file" yang saya kirim (terlampir)
"karena tidak bisa upload lampiran disini maka saya sertakan url file yang saya upload di grup fb"
https://lookaside.fbsbx.com/file/donjo-app.zip?token=AWwhDKbfQF5OdQJD5RTrTGiSz3WvOjzagxzZ08O3qUI80O0shA4WrqQ3ni6aJdNya0B_MHjj_T91qHmC86h50IG87zwAbXP-0Jzx3xM64M4wX0a0vIY_EPk5TrMkowYde3tiDVGHNUm3PEyXP5G9AiIHuagkRYdlP3IA3TMaK3-zSQ

**Comment by eddieridwan** [comment]
Tema hadakewa sudah dimasukkan ke rilis.
