### ISSUE TITLE
#Tolong Perbaiki Bug di upload foto penduduk

### ISSUE THREAD

**Issue by Marzuki5** [eddieridwan/OpenSID#400]
selamat pagi, mohon bantuannya agan2, yang bisa programing untuk memperbaiki bug ganti foto penduduk dan viewnya dikarenakan itu sangat urgent posisinya 

terimakasih, salam 

![screenshot_8](https://cloud.githubusercontent.com/assets/26277417/25510102/d2f050cc-2be7-11e7-95b2-8dad4c454224.png)

**Comment by eddieridwan** [comment]
Sdh dicommit ke master.

**Comment by dadannurman** [comment]
Master @eddieridwan , gimana caranya agar Foto muncul di Biodata Penduduk setelah log in Layanan Mandiri

![poto](https://cloud.githubusercontent.com/assets/28327817/25834563/00360a54-34a3-11e7-92fe-2df2ffaf2210.PNG)
