### ISSUE TITLE
Bug: ekspor excel di Wilayah Administrasi > Dusun hasilnya blank

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#401]
Ketika mau export excel data desa berdasarkan RT, RW dan Dusun mengalami blank kasusnya sama dengan Rumah Tangga yg kemarin

**Comment by eddieridwan** [comment]
Coba tampilkan screen shot. Kami coba di laman Keluarga dan Penduduk, normal.

**Comment by MUHAMMADRANGSEL** [comment]
Kalau keluarga normal masalahnya di wilayah administrasi mas yg saya maksud
untuk rt dan rw

Pada tanggal 29 Apr 2017 12:33, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by MUHAMMADRANGSEL** [comment]
Kalau saya sdh memperbaikinya mas eddie tetapi temen2 yg nanti bingung dan belum tentu bisa merubah

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL Ok, jangan lupa, pada waktu melaporkan masalah selalu beri informasi yang lengkap: langkah2 yang dilalui (misalnya persisnya di menu mana) dan lampirkan screenshot. Supaya programmer tidak bingung dan perlu menebak-nebak apa masalahnya.

**Comment by eddieridwan** [comment]
Juga, jika sudah tahu solusinya, sekalian lampirkan. Atau lebih bagus lagi, sekalian buatkan pull requestnya.

**Comment by pandigresik** [comment]
minimal berikan url ketika akses fitur tersebut, itu akan sangat membantu

**Comment by metalab25** [comment]
mungkin yang dimaksud adalah link ini
http://localhost/opensid115/index.php/sid_core/sub_rt/9/-

Ini memang terjadi blank pada menu Wilayah Administrasi > Dusun (pilih salah satu dusun) lalu klik button excel
![2017-05-11 5](https://cloud.githubusercontent.com/assets/19917739/25953004/b08fe1a2-3694-11e7-9505-4237289fc3a9.png)

**Comment by MUHAMMADRANGSEL** [comment]
Ya itu yg saya maksud

Pada tanggal 11 Mei 2017 21:03, "Happy" <notifications@github.com> menulis:

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
