### ISSUE TITLE
unite tests untuk opensid

### ISSUE THREAD

**Issue by simasta** [eddieridwan/OpenSID#403]
Mas @eddieridwan , ada baiknya kita tambahkan tests unite untuk opensid

**Comment by eddieridwan** [comment]
@simasta Sangat setuju. Silakan usulkan pendekatan yang akan diambil dan mungkin buat contoh kecil dulu. Mungkin teman2 programmer lain bisa ikut memberi masukan. @cafeiklan @batudaa @pandigresik

**Comment by simasta** [comment]
td malam sy sudah coba buat test menggunakan simpletest, nnti coba saya pull ke master, sebagai bahan pertimbangan. bagi saya simpletest lebh mudah digunakan bhkan oleh pengguna sekalipun, jadi mnurut sy foldernya dimasukkan ke dalam release, sehingga pengguna dapat melakukn test masing2 di opensid mereka.

**Comment by batudaa** [comment]
Tergantung keputusan @eddieridwan saja :)

Tapi **sekedar saran**, kalau di masukkan dalam release, bagusnya menunggu sampai opensid sudah memisahkan environment production dan testing. Terutama untuk masalah database. Jangan sampai pengguna menjalankan test dengan database production. Test juga setidaknya sudah mencakup setengah fitur yang ada. Sebelum itu, di sediakan branch khusus dulu.

**Comment by eddieridwan** [comment]
@batudaa , setuju. Pasang di branch _test_ dulu untuk digunakan/dikembangkan oleh programmer. Sambil kita evaluasi dan buat prosedur pengunaannya.

@simasta, pull request anda sudah dicommit ke branch _test_. Sepertinya sudah perlu ada wiki untuk programmer OpenSID, termasuk cara penggunaan simpletest. Mungkin anda dapat mulai buat wiki ini di https://github.com/eddieridwan/OpenSID/wiki?
