### ISSUE TITLE
Tampilan Cetak Biodata

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#404]
Tampilan Cetak Biodata untuk tabel butuh penyesuaian
![image](https://cloud.githubusercontent.com/assets/25834335/25553283/67652844-2cd9-11e7-8b9e-2722e7b7806e.png)

**Comment by metalab25** [comment]
maunya tampilannya dibuat seperti apa om sapa tau saya bisa membantu.
mohon dibuatkan draftnya pake doc aja om

**Comment by MUHAMMADRANGSEL** [comment]
Semua data brada didalam tabel

**Comment by MUHAMMADRANGSEL** [comment]
Dan potonya juga

**Comment by metalab25** [comment]
tabel mana om ?

**Comment by MUHAMMADRANGSEL** [comment]
sperti screnshot yg saya tmbahkn diatas

Pada tanggal 29 Apr 2017 18:51, "Happy" <notifications@github.com> menulis:

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL, apa yang anda inginkan kurang jelas. Seperti diminta oleh @metalab25, harap diperjelas. Apa bedanya gambar anda di atas dengan yang sekarang ada? Ingat, programmer perlu diberi informasi terinci apa yang anda inginkan diubah. Supaya tidak bingung dan menebak-nebak.

**Comment by MUHAMMADRANGSEL** [comment]
tampilan awal seperti gambar dibawah ini
![tangkapan layar 2017-05-04 16 37 50](https://cloud.githubusercontent.com/assets/25834335/25698450/17b82738-30e9-11e7-85ca-64067aa70ec9.png)

mau dirubah seperti gambar dibawah ini
![tangkapan layar 2017-05-04 16 43 14](https://cloud.githubusercontent.com/assets/25834335/25698461/221a7b0e-30e9-11e7-8372-5cdfdd43e7d6.png)

**Comment by eddieridwan** [comment]
Sdh dicommit ke master.
