### ISSUE TITLE
Issue semakin bertambah namun belum ada solusi

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#407]
Issue yang ada di OpenSID dari hari ke hari semakin bertambah, yg disayangkan issue tersebut tdk secepat dulu diselesaikan, apakah OpenSID sdh tidak lagi dihiraukan oleh para programer2 yg ada...????, seyogyanya issue tersebut harus segera terselesaikan apalagi OpenSID hajatannya untuk seluruh desa dan kelurahan yg ada di Indonesia negeri kita tercinta ini.

**Comment by MUHAMMADRANGSEL** [comment]
OpenSID merupakan aplikasi yg sangat banyak manfaatnya untuk desa dan kelurahan, shg dimohon kepada semua programer2 yg peduli kepada desa spy segera menyelesaikan issue yg ada.

**Comment by MUHAMMADRANGSEL** [comment]
Kami hanya bisa membuat issue, sdgkanntdk bisa menyelesaikan issue karna keterbatasan ilmu, dan kami minta maaf sekiranya ada bahasa yg kurang pas, ini semua demi kemajuan OpenSID

**Comment by MUHAMMADRANGSEL** [comment]
Saya sendiri sebenarnya ingin sekali banyak bisa berbuat, tapi apalah daya saya tdk punya keahlian.

**Comment by batudaa** [comment]
Namanya juga di github. Programmer-programmer yang ada itu merupakan sukarelawan dan punya kesibukan lain selain mengembangkan aplikasi ini.

Kalau kebutuhannya sudah mendesak, saya sarankan untuk mencari seseorang atau perusahaan disekitar anda dengan kontrak layanan secara komersial untuk membantu anda.

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL Heheh... komentar anda pasti karena permintaan anda belum dikerjakan, ya.. sebenarnya pengembangan berjalan terus, terbukti dengan adanya rilis setiap dua minggu sekali... berkat bantuan relawan seperti @batudaa dan @pandigresik.

Oke, terima kasih anda telah membuat kontribusi panduan. Issue anda #326 sekarang akan kami mulai kerjakan.

Sebaiknya diskusi ini diteruskan di https://www.facebook.com/groups/OpenSID/ supaya issue bisa murni digunakan untuk pengelolaan masalah/usulan/permintaan.
