### ISSUE TITLE
Tampilan Identitas Peserta penerima Bantuan yg ada di Kartu perlu di munculkan

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#409]
Data Identitas di Kartuperlu di munculkan posisinya seperti gambar dibawah ini
![tangkapan layar 2017-05-03 12 21 11](https://cloud.githubusercontent.com/assets/25834335/25649032/381805fe-2ffc-11e7-8ff1-d36455088cf1.png)

dan juga di export excel juga perlu dimunculkan datanya seperti data yang terekam adapun data yang terekam tersebut seperti gambar dibawah ini
![tangkapan layar 2017-05-03 12 22 46](https://cloud.githubusercontent.com/assets/25834335/25649027/2e85672a-2ffc-11e7-8263-a1f4cf0f336a.png)

**Comment by MUHAMMADRANGSEL** [comment]
adapun manfaatnya supaya ketika kita mencari peserta yang mendapatkan bantuan secara langsung bisa kita lihat apakah terdapat perbedaan atau tidak

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL, yang anda lampirkan di atas adalah screenshot sistem yang sudah ada. Harap anda lampirkan konsep yang anda inginkan:

1. Persisnya kolom2 apa yang anda inginkan di tampilan Daftar Peserta Program
1. Persisnya kolom2 apa yang anda inginkan di export excel

Anda perlu mengusulkan, karena belum tentu semua data bisa muat, dan mungkin urutan kolomnya penting. Jadi harap beri konsep yang jelas. Ini tugas anda sebagai pengguna untuk menentukan. Programmer hanya bisa menebak -- dan sering salah tebak.....

**Comment by MUHAMMADRANGSEL** [comment]
Siap mas eddie

Pada tanggal 3 Mei 2017 14:31, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by MUHAMMADRANGSEL** [comment]
1. Kolom satu tampilannya seperti gambar dibawah ini
![image](https://cloud.githubusercontent.com/assets/25834335/25657947/8c85a492-302a-11e7-899d-5a47e6a49ff7.png)

2. kolom no 2 untuk export seperti gambar dibawah ini
![image](https://cloud.githubusercontent.com/assets/25834335/25657979/bd50205c-302a-11e7-85b0-a1e774be97cd.png)

**Comment by eddieridwan** [comment]
Sdh dicommit ke master. @MUHAMMADRANGSEL: harap diuji-coba. Unduh versi pra-rilis.

**Comment by dadannurman** [comment]
Mohon maaf mas @eddieridwan, saya sudah lakukan perubahan sesuai petunujuk.
namun saya masih bingung cara merubah/memunculkan/input data "identitas di kartu peserta"

![capture33](https://cloud.githubusercontent.com/assets/28327817/26040394/1e566f78-394f-11e7-9aa3-d0b0f924e27a.PNG)

mohon solusinya master
