### ISSUE TITLE
#bug menu dropdown akseptor KB

### ISSUE THREAD

**Issue by dadannurman** [eddieridwan/OpenSID#410]
pada saat tambahdata baru di menu keluarga di klik gak muncul
![1111](https://cloud.githubusercontent.com/assets/28327817/25652532/df74cc4a-3012-11e7-8207-12a8a9bae4ee.PNG)
tapi saat ubah data dari menu penduduk bisa muncul
![22222](https://cloud.githubusercontent.com/assets/28327817/25652553/f7017912-3012-11e7-8db5-54728f206ea9.PNG)

tolong master solusinya, jadi pas tambahdata baru di menu keluarga bisa langsung memilih akseptor KB yang d gunakan, gak harus merubahnya lagi di menu penduduk

**Comment by eddieridwan** [comment]
Sdh dicommit ke master.
