### ISSUE TITLE
#bug LAPORAN BULANAN DESA/KELURAHAN di menu kelompok rentan

### ISSUE THREAD

**Issue by dadannurman** [eddieridwan/OpenSID#411]
Data Umur Penduduk sudah terbaca

![lapor](https://cloud.githubusercontent.com/assets/28327817/25690611/204f9682-30bd-11e7-9249-28664d2f0de2.PNG)

Tetapi di Laporan bulanan pada menu "Laporan Kelompok Rentan" tidak terbaca 

![lapor2](https://cloud.githubusercontent.com/assets/28327817/25690633/5e42beb0-30bd-11e7-8dab-cd7fe2e2261e.PNG)

Mohon solusinya master, agar data umur penduduk bisa otomatis masuk di "Laporan Kelompok Rentan"

**Comment by MUHAMMADRANGSEL** [comment]
Data yg mas input belum ada yg kategori rentan

**Comment by dadannurman** [comment]
oh iya kak @MUHAMMADRANGSEL  makasih banyak :-)
