### ISSUE TITLE
Perlu ada rincian maslah cacat di sub menu laporan kelompok rentan

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#412]
Untuk lebih jelasnya Jenis Cacat yang diderita oleh masyarakat terutama di Laporan kelompok rentan perlu di tambahkan kolom untuk rincian jenis cacat seperti gambar dibawah ini
![tangkapan layar 2017-05-04 17 43 33](https://cloud.githubusercontent.com/assets/25834335/25700354/a02b72f2-30f1-11e7-90fb-4d16a80f5a9e.png)

kenapa ini perlu dirincikan, kemarin kami bingung pada waktu diinput data masyarakat kita pilih "tidak cacat" namun dilaporan kelompok rentan di masuk di cacat shhg pemerintah desa tidak bisa mengetahui berapa yang cacat secara detail sesuai dengan cacat yang diderita

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
