### ISSUE TITLE
Time picker

### ISSUE THREAD

**Issue by dadannurman** [eddieridwan/OpenSID#413]
Master, gimana caranya datepicker

![datepicker](https://cloud.githubusercontent.com/assets/28327817/25735634/f5100698-3196-11e7-9862-b3addb6e9c63.PNG)

ingin jadi time picker, untuk insert jam di surat tertentu.

**Comment by eddieridwan** [comment]
Sudah dicommit melalui https://github.com/eddieridwan/OpenSID/pull/415.
