### ISSUE TITLE
BUG: Lokasi penduduk tidak muncul

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#414]
lokasi penduduk pada waktu memasukkan data keluarga baru, data penduduk baru maupun edit data penduduk tidak muncul alias blank , tampilannya seperti gambar dibawah ini 
1. keluarga
![image](https://cloud.githubusercontent.com/assets/25834335/25743294/cb244d5e-31bd-11e7-890c-401c98ecd061.png)

2. penduduk 
![image](https://cloud.githubusercontent.com/assets/25834335/25743129/101684f0-31bd-11e7-9699-b909eebaa7a9.png)

sebelumnya bisa tampil

**Comment by eddieridwan** [comment]
Sdh dicommit ke master.
