### ISSUE TITLE
dropdown default (Staf Pemerintah Desa dan Jabatan)

### ISSUE THREAD

**Issue by dadannurman** [eddieridwan/OpenSID#417]
Minta solusinya master, gimana caranya saat membuka cetak surat 

![def](https://cloud.githubusercontent.com/assets/28327817/25790349/126f6074-33e2-11e7-89c6-ea7434c3a885.PNG)

pada Staf Pemerintah Desa atau Jabatan langsung default ke Kepala Desa tanpa harus memilih dulu

![def2](https://cloud.githubusercontent.com/assets/28327817/25790381/4767afac-33e2-11e7-87be-3c28f1915fc1.PNG)

**Comment by metalab25** [comment]
Bahasan issunya sama dengan ini https://github.com/eddieridwan/OpenSID/issues/296

**Comment by MUHAMMADRANGSEL** [comment]
yang berhak tanda tangan bukan hanya kepala desa tetapi yang berhak selain kepala desa seperti sekdes dan kaur dsa, ketika kepala desa tidak berada di kantor desa, jadi harus ada pilihan tidak harus baku, dikarenakan kepala desa secara aturan hanya 25% berada di kantor desa dan 75% berada dilapangan, sedangkan sekdes disamping menjadi kepala kantor juga harus stanby di kantor

**Comment by dadannurman** [comment]
gak maaf mas @MUHAMMADRANGSEL, maksud saya untuk default nya, jadi yang seringnya kan kepala desa, kecuali kalo kepala desa gak ada baru kita pilih staf yang lain.

**Comment by dadannurman** [comment]
atau bahkan kita bisa setting deffault nya sendiri di menu admin, jadi siapa yang akan kita set default untuk staf pemerintah desa, kita mau pilih kades/lurah atau kita pilih sekdes dll.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
