### ISSUE TITLE
komentar untuk user "Layanan Mandiri" tdk perlu memasukan data lagi

### ISSUE THREAD

**Issue by dadannurman** [eddieridwan/OpenSID#418]
Maaf master, Setelah login user, bagaimana kalau komentar tanpa input nama dan email lagi?

![layanan](https://cloud.githubusercontent.com/assets/28327817/25835156/bc0cd750-34a6-11e7-82fc-463ab5b2b2d5.PNG)

bagaimana solusinya? trmksih banyak.

**Comment by MUHAMMADRANGSEL** [comment]
Itu sdh seharusnya ada shgg nama dan email menjadi syarat utama, shgg kitq tau siapa yg memberikqn kritik dan saran keppd desa

**Comment by eddieridwan** [comment]
Usulan bagus. Tinggal memberi prioritas saja :)....

Bung @dadannurman, apakah anda programmer?

**Comment by dadannurman** [comment]
Saya hanya newbe dan otodidak mas @eddieridwan, tapi saya sangat tertarik dengan pemograman.
Maaf mas @eddieridwan untuk ranah ini saya ingin belajar dan belum bisa membantu.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master. Tapi hanya terbatas pada nama penduduk, karena saat ini data penduduk belum menyimpan alamat email penduduk.

@dadannurman , @MUHAMMADRANGSEL : saat ini penduduk yang mendaftar layanan mandiri belum diminta untuk memasukkan email. Jika diperlukan, harap buat issue terpisah.
