### ISSUE TITLE
Menu plan

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#419]
Menu plan yg ada di OpenSID perlu banyak perbaikqn2 shgg bisa dimanfaat oleh pemerintah dlm rangka perencanaan desa kedepan, kepada semua programer handal mohon menu plan tersebut dilirik

**Comment by eddieridwan** [comment]
Setiap issue perlu dibuat spesifik supaya bisa dipertimbangkan, karena merupakan daftar tugas. Kalau ada usulan tertentu mengenai 'menu plan' (?) silakan buat issuenya. 

Komentar umum sebaiknya diposting di Facebook group https://web.facebook.com/groups/OpenSID/. Terima kasih atas pengertiannya.
