### ISSUE TITLE
Perubahan untuk halaman error db

### ISSUE THREAD

**Issue by metalab25** [eddieridwan/OpenSID#420]
saya melakukan perubahan pada halaman error db.
perubahan yang saya lakukan adalah menambahkan informasi petunjuk untuk mengatasi kendalanya dan saya juga menambahkan tautan ke panduan installasi awa OpenSID
![2017-05-12 2](https://cloud.githubusercontent.com/assets/19917739/25997753/29bd68cc-3750-11e7-9570-2eeb324c5f46.png)

Perubahan yang saya lakukan ada di (terlampir)
[db_lang.php.txt](https://github.com/eddieridwan/OpenSID/files/996044/db_lang.php.txt)

Mudah"an bisa diterapkan dirilis berikutnya agar tidak ada yang bertanya lagi kendala setting OpenSID

**Comment by sugiantoe** [comment]
setuju om.. hehe jadi ingat waktu pertama kali instal OpenSID, saya mengalami hal demikian :D

**Comment by metalab25** [comment]
Mudah"an bisa diterapkan

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR https://github.com/eddieridwan/OpenSID/pull/472
