### ISSUE TITLE
Bug Slide Header di OpenSID 1.15

### ISSUE THREAD

**Issue by metalab25** [eddieridwan/OpenSID#422]
![2017-05-13](https://cloud.githubusercontent.com/assets/19917739/26012958/f1e8e154-3788-11e7-8c18-13a4a1064515.png)
Terjadi setelah mengaktifkan album sebagai Slide Header

**Comment by eddieridwan** [comment]
Sepertinya anda menggunakan versi sebelum rilis 1.15 resmi. Di https://github.com/eddieridwan/OpenSID/releases sudah diperbaiki. Lihat contoh di sid.bangundesa.info.

**Comment by metalab25** [comment]
Saya menggunakan opensid 1.15 malah yang error ini. Pada saat saya coba yang pra 1.15 malah tidak ada masalah

**Comment by eddieridwan** [comment]
Sudah coba mengambil script dari https://github.com/eddieridwan/OpenSID/releases.

Untuk konfirmasi, cari "layouts/slider.php" di script. Misalnya, di themes/hadakewa/partials/content.php, cek scriptnya berisi:

```
if(count($slider_photos)>0){
	$this->load->view($folder_themes."/layouts/slider.php");
}
```
Jika berbeda, script anda salah.

**Comment by eddieridwan** [comment]
Saya sudah cek, di rilis sudah betul. Lihat https://github.com/eddieridwan/OpenSID/blob/v1.15/themes/hadakewa/partials/content.php

**Comment by metalab25** [comment]
sebentar saya cek, ada kemungkinan saya mengunakan script conten.php yang lama
