### ISSUE TITLE
#gambar upload logo tidak muncul

### ISSUE THREAD

**Issue by sencell45** [eddieridwan/OpenSID#423]
gambar upload logo kok tidak muncul kenapa ya
![asdfasdf](https://cloud.githubusercontent.com/assets/28659152/26013744/f6dbc03c-3783-11e7-9279-8f303bcec17d.PNG)

**Comment by sugiantoe** [comment]
saya juga mengalami masalah yang sama mas, logo, gambar user dan dokumen kelengkapan penduduk tidak bisa di upload
![image](https://cloud.githubusercontent.com/assets/28652833/26020175/a7935220-37a5-11e7-808a-70af13c6fb04.png)

**Comment by eddieridwan** [comment]
Jangan lupa cek panduan. Rajin2 baca panduan. https://github.com/eddieridwan/OpenSID/wiki/Tanya-Jawab-Install-dan-Update

Juga baca mengenai peran folder _desa_ : https://github.com/eddieridwan/OpenSID/wiki/Folder-Desa.
