### ISSUE TITLE
ubah status dasar, tidak menampilkan data sebelumnya.

### ISSUE THREAD

**Issue by sugiantoe** [eddieridwan/OpenSID#426]
pada modul penduduk, jika kita klik menu ubah status dasa, pop up yg muncul tidak menampilkan status dasar sebelum dirubah. jika kita tidak memilih status dasar dan klik simpan, maka akan muncul error.

![image](https://cloud.githubusercontent.com/assets/28652833/26034557/b38469ae-38e8-11e7-9d85-6bad55b11f0d.png)

![image](https://cloud.githubusercontent.com/assets/28652833/26034547/882dd56a-38e8-11e7-8629-97917747b61b.png)

**Comment by metalab25** [comment]
sudah coba di http://demosid.opensid.info om ?

**Comment by sugiantoe** [comment]
sudah Om @metalab25 hasil sama

![image](https://cloud.githubusercontent.com/assets/28652833/26064677/e0860ac4-39bb-11e7-99e2-9c65f7455f28.png)

**Comment by batudaa** [comment]
Selain masalah ini, saya juga sebenarnya menemukan kejanggalan. Contohnya, setelah ubah status dasar atau batal mengubah, trus mau mengubah status dasar penduduk lain, formulirnya tidak muncul. 

Tapi mengingat ini soal javascript yang biasanya terpengaruhi oleh browser yang digunakan, saya tidak bisa memastikan ini hanya terjadi di browser saya atau memang terjadi di semua browser pengguna. Kalau iya mungkin bisa dijadikan issue yang baru dengan perbaikan yang terpisah.

**Comment by eddieridwan** [comment]
Sdh dicommit ke master, melalui pull request https://github.com/eddieridwan/OpenSID/pull/428 oleh @batudaa
