### ISSUE TITLE
Bug pada share button di artikel

### ISSUE THREAD

**Issue by metalab25** [eddieridwan/OpenSID#43]
Saya menemukan sedikit bug, mungkin tepatnya button tersebut tidak berjalan sebagaimana mestinya, mohon master untuk di cek dan buatkan fixnya

thanks

**Comment by metalab25** [comment]
kalo untuk button like gimana master, saya buat seperti ini

<div class=\"form-group\" style=\"clear:both;\">
			<ul id=\"pageshare\" title=\"bagikan ke teman anda\" class=\"pagination\">
			    <li class=\"sbutton\" id=\"fb\"><a name=\"fb_share\" href=\"http://www.facebook.com/sharer.php?u=".site_url()."first/artikel/".$single_artikel["id"]."\"><i class=\"fa fa-facebook-official\"></i>&nbsp;Share</a></li>
				<li class=\"sbutton\" id=\"fb\"><a name=\"fb_like\" href=\"http://www.facebook.com/like.php?u=\"".site_url()."first/artikel/".$single_artikel["id"]."\"><i class=\"fa fa-thumbs-up\"></i>&nbsp;like</a></li>
				<li class=\"sbutton\" id=\"rt\"><a href=\"http://twitter.com/share\" class=\"twitter-share-button\"><i class=\"fa fa-twitter\"></i>&nbsp;Tweet</a></li>
			</ul>
			
		</div>
		<div class=\"form-group\">

**Comment by eddieridwan** [comment]
Terima kasih @batudaa dan @metalab25 . Kami ambil dari kontribusi @metalab25 (ada iconnya..), tapi tanpa FB.like, yang belum berfungsi di sistem saya (menampilkan halaman FB dengan error tidak bisa menemukan halaman yg dicari).
