### ISSUE TITLE
Tampilan Bar Grapic dan  pie Cart tidak tampil

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#432]
Tampilan Bar Grapic dan  pie Cart di semua data tidak tampil di Front End seperti Gambar dibawah ini
![tangkapan layar 2017-05-29 12 50 04](https://cloud.githubusercontent.com/assets/25834335/26537964/80187ce6-446d-11e7-912a-2c9bb0a3c422.png)

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL Ini di situs demo sid.bangundesa.info (v1.16). Normal saja. Apakah ada yang anda ubah?

<img width="1350" alt="statistik-di-web" src="https://cloud.githubusercontent.com/assets/249563/26539118/1a1facc2-448e-11e7-8b93-2b6d09ab9035.png">

**Comment by MUHAMMADRANGSEL** [comment]
Tdk ada
