### ISSUE TITLE
penyimpanan foto tidak tampil

### ISSUE THREAD

**Issue by oindolo** [eddieridwan/OpenSID#433]
mass eddie ridwan, gagal menampilkan foto penduduk.. openSID v.1.16. sedangkan versi sebelumnya tidak apa2.

**Comment by eddieridwan** [comment]
Di http://sid.bangundesa.info (v1.16) berhasil normal. 

Apakah ada error yang ditampilkan? Apakah sudah buat folder desa? Apakah ukuran file fotonya melebihi batas upload di server anda (bisa cek dengan lihat upload size di http://localhost/openside/php.info)?

**Comment by eddieridwan** [comment]
Jika ada kesulitan seperti ini, biasakan mencoba juga di situs demo di http://sid.bangundesa.info. Jika normal di situs demo, berarti ada yang tidak lengkap di instal anda.

**Comment by eddieridwan** [comment]
@oindolo apakah masalah ini sudah teratasi? Kalau tidak ada komentar lagi, kami akan tutup issue ini.

**Comment by eddieridwan** [comment]
Kami tutup, karena tidak ada info tambahan.
