### ISSUE TITLE
Penambahan link ke artikel di Slider

### ISSUE THREAD

**Issue by abdullah-sid** [eddieridwan/OpenSID#434]
sedikit ada saran dari beberapa aparat desa di desa saya, seandainya Slider di halaman depan Opensid jika di klik langsung ke link artikel tentang gambar yg di tempilkan di Slider, karna penduduk pasti bertanya kegiatan apa yg di slider.

**Comment by eddieridwan** [comment]
Slider atas yang berbentuk _carousel_ menggunakan plugin Sothink JavaScript Web Scroller di http://www.sothink.com/product/javascriptwebscroller/. Plugin ini berbayar dan sudah agak tua. Slidernya disusun menggunakan aplikasi yang jalannya di Windows. Sehingga untuk mengubahnya repot.

Sedangkan slider header (di atas artikel) sekarang sudah menggunakan plugin jquery.cycle yang relatif lebih modern. Dan jquery.cycle memiliki plugin tambahan untuk menampilkan _carousel_.

Karena itu kami akan menjajaki mengganti scroller yang digunakan sekarang (Sothink JavaScript Web Scroller) dengan jquery.cycle.

**Comment by eddieridwan** [comment]
Dengan penggantian dari plugin Sothink JavaScript Web Scroller ke Jquery Cycle2, terpaksa dilakukan perombakan struktur header pada tema dasar. Dan tentunya juga berdampak pada tema default dan hadakewa.

Adanya dua penggunaan Jquery Cycle2, di _carousel_ dan di _slider-header_ memerlukan penanganan tambahan untuk membedakan keduanya.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
