### ISSUE TITLE
Website terblokir

### ISSUE THREAD

**Issue by kelbatuix** [eddieridwan/OpenSID#435]
Website Kelurahan kami sudah coba saya online kan, namun selalu terblokir setelah kami mencoba mengakses aplikasinya. Setelah kami tanyakan pada jasa hosting (rumahweb.com), dikatakan bahwa kami mengupload shell yang dianggap membahayakan sistem sehingga diblokir oleh modsecurity. Apa yang harus dilakukan agar tidak diblokir terus?

**Comment by eddieridwan** [comment]
Bisa lampirkan sceenshot error yang ditampilkan?

**Comment by eddieridwan** [comment]
Di file desa/config/config.php cek apakah ada setting seperti berikut:

`$config['libreoffice_path'] = "C:\Program Files (x86)\LibreOffice 4\program";
`

Jika ada, ini akan menyebabkan aplikasi berusaha untuk menjalankan libreoffice pada server SID untuk menghasilkan surat PDF. Coba hapus baris ini atau ganti settingnya menjadi kosong:

`$config['libreoffice_path'] = "";
`

**Comment by kelbatuix** [comment]
Sudah dicoba, dan sejauh ini berhasil, terima kasih.
