### ISSUE TITLE
alamat website kelurahan

### ISSUE THREAD

**Issue by kelbatuix** [eddieridwan/OpenSID#438]
pada sistem informasi identitas kelurahan, alamat website dengan tanda "-" berganti menjadi ' yaitu kel-batuix.go.id berganti menjadi kel'batuix.go.id

**Comment by eddieridwan** [comment]
Ini disebabkan upaya di SID asli untuk mencegah SQL injection dengan mengubah '-' menjadi tanda petik pada waktu menyimpan data dan seharusnya mengembalikan tanda petik menjadi '-' pada waktu menampilkan data. Tetapi urutan penggunaan function _penetration_ dan _unpenetration_ terbalik.

Solusinya menggunakan CI query builder untuk meng-escape parameter secara otomatis untuk mencegah SQL injection. Dan kemudian menghapus penggunaan function _penetration_ dan _unpenetration_ di form dan penyimpanan data konfigurasi.

**Comment by eddieridwan** [comment]
Sdh dicommit ke master.

**Comment by eddieridwan** [comment]
Dari Happy Agung: setelah saya coba OpenSID Pasca 1.16 ternyata tanda - masih berubah menjadi '

**Comment by eddieridwan** [comment]
@metalab25 Di tampilan di mana? Harap lampirkan cetak layarnya.

**Comment by eddieridwan** [comment]
Ok, sudah ketemu, di footer tema 'hadakewa' : themes/hadakewa/partials/copywright.tpl.php.
Sudah dicommit ke master.

**Comment by metalab25** [comment]
saya berkomentar di issue yang sudah di commit karna bahasannya sama
![2017-06-05](https://cloud.githubusercontent.com/assets/19917739/26768842/2f96921a-49dd-11e7-9f44-b891c5267239.png)
