### ISSUE TITLE
Tidak bisa menambah widget atau merubah widget

### ISSUE THREAD

**Issue by kelbatuix** [eddieridwan/OpenSID#439]
Setelah update v1.16 kami tidak bisa menambah atau merubah widget. hanya bisa menggeser. pesan error : Forbidden

You don't have permission to access /index.php/web/update/1003/55/1/0 on this server.
Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by eddieridwan** [comment]
Apakah sudah coba di situs demo http://sid.bangundesa.info. Di situ, tambah/ubah widget normal.

Sepertinya instal anda ada yang kurang. Mungkin install ulang?

Biasakan memeriksa di situs demo. Jika jalan di situs demo, ada sesuatu di instal anda yang menyebabkan error: data, infrastruktur server SID, atau scriptnya berbeda dengan rilis.

**Comment by kelbatuix** [comment]
saya langsung update v1.16 dengan menimpa v1.15. apakah cara mengudate harus dihapus dulu data lama atau bisa langsung ditimpa ya? mohon arahannya.

**Comment by kelbatuix** [comment]
Saya sudah install ulang, bahkan menghapus semua dan proses dari awal. untuk penambahan widget berupa tulisan atau gambar tidak ada masalah, namun penambahan widget dengan embed kalender atau peta menjadi error.

**Comment by eddieridwan** [comment]
Lampirkan screenshot untuk errornya. Juga lampirkan script widgetnya.
Sudah coba di http://sid.bangundesa.info?

**Comment by kelbatuix** [comment]
![screenshot 3](https://cloud.githubusercontent.com/assets/25999158/26669643/d8f49dbe-46d8-11e7-8598-a9244ceb3118.png)
![screenshot 4](https://cloud.githubusercontent.com/assets/25999158/26669644/d8f58738-46d8-11e7-8f1d-d965c19b8de4.png)
![screenshot 5](https://cloud.githubusercontent.com/assets/25999158/26669645/d8f80e04-46d8-11e7-8954-62389f877fc5.png)

**Comment by kelbatuix** [comment]
Kalau di demo sudah di coba dan bisa mas, gk ada mslh. Saya mengupload file langsung dari zip release, dan kedua dari zip master. hasilnya sama mas.

**Comment by kelbatuix** [comment]
iy sebentar mas saya hub teknisi lagi karen website saya terkunci kembali, apa memang seperti itu yang sudah online atau saya aja dengan provider ini ya?

**Comment by kelbatuix** [comment]
![screenshot 6](https://cloud.githubusercontent.com/assets/25999158/26670104/92a72d84-46da-11e7-966a-17e5ad495a02.png)
psan errorny 
![screenshot 5](https://cloud.githubusercontent.com/assets/25999158/26670119/9d15c6ae-46da-11e7-853f-83c90d6fcf5d.png)

**Comment by eddieridwan** [comment]
Sepertinya hanya di hosting anda. Banyak yang lain yang menjalankan 1.16 online tidak ada masalah.

Di file desa/config/config.php, coba ganti baris berikut:

`$config['enable_track'] = TRUE;
`
menjadi 
`$config['enable_track'] = FALSE;
`

**Comment by kelbatuix** [comment]
Sudah bisa dipasang mas dengan config yang mas berikan, mantap, trima kasih mas.

**Comment by eddieridwan** [comment]
Bagaimana dengan widgetnya?

**Comment by kelbatuix** [comment]
widgetnya sudah bisa mas, terima kasih. hanya masalah modsec yg blokir websitenya masih blum ketemu.
