### ISSUE TITLE
Sedikit Rubahan pada Layanan Mandiri dan Profil Penduduk di Layanan mandiri

### ISSUE THREAD

**Issue by metalab25** [eddieridwan/OpenSID#442]
Saya melakukan sedikit perubahan pada tampilan Layanan Mandiri dan Profil penduduk pada Layanan Mandiri agar terlihat lebih rapih semoga bisa diterapkan pada rilis berikutnya

Berikut ini tampilan hasil rubahan saya

![ubahan_layanan_mandiri](https://cloud.githubusercontent.com/assets/19917739/26677580/38379bd4-46ff-11e7-82d1-5a8b054fbf7c.jpg)

Ubahan yang saya lakukan terdapat pada file /donjo-app/views/widget/layanan_mandiri.php dan /themes/forlder_themes/partials/mandiri.php

Berikut file ubahannya
[layanan_mandiri.php.txt](https://github.com/eddieridwan/OpenSID/files/1044558/layanan_mandiri.php.txt)
[mandiri.php.txt](https://github.com/eddieridwan/OpenSID/files/1044557/mandiri.php.txt)

Semoga Bermanfaat

**Comment by metalab25** [comment]
Perubahan yang saya lakukan adalah merubah tampilan tabel biodata yang ada pada menu PROFIL di Layanan Mandiri dan perubahan tampilan pada menu-menu Layanan Mandiri

**Comment by eddieridwan** [comment]
Sudah di-merge pada PR #454.
