### ISSUE TITLE
USULAN : Daftar bantuan di layanan Mandiri

### ISSUE THREAD

**Issue by metalab25** [eddieridwan/OpenSID#443]
Akan sangat bermanfaat apabila didalam Layanan Mandiri ditambahkan daftar Bantuan yang didapat oleh Penduduk, jadi penduduk bisa mengetahui Bantuan apa saja yang didapatkannya.

Semoga usulan saya ini bisa diterapkan di rilis berikutnya.
Mungkin akan lebih mudah dipahami apabila saya sertakan gambar

![daftar_bantuan_layanan_mandiri](https://cloud.githubusercontent.com/assets/19917739/26678266/420cc5dc-4702-11e7-86c0-a476a92a64c9.jpg)

**Comment by dadannurman** [comment]
Mantap gan, bisa juga di tampilkan/cetak Data identitas kartu Bantuan nya (Jika ada)

**Comment by metalab25** [comment]
Memang seperti itu tujuannya

**Comment by metalab25** [comment]
Mungkin sementara hasilnya seperti ini berkat kontribusi @pandigresik 
![layanan_bantuan](https://user-images.githubusercontent.com/19917739/27000921-2914934a-4def-11e7-9133-eef3904e94f7.jpg)

**Comment by metalab25** [comment]
Hasil diskusi tentang issue ini adalah penduduk bisa cetak sendiri kartu peserta baik itu bantuan nasional atau pun bantuan skala desa.
Adapun bantuan nasional kartu pesertanya di scan oleh desa dan diupload ke dalam OpenSID dan ditampilkan di dalam menu bantuan Layanan desa.
Sedangkan untuk bantuan skala desa formatnya menyesuaikan kebutuhan mungkin bisa berupa resi atau keterangan bantuan penduduk

**Comment by eddieridwan** [comment]
Fitur dasar sudah di-merge ke master. Hanya untuk sasaran perorangan, dan hanya menampilkan id kartu peserta (tidak termasuk data identitas lainnya di kartu peserta).
