### ISSUE TITLE
Penambahan Link ke artikel di gambar Slide show besar

### ISSUE THREAD

**Issue by abdullah-sid** [eddieridwan/OpenSID#444]
Maaf sbelumnya,tanpa mengurangi rasa hormat saya, apa tidak sebaiknya yang ngelink ke artikel itu slide show besar. Karna slide show atas sudah di ganti oleh gambar background themenya mas happy agung.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.

Gambar yang ditampilkan di _slider header_ diambil dengan prioritas berikut:

1. Kumpulan gambar artikel yang dimasukkan ke slide (lihat [Panduan Pengelolaan Slide](Pengelolaan-Slide)).
2. Jika tidak ada artikel yang dimasukkan ke slide, tampilkan kumpulan gambar yang diambil dari [album galeri](Pengelolaan-Galeri).
