### ISSUE TITLE
Kosongkan statistik pengunjung

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#445]
Ketika pertama kali instal OpenSID, untuk statistik pengunjung seharusnya 0, mngkinnprrlu ada pasilitas kosongkan statistik pengunjung

**Comment by eddieridwan** [comment]
Bisa dikosongkan. Sudah termasuk di fitur _Kosongkan DB_ di menu _Database > Backup/Restore_. Fitur itu ikut mengosongkan tabel <em>sys_traffic</em> yang berisi statistik pengunjung.

Lihat panduan https://github.com/eddieridwan/OpenSID/wiki/Panduan-Administrasi-Database
