### ISSUE TITLE
pembuatan tulisan berjalan vertikal dari atad ke bawah pd widget komentar

### ISSUE THREAD

**Issue by abdullah-sid** [eddieridwan/OpenSID#447]
untuk memutakhirkan widget Komentar mohon untuk dibuat tulisan berjalan scra vertikal dari atas ke bawah yg tampil bergantian dari yg paling lama sampai yg terbaru, tujuannya agar komentar yg lain tidak hilang begitu saja dan tampilan lebih menarik Seperti breaking news

**Comment by eddieridwan** [comment]
Lampirkan solusi yang dibuat oleh Parso Widodo dan di-share oleh Abdul Laahh di FB.
[komentar.php.zip](https://github.com/eddieridwan/OpenSID/files/1056744/komentar.php.zip)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
