### ISSUE TITLE
log surat menghasilkan duplicate

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#448]
![tangkapan layar 2017-06-06 18 20 41](https://cloud.githubusercontent.com/assets/25834335/26830835/58a12b3a-4af4-11e7-885e-4ecec6ef2ec4.png)

**Comment by MUHAMMADRANGSEL** [comment]
Minta tolong para master untuk memperbaiknyq

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
