### ISSUE TITLE
menghilangkan kata tidak aman dibrowser website

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#449]
![tangkapan layar 2017-06-04 22 32 43](https://cloud.githubusercontent.com/assets/25834335/26833389/7d5ceea2-4afc-11e7-964b-db0a9d0b5beb.png)

**Comment by metalab25** [comment]
Pasang ssl (https) nya di website om Rarang, setingnya di cpanel

**Comment by MUHAMMADRANGSEL** [comment]
Kalau ada panduan lngkapnya mas happy

Pada tanggal 6 Jun 2017 22:42, "Happy" <notifications@github.com> menulis:

**Comment by metalab25** [comment]
Belum sempat buat panduannya karna panjang bgt stepnya

**Comment by eddieridwan** [comment]
Sebaiknya panduan dilengkapi dengan info penanganannya, @metalab25 @MUHAMMADRANGSEL

**Comment by metalab25** [comment]
Penanganan seperti apa bung @eddieridwan, kan sudah saya buat step” penerapan httpsnya

**Comment by eddieridwan** [comment]
Ok, kami sudah tambahkan info di https://github.com/eddieridwan/OpenSID/wiki/Tanya-Jawab-Install-dan-Update dan menambahkan judul di https://github.com/eddieridwan/OpenSID/wiki/Panduan-Menginstall-SID-di-Hosting-Web.

Terima kasih telah membuat panduan.
