### ISSUE TITLE
Widget Sosial Media Terintegrasi dengan icon Media Sosial di Menu Atas Tema Hadakewa

### ISSUE THREAD

**Issue by metalab25** [eddieridwan/OpenSID#455]
Mohon dibuatkan script sosial media agar hanya 1 kali input melalui widget tapi juga URL Linknya juga terpasang pada menu atas tema Hadakewa
![sosmed](https://user-images.githubusercontent.com/19917739/26969583-d81315cc-4d38-11e7-9557-ff3a5fd96f5e.jpg)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
