### ISSUE TITLE
Tampilkan gambar utama artikel saja di slider-besar

### ISSUE THREAD

**Issue by afri18** [eddieridwan/OpenSID#456]
saya kira di realeas 1.17 slider yg besar hanya menampilkan gambar utama dari setiap artikel ehh ternyata tidak, jadi saya usulkan sebaiknya slider yg besar auto menampilkan gambar artikel sebanya 10 terbaru saja, tujuan biar nggak bentrok gambarnya dengan slide atas yang kecil
![image](https://user-images.githubusercontent.com/6611881/26970562-0cb08ae4-4d34-11e7-941a-1e1732b2b183.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
Sekarang slider besar menampilkan gambar utama 10 artikel terbaru saja.
