### ISSUE TITLE
Review Surat Keterangan kelahiran & Permohonan Akta Kelahiran

### ISSUE THREAD

**Issue by fathurvbf** [eddieridwan/OpenSID#459]
Mas @eddieridwan setelah penerapan form surat keterangan lahir & permohonan Akta kelahiran di SID ada beberapa yg kurang mas, jka memungkinkan kita bisa lengkapi seperti ini mas secara bersama dengan kawan2. Ini yang berlaku dari ducapil mas. Biasanya kita tulis secara manual tpi kalau kita bsa terapkan di SID mungkin lebih efektif semua mas dan Open SID akan terus menjawab kebutuhan dari Desa.  
![surat keterangan kelahiran](https://user-images.githubusercontent.com/26631297/26999942-6d431c6e-4dcf-11e7-9479-12d7c053b8fc.jpg)
![permohohan akta kelahiran](https://user-images.githubusercontent.com/26631297/26999958-bdcdbf5e-4dcf-11e7-832a-03a77c27dfc3.jpg)

**Comment by fathurvbf** [comment]
Bung @eddieridwan   mohon petunjuknya saya mau coba belajar lengkapi form surat Keterangan Kelahiran 	S-17, dimana nanti hasil nanti adalah sperti format laporan diatas. 
Saya Mau tanya, model perbaikannya nanti dibuat baru dan hasilnya tersimpan di folder desa/surat/foldernamasurat atau saya rubah lansung dimaster form surat yang tersedia begitu jga hasil laporannya.

**Comment by eddieridwan** [comment]
Langkah yang dapat anda lakukan:

1. salin semua isi folder surat/surat_ket_kelahiran ke folder desa/surat/surat_ket_kelahiran
2. buat perubahan yang diperlukan pada berkas di folder desa/surat/surat_ket_kelahiran
3. kirim hasil anda, folder desa/surat/surat_ket_kelahiran untuk di-review oleh calon pengguna

**Comment by fathurvbf** [comment]
@eddieridwan  siap om.

**Comment by eddieridwan** [comment]
Sudah dicommit melalui pull request https://github.com/eddieridwan/OpenSID/issues/488.
