### ISSUE TITLE
Report OpenSID pasca 1.17

### ISSUE THREAD

**Issue by metalab25** [eddieridwan/OpenSID#462]
Bung Eddie Ridwan pada pasca 1.17 setting aplikasi blank.
Langkah" sudah sesuai
![2017-06-11](https://user-images.githubusercontent.com/19917739/27012162-60db5b38-4efd-11e7-94b2-1b40cc9743ef.png)

**Comment by MUHAMMADRANGSEL** [comment]
sama saya juga mengalami hal yang sama mas happy

**Comment by eddieridwan** [comment]
Untuk melacak masalahnya (di demo http://sid.bangundesa.info normal saja), coba ganti baris di index.php

```	
        // define('ENVIRONMENT', 'development');
	define('ENVIRONMENT', 'production');
```
menjadi

```	
        define('ENVIRONMENT', 'development');
	// define('ENVIRONMENT', 'production');
```
Kemudian harap laporkan error yang ditampilkan.

**Comment by metalab25** [comment]
Sepertinya Mas Wid juga mengalami hal yang sama

**Comment by eddieridwan** [comment]
Coba ganti donjo-app/views/setting/setting_form.php dengan file berikut (di-extract dulu):

[setting_form.php.zip](https://github.com/eddieridwan/OpenSID/files/1067551/setting_form.php.zip)

**Comment by metalab25** [comment]
bung @eddieridwan silahkan cek di file setting_form.php pada line 35
disana saya udah dari ` <? endif;  ?>` menjadi ` <?php endif;  ?>` dan itu berhasil menggunakan file setting_form.php yang baru

**Comment by MUHAMMADRANGSEL** [comment]
Mantap mas happy

Pada tanggal 12 Jun 2017 18:27, "Happy" <notifications@github.com> menulis:

**Comment by metalab25** [comment]
Perlu perbaikan tema hadakewa dalam versi ini, nanti akan saya PR lagi bung @eddieridwan

**Comment by eddieridwan** [comment]
Ok, sepertinya PHP 5.5 tidak seteliti 5.6. Di 5.6 error itu least saja. Trims sdh menemukan.

**Comment by metalab25** [comment]
perlu saya PR apa bung @eddieridwan  yang ubah ?

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
