### ISSUE TITLE
Penataan ulang style/css tema hadakewa

### ISSUE THREAD

**Issue by eddieridwan** [eddieridwan/OpenSID#466]
Saat ini di folder desa-contoh/css/hadakewa, ada beberapa file css:

1. front/default.css
2. front/first.css
3. desa-default.css
4. desa-web.css

Tambahan pula, isi file css di atas mengulangi style yang ada di file inti:

1. assets/front/css/first.css
1. assets/front/css/default.css

Tumpang tindih styles ini menyebabkan kerancuan, dan kesulitan untuk melacak style yang mana yang diberlakukan oleh browser. Dan mungkin juga server/browser berbeda dalam penanganannya, sehingga berbeda penampilan.

Supaya lebih mudah dikelola/dikembangkan, perlu dilakukan perombakan sebagai berikut:

1. gabung ke-empat file css tersebut, menjadi dua file saja:
    1. css/hadakewa/desa-default.css
    2. css/hadakewa/desa-web.css
2. ke dua file tersebut supaya **TIDAK** mengulangi styles yang ada di file inti, tetapi **HANYA** berisi **PERUBAHAN** yang diperlukan atas styles yang ada di assets/front/css/first.css dan assets/front/css/default.css

**Comment by eddieridwan** [comment]
Sesudah issue ini selesai, nanti saya akan gabungkan style/css tema hadakewa ke file inti di folder _themes/hadakewa_ sehingga yang tinggal di folder _desa_ hanya yang diperlukan untuk penyesuaian oleh desa, seperti gambar background. Karena folder desa tujuannya untuk penyesuaian oleh desa, sedangkan folder desa/css/tema saat ini lebih berperan sebagai style dasar tema, bukan penyesuaian oleh desa.

**Comment by metalab25** [comment]
berarti saya harus menggabungkan file front/first.css dan hadakewa/desa-web.css menjadi 1 css yaitu hadakewa/desa-web.css dan menggantikan fungsi assets/front/css/first.css

**Comment by metalab25** [comment]
On Progress

**Comment by eddieridwan** [comment]
Yang dimasukkan ke hadakewa/desa-web.css hanya styles yang mengubah assets/front/css/first/css. Jangan mengulangi styles yang sudah ada. 

Jadi seharusnya hadakewa/desa-web.css singkat saja, tidak men-duplikasi assets/front/css/first/css.

Langkah yang saya rekomendasikan:

1. hapus semua file css yang ada di css/hadakewa sekarang (salinannya ada di desa-contoh).
2. buat hadakewa/desa-web.css baru dan masukkan **PERUBAHAN** styles  assets/front/css/first.css yang diperlukan saja (jangan diulangi)
3. buat hadakewa/default-web.css baru dan masukkan **PERUBAHAN** styles assets/front/css/default.css yang diperlukan saja (jangan diulangi)

**Comment by metalab25** [comment]
Metode yang saya gunakan adalah class" yang digunakan pada first.css saya pindahkan ke desa-web.css
Apakah metode seperti itu bisa saya terapkan ?

**Comment by eddieridwan** [comment]
Lampirkan contoh yg sedang dikerjakan. Prinsipnya hanya tambahkan css seperlunya, se-minim mungkin.

**Comment by metalab25** [comment]
Bung @eddieridwan ini saya lampirkan hasil penataan ulanh css tema hadakewa, mohon di review
Lampiran link dibawah ini 
[http://www.opensid.info/penataan_css_tema_hadakewa.zip](http://www.opensid.info/penataan_css_tema_hadakewa.zip)

**Comment by eddieridwan** [comment]
@metalab25 itu masih men-duplikasi styles inti. 

Coba lihat contoh yang seperti saya lampirkan berikut. Di situ terlihat di folder hadakewa hanya ada dua file css (desa-web.css dan desa-default.css). Saya baru beri contoh desa-web.css yang fungsinya untuk mengubah styles yang ada di assets/front/css/first.css.

Contoh itu baru menunjukkan perubahan untuk menampilkan #footer sesuai dengan tema hadakewa. Jadi cukup hanya mengubah warna saja.

Juga contoh untuk mulai mengubah #topsection, di mana yang perlu diubah hanya background, height dan margin-left.

Silakan meneruskan! Silakan bertanya jika masih kurang jelas. 

[hadakewa.zip](https://github.com/eddieridwan/OpenSID/files/1072800/hadakewa.zip)

**Comment by metalab25** [comment]
bung @eddieridwan mohon di review lagi apakah yang ini sudah benar

Lampiran 
[www.opensid.info/penataan_hadakewa.zip](www.opensid.info/penataan_hadakewa.zip)

**Comment by eddieridwan** [comment]
Bung @metalab25 , filenya tidak ada. Coba lampirkan lagi.

**Comment by metalab25** [comment]
Sudah saya perbaiki URL Lampirannya bung @eddieridwan , silakan diperiksa kembali

**Comment by eddieridwan** [comment]
@metalab25 : sudah hampir.. berikut ini saya lampirkan css anda dengan perubahan:

1. menambah keterangan di atas setiap file
2. mengubah ejaan 'merubah' menjadi 'mengubah'
3. memindahkan style untuk #footer dari desa-default.css ke desa-web.css
4. memindahkah style untuk #siteTitle agar terkelompok dalam desa-web.css

Tetapi masih ada yang anda perlu sempurnakan:

1. #siteTitles masih ada di desa-web.css, walaupun tidak ada element dengan id itu (mungkin di footer versi dulu?). Sebaiknya dihilangkan.
2. cek sekali lagi -- apakah ada styles lainnya yang tidak digunakan lagi (seperti #siteTitles) -- kalau ada sebaiknya dihapus.
3. cek style untuk id/class yang sama supaya dikelompokkan (tidak terpisah-pisah di dalam file)

[hadakewa.zip](https://github.com/eddieridwan/OpenSID/files/1075786/hadakewa.zip)

**Comment by metalab25** [comment]
Bung @eddieridwan , sudah saya periksa. 
Terimakasih atas bimbingannya.

Dibawah ini saya lampirkan sytle yang sudah saya periksa dan saya fix
[http://www.opensid.info/penataan_hadakewa_fix.zip](http://www.opensid.info/penataan_hadakewa_fix.zip)
Silahkan dicommit

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.

**Comment by DITOO91** [comment]
bg mohon maaf mau tanya kenapa file css saya tidak terbaca saat sudah saya hosting di github?
