### ISSUE TITLE
Tampilkan/cetak Data identitas kartu Bantuan di Layanan Mandiri

### ISSUE THREAD

**Issue by eddieridwan** [eddieridwan/OpenSID#468]
Dari @metalab25 : ( lihat #443  )
![layanan_bantuan](https://user-images.githubusercontent.com/19917739/27000921-2914934a-4def-11e7-9133-eef3904e94f7.jpg)

**Comment by eddieridwan** [comment]
@metalab25 :
Hasil diskusi tentang issue ini adalah penduduk bisa cetak sendiri kartu peserta baik itu bantuan nasional atau pun bantuan skala desa.
Adapun bantuan nasional kartu pesertanya di scan oleh desa dan diupload ke dalam OpenSID dan ditampilkan di dalam menu bantuan Layanan desa.
Sedangkan untuk bantuan skala desa formatnya menyesuaikan kebutuhan mungkin bisa berupa resi atau keterangan bantuan penduduk

**Comment by metalab25** [comment]
Benar sekali bung @eddieridwan. Mohon dibuatkan seperti permintaan digambar. Maaf kalo ini saya tidak bisa PR

**Comment by metalab25** [comment]
Sepertinya issue ini belum dapat prioritas yah bung eddie.
Mohon maaf kalo untuk issue ini saya ga bisa PR

**Comment by eddieridwan** [comment]
Scan kartu peserta bisa diunggah dan ditampilkan di halaman bantuan di layanan mandiri.

Sudah dicommit ke master.
