### ISSUE TITLE
Tugas dapur: upgrade fontawesome ke versi 4.6.x

### ISSUE THREAD

**Issue by eddieridwan** [eddieridwan/OpenSID#47]
Versi fontawesome yang dipergunakan saat ini versi 3.2.1. Versi baru menyediakan icon yang lebih terkini, misalnya untuk sosmed seperti google plus.

Untuk memanfaatkan icon baru, fontawesome perlu diupgrade, unduh dari http://fontawesome.io/.

**Comment by metalab25** [comment]
heheheheh.... kalo saya udah duluan beberapa hari yang lalu

**Comment by eddieridwan** [comment]
@metalab25, apakah anda sudah mengubah semua script berbentuk seperti ini 
`<i class="icon-gear icon-large">` 
ke dalam bentuk ini
`<i class="fa fa-gear fa-lg">` ?

Dan juga menggantikan nama icon seperti dijelaskan di:
https://github.com/FortAwesome/Font-Awesome/wiki/Upgrading-from-3.2.1-to-4 ?

Kalau sudah, mohon buat pull request untuk perubahan yang telah dilakukan. Daripada mengulang.. :)

**Comment by metalab25** [comment]
sudah om cuma memang ada beberapa yang tidak bisa digunakan seperti fa-commenting dan ada beberapa lainnya tidak bisa digunakan

**Comment by eddieridwan** [comment]
Sudah dicommit melalui PR https://github.com/eddieridwan/OpenSID/pull/482
