### ISSUE TITLE
[teknis] Konversi icon jquery-ui ke font-awesome 4.7.0

### ISSUE THREAD

**Issue by eddieridwan** [eddieridwan/OpenSID#477]
Pull request https://github.com/eddieridwan/OpenSID/pull/476 telah mengupgrade font-awesome ke 4.7.0. 

Supaya penggunaan icon konsisten secara menyeluruh, penggunaan icon jquery-ui perlu diganti dengan icon font-awesome.

Sebagai contoh:

1. mengganti `class="ui-icon ui-icon-triangle-1-n"` dengan class="fa fa-sort-asc"
2. mengganti `class="ui-icon ui-icon-triangle-2-n-s"` dengan class="fa fa-sort"
dstnya.

Issue ini untuk dikerjakan sesudah PR #476 selesai di-merge (sesudah rilis 2.0).

**Comment by metalab25** [comment]
Akan saya coba kerjakan, apa bisa digabung dengan PR update Font Awesome

**Comment by eddieridwan** [comment]
Tidak, karena sudah saya proses, dan buat perubahan.
Tunggu saja, sesudah rilis 2.0 dan sesudah saya merge PR #476.

**Comment by eddieridwan** [comment]
@metalab25 , ok sudah siap untuk anda buat PR.

**Comment by metalab25** [comment]
On progress

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR https://github.com/eddieridwan/OpenSID/pull/482.
