### ISSUE TITLE
Menyeragamkan icon di tombol Simpan, Reset, Tutup dll..

### ISSUE THREAD

**Issue by eddieridwan** [eddieridwan/OpenSID#478]
Pull request #476 telah mengupgrade font-awesome ke 4.7.0.

Supaya penggunaan icon pada tombol konsisten secara menyeluruh, perlu dilakukan:

1. warna icon dengan later belakang biru tua perlu diubah supaya lebih tampak
2. tombol di modal dialog perlu diberi icon.

Sebagai contoh:

1. di modal dialog _SID Home > Identitas Desa > Wilayah Desa_, ada dua tombol _Reset_ dan _Simpan_ yang perlu ditambahi icon
2. di modul dialog _Penduduk > Penduduk > Pencarian Spesifik_, ada dua tombol _Close_ dan _Search_ yang perlu ditambahi icon (sekaligus ubah _Close_ menjadi _Tutup_).
3. dstnya.

Issue ini untuk dikerjakan sesudah PR #476 selesai di-merge (sesudah rilis 2.0).

**Comment by metalab25** [comment]
Nanti akan daya coba kerjakan dengan mengganti sekalian ke button bootsrap agar lebih bagus

**Comment by eddieridwan** [comment]
@metalab25 , ok sudah siap untuk anda buat PR.

**Comment by metalab25** [comment]
On progress

**Comment by metalab25** [comment]
"warna icon dengan later belakang biru tua perlu diubah supaya lebih tampak"
mau di ganti warna apa iconnya

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR https://github.com/eddieridwan/OpenSID/pull/482.
