### ISSUE TITLE
[tugas-dapur] Seragamkan tombol aksi di menu Plan

### ISSUE THREAD

**Issue by eddieridwan** [eddieridwan/OpenSID#483]
Setelah konversi font-awesome ke versi 4.7.0, masih ada halaman yang penyeragaman icon belum sempurna.

Di menu Plan, tombol aksi di halaman berikut perlu dibenahi:

1. Plan > Lokasi
2. Plan > Tipe Point
3. Plan > Garis
4. Plan > Tipe Garis
5. Plan > Area
6. Plan > Tipe Polygon

Contoh: 
<img width="965" alt="seragamkan-tombol-aksi" src="https://user-images.githubusercontent.com/249563/27503180-54037b7e-58bd-11e7-8697-9164ae7106b4.png">

**Comment by eddieridwan** [comment]
Bung @metalab25: apakah bisa buat PR untuk issue ini?

**Comment by metalab25** [comment]
On Progress

**Comment by eddieridwan** [comment]
Terima kasih. Jangan lupa: (1) hindari inline style (2) kalau perlu tambah style di siteman_styles.css

**Comment by metalab25** [comment]
![2017-06-24](https://user-images.githubusercontent.com/19917739/27508940-595122aa-5923-11e7-9f2f-77729d0a424e.png)
![2017-06-24 1](https://user-images.githubusercontent.com/19917739/27508942-5f74aeea-5923-11e7-9570-c7ed9dad9958.png)
![2017-06-24 2](https://user-images.githubusercontent.com/19917739/27508944-5fbf7376-5923-11e7-955a-a33fba9ef6f9.png)
![2017-06-24 3](https://user-images.githubusercontent.com/19917739/27508943-5faeb568-5923-11e7-85b4-a39b40b44af2.png)
![2017-06-24 4](https://user-images.githubusercontent.com/19917739/27508945-5fea5cf8-5923-11e7-84a3-869361ee66b3.png)
![2017-06-24 5](https://user-images.githubusercontent.com/19917739/27508946-5fed35d6-5923-11e7-9fc8-82e5dbbc8fe9.png)
![2017-06-24 6](https://user-images.githubusercontent.com/19917739/27508947-5fedfcdc-5923-11e7-950e-2a815e7dbbd6.png)
![2017-06-24 7](https://user-images.githubusercontent.com/19917739/27508948-6002ceb4-5923-11e7-9db6-8883fb531c15.png)
![2017-06-24 8](https://user-images.githubusercontent.com/19917739/27508949-604258ae-5923-11e7-880a-c56c822349ba.png)

**Comment by metalab25** [comment]
Ini sudah dimerger kok ga di close bung eddie

**Comment by eddieridwan** [comment]
Sudah dicommit melalui PR #484.
