### ISSUE TITLE
Bugs konversi kode kolom cacat pada tampilan data didalam layanan Mandiri

### ISSUE THREAD

**Issue by Jhiban-Khang** [eddieridwan/OpenSID#487]
Tampilan data pada halaman biodata setelah masuk dalam layanan mandiri, kode cacat masih dalam bentuk angka, tidak dikonversi ke dalam tulisan.

**Comment by metalab25** [comment]
Script php  kolom isiian cacat pada biodata tersebut harusnya bukan panggil id tapi panggil nama, saya pernah coba hal tersebut

**Comment by eddieridwan** [comment]
Terima kasih telah melaporkan. Lebih hebat lagi, jika langsung buatkan pull-requestnya.

Sudah dicommit ke master.
