### ISSUE TITLE
Pemisahan table menu database

### ISSUE THREAD

**Issue by metalab25** [eddieridwan/OpenSID#490]
Bung @eddieridwan, saat ini saya sedang mencoba membuat top menu opensid menjadi responsive dengan bootsrap, namun saya mengalami kendala karna panggilan menu dari tabel menu database yang isinya antara menu dan sub menu menjadi satu tabel.
Bisa ga dibuatkan antara menu dengan sub menu menjadi 2 tabel terpisah agar mempermudah penerapan tampilan resposive bootsrap.
Untuk metode timbal balik pasti akan saya berikan yang penting diterapkan

**Comment by eddieridwan** [comment]
Penampilan web responsif tidak terpengaruh oleh struktur database. Yang menentukan hanya html/css.

Jika diperlukan perombakan yang besar/rumit, sebaiknya dilakukan sebagai bagian dari rancangan OpenSIDWeb. 

Tetapi jika anda tidak sabar dan ingin menyesuaikan tema yang ada, silakan jelaskan persisnya apa yang anda sedang coba, and sebaiknya dibahas dengan pengembang lainnya, seperti bung Herman, Ahmad Afandi dan Hadyan.

Anda dapat lakukan dengan membuat _branch_ khusus di github anda di https://github.com/metalab25/OpenSID berisi script yang anda sedang kembangkan. Kemudian ajak teman2 lain untuk me-review script anda dan membantu.

**Comment by eddieridwan** [comment]
Nanti kalau sudah berhasil, bisa digabungkan ke rilis OpenSID resmi melalui pull request dari branch anda tersebut.

Kami akan tutup issue ini, karena permintaan memisahkan tabel menu dan sub-menu tidak ada kaitannya dengan mengembangkan web responsif.
