### ISSUE TITLE
DPT

### ISSUE THREAD

**Issue by noefa86** [eddieridwan/OpenSID#495]
Salam para master, karena saya gak mudeng pemrograman, sy bisanya hanya request, kali aja disetujui. Hehe. Begini, kalau musim Pilkades, Pilbup, Pilgup, Pilpres dsb, sangat butuh sekali seleksi data penduduk untuk penentuan DPT. Di modul penduduk memang sudah ada fitur pencarian spesifik berdasarkan umur, tp umurnya didasarkan pada tanggal sekarang, bukan tanggal tertentu (misal tgl pemilu) Sekaligus ada tombol export DPT (excel). Mudah2an fitur ini bisa dikabulkan sehingga operator data di desa bisa dimudahkan saat penyelenggaraan pemilu.

**Comment by eddieridwan** [comment]
Duplikat #503. Issue ini ditutup karena #503 sudah dilengkapi dengan syarat dan ketentuan.
