### ISSUE TITLE
SLIDER BESAR

### ISSUE THREAD

**Issue by afri18** [eddieridwan/OpenSID#496]
sebaiknya menampilkan 10 artikel teratas dan yg mempunyai gambar utama secara auto/langsung
slider yg sekarang sepertinya gambar utama artikel aja yg sudah di slide
![image](https://user-images.githubusercontent.com/6611881/27984461-94cfa17a-6400-11e7-8064-9fb9132e5fac.png)

**Comment by eddieridwan** [comment]
Sediakan pilihan sumber gambar slider.

<img width="997" alt="pilihan-sumber-gambar-slider" src="https://user-images.githubusercontent.com/249563/28003394-8ecd7ac8-6580-11e7-9c6e-62798dc50e75.png">

Sudah dicommit ke master.

**Comment by afri18** [comment]
mantaab .. dah ane coba

**Comment by onhar11** [comment]
gan nya ane kok dak muncul gambar di artikel

**Comment by afri18** [comment]
kalau gambar utama ada pasti muncul, sudah di migrasi belum data base nya ??
