### ISSUE TITLE
Surat kematian sebaiknya mengarah ke data log penduduk

### ISSUE THREAD

**Issue by afri18** [eddieridwan/OpenSID#498]
bila issue #497 maka surat kematian saat diisi nama/nik langsung mengarah kedata logpenduduk

**Comment by eddieridwan** [comment]
Untuk mengerjakan issue ini, kita perlu matangkan dulu proses pendataan terkait perubahan status dasar penduduk akibat kematian.

Kalau yang meninggal adalah penduduk yang anggota KK, dan bukan kepala keluarga, proses yg kami usul untuk diterapkan adalah:

1. ubah status dasar penduduk tsb menjadi mati
2. peristiwa perubahan status dasar tersebut direkam di tabel log_penduduk
3. data penduduk tersebut masih tersimpan di tabel tweb_penduduk, dengan status dasar 'mati'
4. pembuatan Surat Keterangan Kematian akan mengambil data penduduk tersebut dari daftar penduduk dengan status dasar 'mati'.

Langkah (1) s/d (3) di atas adalah yang sudah berlaku di semua versi OpenSID sejak dari SID 3.04. Langkah yg baru hanya langkah (4).

Kalau yang meninggal adalah kepala keluarga, kita perlu merujuk pada proses administrasi yang berlaku: http://www.hukumonline.com/klinik/detail/lt55f7d81c1f253/orang-tua-meninggal-dunia--haruskah-perbaharui-kartu-keluarga.

Yaitu, kartu keluarga yg ada akan di-pensiunkan, dan anggota keluarga yang tinggal perlu dibuatkan kartu keluarga baru.

Proses yang kami usulkan adalah sebagai berikut:

1. ubah status dasar kepala keluarga tsb menjadi mati
2. peristiwa perubahan status dasar tersebut direkam di tabel log_penduduk
3. data penduduk tersebut masih tersimpan di tabel tweb_penduduk, dengan status dasar 'mati'
4. data keluarga (di tabel tweb_keluarga) diubah statusnya menjadi 'mati'
5. peristiwa perubahan keluarga tersebut direkam di tabel log_keluarga
6. pembuatan Surat Keterangan Kematian akan mengambil data kepala keluarga tersebut dari daftar penduduk dengan status dasar 'mati'.

Langkah (1), (2), (3) adalah seperti yang sudah berlaku selama ini. Yang baru adalah langkah (4), (5) dan (6).

Yang penting diperhatikan dengan usulan di atas adalah:

1. data penduduk dan data keluarga tidak dihapus, hanya diubah statusnya menjadi 'mati. Dengan demikian, data tersebut bisa disembunyikan dari tampilan Penduduk dan Keluarga, tetapi masih tetap ada untuk diambil dan ditampilkan pada proses yang memerlukan (seperti Surat Keterangan Kematian)
2. log_penduduk hanya perlu menyimpan data peristiwa perubahan status dasar (tgl kejadian, keterangan, dsbnya), tetapi tidak perlu menyalin data penduduk atau keluarga (karena masih tersimpan).

**Comment by bhien76** [comment]
Usulan bang @eddieridwan tentang surat kematian diatas sudah tepat. jadi, siapapun yg meninggal baik itu Kepala Keluarga atau anggota keluarga, datanya tetap tersimpan di tweb penduduk dan tweb keluarga. jadi pada saat pembuatan keterangan kematian, data tersebut yang diambil. kalau untuk perubahan kartu keluarga. kalau yg meninggal kepala keluarga, maka salah satu anggota keluarga dirubah posisinya menjadi kepala keluarga. dalam hal ini isteri atau anak tertua yang ada didalam kartu keluarga. jadi nomor kartu keluarga tidak berubah

**Comment by afri18** [comment]
Kalau menurut pendapat saya penduduk yg mati di pindahkan seluruh datanya termasuk no kk di suatu table (sebut saja tweb_mati) dan datanya di hapus dari table tweb penduduk dengan alasan : 
dengan terpisahnya data yg mati maka kita dapat menginventarisir/memasukan data kematian sebelum memakai SID/OPENSID,

**Comment by eddieridwan** [comment]
@afri18 @bhien76 : bukankan menurut aturan, jika kepala keluarga meninggal, nomor kartu keluarga HARUS diganti? Yaitu tidak boleh hanya diubah kepala keluarganya, tetapi harus ganti kartu keluarga baru sama sekali?

**Comment by eddieridwan** [comment]
@afri18 : untuk kebutuhan '_menginventarisir/memasukan data kematian sebelum memakai SID/OPENSID_' silakan buatkan issue baru. Penerapannya bisa saja tanpa harus ada tabel khusus.

**Comment by eddieridwan** [comment]
Sudah diterapkan mengikuti usulan di atas. 
Sudah dicommit ke master.

**Comment by bhien76** [comment]
kalau di kabupaten kami seperti itu bang @eddieridwan, nomor kartu keluarga tidak berubah. hanya perubahan salah satu anggota keluarga menjadi kepala keluarga saja

**Comment by bhien76** [comment]
bang @eddieridwan, saya sudah coba surat keterangan kematian di sid.bangundesa.info. sudah ok, datanya diambil dari log penduduk. tapi masih ada beberapa yg harus diperbaiki.
1. Kalau yang meninggal Kepala Keluarga atau Isteri, sebaiknya data ayah dan ibunya, selain nama, yang lain tidak harus diisi, jadi biar kosong tidak apa2. dengan pertimbangan bahwa bisa saja kalau kepala keluarga yg meninggal umurnya diatas 50 tahun, bisa jadi orang tuanya jg sdh meninggal duluan, jadi daatanya tdk ada kecuali nama
2. Pada lampiran F-2.29, tgl kematian harus diperbaiki. saya masukkan tgl kematiannya hari ini 05-10-207, tp yg muncul di lamriran tgl 31-12-1969
3. Penanda tangan surat kasih sama modelnya dengan surat keterangan kelahiran. jadi, yg dipilih di form, itu yang masuk di lampiran. kalau sekarang, penanda tangan dikunci dengan nama kepala desa
![format surat kematian](https://user-images.githubusercontent.com/28255642/31230318-45444636-aa16-11e7-9b82-4f5367721171.jpg)
![tgl kematian](https://user-images.githubusercontent.com/28255642/31230354-5d2a32ec-aa16-11e7-85c0-2c1e48ae2cd1.jpg)
![penanda tangan](https://user-images.githubusercontent.com/28255642/31230388-6d2e6794-aa16-11e7-8fe2-3e116bdb41c5.jpg)
