### ISSUE TITLE
Tambah laporan Daftar Pemilih Tetap (DPT) berdasarkan tanggal pemungutan suara

### ISSUE THREAD

**Issue by afri18** [eddieridwan/OpenSID#503]
sediakan tombol calon daftar pemilih di menu PENDUDUK dengan kriteria :
saat tombol di diklik ada form tanggal pencoblosan (hari tanggal pemilihan) , bila telah terisi maka tinggal klik tmbol tampilkan
maka data tersaji persis seperti data penduduk
bisa nggak ya ??
![image](https://user-images.githubusercontent.com/6611881/28053668-d769a0fc-663b-11e7-8c15-d390d61adba5.png)

ma'af ane cuma bisa buat issue, nggak bisa mengerjakan
data yg ditampilka adalah usia 17 tahun saat pencoblosan dan yang berstatus kawin terdiri dari, nama,nik,nokk,tempatlahir,tgllahir,alamat,rt,rw
sekaligus bisa cetak excel dengan format text

**Comment by eddieridwan** [comment]
Bung @afri18, sepertinya ketentuan yang diperlukan adalah:

".....usia 17 tahun saat pencoblosan **ATAU** yang status kawinnya **bukan "BELUM KAWIN"** (jadi yang KAWIN, CERAI HIDUP, atau CERAI MATI) .....".

"Pasal 27 ayat (1) UU Pilpres yang berbunyi, “Warga Negara Indonesia yang pada hari pemungutan suara telah genap berumur 17 tahun atau lebih atau sudah/pernah kawin mempunyai hak memilih.” Sedangkan Pasal 19 ayat (1) UU Pemilu Legislatif berbunyi, “Warga Negara Indonesia yang pada hari pemungutan suara telah genap berumur 17 (tujuh belas) tahun atau lebih atau sudah/pernah kawin mempunyai hak memilih.”

**Comment by eddieridwan** [comment]
UU 32/2004 Tentang Pemerintahan Daerah:

Pasal 68: "Warga negara Republik Indonesia yang pada hari pemungutan suara pemilihan kepala daerah dan wakil kepala daerah sudah berumur 17 (tujuh belas) tahun atau sudah/pernah kawin mempunyai hak memilih."

**Comment by eddieridwan** [comment]
Dari #495, @noefa86: laporan DPT ini digunakan untuk Pilkades, Pilbup, Pilgup, Pilpres dsb., dengan asumsi syarat pemilih sama untuk semua jenis pemilihan umum.

**Comment by afri18** [comment]
betul bung eddieridwan yg statusnya belum kawin

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
