### ISSUE TITLE
Usul : penambahan switch komentar.

### ISSUE THREAD

**Issue by Jhiban-Khang** [eddieridwan/OpenSID#506]
usul penambahan pengaturan komentar, yakni memungkinkan untuk men disable atau enable form komentar pada setiap artikel. ini memberikan keluasaan admin untuk mengatur apakah akan disediakan form komentar atau tidak pada semua artikel. seperti pada fasilitas wordpress.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
