### ISSUE TITLE
Bug pra 2.2 Penggantian nama dusun

### ISSUE THREAD

**Issue by metalab25** [eddieridwan/OpenSID#509]
Pada OpenSID Pra Rilis 2.2 terdapat bug yaitu pada saat nama dusun diganti pada Wilayah Administrasi namun pada data penduduk Nama Dusun tidak berubah.
Bung @eddieridwan mohon di cek apakah hal ini cuma terjadi pada http://demosid.opensid.info dan http://sid.bangundesa.info

**Comment by eddieridwan** [comment]
Masalah ini sudah ada sejak zaman SID 3.04. Aneh baru sekarang ada yang melaporkan.

Ok, sudah diperbaiki. Ada di versi pra-rilis.
