### ISSUE TITLE
BUG : Alert pada static widget Layanan Mandiri

### ISSUE THREAD

**Issue by metalab25** [eddieridwan/OpenSID#51]
Saya mencoba menggunakan Layanan Mandiri dengan data yang salah, hasilnya muncul notifikasi salah cuma setelah di refresh, di closeberulang" notifikasi tersebut tidak hilang terlihat seperti di gambar

![bug1](https://cloud.githubusercontent.com/assets/19917739/16194015/f0831222-3724-11e6-8fe9-6981e0e8c257.jpg)

**Comment by eddieridwan** [comment]
@metalab25, ini terjadi pada OpenSID versi berapa? Ataukah di versi SID CRI lain? Masalah ini tidak ditemukan di OpenSID v0.9.2.

Saya akan tutup issue ini. Silakan buat issue baru apabila ada masalah lain.
