### ISSUE TITLE
Seragamkan hasil cetak dan export excel

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#510]
Perlu diseragamkan di menu keluarga hasil cetak dgn export excel supya lebih mantap. 
Adapun hasil export excel perlu diseragamkan dengan cetak nya.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.

Terima kasih pada @MUHAMMADRANGSEL dan @metalab25 untuk https://github.com/eddieridwan/OpenSID/pull/521. PR itu tidak jadi digunakan, karena yang dilakukan adalah:

1. Menggunakan file yang sama (_print.php) untuk cetak dan export excel, supaya tidak duplikasi
2. Memperbaiki agar nomor KK and NIK tampil sebagai text di Excel
3. Mengubah supaya favicon tampil di halaman cetak
