### ISSUE TITLE
Kolom Peserta Bantuan pada Form tidak otomatis terisi setelah pilih peserta

### ISSUE THREAD

**Issue by metalab25** [eddieridwan/OpenSID#514]
Kolom-kolom isian Identitas Pada Kartu Peserta tidak terisi otomatis setelah pilih peserta penerima bantuan. 
Sudah dicoba juga pada OpenSID demo di http://sid.bangundesa.info namun tetap sama
OpenSID v.2.2
![2017-07-21](https://user-images.githubusercontent.com/19917739/28464363-606de714-6e57-11e7-990f-364b6e40dfc6.jpg)

**Comment by eddieridwan** [comment]
Tidak diisi otomatis karena kolom2 itu diambil dari kartu peserta yang datanya sering berbeda dengan yang ada di database SID. Silakan lihat issue asli pembuatan fitur ini.  Atau tanya pada bung Rarang Selatan. (@ MUHAMMADRANGSEL). Jadi hanya bisa diisi manual dengan menyalin dari kartu peserta.

**Comment by eddieridwan** [comment]
Form itu justru untuk merekam data dari kartu peserta supaya bisa disimpan di tabel program_peserta.
