### ISSUE TITLE
NIP Pamong dalam mode cetak surat

### ISSUE THREAD

**Issue by metalab25** [eddieridwan/OpenSID#517]
NIP Pamong tidak muncul apabila surat di eksekusi dengan langsung cetak, tapi apabila di eksekusi dengan export NIP sudah muncul.
Apakah ini bug atau memang sengaja tidak ditampilkan dalam mode cetak

**Comment by eddieridwan** [comment]
Bung @metalab25 : seperti dijelaskan di https://github.com/eddieridwan/OpenSID/wiki/Panduan-Mencetak-Surat, kami menganjurkan untuk hanya menggunakan export doc untuk mencetak surat. Seperti dijelaskan di situ, rilis OpenSID tidak akan memperbaiki atau mengembangkan fitur cetak langsung. 

Tetapi bagi yang ingin tetap menggunakan, silakan memperbaiki sendiri dengan mengubah file print di folder desa/surat.

**Comment by eddieridwan** [comment]
Bung @metalab25, karena fitur cetak langsung tidak akan masuk rilis OpenSID, mungkin issue ini sebaiknya ditutup saja.

**Comment by metalab25** [comment]
saya sudah mencona di file print surat tersebut cuma masih tidak tampil, mungkin karena saya tidak tau parameter apa yang harus dimasukan bung @eddieridwan

**Comment by metalab25** [comment]
saya coba tambahkan <?php echo $data['pamong_nip']?> tapi tidak tampil bung @eddieridwan

**Comment by eddieridwan** [comment]
Karena rilis OpenSID tidak akan melakukan perbaikan pada fitur cetak langsung, kami akan tutup issue ini. Untuk bantuan programming, silakan bertanya pada programmer di https://www.facebook.com/groups/OpenSID/ atau di https://opensid.slack.com.
