### ISSUE TITLE
Fitur: Tambahkan tautan ke forum OpenSID

### ISSUE THREAD

**Issue by eddieridwan** [eddieridwan/OpenSID#52]
Forum diskusi OpenSID telah dibuka di https://groups.google.com/forum/?hl=id#!forum/opensid.

Untuk memudahkan pengguna OpenSID mengakses forum tersebut, tambahkan tautan ke forum OpenSID itu di modul Administrasi SID dan modul web SID.

**Comment by metalab25** [comment]
udah saya join om tinggal di approve aja

**Comment by arzaddin** [comment]
slack please... :dancers:

**Comment by eddieridwan** [comment]
@batudaa , @siayi, @arzaddin, @healm4n, @hilmanyuda: mau bergabung di https://groups.google.com/forum/?hl=id#!forum/opensid untuk diskusi teknis OpenSID?

Maaf, @arzaddin & @batudaa: slack lebih cocok untuk diskusi tim kegiatan umum; sedangkan google groups, walaupun tidak sempurna, sepertinya lebih cocok untuk support forum bagi pengguna & diskusi bug/fitur dsbnya. Tadinya mau pakai Discourse (https://meta.discourse.org/) tapi berbayar.

**Comment by metalab25** [comment]
wah bahasanya aneh"
slack itu apa yah....????? setau saya slackware (distro Linux)

**Comment by eddieridwan** [comment]
@metalab25 : slack adalah perangkat komunikasi/kolaborasi tim, terintegrasi dengan banyak app lainnya : https://slack.com/. Penampilan keren, dipakai oleh banyak tim.

**Comment by arzaddin** [comment]
Kalo pengguna juga ikut kayaknya slack tidak cocok. Karna perlu login ke layanan lain lagi. Sedangkan pengguna besar kemungkinan selalu nongkrong di facebook. 

Btw, kenapa tidak sekalian di facebook aja?

**Comment by eddieridwan** [comment]
@arzaddin, diskusi di Google Groups terstruktur per topik atau pertanyaan, dan lebih mudah di-cari berdasarkan topik (pengguna bisa lebih mudah mencari solusi untuk masalah mereka, sebelum bertanya). Jadi lebih cocok untuk _support forum_ daripada Facebook yang lebih cocok untuk diskusi bebas. Sampai ketemu di https://groups.google.com/forum/?hl=id#!forum/opensid !

**Comment by eddieridwan** [comment]
Sekarang menjadi jelas, komunitas SID jauh lebih terbiasa dengan Facebook ketimbang Google Groups. Yang berkembang dan aktif adalah https://www.facebook.com/groups/OpenSID/. Karena itu, tautan yang ditambahkan di laman http://localhost/index.php/hom_desa/about adalah ke Forum Pengguna dan Pegiat OpenSID.

**Comment by batudaa** [comment]
Terserah di mana aja.
Asal tetap bisa berkarya dan berkembang secara bersama-sama.

**Comment by eddieridwan** [comment]
@batudaa , silakan bergabung di https://www.facebook.com/groups/OpenSID/. Saya lihat anda belum jadi anggota.
