### ISSUE TITLE
Buatkan dokumentasi SK Kades dan Perdes

### ISSUE THREAD

**Issue by afri18** [eddieridwan/OpenSID#522]
sekalian dibuatkan dokumentasi SK Kades/Perdes isinya > tanggal-no sk-tentang-sasaran
di menu surat juga nggak apa

**Comment by eddieridwan** [comment]
@afri18 , apakah fitur ini lebih cocok di modul _Admin Web > Dokumen_ atau di _Surat > Surat Keluar_?

Jika di _Admin Web > Dokumen_ mungkin bisa ditambahkan fitur untuk menampilkan daftar SK Kades dan Perdes di web.

**Comment by eddieridwan** [comment]
@afri18 Harap beri beberapa contoh SK Kades dan Perdes, termasuk contoh data kolom isian yang diinginkan:

- tanggal
- no sk
- tentang
- sasaran

Format berkas apa saja yang diperbolehkan: PDF saja, atau juga Word?

**Comment by fathurvbf** [comment]
Izin Share Mas, Dekumentasi SK dan Perdes @eddieridwan Bisa dilengkapi Mas @afri18 
[SK WEB UPLOAD.docx](https://github.com/eddieridwan/OpenSID/files/1254493/SK.WEB.UPLOAD.docx)
[PERDES PENGHASILAN KEPALA DESA DAN PERANGKAT DESA.pdf](https://github.com/eddieridwan/OpenSID/files/1254496/PERDES.PENGHASILAN.KEPALA.DESA.DAN.PERANGKAT.DESA.pdf)

**Comment by fathurvbf** [comment]
![buku perdes](https://user-images.githubusercontent.com/26631297/29751657-852375e8-8b7a-11e7-8fb9-fdc98bb0ab9d.jpg)
![sk kepusan](https://user-images.githubusercontent.com/26631297/29751659-8a330846-8b7a-11e7-9928-b4e409219a19.jpg)

**Comment by eddieridwan** [comment]
Terima kasih @fathurvbf . Harap lampirkan juga contoh _Buku Peraturan di Desa_ dan _Buku Keputusan Kepala Desa_ yang telah terisi. @afri18 

Apakah format laporan2 tersebut sudah baku, atau berbeda menurut daerah?
 
Apakah masing2 laporan itu dikeluarkan per tahun, per bulan atau atas permintaan?

**Comment by MUHAMMADRANGSEL** [comment]
Banyak mas eddie

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL @fathurvbf @afri18 Silakan didaftarkan, walaupun banyak. 30? 50? Jika ingin dibuatkan pilihan drop-down, ya harus didaftarkan semuanya.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.

Tetapi karena teman2 tidak memberi penjelasan yang diperlukan, terpaksa menebak. Jadi belum tentu benar. Itulah resikonya jika teman2 tidak aktif memberi masukan.

Belum dibuat laporan untuk masing2 kategori dokumen. Juga belum dibuat laporan yang bisa ditambahkan ke menu statis. Jika diperlukan, silakan buat issuenya.
