### ISSUE TITLE
Perbaiki surat keterangan kurang mampu

### ISSUE THREAD

**Issue by eddieridwan** [eddieridwan/OpenSID#526]
Permintaan dari Arcom Zulkarnain untuk memperbaiki tampilan anggota keluarga di Surat Keterangan Kurang Mampu. Inginnya diurut tanggal lahir sesuai kartu keluarga.

[surat_ket_kurang_mampu.zip](https://github.com/eddieridwan/OpenSID/files/1199063/surat_ket_kurang_mampu.zip)

**Comment by MUHAMMADRANGSEL** [comment]
Semoga segera ditemukan solusinya

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
