### ISSUE TITLE
Link Artikel baru tidak ada (Versi 2.3)

### ISSUE THREAD

**Issue by dadannurman** [eddieridwan/OpenSID#528]
Maaf master mohon petunjuknya,
di versi sebelumnya lancar, setelah instal baru (versi 2.3) mencoba membuat artikel baru

![artikel](https://user-images.githubusercontent.com/28327817/29015343-d862195c-7b77-11e7-93fb-4b596778c82d.PNG)

pada "tambah sub menu layanan"

![artikel2](https://user-images.githubusercontent.com/28327817/29015376-fad02d76-7b77-11e7-9989-387a38f9dd1b.PNG)

Link artikel yang akan di tujukan adalah "Surat Keterangan dan Pengantar"

![artikel4](https://user-images.githubusercontent.com/28327817/29015430-30b7a1bc-7b78-11e7-99d5-7965ee8fb77c.PNG)

Tetapi hasilnya tidak ada

![artikel3](https://user-images.githubusercontent.com/28327817/29015454-43464fe0-7b78-11e7-8a60-c553d9581010.png)

Begitu juga untuk Semua Artikel baru yang saya buat.
![artikel](https://user-images.githubusercontent.com/28327817/29015546-96189d2c-7b78-11e7-8454-1804b67dd856.PNG)
tidak bisa di masukan ke submenu.

Terimakasih sebelumnya.

**Comment by eddieridwan** [comment]
Sepertinya ini bukan error, tetapi kesalah-pahaman antara pengertian 'Menu/Artikel Statis' dan 'Menu/Artikel Dinamis'.

Artikel yang dapat di-link pada Menu Statis hanya artikel statis. Artikel dinamis (yang dibuat oleh bung Dadan) tidak bisa di-link ke Menu Statis.

Bung Dadan Nurman, jika anda ingin membuat link ke artikel di menu atas, anda perlu membuar artikel statis. Silakan lihat panduan https://github.com/eddieridwan/OpenSID/wiki/Menu-Statis.

Sepertinya panduan ini kurang jelas. Ok. Silakan perbaiki panduannya. Ayo, silakan ikut kontribusi.

**Comment by dadannurman** [comment]
Menambah sub menu, mengubah data, hapus data dan menon-aktifkan menu

Untuk menambah sub menu, klik tanda + pada menu yang sudah dibuat.
Untuk mengubah data, klik tanda pensil pada menu.
Untuk hapus data, klik tanda tong sampah pada menu.
Untuk menon-aktifkan, klik tanda gembok pada menu. Tampak seperti gambar berikut.

https://cloud.githubusercontent.com/assets/20512335/17277883/8e177ea8-5780-11e6-9c40-14b69c5ab676.png

Untuk menambah sub menu pada "menu statis" seperti tampak pada gambar di bawah.

![coba](https://user-images.githubusercontent.com/28327817/29054743-30465f02-7c22-11e7-94fc-7202d749be01.png)

Ketika di ketikan "keyword judul artikel" link yang akan di tuju, tampak seperti gambar di bawah.

![coba1](https://user-images.githubusercontent.com/28327817/29054775-6c8e364c-7c22-11e7-975f-becd9abaff0e.png)

Maka "saran judul artikel" yang akan muncul hanya artikel yang berada di halaman statis seperti gambar di bawah ini.

![coba2](https://user-images.githubusercontent.com/28327817/29054833-be769f9e-7c22-11e7-9cbc-b9bd8f5be714.png)

**Comment by dadannurman** [comment]
Mencoba memperjelas panduan https://github.com/eddieridwan/OpenSID/wiki/Menu-Statis#menambah-sub-menu-mengubah-data-hapus-data-dan-menon-aktifkan-menu bung @eddieridwan , mohon bimbingannya.

**Comment by eddieridwan** [comment]
Bung @dadannurman, perbaikan panduan langsung saja ditambahkan ke panduan di https://github.com/eddieridwan/OpenSID/wiki/Menu-Statis#menambah-sub-menu-mengubah-data-hapus-data-dan-menon-aktifkan-menu. Bukan di issue ini....

Panduan mengedit panduan ada di https://github.com/eddieridwan/OpenSID/wiki/Menyunting-Panduan-OpenSID.

**Comment by dadannurman** [comment]
maaf sebelumnya bung @eddieridwan , maksud saya minta pendapatnya apakah penjelasan di atas sudah layak dimasukkan ke panduan?

**Comment by eddieridwan** [comment]
@dadannurman , ya sudah ok. Nanti kalau ada yang merasa masih perlu diperbaiki, mereka akan edit lagi. Di github, setiap perubahan tercatat -- jadi tidak perlu harus langsung sempurna. Ok, silakan masukan perbaikan anda langsung ke panduan. Terima kasih.

**Comment by eddieridwan** [comment]
Bung @dadannurman , nanti sesudah anda pindahkan tulisan ke panduan, harap tutup issue ini. Terima kasih.

**Comment by dadannurman** [comment]
terima kasih banyak bung @eddieridwan
