### ISSUE TITLE
Bug: Paginasi halaman widget salah pada saat penampilan awal

### ISSUE THREAD

**Issue by dadannurman** [eddieridwan/OpenSID#529]
Pada Widget "Statistik" tidak bisa di nonaktifkan, walaupun statusnya "nonaktif"

![widget](https://user-images.githubusercontent.com/28327817/29015852-fc58fff4-7b79-11e7-8a73-8d2b5d580432.PNG)

Tetapi masih tetap tampil di Halaman

![widget2](https://user-images.githubusercontent.com/28327817/29015872-126f50a4-7b7a-11e7-9c08-af1178579dad.PNG)

Juga tidak ada Widget "Arsip" di menu pengaturan Widget

![widget3](https://user-images.githubusercontent.com/28327817/29015903-3c9a4cb2-7b7a-11e7-8dcb-0af296f87c91.PNG)

**Comment by eddieridwan** [comment]
Bung @dadannurman, errornya masalah penampilan paginasi halaman widget. Tidak semua widget tampak. Di situs demo, ada 13 widget, tapi hanya 10 yang tampil di daftar. Jika anda ganti pilihan _Tampilan_ menjadi 50, misalnya, semua widget akan tampil. 

Yang anda non-aktifkan bukan _statistik pengunjung_ tetapi widget  _statistik_ lainnya.

<img width="1311" alt="error-paginasi-widget" src="https://user-images.githubusercontent.com/249563/29018367-2bbcac86-7b9e-11e7-8e8f-eb371373dba8.png">

**Comment by eddieridwan** [comment]
Seharusnya tampil seperti gambar di bawah. Sesudah klik _Tampilkan_ 50, dan sesudah itu 20.

<img width="1311" alt="error-paginasi-widget-seharusnya" src="https://user-images.githubusercontent.com/249563/29018466-84fe160e-7b9e-11e7-8e97-c4432b21f7b2.png">

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
