### ISSUE TITLE
Bug: Artikel baru yang tidak bergambar seharusnya tidak berisi gambar default

### ISSUE THREAD

**Issue by dadannurman** [eddieridwan/OpenSID#530]
Izin master, ketika membuat artikel yang tidak menggunakan gambar/foto

![gambar](https://user-images.githubusercontent.com/28327817/29016196-9c9325ca-7b7b-11e7-9705-1a43d8f12f3b.PNG)

bagaimana jika tidak perlu tampil Gambar Default

![gambar2](https://user-images.githubusercontent.com/28327817/29016215-bb2f6570-7b7b-11e7-8306-b027f8dd0979.PNG)

**Comment by eddieridwan** [comment]
Bung @dadannurman, gambar default tampil karena artikel itu ada gambar, tetapi gambarnya tidak ditemukan (mungkin terhapus, atau database direstore, sedangkan folder desa tidak lengkap).

Jika artikel memang tidak ingin bergambar, klik saja kotak _Hapus Gambar_ dan _Simpan_. Sesudah itu artikelnya akan tampil tanpa ada gambar default.

Jadi ini bukan error, tapi salah pengertian.

Ok, sepertinya sekali lagi ini disebabkan panduan yang kurang jelas (https://github.com/eddieridwan/OpenSID/wiki/Menulis-Artikel). Silakan perbaiki panduannya.

**Comment by dadannurman** [comment]
Saya mencoba membuat artikel baru (tanpa gambar) di situs demo

![tambah](https://user-images.githubusercontent.com/28327817/29055773-99c7cd34-7c28-11e7-88e4-92fe1846c301.PNG)

![tambah2](https://user-images.githubusercontent.com/28327817/29055778-a318b934-7c28-11e7-99c1-893c3f8d2c09.PNG)

Tetapi saat menambah artikel baru, kotak "hapus gambar" tidak muncul

![tambah3](https://user-images.githubusercontent.com/28327817/29055803-cffab6aa-7c28-11e7-88b0-21ef5dbf1f44.PNG)

Sehingga setelah di simpan

![tambah4](https://user-images.githubusercontent.com/28327817/29055811-e6e794d2-7c28-11e7-925a-edb441433792.PNG)

artikel muncul tetap dengan "gambar default"

![tambah5](https://user-images.githubusercontent.com/28327817/29055822-fc1ed11c-7c28-11e7-9fa4-b9224ee17a3b.PNG)

Sehingga perlu mengubah lagi artikel yang di maksud (artikel tanpa gambar)

![tambah6](https://user-images.githubusercontent.com/28327817/29055843-261e215c-7c29-11e7-8139-a66e9270e0d0.PNG)

dan mengklik kotak "hapus gambar" lagi

![tambah7](https://user-images.githubusercontent.com/28327817/29055871-434bc37e-7c29-11e7-86dd-c4d0e1a31389.PNG)

Baru berhasil

![tambah8](https://user-images.githubusercontent.com/28327817/29055875-4b254bb0-7c29-11e7-9393-d7c21a62a05b.PNG)



Apakah bisa menampilkan kotak "hapus gambar" pada saat awal pembuatan artikel? ataukah ada solusi lain untuk memperbaiki "gambar yang tidak ditemukan  (mungkin terhapus, atau database direstore, sedangkan folder desa tidak lengkap)" ?

Kiranya dapat memahami maksud saya, mohon bimbingannya. Terimakasih.

**Comment by eddieridwan** [comment]
Heheh... bung @dadannurman. Error yang anda temukan itu sudah ada sejak SID 3.04, dan masih ada di SID 3.10 versi ujicoba.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
