### ISSUE TITLE
"Directory access is forbidden" di menu cetak surat

### ISSUE THREAD

**Issue by Jehamahdan** [eddieridwan/OpenSID#531]
Menu cetak surat "Directory access is forbidden" versi 2.3 online.

**Comment by eddieridwan** [comment]
@Jehamahdan , Jika melaporkan masalah harap selalu melampirkan screenshot masalah. Kami tidak bisa membantu jika tidak jelas masalahnya.

Apakah masalah ini ditemukan juga di situs demo http://sid.bangundesa.info? Jika tidak, ada sesuatu di server SID anda yang menyebabkan.

**Comment by eddieridwan** [comment]
@Jehamahdan , sepertinya masalah anda terkait adanya file .htacess, seperti dijelaskan di https://github.com/eddieridwan/OpenSID/wiki/Tanya-Jawab-Install-dan-Update (lihat bagian error '404').

Ok, karena tidak ada info tambahan, kami akan tutup issue ini. Jika perlu, silakan buka lagi.
