### ISSUE TITLE
Penyesuaian Tujuan Disposisi pada Form Surat Masuk

### ISSUE THREAD

**Issue by siayi** [eddieridwan/OpenSID#533]
Fitur penyesuaian istilah pada Pilihan Tujuan Disposisi pada Form Surat Masuk sepertinya mesti disediakan. Sebagaimana contoh dalam gambar di bawah, di desa kami istilah **Kawi**l tidak digunakan tapi menggunakan istilah **Kadus**.
![screenshot_96-kawil](https://user-images.githubusercontent.com/1229849/29105083-bac50fe8-7cf4-11e7-9e68-74e66fefb24e.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.

**Comment by eddieridwan** [comment]
Sudah ditambahkan setting sebutan_singkatan_kadus di halaman setting aplikasi. Default _kawil_.
