### ISSUE TITLE
Bug: Artikel berisi tabel merusak tampilan web

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#534]
Artikel yang berisi data yang tabel membuat tampilan widget berantakan kalau versi sebeulmnya tidak dan ini sangat membuat tampilan Opensid jadi acak-acakan contoh . Ada di sidbangun.info
![tangkapan layar 2017-08-10 15 24 58](https://user-images.githubusercontent.com/25834335/29173778-8d66d85e-7e0e-11e7-9905-c63a36858b66.png)

**Comment by metalab25** [comment]
Karna table tema default tidak responsive

**Comment by MUHAMMADRANGSEL** [comment]
Di hadakewa jg begitu mas happy

Pada tanggal 10 Agt 2017 17:42, "Happy" <notifications@github.com> menulis:

**Comment by MUHAMMADRANGSEL** [comment]
Versi 1.17 normal bisa di coba di rarangselatan.desa.id

**Comment by MUHAMMADRANGSEL** [comment]
Masalahnya ada di folder donjo-app/view/web, mohn diperbaiki, di versi 2.3 ok, tempat maslahnya di pasca 2.3

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
