### ISSUE TITLE
Bug: Batasi jenis file yang bisa diupload [kritikal]

### ISSUE THREAD

**Issue by telo99** [eddieridwan/OpenSID#535]
Barusan nyoba, saya bisa upload file PHP, itu artinya user bisa saja mengirimkan file php shell yang bisa dipakai untuk mengacak² web.
Harap batasi jenis file yang bisa diupload, misal hanya bisa gambar (jpg,png,gif) dan dokumen (doc,xls).

**Comment by eddieridwan** [comment]
Dan .pdf

**Comment by eddieridwan** [comment]
Sudah dicommit ke master
