### ISSUE TITLE
INGATKAN PENGGUNA UNTUK MENGGANTI SEMUA PASSWORD

### ISSUE THREAD

**Issue by telo99** [eddieridwan/OpenSID#536]
Tolong ingatkan pengguna openSID untuk mengganti ke-empat password yang ada, baik itu admin, redaksi, operator maupun Master Admin.
Berusan nemu web yang pake openSID, admin utama udah ganti password tapi redaksi tidak diganti. Ini jelas berbahaya karena bisa upload file dan ngacak² web

**Comment by eddieridwan** [comment]
Untuk itu, silakan beritahu di https://www.facebook.com/groups/OpenSID. Supaya mengingatkan para pengguna.

Dan lengkapi panduan di https://github.com/eddieridwan/OpenSID/wiki/Pengaturan-Pengguna dan di https://github.com/eddieridwan/OpenSID/wiki/Tanya-Jawab-Pengaturan-Pengguna
Karena untuk OpenSID, kita semua perlu saling mengingatkan. Dan forum https://github.com/eddieridwan/OpenSID/wiki/Tanya-Jawab-Pengaturan-Pengguna adalah tempatnya.
