### ISSUE TITLE
Informasi Donasi OpenSID

### ISSUE THREAD

**Issue by dadannurman** [eddieridwan/OpenSID#538]
Barangkali bisa dibuatkan halaman (Informasi untuk berdonasi OpenSID), dan dimasukkan ke menu di admin/semua akun pengguna.

Atau cukup di sini

![donasi](https://user-images.githubusercontent.com/28327817/29200171-4041d898-7e7d-11e7-8ec8-36223ff70e14.PNG)

**Comment by metalab25** [comment]
Akan lebih bagus bila setelah sukses login di directnya ke halaman itu

**Comment by eddieridwan** [comment]
Bung @metalab25 , apakah anda bisa mempercantik halaman itu? Supaya lebih menarik.

**Comment by metalab25** [comment]
Belum sempat karna masih disibukan dengan pekerjaan di kominfo yang targetnya akan membantu penyebaran OpenSID di kab. Bombana

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.

Tapi masih perlu bantuan pegiat yang dapat mempercantik halaman dan artikel donasi di http://www.opensid.info/index.php?id=41:donasi-pengembangan-opensid.
