### ISSUE TITLE
Bug: Seharusnya file di folder surat tidak bisa diakses langsung

### ISSUE THREAD

**Issue by telo99** [eddieridwan/OpenSID#540]
File-file yang ada di folder surat bisa diakses secara langsung dan memperliharkan error.
Misal: http://sid.bangundesa.info/surat/surat_ket_pergi_kawin/surat_ket_pergi_kawin.php

"Warning: include(donjo-app/views/surat/form/_pamong.php) [function.include]: failed to open stream: No such file or directory in /home/eddier/public_html/sid/surat/surat_ket_pergi_kawin/surat_ket_pergi_kawin.php on line 85"

Buat orang yang isengnya kebangetan, informasi seperti ini mungkin bisa jadi modal untuk melakukan brute force login cpanel misalnya, karena ada informasi nama user cpanel di sana (eddier).

Usul: Karena sepertinya semua file di folder surat tersebut hanya di-include, ada baiknya tidak bisa diakses secara langsung. Mungkin bisa mencontoh pembatasan akses seperti di wordpress (bukan pake htaccess)
![screenshot_49](https://user-images.githubusercontent.com/30897391/29208046-ac3a9d52-7eb2-11e7-8421-62e10ac32a44.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
