### ISSUE TITLE
Menambahkan email di Surat Export 

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#541]
Untuk Menampilkan Email Desa yang ngambil di SID HOME maka perlu ada penambahan di surat_model.php pada Data Konfigurasi Desa semula **$buffer=str_replace("[alamat_des]","$config[alamat_kantor] Kode Pos : $config[kode_pos]",$buffer);** menjadi $buffer=str_replace("[alamat_des]","$config[alamat_kantor] $config[email_desa] Kode Pos : $config[kode_pos]",$buffer); supaya tdk merubah alamat desa semua surat export
shgg tapilan seperi dibawah ini 👍 
![image](https://user-images.githubusercontent.com/25834335/29210379-88337bd0-7ebd-11e7-8e48-90f804e59694.png)

**Comment by MUHAMMADRANGSEL** [comment]
[surat_model.zip](https://github.com/eddieridwan/OpenSID/files/1220518/surat_model.zip)
Diatas Scrip perubahannya mas eddie

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
