### ISSUE TITLE
Seragamkan huruf besar/kecil di tampilan alamat di surat export doc

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#542]
Supaya Kelihatan Lebih Cantik perlu di seragamkan semua penulisan alamat di Export Surat menjadi Huruf Besar Awal saja Baik Alamat Individu, Alamat Orang Tua dan Yang Lainnya  yang ada surat_model.php Contoh Kecil : 
1. $buffer=str_replace("[alamat]","$individu[alamat_wilayah]",$buffer);
2. $buffer=str_replace("[alamat_jalan]","$individu[alamat]",$buffer);
3. $buffer=str_replace("[alamat_sebelumnya]",ucwords(strtolower($individu[alamat_sebelumnya])),$buffer);

yg hasilnya seperti 
![image](https://user-images.githubusercontent.com/25834335/29210902-2929b548-7ec0-11e7-9d76-94a323164756.png)
menjadi
1. $buffer=str_replace("[alamat]",ucwords(strtolower($individu[alamat_wilayah])),$buffer);
2. $buffer=str_replace("[alamat_jalan]",ucwords(strtolower($individu[alamat])),$buffer);
3. $buffer=str_replace("[alamat_sebelumnya]",ucwords(strtolower($individu[alamat_sebelumnya])),$buffer);
setelah perubahan hasilnya :

![image](https://user-images.githubusercontent.com/25834335/29210940-5b09f122-7ec0-11e7-8b5b-539dc4722b9a.png)

**Comment by MUHAMMADRANGSEL** [comment]
mengingat kami di lombok timur sudah  terlanjur IMPORT DATA BASE untuk alamatnya menggunakan HURUF BESAR

**Comment by MUHAMMADRANGSEL** [comment]
Hanya alamat Jalan saya yang saya tambahkan scripnya
[surat_model.zip](https://github.com/eddieridwan/OpenSID/files/1220521/surat_model.zip)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui pull request #542.

@MUHAMMADRANGSEL : Tetapi hanya untuk alamat, alamat_wilayah dan alamat_sebelumnya. Jika ada yang lain, harap buat issue terpisah dengan merinci kolom mana yang perlu diperbaiki.
