### ISSUE TITLE
Hapus Dokumen hanya menghapus database

### ISSUE THREAD

**Issue by telo99** [eddieridwan/OpenSID#543]
Saat menghapus dokumen yang pernah di-upload, yang terhapus hanya data di database sedangkan filenya tetap ada di server.
Harap diperbaiki.
![screenshot_50](https://user-images.githubusercontent.com/30897391/29218569-6c10f9ec-7edf-11e7-8e0b-1fc7ab632799.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
