### ISSUE TITLE
Penyesuaian Tampilan Menu Statis 

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#544]
Versi 2.3 Menu Statis menjadi Lebar, mohon di sesuaikan lagi seperti menu Dinamis
![tangkapan layar 2017-08-11 22 09 05](https://user-images.githubusercontent.com/25834335/29219668-e3e23a96-7ee2-11e7-8bf0-bc4956438e72.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
