### ISSUE TITLE
Tampilan Gambar Backround ikut mengecil

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#545]
Seharusnya ketika memperkecil ukuran layar seharusnya gambar backround tidak ikut mengecil tampilannya seperti ini :
![image](https://user-images.githubusercontent.com/25834335/29221749-13a1f864-7eea-11e7-9dbe-077e331643ba.png)

**Comment by eddieridwan** [comment]
Contoh perubahan css di folder _desa-contoh/css/default/desa-web.css_ tidak perlu dan menyebabkan konflik dengan yg styles di _themes/default/css/first.css_, sehingga gambar latar belakang mengecil.

Contoh perubahan css di _desa-contoh/css/default/desa-web.css_ telah diubah (di pra-rilis). Salin contoh ini ke folder _desa/css/default/desa-web.css_ supaya menjadi aktif.

**Comment by MUHAMMADRANGSEL** [comment]
Siap mas eddie

Pada tanggal 12 Agt 2017 14:33, "Eddie Ridwan" <notifications@github.com>
menulis:
