### ISSUE TITLE
phpinfo di direktori "script"

### ISSUE THREAD

**Issue by telo99** [eddieridwan/OpenSID#546]
Saya kurang tau fungsi dari file² yang ada di direktori 'script'.
yang jelas, info.php rasanya juga kurang pas untuk diketahui umum, karena banyak informasi menarik di sana. misal: "**_SERVER["DOCUMENT_ROOT"] | /home/eddier/public_html**".

Seandainya file di direktori tersebut hanya untuk coba², alangkah baiknya dihapus saja.

**Comment by lynggo** [comment]
sebelum di upload ke server, baiknya di hapus saja fle info.php

**Comment by eddieridwan** [comment]
Semua file di folder /script adalah peninggalan SID CRI 3.04 yang sepertinya tidak digunakan aplikasi. Akan dihapus.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
