### ISSUE TITLE
Bug: Seharusnya User yg masih terkunci tidak bisa Login

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#548]
Seharusnya user yang masih  dikunci tidak bisa login, tetapi nyatanya masih bisa login, mohon di perbaiki kembali shg user yang masih terkunci tidak bisa login
![tangkapan layar 2017-08-12 22 12 32](https://user-images.githubusercontent.com/25834335/29246295-161dec3e-801f-11e7-9542-0b7df9554bbb.png)

![tangkapan layar 2017-08-12 22 13 07](https://user-images.githubusercontent.com/25834335/29246296-20a02fc8-801f-11e7-8b9b-17190ba9b60c.png)

**Comment by eddieridwan** [comment]
Error ini juga masih ada di SID 3.10. 

Sepertinya SID mempunyai ketentuan user dengan username _admin_ adalah user khusus yang tidak boleh di-non-aktifkan.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
