### ISSUE TITLE
Bug: Foto Perangkat Desa Hilang

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#549]
Seharusnya ketika memperbaiki nama Perangkat Desa Poto tidak hilang dan Upayakan Poto Bisa diupload pada waktu menambah perangkat Desa sehingga tidak kerja dua Kali

![tangkapan layar 2017-08-13 12 05 09](https://user-images.githubusercontent.com/25834335/29246327-80e64ccc-8020-11e7-9091-08b047de0e2d.png)

**Comment by pandigresik** [comment]
Bisa dilakukan perbaikan, mohon dicek
https://github.com/eddieridwan/OpenSID/pull/553

**Comment by MUHAMMADRANGSEL** [comment]
Siap mas

Pada tanggal 14 Agt 2017 08:09, "pandigresik" <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
Perubahan oleh @pandigresik di pull request #553 telah digabungkan ke master.
