### ISSUE TITLE
Bug: Normalkan tampilan pendidikan terakhir di surat

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#551]
Hasil Export maupun Cetak langsung untuk Pendidikan terakhir perlu perbaikan contoh **Akademi/ Diploma Iii/s. Muda** seharusnya **Akademi/ Diploma III/S. Muda** Dan juga pendidikan yang lain semua sama

![tangkapan layar 2017-08-13 22 15 12](https://user-images.githubusercontent.com/25834335/29250940-f867221c-8075-11e7-9af2-eeffad80d2d6.png)

**Comment by eddieridwan** [comment]
Telah dicommit ke master melalui pull request #561.
