### ISSUE TITLE
Isian pada Lampiran Formulir isian Kartu Keluarga baiknya menggunakan kata saja.

### ISSUE THREAD

**Issue by sukrimalendra** [eddieridwan/OpenSID#555]
Selamat pagi pak eddieridwan, perkenalkan saya staff Desa Pelangan, Kec. Sekotong Kab. Lombok Barat, Prov. NTB. Usul saya, untuk lebih baiknya mohon Isian pada Lampiran Formulir isian Kartu Keluarga baiknya menggunakan kata saja. Karena kode isian menggunakan angka kurang jelas. Sekian masukan dari saya. Kurang lebihnya mohon dimaklumi.

![github](https://user-images.githubusercontent.com/30992964/29258468-67cf8a88-80ec-11e7-8f8d-4c019d525f84.PNG)

**Comment by MUHAMMADRANGSEL** [comment]
Itu memang sesuai aturan harus pakai kode alias angka, jd tdk bisa dirubah

**Comment by sukrimalendra** [comment]
Tapi di kantor desa saya masih menggunakan pada lampiran dibawah ini. Apakah tidak masalah nanti jika di bawa ke kantor camat dan seterusnya?
![kk](https://user-images.githubusercontent.com/30992964/29260194-f64951e6-80fa-11e7-8099-e1ae5128d3cb.PNG)

**Comment by MUHAMMADRANGSEL** [comment]
Itu beda form pak, yg dipakai F.1 01 itu yg baku

Pada tanggal 14 Agt 2017 14:15, "sukrimalendra" <notifications@github.com>
menulis:

**Comment by sukrimalendra** [comment]
Berarti kami di desa Pelangan bisa hanya menggunakan form F-1.01 untuk menggantikan surat permohonan kk pada lampiran diatas pak?

**Comment by MUHAMMADRANGSEL** [comment]
Ya yg dibuat tuk pengAntar pembuatan KK baru maupun menambah anggota baru
yg digunakan F.1 15 dan F1 01 sprt yg sdh tersedia di OpenSID skrg ini.

Pada tanggal 14 Agt 2017 14:23, "sukrimalendra" <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
Ok. Kami akan tutup issue ini, karena tidak ada yang perlu diubah.

@sukrimalendra , karena anda di Lombok Barat, mungkin bisa menghubungi Jaringan Masyarakat Sipil Lombok (https://www.facebook.com/pages/Jaringan-Masyarakat-Sipil-Lombok-Office/957931284305451). Mereka menyelenggarakan pelatihan SID, dan juga mempunyai hubungan yang baik dengan Disdukcapil -- sehingga dapat membantu anda berkaitan penggunaan form dsbnya.

**Comment by MUHAMMADRANGSEL** [comment]
Siap mas eddie karn itu sdh baku dan berlwku di seluruh nusantara

Pada tanggal 14 Agt 2017 14:28, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by sukrimalendra** [comment]
Baik. Terimakasih atas penjelasan bapak2.
