### ISSUE TITLE
Bug: Manajemen Surat Keluar hanya menampilan 10 surat keluar pada halaman pertama

### ISSUE THREAD

**Issue by sukrimalendra** [eddieridwan/OpenSID#556]
Setelah saya coba semua format surat pada OpenSID menggunakan XAMPP (Offline). Surat keluar yang terekam hanya sampai 10 surat. Jika bisa surat surat keluar juga di buatkan menu cetak agar dapat dijadikan laporan surat keluar dan jika bisa juga agar dibuatkan menu untuk input surat keluar untuk serta upload surat keluarnya agar bisa diarsipkan surat keluar seperti undangan rapat, himbauan, dll.

**Comment by eddieridwan** [comment]
Jumlah surat keluar yang terrekam tidak dibatasi. Yang tampil 10 surat adalah karena paginasi. Klik tombol di bagian bawah halaman untuk menampilkan halaman berikutnya, atau untuk mengubah jumlah surat yang ditampilkan per halaman.

Untuk usulan laporan surat keluar, silakan buat issue terpisah. Dan lampirkan penjelasan rinci seperti apa laporan yang diinginkan, yaitu informasi apa yang perlu ditampilkan.

Untuk usulan mengunggah surat non-layanan (seperti undangan rapat, dsbnya) ke arsip surat keluar, silakan buat issue terpisah. Dan lampirkan penjelasan rinci seperti apa informasi yang akan disimpan -- apakah sama dengan surat layanan.

Harap membatasi satu topik per issue, karena pegiat akan menerapkan issue satu per satu. Dan harap mengikuti petunjuk di https://github.com/eddieridwan/OpenSID/wiki/Pengelolaan-Masalah-dan-Permintaan-Perbaikan-SID (bagian bawah) jika ingin issue anda mendapatkan prioritas.

**Comment by eddieridwan** [comment]
Kami ganti issue ini -- khusus untuk masalah di mana pada pertama kalinya menampilkan halaman surat keluar hanya 10 surat keluar yang ditampilkan, walaupun setting paginasi adalah 20 surat per halaman.

**Comment by eddieridwan** [comment]
@sukrimalendra : silakan buat issue terpisah untuk masing2 usulan anda yang lain.

**Comment by sukrimalendra** [comment]
Baik pak. Tapi sudah saya coba lagi membuat surat keterang. Lalu setelah
saya cek lagi tetap hanya 10 surat yang tampil walaupun diganti tampilannya
ke 100.

Pada tanggal 14 Agt 2017 2:38 PM, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
@sukrimalendra: apakah membuat surat keterangan menggunakan _Export Doc_? Jika menggunakan tombol _Cetak_ surat tidak akan tersimpan di arsip surat keluar.

Silakan cek di http://sid.bangundesa.info.

**Comment by eddieridwan** [comment]
Sudah diperbaiki dan dicommit ke master. Sekarang solusi ada di pra-rilis.

**Comment by sukrimalendra** [comment]
Baik. Terimakasih pak @eddieridwan
