### ISSUE TITLE
Bug: View Kartu Keluarga dan Cetak Kartu Keluarga tabel no kosong

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#559]
View dan Cetak Kartu Keluarga pada tabel di Bawah pada kolom nomor Kosong
![tangkapan layar 2017-08-14 17 21 30](https://user-images.githubusercontent.com/25834335/29268183-e9611714-8115-11e7-8c79-c95c576cca70.png)
![tangkapan layar 2017-08-14 17 21 52](https://user-images.githubusercontent.com/25834335/29268191-f59906ae-8115-11e7-8da5-57521776fe7f.png)

Bersama ini saya lampirkan perbaikannya
[kartu_keluarga.php dan cetak_kk.php.zip](https://github.com/eddieridwan/OpenSID/files/1221948/kartu_keluarga.php.dan.cetak_kk.php.zip)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
