### ISSUE TITLE
Pindah file upload ke folder desa

### ISSUE THREAD

**Issue by eddieridwan** [eddieridwan/OpenSID#56]
Ada beberapa file upload yang masih tersimpan di asset/files:

- assets/files/galeri/
- assets/files/artikel/
- assets/files/gis/lokasi/
- assets/files/gis/garis/
- assets/files/gis/area/
- assets/files/dokumen/

File yang diunggah ini perlu dipindahkan ke folder desa.

**Comment by metalab25** [comment]
mana filenya om

**Comment by eddieridwan** [comment]
File upload assets/files sudah dipindah ke desa/uploads pada v0.5.2.
