### ISSUE TITLE
Jangan unggah berkas berisi script PHP

### ISSUE THREAD

**Issue by eddieridwan** [eddieridwan/OpenSID#560]
Saat ini, berkas berisi script PHP masih bisa diunggah ke arsip dokumen dan dokumen kependudukan (oleh hacker yang punya tools untuk mengelabui browser).

Cara untuk mencegah itu yang diketahui saat ini adalah dengan:

1. tidak mengizinkan berkas dengan extension .php
2. tidak mengizinkan berkas dengan isi string `<?php`, `<?=`, `<?`, `<%` atau `<script`

**Comment by pandigresik** [comment]
Kalau dicek mime type di sisi server pakai php ? Jadi yang diizinkan hanya mime type yang image aja

**Comment by eddieridwan** [comment]
@pandigresik Saat ini, mime-type sudah diperiksa. Tools yang digunakan mengubah mime type sebelum dikirim ke server. Jadi issue ini bukan lagi untuk hacker 'iseng', tapi yang agak berilmu.

**Comment by eddieridwan** [comment]
Ini contoh diskusi untuk mendeteksi script PHP yg disembunyikan di dalam image file: https://webmasters.stackexchange.com/questions/89671/how-to-detect-if-file-with-a-png-extension-contains-code-or-an-image

**Comment by eddieridwan** [comment]
Ternyata file image dan pdf banyak yang mengandung teks `<?` dan `<%`. Jadi solusi yang kami terapkan adalah:

1. tidak mengizinkan berkas dengan extension .php
2. tidak mengizinkan berkas dengan isi string `<?php`, `<?=` atau `<script`.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
