### ISSUE TITLE
Form inputan data PHP untuk membuat surat KK pada menu Cetak Surat 

### ISSUE THREAD

**Issue by sukmaalamsyah** [eddieridwan/OpenSID#565]
Pada menu cetak surat tidak ada menu untuk pembuatan Surat KK, sedangkan pada folder surat sudah tersedia file kk.rtf nya, apakah bisa membuat form php nya untuk menginputkan data langsung sesuai dengan format kk. Di desa saya banyak yang mengurus KK sesuai dengan blanko sama seperti format rtf yang ada pada aplikasi tetapi tidak ada form untuk penginputan data KK tersebut.

**Comment by metalab25** [comment]
Perlu diluruskan bahwa desa tidak membuatkan KK, yang membuatkan KK adalah Capil.
Jadi disediakan fitur cetak KK itu adalah merupakan salinan dari format yang ada di Capil.
Salinan KK bisa di cetak melalui menu penduduk > keluarga > rincian pada keluarga yang salinan KKnya mau dicetak

**Comment by MUHAMMADRANGSEL** [comment]
Betul sekali itu merupakqn salinan dr format dukcapil, kalqu untuk pembuqtqn KK sdh tersedia

**Comment by metalab25** [comment]
Ya benar kalo surat pengantarnya sudah tersedia

**Comment by sukrimalendra** [comment]
clear

**Comment by eddieridwan** [comment]
Data untuk KK tinggal diisi pada halaman Keluarga dan Penduduk.
