### ISSUE TITLE
Bug: bisa kirim artikel tanpa judul dan isi

### ISSUE THREAD

**Issue by telo99** [eddieridwan/OpenSID#567]
![sidartikel](https://user-images.githubusercontent.com/30897391/29390342-e6f9e518-8319-11e7-96d7-0058d1f1d60b.jpg)

Mungkin jarang terjadi, tapi ya agak aneh aja kalau bisa kirim artikel kosong :).

**Comment by eddieridwan** [comment]
Sudah di master melalui pull request #567.
