### ISSUE TITLE
error loading Google Maps SID di hosting

### ISSUE THREAD

**Issue by metalab25** [eddieridwan/OpenSID#57]
saya baru aja coba onlinekan openSID ke hosting, semua berjalan lancar. tapi setelah saya cek ulang widget map lokasi desa mengalami masalah
"Oops! Something went wrong.
This page didn't load Google Maps correctly. See the JavaScript console for technical details."
setelah saya seaching by google ternyata bermasalah dengan api key.
saya cek di SID saya tidak menemukan api key

apakah ada yang bisa membantu

![untitled](https://cloud.githubusercontent.com/assets/19917739/16337538/e4f8aae4-3a48-11e6-9844-d3bbc60a605b.jpg)

**Comment by eddieridwan** [comment]
Google map sekarang memerlukan api key: [https://www.latecnosfera.com/2016/06/google-maps-api-error-missing-keymap-error-solved.html](https://www.latecnosfera.com/2016/06/google-maps-api-error-missing-keymap-error-solved.html).

Key tersebut harus ditambahkan di belakang setiap script yang memanggil google maps, seperti berikut:
http://maps.googleapis.com/maps/api/js?v=4&sensor=false&key=YOUR_API_KEY 

Sepertinya setiap desa perlu mendapatkan Google map key sendiri. Jika demikan, script perlu diperbaiki supaya tidak harus diubah oleh masing2 desa untuk memasukkan key mereka. Yaitu, API key perlu diambil dari satu tempat saja yang mudah diubah desa.

**Comment by eddieridwan** [comment]
Mungkin tambahkan file konfigurasi, _opensid.ini_, yang disimpan di folder desa/config, untuk meletakkan semua setting seperti Google Maps API key.

http://php.net/parse_ini_file

**Comment by eddieridwan** [comment]
@batudaa, anda tertarik untuk menerapkan ini?

**Comment by eddieridwan** [comment]
Diterapkan memakai file konfigurasi _sid.ini_, dan dibaca oleh script config/sid_ini.php ke dalam variable $config.
