### ISSUE TITLE
Tampilan menu plan masih berantakan

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#571]
Perlu diperbaiki tampilan pada menu Plan yang masih berantakan seperti gambar dibawah ini :
1. sub mwnu lokasi
![image](https://user-images.githubusercontent.com/25834335/29403074-5d0543c8-8361-11e7-8d0c-afd3766c5872.png)
2. sub menu garis
![image](https://user-images.githubusercontent.com/25834335/29403105-73f4c02c-8361-11e7-8567-2cc3c994ea48.png)
3. sub menu tipe garis
![image](https://user-images.githubusercontent.com/25834335/29403121-8119010a-8361-11e7-91bf-33d909f8285b.png)
4. sub menu area
![image](https://user-images.githubusercontent.com/25834335/29403121-8119010a-8361-11e7-91bf-33d909f8285b.png)
5. sub menu polygon
![image](https://user-images.githubusercontent.com/25834335/29403152-9d82c4ca-8361-11e7-9e54-936c6011cde0.png)

**Comment by MUHAMMADRANGSEL** [comment]
di rubah seperti tampilan tipe point
![image](https://user-images.githubusercontent.com/25834335/29403214-e1a5893a-8361-11e7-8d1e-d4a63efc3596.png)

**Comment by metalab25** [comment]
Sebenarnya menu plan sudah harus mulai digarap karna ini masuk dalam bagian pekerjaan perencanaan desa.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui pull request #580.
