### ISSUE TITLE
Form layanan mandiri tetap muncul ketika sudah login

### ISSUE THREAD

**Issue by simasta** [eddieridwan/OpenSID#578]
![2017-08-19_212819](https://user-images.githubusercontent.com/26613576/29487612-720d7c2e-8526-11e7-8099-684b1f8f0d4f.jpg)

**Comment by metalab25** [comment]
Itu memang tetap muncul cuma bukan form login tetapi form untuk mengganti pin

**Comment by simasta** [comment]
Eh iya, kurang jeli saya, tapi kok title nya masih sama ya..
