### ISSUE TITLE
Penyesuaian Hasil Export Data dengan Import Data dan Penambahan Fitur Export Data CSV di Menu Database/export

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#587]
Penyesuaian Hasil Export Data dengan Import Data dan Penambahan Fitur Export Data CSV di Menu Database/export
![tangkapan layar 2017-08-22 09 35 11](https://user-images.githubusercontent.com/25834335/29547001-c9ef2814-8721-11e7-9eed-12351078d2cb.png)

dan adapun perbaikan dan penambahan scripnya seperti terlampir
[Perbaikan Export data Excel dan Penambahan Fitur Export CSV.zip](https://github.com/eddieridwan/OpenSID/files/1240659/Perbaikan.Export.data.Excel.dan.Penambahan.Fitur.Export.CSV.zip)

export ecxcel  hasilnya seperti dibawah ini 👍 
![image](https://user-images.githubusercontent.com/25834335/29547072-3217f858-8722-11e7-86c5-72cbfb853f76.png)

untuk hasil export data CSV belum sesuai dengan hasil import excel mas eddie agak sulit saya belum bisa buat.

**Comment by MUHAMMADRANGSEL** [comment]
menurut saya ini sangat membantu ketika ada kesalahan terutama setelah meng import data seperti yang saya alami

**Comment by sukrimalendra** [comment]
Mantab

**Comment by eddieridwan** [comment]
Ok, nanti di lihat.

**Comment by MUHAMMADRANGSEL** [comment]
Smga segera dicommit

Pada tanggal 22 Agt 2017 18:18, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.

Tetapi seperti apa adanya. Hanya dengan sedikit penyesuaian, supaya cocok dengan contoh data awal.
Harap buat issue baru untuk penyesuaian export data CSV. Perlu diperhatikan, hasil export CSV memang tidak bisa diimport menggunakan import Excel, karena format berbeda. Untuk import CSV diperlukan fitur terpisah.

**Comment by MUHAMMADRANGSEL** [comment]
Ok siap mas Eddie
