### ISSUE TITLE
Data untuk surat keterangan kelahiran di ambilkan dari  database penduduk

### ISSUE THREAD

**Issue by justotemon** [eddieridwan/OpenSID#591]
pada surat kelahiran kolom saksi 
![saksi](https://user-images.githubusercontent.com/24327651/29656322-5549131c-88de-11e7-9adb-f13d6ff3e469.JPG)

yang sering melaporkan adalah kerabat dari keluarga bayi,, adalah penduduk desa sendiri. dari pada memasukan manual biodata, usul agar data biodata tersebut di load dari database penduduk seperti halnya ibu dari bayi
![ibu](https://user-images.githubusercontent.com/24327651/29656236-165be238-88de-11e7-9ce3-ed085691750c.JPG)

terima kasih

**Comment by fathurvbf** [comment]
@eddieridwan saya riview lagi mas eddie Perbaikannya ?

**Comment by bhien76** [comment]
Hampir sama dengan dengan Surat Keterangan Kematian, apabila data form saksi 1 dan 2 diambilkan dari database kependudukan akan mempercepat pengerjaan Surat Keterangan Kelahiran dan lampirannya. Surat ini sangat dibutuhkan desa, karena merupakan salah satu surat yang banyak diminta oleh masyarakat

**Comment by fathurvbf** [comment]
Kerena Form Surat keterangan kelahiran sudah hampir sama dengan Versi Ducapil, dan ada beberpa yang masih kurang sempurna alangkah baiknya disempurnakan. Karena Penerapan Surat keterangn kelahiran ini hampir setiap saat dikeluarkan dari TK. Desa hingga ducapil

**Comment by eddieridwan** [comment]
@fathurvbf silakan lampirkan bentuk surat keterangan yang diinginkan (versi Disdukcapil?). Apa yang perlu disempurnakan? Selalu beri rinciannya, supaya jelas apa yang diinginkan.

**Comment by eddieridwan** [comment]
Anggota Pokja: Untuk kolom isian _Hubungan Pelapor dengan Bayi_, pilihannya apa saja? Lebih mudah dan konsisten jika bisa diisi menggunakan pilihan (seperti Pekerjaan) daripada harus mengarang sendiri.

**Comment by eddieridwan** [comment]
Sekarang, data berikut bisa dari database atau diisi manual:

1. ibu kandung
1. yang lahir
1. pelapor
1. saksi1
1. saksi2

Salah satu dari (1) ibu kandung atau (2) yang lahir harus dari database penduduk.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.

Jika ingin perbaikan tambahan, silakan buat issue baru.
