### ISSUE TITLE
lampiran surat kematian F 2.29

### ISSUE THREAD

**Issue by justotemon** [eddieridwan/OpenSID#592]
[SURAT KEMATIAN  F - 2.29.xlsx](https://github.com/eddieridwan/OpenSID/files/1248944/SURAT.KEMATIAN.F.-.2.29.xlsx)
Mohon memasukan form ini ke lampiran data surat kematian. 
Dan form saksi 1 & saksi 2 di ambilkan dari database penduduk 
Terimakasih

**Comment by bhien76** [comment]
Lampiran Surat F-2.29 merupakan lampiran Surat Keterangan Kematian yang sangat diperlukan oleh desa. karena selama ini pengisian Surat Keterangan Kematian disi satu persatu secara manual. dan ini merupakan salah satu dari sekian banyak administrasi surat menyurat yang dibutuhkan desa. Dan data form saksi 1 & saksi 2 kalau diambilkan dari database kependudukan akan mempercepat pengerjaan kedua surat tersebut

**Comment by afri18** [comment]
data langsung diambil dari log_penduduk termasuk tanggal kematian

**Comment by fathurvbf** [comment]
Hampir sama dengan Surat keterangan kelahiran.

**Comment by eddieridwan** [comment]
[F-2.29_SURAT_KETERANGAN_KEMATIAN_DESA.pdf](https://github.com/eddieridwan/OpenSID/files/1340188/F-2.29_SURAT_KETERANGAN_KEMATIAN_DESA.pdf)

![f-2 29_surat_keterangan_kematian_desa](https://user-images.githubusercontent.com/249563/30958137-91624e7e-a47f-11e7-9287-b768db096d09.jpg)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui perubahan PR https://github.com/eddieridwan/OpenSID/pull/636.

**Comment by eddieridwan** [comment]
Versi ini masih berasumsi data yang meninggal belum diubah status dasarnya -- yaitu statusnya masih 'hidup'. Pengambilan data yang meninggal sesudah diubah status dasarnya nanti dilakukan melalui issue https://github.com/eddieridwan/OpenSID/issues/498.

**Comment by afri18** [comment]
sebaiknya setiap surat kematian mengarah ke log_penduduk, dengan sendirinya status dasarnya sudah dirubah, gunanya agar admin/operator tidak lupa/sebagai koreksi data
