### ISSUE TITLE
Bug: menghapus surat keluar seharusnya juga menghapus berkas surat dan lampiran

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#598]
Perlu diperbaiki seperti halnya menghapus poto galeri, artikel dan poto perangkat desa, ketika menghapus surat keluar di menu surat keluar seharusnya arsip surat keluar yang diexport atau lampiran  yang ada di folder desa/arsip ikut terhapus.
sehingga arsip surat keluar tidak numpuk 
![cetak surat](https://user-images.githubusercontent.com/25834335/29819984-19b337ca-8ced-11e7-8725-9245dd6a35c0.jpg)

semoga segera dikerjjakan

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
