### ISSUE TITLE
Upload Poto Waktu menambah artikel baru tdk tampil

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#599]
setelah saya mencoba membuat artikel baru pas waktu upload poto ternyata foto tdk tampil
![tangkapan layar 2017-08-29 22 37 07](https://user-images.githubusercontent.com/25834335/29829995-1f5cf8d2-8d0b-11e7-90e3-905626904368.png)
tapi difolder desa/upload/artikel fotonya ada
![tangkapan layar 2017-08-29 22 38 33](https://user-images.githubusercontent.com/25834335/29830028-3a03abf4-8d0b-11e7-913d-4869eff88d7e.png)
dan juga tombol simpan kurang merespon
![tangkapan layar 2017-08-29 22 36 46](https://user-images.githubusercontent.com/25834335/29830061-52622694-8d0b-11e7-9558-d6c23b0300c7.png)

**Comment by MUHAMMADRANGSEL** [comment]
dengan kurang responyya tombol simpan menyebabkan gambar yang diupload menjadi double
![tangkapan layar 2017-08-29 23 05 54](https://user-images.githubusercontent.com/25834335/29831291-d2c0a5d8-8d0e-11e7-9a77-5f49393f3deb.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.

**Comment by MUHAMMADRANGSEL** [comment]
tinggal fotonya yang belum ikut terhapus ketika menghapus artikel mas eddie

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL Untuk itu, silakan buat issue baru.

**Comment by MUHAMMADRANGSEL** [comment]
siap

Pada tanggal 30 Agt 2017 08:22, "Eddie Ridwan" <notifications@github.com>
menulis:
