### ISSUE TITLE
waktu masuk login seharusnya yang muncul submenu identitas desa

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#600]
waktu masuk login yang muncul ini
![image](https://user-images.githubusercontent.com/25834335/29831012-0dde404a-8d0e-11e7-9adc-854792c6120c.png)

seharusnya ini
![image](https://user-images.githubusercontent.com/25834335/29831046-2492586c-8d0e-11e7-9370-cdf4ce5d2c96.png)

**Comment by eddieridwan** [comment]
Perubahan ini sengaja dibuat supaya pengguna baru membaca info mengenai SID. Karena sepertinya, banyak pengguna tidak mengerti betul tujuan SID dan tidak tahu di mana bisa memperoleh informasi mengenai OpenSID. Mungkin isi halaman ini bisa dilengkapi dan dipercantik supaya lebih jelas dan memberi arahan bagi pengguna baru.

Bagi pengguna lama, mereka juga tidak selalu ingin ke halaman _Identitas Desa_. Halaman ini biasanya jarang dikunjungi setelah pertama kali diisi. Itupun tinggal klik saja untuk ke halaman _Identitas Desa_.

**Comment by MUHAMMADRANGSEL** [comment]
OK siap mas eddie

**Comment by MUHAMMADRANGSEL** [comment]
Ok siap mas eddie

Pada tanggal 30 Agt 2017 07:25, "Eddie Ridwan" <notifications@github.com>
menulis:
