### ISSUE TITLE
Bug: menghilangkan tanda titik2 Bulat di samping poto aparatur desa

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#601]
_Disamping Poto SLIDER Aparatur Desa ada Titik2 bulat yang perlu dihilangkan : _ 
![tangkapan layar 2017-08-29 23 09 37](https://user-images.githubusercontent.com/25834335/29831604-d61ce15a-8d0f-11e7-8657-a47312a642d7.png)

perubahn scripnya
[aparatur_desa.zip](https://github.com/eddieridwan/OpenSID/files/1260946/aparatur_desa.zip)

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL solusi anda menghilangkan titik2 sama sekali, termasuk yang ingin ditampilkan supaya bisa melihat berapa jumlah foto dan supaya bisa langsung menampilkan foto tertentu.

Solusi yang dicari adalah style yang bisa menampilkan titik2 itu secara benar di tampilan mobile (layar kecil), bukan menghilangkan titik2 itu.

**Comment by eddieridwan** [comment]
Kami tidak bisa mereplikasi masalah ini, baik di laptop maupun di Android. Apakah ada url website di mana masalah ini ditemukan -- yang sudah versi v2.5? Supaya kami bisa cek dari laptop dan Android.

**Comment by MUHAMMADRANGSEL** [comment]
![tangkapan layar 2017-09-02 10 44 51](https://user-images.githubusercontent.com/25834335/29992746-19a40042-8fcd-11e7-90e1-622b95908364.png)
di http://sid.bangundesa.info  versi 2.5  juga masih ada titik2 bulat mas eddie seperti gambar dibawah ini :

**Comment by eddieridwan** [comment]
Dihilangkan dengan menghilangkan pager-template untuk slider-besar dan slider-aparatur-desa:

```
	$(document).ready(function() {
    $('#aparatur_desa').cycle({
			pauseOnHover: true,
			// Untuk menghilangkan titik-titik di cycle pager
			pagerTemplate: '<span></span>'
		});
	});
```

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.
