### ISSUE TITLE
waktu menghapus artikel  foto tidk ikut terhapus

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#602]
![tangkapan layar 2017-08-29 22 38 33](https://user-images.githubusercontent.com/25834335/29850153-bbb91e82-8d55-11e7-8664-8a78f5791c29.png)

**Comment by eddieridwan** [comment]
Sudah dicommit ke master. Sekalian menghapus gambar lama pada waktu mengunggah gambar artikel pengganti.
