### ISSUE TITLE
Mohon buatkan Surat Keterangan Izin Suami/Istri

### ISSUE THREAD

**Issue by sukrimalendra** [eddieridwan/OpenSID#603]
Desa kami sering membuat Surat Keterangan Izin Suami/Istri untuk masyarakat yang bepergian ke luar negeri untuk bekerja sebagai TKI. Oleh karena itu mohon dibuatkan Surat Keterangan Izin Suami/Istri seperti pada lampiran dibwah ini. 
[ket. izin adi.pdf](https://github.com/eddieridwan/OpenSID/files/1270071/ket.izin.adi.pdf)

**Comment by MUHAMMADRANGSEL** [comment]
Isuue sudah dibuat silahkan lihat issue #259

**Comment by eddieridwan** [comment]
Ok, issue ini ditutup karena duplikat dari #259.

**Comment by sukrimalendra** [comment]
Baik. Terimakasih atas infonya bapak-bapak.

Pada tanggal 2 Sep 2017 9:35 AM, "Eddie Ridwan" <notifications@github.com>
menulis:
