### ISSUE TITLE
Perubahan Posisi Slider Besar

### ISSUE THREAD

**Issue by bhien76** [eddieridwan/OpenSID#605]
Bang Eddi, kalau bisa peletakan posisi gambar slider besar dirubah dari posisi depan ke belakang sama seperti posisi artikel. seperti yg saya kasih lihat di gambar 1. 
![1](https://user-images.githubusercontent.com/28255642/29997278-de94d6aa-9041-11e7-8aa7-33fed15d3778.jpg)
![2](https://user-images.githubusercontent.com/28255642/29997283-fae0b432-9041-11e7-8b73-b4fa30c4ff7b.jpg)

**Comment by sukrimalendra** [comment]
Bang @bhien76. Bagaimana caranya merubah gambar baground webnya?

**Comment by bhien76** [comment]
ganti gambar dgn nama img1.jpg di folder themes, default, css, images dengan gambar pengganti degan nama yg sama

**Comment by eddieridwan** [comment]
@sukrimalendra bertanya yang tidak terkait issue jangan di issue. Tanyakan di https://www.facebook.com/groups/OpenSID/. Issue khusus digunakan untuk membahas penerapan masalah/permintaan yang diajukan.

**Comment by eddieridwan** [comment]
@bhien76 saya melihat situs anda di http://kalaena-kiri.daftarhosting.id/. Saya tidak melihat masalah tumpang tindih seperti yang anda tunjukkan di atas, walaupun lebar browser diperkecil. Di browser Android pun tidak tampak masalah ini. Mungkin bisa beri info di mana masalah ini bisa dilihat.

**Comment by sukrimalendra** [comment]
Baik pak @eddie. Terimakasih

Pada tanggal 3 Sep 2017 10:05 AM, "Eddie Ridwan" <notifications@github.com>
menulis:
