### ISSUE TITLE
masalah waktu membuat menu dinamis

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#606]
![tangkapan layar 2017-09-04 19 21 57](https://user-images.githubusercontent.com/25834335/30026348-b89afb12-91a6-11e7-9ddc-e98abf64918e.png)
tiba tiba didalam didalam rincian surat keputusan sudah ada ini sperti digambar
![tangkapan layar 2017-09-04 19 23 13](https://user-images.githubusercontent.com/25834335/30026367-cc139bc2-91a6-11e7-896b-fb328675eff3.png)

anehnya lagi didalam surat keputusan ada artikel sedangkan artikel yang muncul dari artikel statis
![tangkapan layar 2017-09-04 19 26 25](https://user-images.githubusercontent.com/25834335/30026459-3754d6d0-91a7-11e7-9d1f-01a64f9905db.png)

apa ada yang salah...?????

**Comment by MUHAMMADRANGSEL** [comment]
Herannya maslahnya hanya di ONLINE kalau offline lancar.
Dan Selama saya hosting seringkali ada masalah
1. Menambahkan Widget baru masalah
2. membuat menu dinamis masalah
Kira2 Apa Maslahnya..."????

**Comment by eddieridwan** [comment]
@MUHAMMADRANGSEL sepertinya terbuat kategori dengan nilai '0'. Jadi rincian menampilkan semua kategori lagi, bukan subkategori dari kategori _Surat Keputusan_.

Karena kategori bernilai '0', di artikel dengan kategori itu, mungkin sudah ada dari sebelumnya.

Coba buat menu dinamis lagi yang baru. Berapa index (kode) untuk kategori itu? Kode kategori adalah bilangan terakhir di url pada waktu melihat rincian.

Tapi kalau juga bermasalah dengan widget dll, mungkin database anda di server online rusak dan perlu dibuat baru.

**Comment by MUHAMMADRANGSEL** [comment]
Ok siap mas eddie

**Comment by MUHAMMADRANGSEL** [comment]
Kira2 apa yg menyebabkan error atau rusak...? Apakah xammp yg dipakai online haris sama dengan yg di offline

**Comment by eddieridwan** [comment]
Tidak harus sama. Asal PHP, Apache, PHPMyadmin, Mysql dstnya saling kompatibel dan terinstall yang benar. Tergantung hostingnya. Mudah2an masalah anda telah teratasi.

**Comment by MUHAMMADRANGSEL** [comment]
saya td memback up dan menghapus beberapa menu lewat phpmyadmin offline dan
saya ambilkan dari rilis terbaru OpenSID dan saya import lg dilocalhost
setelah bisa saya import ulqng dionline database sqlnya alhmdllh bisa tp
buat artikel baru lg mas

Pada tanggal 5 Sep 2017 17:01, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by MUHAMMADRANGSEL** [comment]
Mudah2an waktu update OpenSID versi 2.6 yg akan dtg tdk ada lg yg maslah

Pada tanggal 5 Sep 2017 18:07, "MUHAMMAD SPD" <muhammadrangsel@gmail.com>
menulis:

**Comment by eddieridwan** [comment]
Heheh... tidak ada software/aplikasi yang tidak bermasalah... pasti ada bug atau sesuatu yang tidak jalan... karena variasi sistem tempat jalannya aplikasi begitu banyak dan tidak mungkin diuji semua....

**Comment by MUHAMMADRANGSEL** [comment]
Ya sih mas trima kasih atas sarannya

Pada tanggal 5 Sep 2017 18:14, "Eddie Ridwan" <notifications@github.com>
menulis:

**Comment by MUHAMMADRANGSEL** [comment]
diphpmyadmin localhost / offline
![tangkapan layar 2017-09-05 20 40 22](https://user-images.githubusercontent.com/25834335/30064778-ff467600-927c-11e7-8fe9-1bdc90ed184e.png)
sedangkan di server atau online
![tangkapan layar 2017-09-05 20 40 27](https://user-images.githubusercontent.com/25834335/30064818-1c0a5bbc-927d-11e7-83ec-0e4a01cae85d.png)

ternyata disinilah letak masalahnya
