### ISSUE TITLE
Logo Cetak Surat dibuatkan atau diambilkan dari tempat lain

### ISSUE THREAD

**Issue by bhien76** [eddieridwan/OpenSID#607]
Bang @eddieridwan, saya usul, kalau bisa untuk fasilitas cetak surat, logonya dibuatkan atau dibuatkan link untuk ngambil gambar lain, bukan dari logo desa yg ada di sid home/identitas desa. karena, kalau di kabupaten kami, desa tidak diperbolehkan menggunakan logo warna untuk surat menyurat. gak tau kalau kabupaten lain
![admin](https://user-images.githubusercontent.com/28255642/30058633-72fb532c-926e-11e7-999f-73a94f4616b1.jpg)
![contoh surat](https://user-images.githubusercontent.com/28255642/30058657-913aa356-926e-11e7-816b-fa8fb89b292b.jpg)

**Comment by MUHAMMADRANGSEL** [comment]
Kalau yg begitu tinggal di ganti sajq logo warna dengan tidak berwarna

**Comment by eddieridwan** [comment]
@bhien76 , cara sederhana adalah: cetak saja hitam-putih...

Terpisah dari solusinya, rilis OpenSID tidak akan memperbaiki atau mengembangkan fitur cetak surat langsung. Rekomendasi kami adalah agar desa hanya menggunakan fitur cetak Export Doc. Silakan lihat penjelasan di  [[Panduan-Mencetak-Surat]].

Tetapi, jika masih ingin menggunakan cetak langsung, silakan kembangkan sendiri.
