### ISSUE TITLE
Pada tampilan mobile tema hadakewa, tampilkan submenu dengan klik, untuk tetap terbuka

### ISSUE THREAD

**Issue by dadannurman** [eddieridwan/OpenSID#614]
Mohon maaf suhu, @metalab25 

Saya coba buka situs demo via PC,
Saat kursor saya arahkan ke menu "pemerintah Desa" (tanpa klik), muncul otomatis sub-menu dropdown "visi dan misi"
"pemerintah desa"

![tema](https://user-images.githubusercontent.com/28327817/30256197-16b4c5bc-96d3-11e7-97b7-6e91b85a6fc2.png)

Tetapi ketika di klik menu "pemerintah desa", dia langsung menuju halaman "pemerintah desa" (http://sid.bangundesa.info/index.php/first/artikel/85)

![tema4](https://user-images.githubusercontent.com/28327817/30256388-89eb85b0-96d4-11e7-97cd-62d6de414a65.png)

Berbeda dengan situs Desa Hadakewa http://www.hadakewa.desa.id/first, untuk memunculkan sub-menu dropdown harus meng-klik dulu menu "pemerintah desa", baru muncul sub-menunya. Jadi ketika di klik menu "pemerintah desa" dia tidak menuju ke halaman "pemerintah desa"

![tema2](https://user-images.githubusercontent.com/28327817/30256237-752ace16-96d3-11e7-8410-8ccc01be75e4.PNG)

Di situs Desa Hadakewa http://www.hadakewa.desa.id/first akan memudahkan pada Mobile Device, ketika ingin membuka sub-menu (contoh "visi dan misi") maka tinggal mengklik "pemerintah desa" dan klik lagi "sub menu "visi dan misi", (tanpa meredirect langsung ke halaman "pemerintah desa")

Tetapi jika di situs Demo (via Mobile Device) ingin menuju ke salah satu sub-menu akan susah, karena saat mengklik salah satu menu, dia akan langsung menuju halaman menu walaupun muncul sub-menu nya sebentar.
Contoh d bawah ini,

![tema5](https://user-images.githubusercontent.com/28327817/30256547-db3e31dc-96d5-11e7-9348-2adcafd66f99.png)

meng-klik menu "pemerintah desa" langsung menuju ke halaman "pemerintah desa" walaupun sub-menu nya muncul tapi kalah cepat dengan halaman "pemerintah desa" yang di tuju.

**Comment by metalab25** [comment]
Ada yabg harus diubah pada menu_tpl.php

**Comment by dadannurman** [comment]
apakah mungkin diterapkan di pada rilis selanjutnya bung?

**Comment by eddieridwan** [comment]
Cara bekerja menu atas sama pada kedua tema: _default_ dan _hadakewa_. Cara bekerja saat ini adalah berdasarkan rancangan yang sudah ada sejak SID CRI: yaitu menu utama ketika di-klik fungsinya adalah untuk menampilkan artikel, yang biasanya berisi keterangan untuk memperkenalkan/menjelaskan isi sub-menu. Jadi tidak beda dengan fungsi sub-menu, yang juga menampilkan artikel pada saat di-klik.

Saat ini sub-menu ditampilkan hanya pada saat mouse berada di atas menu utama.

Cara bekerja ini bisa saja diubah di rilis. Tetapi, untuk dikerjakan, diperlukan:

1. konsultasi dengan pengguna lainnya -- supaya mereka juga setuju. Ingat banyak yang menggunakan tema _hadakewa_. Dan belum tentu semua setuju dengan perubahan yang anda usulkan. Konsultasi ini sebaiknya dilakukan di https://www.facebook.com/groups/OpenSID/.
2. persetujuan Kelompok Kerja Analisis Kebutuhan OpenSID supaya issue ini diprioritaskan. Pokja dapat dihubungi melalui channel #analisis-kebutuhan di https://opensid.slack.com/messages/C6XQEDF3Q/details/.

**Comment by eddieridwan** [comment]
Diterapkan sebagai berikut:
1. di layar PC tidak berubah
2. di layar mobile, klik menu untuk menampilkan sub menu, terus
    1. klik menu untuk navigasi ke tautannya
    2. klik submenu untuk navigasi ke tautannya

Tapi masih ada masalah: langkah (2.i) seharusnya hanya berlaku pada menu yang terbuka, dan tidak pada menu lainnya.

**Comment by eddieridwan** [comment]
Ok, sudah diperbaiki. Sekarang di tampilan mobile hadakewa, menu atas hanya bisa di-klik untuk navigasi ke tautannya jika submenunya sudah tampil.

Sudah dicommit ke master.

**Comment by dadannurman** [comment]
Mohon maaf bung @eddieridwan, kata
"apakah mungkin diterapkan di pada rilis selanjutnya bung?"
maksud saya adalah d usulkan pada rilis selanjutnya, mohon maaf atas kelancangan saya bung @eddieridwan 🙏🏻
