### ISSUE TITLE
Tata ulang menu Cetak Surat dan Dokumen 

### ISSUE THREAD

**Issue by afri18** [eddieridwan/OpenSID#617]
setelah saya perhatikan ada yg janggal di menu Cetak Surat, di sub menu ada sub menu "surat keluar" dan "surat masuk", sepintas seperti kearsipan surat masuk dan keluar, padahal menurut saya berbeda,di sub menu "surat keluar" adalah surat untuk layanan masyarakat sedangkan disub menu "surat masuk" adalah inventarisir "surat masuk"
![image](https://user-images.githubusercontent.com/6611881/30366437-35a0bd1e-9895-11e7-93b9-ac1fa8280420.png)
agar tidak membingungkan sebaiknya nama menu "Cetak Surat" diganti menjadi menu "Layanan Surat" dan sub menu "Surat Keluar" diganti menjadi sub menu "Catatan Layanan" dan .....
menambahkan satu menu lagi dengan nama menu "Sekretariat" yang sub menunya :
1, Surat Keluar (Catatan surat keluar Pemerintah Desa / bukan surat layanan)
2 Surat Masuk ( Catatan Surat Masuk untuk Pemerintah Desa
3 SK Kades (Catatan Surat Keputusan Kepala Desa)
4 PERDES (Catatan Pemerintah Desa dalam mengeluarkan Peraturab Desa)
5 INVENTARIS (Catatan inventaris Barang/Usaha milik Desa)
![tambahmenu](https://user-images.githubusercontent.com/6611881/30366751-5a1896de-9896-11e7-8af7-7b920f2ac3f5.png)

**Comment by eddieridwan** [comment]
Penataan menu Cetak Surat dan Sekretariat sudah dicommit ke master. 

Fitur Sekretariat > Surat Keluar dan Sekretariat > Inventaris Desa hanya tombol saja. Perlu dibuatkan issue baru untuk masing2 fitur untuk diterapkan di lain waktu.

**Comment by afri18** [comment]
kalau dah jadi dasyaat ...
