### ISSUE TITLE
Widget Peta Desa gagal menampilkan Peta

### ISSUE THREAD

**Issue by abahku** [eddieridwan/OpenSID#621]
Awalnya saya ingin menyesuaikan Widget Peta Desa di Web dengan Peta Desa kami. Lalu saya menghapus Kode Widget Peta Desa seperti di gambar berikut (saya simpan Kode Widget di tempat lain untuk antisipasi Error), sebelum saya menempatkan Kode Widget Peta Desa yang baru.

![screen shot 2017-09-16 at 15 10 13](https://user-images.githubusercontent.com/31700811/30510529-4f7b2dd4-9af0-11e7-94ae-8c0c7c0d55dd.png)

dan hasilnya seperti berikut ini, dimana Widget Peta Desa menjadi kosong. 

![screen shot 2017-09-16 at 15 19 46](https://user-images.githubusercontent.com/31700811/30510555-a0006b3e-9af0-11e7-8d00-5385b9d8ba91.png)

Karena saya belum mendapatkan Kode Widget Peta Desa yang baru, lalu saya tempatkan kembali Kode Widget yang tadi saya hapus (simpan), saya lanjutkan dengan mengklik tombol simpan.

![screen shot 2017-09-16 at 15 24 50](https://user-images.githubusercontent.com/31700811/30510589-54651c00-9af1-11e7-9030-35358d31c92e.png)

Kembali saya buka web tersebut namun hasilnya tidak menampilkan peta, melainkan pada box Widget Peta Desa yang ditampilkan adalah Kode Widget Peta Desa tersebut. Berikut penampakannya.

![screen shot 2017-09-16 at 15 05 36](https://user-images.githubusercontent.com/31700811/30510609-98e11dc0-9af1-11e7-8391-9fa11b542b51.png)

Sampai Issue ini saya lotarkan, saya juga masih mencoba untuk mengatasi masalahnya. Semoga aja ketemu. Saya juga memohon bantuan rekan-rekan lain untuk menemukan solusinya.

Terima kasih.

**Comment by MUHAMMADRANGSEL** [comment]
Coba masuk lewat phpmyadmin cari widget peta desa lalu hapus scrip yg ada copy.paste yg baru

**Comment by MUHAMMADRANGSEL** [comment]
Di php myadmin ternyata ada tambahan scrip disana shgg tdk tampil widget peta

**Comment by eddieridwan** [comment]
Masalah ini disebabkan penambahan global_xss_filter pada rilis sebelumnya, untuk mencegah serangan xss. Filter itu menyebabkan semua isian javascript dihilangkan, dan semua isian html di-nonaktifkan. Karena memang resiko keamanan.

Solusinya, khusus untuk widget dinamis, tag html dikembalikan pada waktu ditampilkan. Tetapi solusi ini tidak bisa mengembalikan javascript apabila widget dinamis berisi javascript. Dalam hal ini, alternatifnya adalah membuat widget statis dengan script yang sama. Karena widget statis disimpan di file (tidak di database), yang hanya bisa dilakukan admin yang mempunyai akses ke server/cpanel, seharusnya lebih aman.

**Comment by eddieridwan** [comment]
Sudah dicommit ke master.

**Comment by abahku** [comment]
Terima kasih Pak @eddieridwan

**Comment by abahku** [comment]
Alhamdulillah ... sdh ok.
