### ISSUE TITLE
Widget dinamis tidak bisa membaca script html

### ISSUE THREAD

**Issue by healm4n** [eddieridwan/OpenSID#625]
tolong bantuannya temen2, setelah update bertahap dari 1.7 ke 2.5.1 saya menemukan kendala pada widget yang saya tambahkan.

**sebelum update (masih versi 1.7)**
![16](https://user-images.githubusercontent.com/3977384/30518198-dc225dec-9ba0-11e7-864e-d187ea9ddf74.png)

**setelah update (versi2.5.1)**
![17](https://user-images.githubusercontent.com/3977384/30518199-dc4da90c-9ba0-11e7-97ef-304c05903c58.png)

sebelumnya saya ucapkan terima kasih

**Comment by batudaa** [comment]
Di versi baru ini secara default sudah mengaktifkan **global_xss_filtering** di konfigurasi (donjo-app/config/config.php), yang mana akan mencegah inputan berupa tag iframe.

**Comment by healm4n** [comment]
terima kasih mas atas petunjuknya

**Comment by eddieridwan** [comment]
Khusus untuk penampilan widget dinamis, di https://github.com/eddieridwan/OpenSID/issues/621 telah ditambahkan penampilan tag html.

**Comment by eddieridwan** [comment]
@healm4n perbaikan sudah dicommit ke versi pra-rilis.

**Comment by healm4n** [comment]
Terima kasih pak
