### ISSUE TITLE
Error Tampilkan Data OpenSID pada Wordpress

### ISSUE THREAD

**Issue by siayi** [eddieridwan/OpenSID#628]
Saya [pengguna OpenSID yg diintegrasikan dengan wordpress](https://github.com/eddieridwan/OpenSID/wiki/Integrasikan-OpenSID-dan-SID-ke-web-Wrodpress)  dan menemukan error ketika menampilkan data OpenSID pada website sbb:
```
A PHP Error was encountered
Severity: Notice
Message: Only variable references should be returned by reference
Filename: core/Common.php
Line Number: 257
```

**Comment by hadyanwijaya** [comment]
buka file /donjo-sys/core/Common.php

pada baris ke 257 

ganti
return $_config[0] =& $config;

menjadi
$_config[0] =& $config;
return $_config[0];

**Comment by siayi** [comment]
pak @hadyanwijaya seperti yang sedang didiskusikan di pull request  https://github.com/eddieridwan/OpenSID/pull/619  ?

**Comment by hadyanwijaya** [comment]
itu masalah di CI 2, dengan cara seperti yang saya sebutkan tadi sudah
solved

**Comment by hadyanwijaya** [comment]
solved mohon ditutup issunya
