### ISSUE TITLE
Surat Keterangan Lahir: ayah mungkin tidak dalam database; tambah panjang/berat bayi

### ISSUE THREAD

**Issue by afri18** [eddieridwan/OpenSID#632]
1. untuk ayah bayi sebaiknya jangan auto, ada pilihan juga seperti saksi1 dan 2 termasuk ibu, karna tidak menutup kemungkinan ayahnya bukan dari desa (tidak ada dalam database)
2. panjang bayi dalam cm
3.berat bayi dalam kg > (0,00 kg)

**Comment by eddieridwan** [comment]
@afri18 : data panjang bayi dan berat bayi ditampilkan di surat/lampiran mana? Harap lampirkan contoh penampilan data itu.

**Comment by afri18** [comment]
![image](https://user-images.githubusercontent.com/6611881/30749932-276d72c2-9fdf-11e7-8352-4e45fa0ee085.png)

**Comment by bhien76** [comment]
ada tambahan bang @eddieridwan, pada bagian bawah. 
1. Titik-titik sebaiknya diganti dengan nama desa, tgl bln thn
2. Nama Pemohon bukan nama nama ibu kandungnya tapi nama pelapornya
3. Nama Pamong sama dengan nama pamong dan jabatan yang ada di form isian surat
![penandatangan](https://user-images.githubusercontent.com/28255642/30757019-a388370a-9fff-11e7-90e8-749e9971b300.jpg)

**Comment by eddieridwan** [comment]
Ini format yang telah diterapkan, berdasarkan contoh yang diberikan dulu:
![surat_ket_kelahiran_5201144301171725_2017-09-23_12399_lampiran 2](https://user-images.githubusercontent.com/249563/30772027-81084fd8-a097-11e7-8d61-264510650ef8.png)

Tapi format itu berbeda dengan F-201 yang baru dilampirkan @afri18:
![surat-keterangan-kelahiran-kode -f-201](https://user-images.githubusercontent.com/249563/30772046-9afebb8e-a097-11e7-831b-b0f9618bd3fb.png)

Yang mana yang benar? Harap segera beri penjelasan.

**Comment by eddieridwan** [comment]
Harap jelaskan:

- apakah pekerjaan seharusnya ditampilkan sebagai kode, bukan tulisan nama pekerjaan?
- apakah untuk bayi perlu ada baris NIK (tidak ada di F-201)
- apakah untuk Pelapor, Saksi 1 dan Saksi 2, kolom Umur perlu ada tgl/bln/thn, atau cukup umur saja (seperti di F-201 yang diunduh)?

**Comment by fathurvbf** [comment]
@eddieridwan itu stadar semua formnya om dan bisa digunakan semua, Kita lengkapi saja agar lebih lengkap karena form F-201 sebagai berkas pendukung terbit Akta kelahiran.
1. Pekerjaan Sebaiknya Tulisan Nama Pekerjaan
2. Pada baris bayi harus ada nik, apakah nanti akan diisi atau tidak tergantung dari administrator karena syarat terbit akta kelahiran harus ada NIK.
3. Form Saksi 1 dan 2 Bisa dimasukkan tgl/bln/thun serta umur agar lebih lengkap
4. Form Saksi 1 dan 2 sharusnya ada jenis kelamin agar identitas JK saksi diketahui

**Comment by afri18** [comment]
ini yg baru dari disdukcapil
[F-2.01_SURAT_KETERANGAN_KELAHIRAN.pdf](https://github.com/eddieridwan/OpenSID/files/1326611/F-2.01_SURAT_KETERANGAN_KELAHIRAN.pdf)
sebaiknya samakan dengan disdukcapil, misal pekerjaan > hanya kodepekerjaan atau kosongkan bila ragu

**Comment by bhien76** [comment]
saya setuju dengan bang @afri18 dan bang @fathurvbf. format surat sebaiknya mengikuti yang dari disdukcapil tentang.
1. Bayi harus ada niknya
2. Form Saksi 1 dan 2 Bisa dimasukkan tgl/bln/thun serta umur agar lebih lengkap
3. Form Saksi 1 dan 2 sharusnya ada jenis kelamin agar identitas JK saksi diketahui
4. Untuk Pekerjaan, sebaiknya ditulis kode pekerjaan di 2 kolom depan dan nama pekerjaan di kolom berikutnya
. 5. Kop Surat sebaiknya disamakan dengan yang dari disdukcapil
![kop akta kelahiran](https://user-images.githubusercontent.com/28255642/30774504-176c7a62-a0b6-11e7-9e8a-f36f656172cd.jpg)

**Comment by eddieridwan** [comment]
Jika berbeda dengan F-2.01 yang baku apakah akan diterima oleh Disdukcapil?

**Comment by bhien76** [comment]
Diterima bang @eddieridwan. bukankah selama ini format F-2.01 yang digunakan agak berbeda dengan format F-2.01 dari Disdukcapil? nyatanya tdak pernah ada yang bermasalah

**Comment by eddieridwan** [comment]
Dengan tambahan baris NIK bayi, dan jenis kelamin untuk pelapor dan saksi2, lampiran F-2.01 menjadi agak padat.  

Isian Kode Wilayah sementara dikosongkan, karena belum mendapat penjelasan apa isinya.

Sudah dicommit ke master.

**Comment by eddieridwan** [comment]
@bhien76 @afri18 : di kop lampiran F-2.01, Kode Wilayah diisi dengan data dari mana?

**Comment by eddieridwan** [comment]
Kalau kita lihat kode wilayah dari http://www.kemendagri.go.id/pages/data-wilayah, seperti di http://www.kemendagri.go.id/media/filemanager/2015/08/18/1/1/11._aceh_2.pdf, terlihat kode wilayah ada 10 digit (kode-provinsi.kode-kabupaten.kode-kecamatan.kode-desa), sedangkan kotak di F-2.01 hanya ada 9.

[11._aceh_2.pdf](https://github.com/eddieridwan/OpenSID/files/1327843/11._aceh_2.pdf)

**Comment by eddieridwan** [comment]
Mungkin sementara ini kita kosongkan saja. Juga karena belum tentu pengisian data identitas desa benar -- jadi biarkan dulu diisi oleh Disdukcapil. Mungkin nanti kita bisa tinjau lagi apabila kita bisa lebih yakin pengisian kode wilayah di identitas desa benar -- yaitu kita bisa cek akurasinya.

**Comment by bhien76** [comment]
ini bang @eddieridwan, kode kode wilayah yang diambil. 2 digit pertama kode propinsi, 2 digit berikutnya kode kabupaten, 2 digit berikutnya kode kecamatan, dan 4 digit berikutnya kode desa
![kode](https://user-images.githubusercontent.com/28255642/30796557-2bf88ef8-a205-11e7-8d5f-5b977170153b.jpg)

**Comment by eddieridwan** [comment]
Apakah yakin desa biasanya mengisi kode2 tersebut secara benar?

**Comment by afri18** [comment]
sebaiknya kosongkan aja, kadang kode desa nggak 4 digit, contoh prodeskel, usernya adalah kode desa sampai provinsi, tapi bukan 2009 (4 digit)
belum valid antar disduk, depdagriprodeskel, dan instansilainnya, yg valid baru sampai tingkat kecamatan

**Comment by eddieridwan** [comment]
Jika ada kerancuan/keraguan, lebih baik dikosongkan dulu. Nanti bisa ditambahkan kalau sudah lebih mapan penggunaan kode wilayah.

**Comment by sugiantoe** [comment]
maaf mas @afri18, setahu kami kode registrsi di prodeskel bukan kode desa. kode desa adalah kode PUM.
