### ISSUE TITLE
Bug: Layanan mandiri tidak bisa cetak Kartu Keluarga atau Biodata

### ISSUE THREAD

**Issue by meiki** [eddieridwan/OpenSID#645]
Pada Layanan Mandiri, ketika dilakukan cetak Kartu keluarga & cetak biodata.. muncul halaman dengan pesan database error 500. Error Number: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ORDER BY `urut`' at line 5

SELECT * FROM (`setting_modul`) WHERE `aktif` = 1 AND `level` >= ORDER BY `urut`

Filename: /Applications/MAMP/htdocs/OpenSID/models/modul_model.php

Line Number: 24

![screen shot 2017-10-03 at 9 06 07 pm](https://user-images.githubusercontent.com/3370238/31129745-ab73a638-a87f-11e7-8b38-da1ff5ae35a4.png)

**Comment by eddieridwan** [comment]
Terima kasih telah melaporkan. 
Sudah dicommit ke master. Bisa diunduh dari pra-rilis.
