### ISSUE TITLE
Double sub menu perdes, sk kepala desa di admin web dengan di menu baru sekretariat

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [eddieridwan/OpenSID#646]
dengan adanya penambahan menu baru maslah sekretariat seperti gambar dibawah ini
![image](https://user-images.githubusercontent.com/25834335/31223226-75876f28-a97e-11e7-9dfd-f083e6207aa0.png)

maka di menu admin web di sub menu dokumen 
![image](https://user-images.githubusercontent.com/25834335/31223243-83e121c2-a97e-11e7-85e3-712cb344f899.png)
menurut saya ini double dan alangkah baiknya di hapus saja saja sub menu dokumen yang ada di admin web

**Comment by metalab25** [comment]
Memang untuk yang di Admin Web harusnya hanya Dokumen Umum saja sedangkan Dokumen yang sifatnya pemerintahan desa dimasukan ke Sekretariat

**Comment by eddieridwan** [comment]
Sudah dicommit ke master melalui PR #662
