### ISSUE TITLE
Fitur: Sediakan fungsi Import excel yang menambah data, tidak menimpa yang sudah ada

### ISSUE THREAD

**Issue by siayi** [eddieridwan/OpenSID#65]
Untuk mengatasi Import excel gagal apabila jumlah data terlalu besar #23 , saya mencoba membagi File Excel menjadi beberapa bagian, sehingga ukuran filenya menjadi lebih kecil.

File excel yang berukuran lebih kecil berhasil diimport, namun ketika import file berikutnya ternyata data import sebelumnya hilang alias tertimpa dengan file import terakhir.

Hal ini menyebabkan fasilitas import excel tidak bisa digunakan karena jumlah data yang kami import ukurannya datanya besar.

**Comment by siayi** [comment]
Informasi tambahan,,
saya coba import excel pada aplikasi SID CRI original (hasil download dari sid.web.id) ternyata import sukses tidak gagal seperti masalah #23 .

**Comment by batudaa** [comment]
SID CRI dan OpenSID Menggunakan konfigurasi PHP yang sama?
Kalau beda coba bandingkan nilai konfigurasi PHP untuk 'upload_max_filesize'

**Comment by eddieridwan** [comment]
Kami akan memulai membuat fitur menambah data melalui import excel, dan tidak menghilangkan data yang sudah ada.

Pseudo-codenya seperti ini:

function import_excel_tambah() {
		// cek upload berhasil
		// -- proses ber baris
			// -- penduduk baru
				// masukkan baris ke tabel penduduk
				// -- proses data keluarga apabila ada no_kk
					// buat keluarga baru kalau no_kk belum ada
					// 		kepala keluarga dikosongkan apabila baris ini bukan kepala keluarga
					// tambahkan ke keluarga kalau no_kk sudah ada
					// 		ganti kepala keluarga apabila baris ini kepala keluarga
			// -- penduduk sudah ada
				// -- ubah data penduduk yang sudah ada
				// -- proses data keluarga apabila ada no_kk
					// -- ubah keluarga apabila berbeda
						// buat keluarga baru kalau no_kk belum ada
						// 		masukkan kepala keluarga sementara apabila baris in bukan kepala keluarga
						// tambahkan ke keluarga kalau no_kk sudah ada
						// 		ganti kepala keluarga apabila baris ini kepala keluarga
					// -- keluarga sama
						// ganti hubungan dalam keluarga kalau berbeda
	}

Proses ini sekali pass saja, tidak seperti import_excel saat ini yang mengisi tabel impor dulu. 
Proses ini bisa menghasilkan keluarga tanpa kepala keluarga. Karena itu semua fungsi SID yang menampilkan kepala keluarga perlu diubah untuk bisa menangani keluarga yang belum kepala keluarganya belum terrekam.

**Comment by eddieridwan** [comment]
Sudah di commit untuk dirilis di v0.8.
