### ISSUE TITLE
Gambar untuk wiki OpenSID 1

### ISSUE THREAD

**Issue by eddieridwan** [eddieridwan/OpenSID#66]
Issue ini hanya untuk meng-upload gambar yang dipakai di wiki OpenSID.

Folder desa:
![folder-desa](https://cloud.githubusercontent.com/assets/249563/16940193/a6715bf6-4dba-11e6-95cb-73db22a9612e.jpg)

**Comment by eddieridwan** [comment]
<img width="541" alt="folder desa-contoh" src="https://cloud.githubusercontent.com/assets/249563/16940270/3ab78600-4dbb-11e6-8234-23ccd034838f.png">

**Comment by buchary** [comment]
![download xampp](https://cloud.githubusercontent.com/assets/20512335/16940465/c361ec2e-4dbc-11e6-88eb-dc107f06c3fb.png)
![xampp 2](https://cloud.githubusercontent.com/assets/20512335/16940466/c366efc6-4dbc-11e6-81c3-d7c602849b54.png)
![xampp 3](https://cloud.githubusercontent.com/assets/20512335/16940467/c3691b84-4dbc-11e6-805d-78ca89979e6e.png)
![xampp 4](https://cloud.githubusercontent.com/assets/20512335/16940469/c36ad0d2-4dbc-11e6-8f2f-2427e5e65676.png)
![xampp 5](https://cloud.githubusercontent.com/assets/20512335/16940470/c36ce82c-4dbc-11e6-8a5e-35c1b3dfdf65.png)
![xampp](https://cloud.githubusercontent.com/assets/20512335/16940471/c36edef2-4dbc-11e6-9d3c-b434ec05fd21.png)

**Comment by buchary** [comment]
![download opensid](https://cloud.githubusercontent.com/assets/20512335/16964981/962f6118-4e30-11e6-8702-7a9aea2813e9.png)

**Comment by buchary** [comment]
![download opensid2](https://cloud.githubusercontent.com/assets/20512335/16965148/69718bd2-4e31-11e6-93fb-fbe55015ceaf.png)

**Comment by buchary** [comment]
![xampp](https://cloud.githubusercontent.com/assets/20512335/16966334/b11a7f34-4e36-11e6-8862-1c89840a2f65.png)

**Comment by buchary** [comment]
![htdoc](https://cloud.githubusercontent.com/assets/20512335/16966353/c7b68846-4e36-11e6-8f49-749b8d01731b.png)

**Comment by saprudinote** [comment]
![import](https://cloud.githubusercontent.com/assets/20571259/17016751/0a02906e-4f63-11e6-8e5e-75a4b776d8c0.png)

**Comment by buchary** [comment]
![halaman keluarga](https://cloud.githubusercontent.com/assets/20512335/17048685/6816d7a2-501a-11e6-9540-8a90430597bb.png)

**Comment by Jhonysuryadi** [comment]
![judul home desa](https://cloud.githubusercontent.com/assets/20592788/17050074/8d4ca688-5023-11e6-8bea-54682b64b78b.png)

**Comment by Jhonysuryadi** [comment]
![gambar](https://cloud.githubusercontent.com/assets/20592788/17201312/dd0a71d2-54bf-11e6-854f-f93e4e59b861.png)

**Comment by YuwanFanani** [comment]
![gambar1](https://cloud.githubusercontent.com/assets/20694977/17206326/bd29b446-54e1-11e6-831c-f7ad4382c45d.png)

**Comment by YuwanFanani** [comment]
![xxxxx](https://cloud.githubusercontent.com/assets/20694977/17207188/ea16b7fc-54e5-11e6-9ac9-4a8af9d54fdb.png)

**Comment by YuwanFanani** [comment]
![ccccc](https://cloud.githubusercontent.com/assets/20694977/17207432/2739608e-54e7-11e6-8ce8-8bc26ea496a2.png)

**Comment by YuwanFanani** [comment]
![mmm](https://cloud.githubusercontent.com/assets/20694977/17207839/ec2da0fc-54e8-11e6-9353-d9ccba83c225.png)

**Comment by buchary** [comment]
![menu statis](https://cloud.githubusercontent.com/assets/20512335/17277676/4f9c0dec-577b-11e6-979a-7c046c1fae98.png)

**Comment by buchary** [comment]
![halaman cetak surat](https://cloud.githubusercontent.com/assets/20512335/17277695/b6126d46-577b-11e6-995f-8ed2f66d72e9.png)

**Comment by buchary** [comment]
![surat keterangan](https://cloud.githubusercontent.com/assets/20512335/17277704/f93baad8-577b-11e6-8632-27d52ed1accb.png)

**Comment by buchary** [comment]
![tambah menu statis](https://cloud.githubusercontent.com/assets/20512335/17277788/5cd585ee-577e-11e6-829f-4504232cbaa0.png)

**Comment by buchary** [comment]
![edit menu](https://cloud.githubusercontent.com/assets/20512335/17277883/8e177ea8-5780-11e6-9c40-14b69c5ab676.png)

**Comment by Jhonysuryadi** [comment]
![gambar01](https://cloud.githubusercontent.com/assets/20592788/17278133/9b69819e-5787-11e6-807d-f93026a10b56.png)

**Comment by buchary** [comment]
![artikel statis](https://cloud.githubusercontent.com/assets/20512335/17278220/679546f2-578a-11e6-9d7f-e99d1934d210.png)

**Comment by buchary** [comment]
![tambah artikel statis](https://cloud.githubusercontent.com/assets/20512335/17278295/66bbdb68-578c-11e6-92dd-d24c41ac951b.png)

**Comment by buchary** [comment]
![isi artikel](https://cloud.githubusercontent.com/assets/20512335/17278324/4242598c-578d-11e6-888f-a4f5584dd376.png)

**Comment by Jhonysuryadi** [comment]
![gambar07](https://cloud.githubusercontent.com/assets/20592788/17278401/4afe8cce-578f-11e6-8295-804ce364a5b3.png)

**Comment by Jhonysuryadi** [comment]
![artikel dinamis](https://cloud.githubusercontent.com/assets/20592788/17303780/be719280-5854-11e6-8d32-43adde976a29.png)

**Comment by Jhonysuryadi** [comment]
![membuat artikel](https://cloud.githubusercontent.com/assets/20592788/17304143/b64aa126-5856-11e6-83fc-5c686dfa634b.png)

**Comment by Jhonysuryadi** [comment]
![contoh artikel](https://cloud.githubusercontent.com/assets/20592788/17304279/748f4358-5857-11e6-8349-63fb8452faff.png)

**Comment by eddieridwan** [comment]
![form-isian-surat](https://cloud.githubusercontent.com/assets/249563/17328547/dfbf27ee-58f0-11e6-867e-20ef6192257e.jpg)
![tampilan-kode-isian](https://cloud.githubusercontent.com/assets/249563/17328549/dfc5c8d8-58f0-11e6-8686-d6fe0a18ae60.jpg)
![tampilkan-kode-isian](https://cloud.githubusercontent.com/assets/249563/17328548/dfc4a9f8-58f0-11e6-83bd-b7aa77e4a002.jpg)

**Comment by eddieridwan** [comment]
Artikel statistik:

![menu-statis](https://cloud.githubusercontent.com/assets/249563/17355872/5693effe-5986-11e6-887b-3711787e8177.jpg)
![menu-statistik](https://cloud.githubusercontent.com/assets/249563/17355873/56972dcc-5986-11e6-93ad-ca0edb2dec88.jpg)
![submenu-statistik](https://cloud.githubusercontent.com/assets/249563/17355874/56985c6a-5986-11e6-86d5-2f2c694bfb47.jpg)
![tambahkan-menu-statistik](https://cloud.githubusercontent.com/assets/249563/17355875/569eef4e-5986-11e6-8c71-ba966e823e02.jpg)

**Comment by buchary** [comment]
![download release terbaru](https://cloud.githubusercontent.com/assets/20512335/17388411/8da7a41a-5a2e-11e6-8930-52d6b2f8df30.png)

**Comment by eddieridwan** [comment]
Ganti Lokasi Desa

![ganti-lokasi-kantor-desa](https://cloud.githubusercontent.com/assets/249563/17394178/4ac790f2-5a5a-11e6-9e06-d2442e195b01.jpg)

**Comment by eddieridwan** [comment]
Google API
![dapatkan-google-api-key](https://cloud.githubusercontent.com/assets/249563/17460963/11b41cbc-5cae-11e6-8b52-c57c64a7e7f5.jpg)

**Comment by eddieridwan** [comment]
Administrasi Web
![unsur-tampilan-website](https://cloud.githubusercontent.com/assets/249563/17466325/f2903d9c-5d3f-11e6-840b-1f66d4e194de.jpg)

**Comment by eddieridwan** [comment]
Import Excel
![file-untuk-diimport](https://cloud.githubusercontent.com/assets/249563/17589492/bcd02cb0-6007-11e6-95fe-aa50366d051a.jpg)
![laman-import-excel](https://cloud.githubusercontent.com/assets/249563/17589493/bcd1a662-6007-11e6-9b5f-32730e811cd7.jpg)
![pilih-file-untuk-diimport](https://cloud.githubusercontent.com/assets/249563/17589495/bcd7fc9c-6007-11e6-848a-52841a6d79f5.jpg)

**Comment by Jhonysuryadi** [comment]
![01](https://cloud.githubusercontent.com/assets/20592788/17737682/be0bb762-64c0-11e6-8e9e-9037b34fd28d.png)

**Comment by Jhonysuryadi** [comment]
![02](https://cloud.githubusercontent.com/assets/20592788/17738410/bb103698-64c3-11e6-82f1-951614690738.png)

**Comment by buchary** [comment]
![database](https://cloud.githubusercontent.com/assets/20512335/17797686/76cb48a2-65fd-11e6-9b24-bbbf15b2a00f.png)

**Comment by buchary** [comment]
![xampp](https://cloud.githubusercontent.com/assets/20512335/17800841/f9ec3bea-6618-11e6-988e-7c4c67d04916.png)

**Comment by buchary** [comment]
![php](https://cloud.githubusercontent.com/assets/20512335/17801703/311bb172-661e-11e6-95de-ac4cf2d2f1c0.png)

**Comment by eddieridwan** [comment]
Modul Administrasi
![tautan-modul-administrasi](https://cloud.githubusercontent.com/assets/249563/17801803/ce5ffe7a-661e-11e6-9970-e949b9aef287.jpg)

**Comment by Jhonysuryadi** [comment]
![identitas desa](https://cloud.githubusercontent.com/assets/20592788/17802341/5325e9aa-6622-11e6-8c73-45049d3ce581.png)

**Comment by buchary** [comment]
![import data](https://cloud.githubusercontent.com/assets/20512335/17802583/9e8075c2-6623-11e6-939b-49ebefadee7a.png)

**Comment by Jhonysuryadi** [comment]
![hom](https://cloud.githubusercontent.com/assets/20592788/17802721/8ddc8bba-6624-11e6-8e36-a2b53b43423b.png)

**Comment by Jhonysuryadi** [comment]
![home sid](https://cloud.githubusercontent.com/assets/20592788/17802949/ddff692c-6625-11e6-8291-ab2a1be9cd79.png)

**Comment by buchary** [comment]
![aaa](https://cloud.githubusercontent.com/assets/20512335/17802815/fbc43592-6624-11e6-8849-b54ff7738869.png)

**Comment by Jhonysuryadi** [comment]
![go](https://cloud.githubusercontent.com/assets/20592788/17803452/17528486-6629-11e6-8a32-edff816069c0.png)

**Comment by eddieridwan** [comment]
Panduan

![cari-halaman-berisi-kata](https://cloud.githubusercontent.com/assets/249563/18052096/055ceece-6e2b-11e6-9aaa-b83bde2cf3d7.jpg)
![cari-nama-halaman-panduan](https://cloud.githubusercontent.com/assets/249563/18052094/055b613a-6e2b-11e6-8a31-287bbfc555f5.jpg)
![tautan-panduan](https://cloud.githubusercontent.com/assets/249563/18052095/055bfb2c-6e2b-11e6-82c9-8f137a5b0b89.jpg)

**Comment by eddieridwan** [comment]
Issue install

![image](https://cloud.githubusercontent.com/assets/249563/18076850/d4f9d6be-6eb3-11e6-8073-27ba40e81eb4.png)

**Comment by eddieridwan** [comment]
Data Keluarga

![cari-nama-kepala-keluarga](https://cloud.githubusercontent.com/assets/249563/18089201/5b712034-6ef1-11e6-8878-026d26f29d59.jpg)
![cetak-daftar-keluarga](https://cloud.githubusercontent.com/assets/249563/18089204/5b72e950-6ef1-11e6-8aae-6003e6f9cd35.jpg)
![daftar-anggota-keluarga](https://cloud.githubusercontent.com/assets/249563/18089202/5b71b36e-6ef1-11e6-982e-2b7d69172a22.jpg)
![hapus-keluarga](https://cloud.githubusercontent.com/assets/249563/18089200/5b6f435e-6ef1-11e6-8f61-94d04c2fc5d4.jpg)
![hasil-cetak-daftar-keluarga](https://cloud.githubusercontent.com/assets/249563/18089203/5b725080-6ef1-11e6-93cb-fb6cf9f5dafc.jpg)
![isi-data-keluarga](https://cloud.githubusercontent.com/assets/249563/18089205/5b77ae7c-6ef1-11e6-9901-108c13a654fd.jpg)
![kartu-keluarga](https://cloud.githubusercontent.com/assets/249563/18089759/1c64fb74-6ef4-11e6-83f4-ad38f130e1aa.jpg)
![halaman-keluarga](https://cloud.githubusercontent.com/assets/249563/18089967/093c4844-6ef5-11e6-8664-1e2141eb7c67.jpg)
![tambah-keluarga-baru](https://cloud.githubusercontent.com/assets/249563/18090057/8f3277ac-6ef5-11e6-8b5d-67c37679f605.jpg)

![pemilahan-keluarga](https://cloud.githubusercontent.com/assets/249563/18089206/5ba402ec-6ef1-11e6-8c05-3bbc95f2d23c.jpg)
![pindah-keluarga-di-desa](https://cloud.githubusercontent.com/assets/249563/18089211/5baad8e2-6ef1-11e6-8880-45c689aac6f6.jpg)
![status-keikutsertaan-program](https://cloud.githubusercontent.com/assets/249563/18089209/5ba87a84-6ef1-11e6-830a-c2a820fb4e23.jpg)
![tambah-anggota-keluarga](https://cloud.githubusercontent.com/assets/249563/18089208/5ba7035c-6ef1-11e6-8fc3-e18a87b806d0.jpg)
![tambah-keluarga-dari-penduduk-lepas](https://cloud.githubusercontent.com/assets/249563/18089210/5baa6204-6ef1-11e6-9dfa-69f0ed079d91.jpg)
![tampilkan-daftar-anggota-keluarga](https://cloud.githubusercontent.com/assets/249563/18089213/5bd8691a-6ef1-11e6-881a-2a6cf4cbb7b9.jpg)
![tampilkan-kartu-keluarga](https://cloud.githubusercontent.com/assets/249563/18089212/5bd54956-6ef1-11e6-8e90-27502ae27baa.jpg)

**Comment by eddieridwan** [comment]
Laman Penduduk
![halaman-penduduk](https://cloud.githubusercontent.com/assets/249563/18110913/e191a40c-6f4d-11e6-8285-f63779d98d84.jpg)

**Comment by eddieridwan** [comment]
![hapus-beberapa-penduduk](https://cloud.githubusercontent.com/assets/249563/18116104/8d426330-6f77-11e6-8568-d36d5030195b.jpg)
![hapus-penduduk](https://cloud.githubusercontent.com/assets/249563/18116105/8d8bc1e2-6f77-11e6-9017-ac549542d923.jpg)
![ubah-status-dasar-penduduk](https://cloud.githubusercontent.com/assets/249563/18116106/8da6cd52-6f77-11e6-99c4-fae0c8b9929d.jpg)
![ubah-biodata-penduduk](https://cloud.githubusercontent.com/assets/249563/18116107/8daa1ce6-6f77-11e6-929a-630206470525.jpg)

**Comment by eddieridwan** [comment]
![hasil-cetak-penduduk](https://cloud.githubusercontent.com/assets/249563/18119049/3357ac2c-6f8b-11e6-9460-3e6c3c315382.jpg)
![cetak-penduduk](https://cloud.githubusercontent.com/assets/249563/18119050/3357d8d2-6f8b-11e6-8ca8-e6c6d59cecfd.jpg)
![memilah-penduduk](https://cloud.githubusercontent.com/assets/249563/18119048/33578d82-6f8b-11e6-90a9-76ba6bba53aa.jpg)
![cari-penduduk-berdasarkan-nama](https://cloud.githubusercontent.com/assets/249563/18119052/33609cba-6f8b-11e6-81c6-c1320d5db972.jpg)
![tampilan-biodata-penduduk](https://cloud.githubusercontent.com/assets/249563/18119051/336010b0-6f8b-11e6-865d-83cbf3c075e2.jpg)

**Comment by Jhonysuryadi** [comment]
![gambar 2](https://cloud.githubusercontent.com/assets/20592788/18192389/6d50e214-7106-11e6-9889-4fcf2f4e5874.png)

**Comment by eddieridwan** [comment]
Galeri

![memilah-album](https://cloud.githubusercontent.com/assets/249563/18194830/062d62c8-711b-11e6-834e-e227022fb0fe.jpg)
![cari-album-berdasarkan-nama](https://cloud.githubusercontent.com/assets/249563/18194832/0633b682-711b-11e6-83ab-e75be994e3f3.jpg)
![hapus-beberapa-album](https://cloud.githubusercontent.com/assets/249563/18194833/06346f6e-711b-11e6-940a-7d25ce857158.jpg)
![form-ubah-data-album](https://cloud.githubusercontent.com/assets/249563/18194831/06324c20-711b-11e6-9c05-1a399211cc54.jpg)
![tampilkan-gambar-album](https://cloud.githubusercontent.com/assets/249563/18194834/06366850-711b-11e6-826e-ca2e1f8ff12a.jpg)
![aktifkan-album](https://cloud.githubusercontent.com/assets/249563/18194835/0636ae50-711b-11e6-9843-40b4ce7adf5a.jpg)
![tombol-hapus-album](https://cloud.githubusercontent.com/assets/249563/18194836/065b4abc-711b-11e6-82d5-45deefd856e9.jpg)
![tombol-ubah-data-album](https://cloud.githubusercontent.com/assets/249563/18194837/06610c4a-711b-11e6-9f88-884a8d72f7f9.jpg)
![form-tambah-album-baru](https://cloud.githubusercontent.com/assets/249563/18194838/0662d5e8-711b-11e6-841f-b503587e7908.jpg)
![widget-galeri](https://cloud.githubusercontent.com/assets/249563/18194839/06652780-711b-11e6-8b6a-b002e7e9e45a.jpg)
![laman-galeri](https://cloud.githubusercontent.com/assets/249563/18194840/0668f41e-711b-11e6-8e95-dcc4859121f7.jpg)
![tambah-album-baru](https://cloud.githubusercontent.com/assets/249563/18194841/0669c3da-711b-11e6-94bb-3df2bae08693.jpg)

**Comment by eddieridwan** [comment]
Gambar dalam album galeri

![memilah-gambar](https://cloud.githubusercontent.com/assets/249563/18196504/637f3132-7124-11e6-9621-38844866a7b1.jpg)
![cari-gambar-berdasarkan-nama](https://cloud.githubusercontent.com/assets/249563/18196505/6381bdda-7124-11e6-8313-67ebadc858b3.jpg)
![hapus-beberapa-gambar](https://cloud.githubusercontent.com/assets/249563/18196507/63843eca-7124-11e6-9920-a3a85b6c7144.jpg)
![form-ubah-gambar](https://cloud.githubusercontent.com/assets/249563/18196506/6382303a-7124-11e6-9a93-e9ce56b99707.jpg)
![aktifkan-gambar](https://cloud.githubusercontent.com/assets/249563/18196508/6386eaf8-7124-11e6-8a4c-91a905ccbe14.jpg)
![hapus-gambar](https://cloud.githubusercontent.com/assets/249563/18196509/638ae19e-7124-11e6-9b4d-7a7bc3059cfd.jpg)
![tombol-ubah-gambar](https://cloud.githubusercontent.com/assets/249563/18196511/63b6da92-7124-11e6-8e87-14b361dd1d65.jpg)
![form-tambah-gambar-baru](https://cloud.githubusercontent.com/assets/249563/18196512/63b6ef46-7124-11e6-8161-da3b6c6b3da3.jpg)
![tombol-tambah-gambar-baru](https://cloud.githubusercontent.com/assets/249563/18196510/63b5a2da-7124-11e6-9e3c-bba19163ef2c.jpg)
![tabel-gambar-dalam-album](https://cloud.githubusercontent.com/assets/249563/18196513/63ba14e6-7124-11e6-92ef-9d6e505b4eaf.jpg)

**Comment by Jhonysuryadi** [comment]
![gambar3](https://cloud.githubusercontent.com/assets/20592788/18204140/afa19388-714d-11e6-8064-e49c7e9f06d9.png)

**Comment by Jhonysuryadi** [comment]
![pemerintah desa](https://cloud.githubusercontent.com/assets/20592788/18205086/c423033c-7152-11e6-9ba3-a5155c98ab44.png)

**Comment by Jhonysuryadi** [comment]
![pengisian](https://cloud.githubusercontent.com/assets/20592788/18205128/f2a272a6-7152-11e6-957d-9f32a963815d.png)

**Comment by eddieridwan** [comment]
Teks berjalan
![teks-berjalan](https://cloud.githubusercontent.com/assets/249563/18245570/8efcde60-7398-11e6-96de-03440e79cebf.jpg)
![tambah-artikel-teks-berjalan](https://cloud.githubusercontent.com/assets/249563/18245571/8f00a220-7398-11e6-880a-fc0cf1f2b3a4.jpg)
![tambah-kategori-menu-dinamis](https://cloud.githubusercontent.com/assets/249563/18245572/8f012ab0-7398-11e6-9c95-0367164264d8.jpg)

**Comment by eddieridwan** [comment]
Cetak surat
![form-surat](https://cloud.githubusercontent.com/assets/249563/18459333/3687efa0-799b-11e6-8ca9-78d833d83352.png)

**Comment by eddieridwan** [comment]
Layanan Mandiri
![memilah-laporan-layanan-mandiri](https://cloud.githubusercontent.com/assets/249563/18511794/6e150f8e-7ab8-11e6-819a-290ab885a5de.jpg)
![cari-laporan-layanan-mandiri](https://cloud.githubusercontent.com/assets/249563/18511795/6e18dd44-7ab8-11e6-859e-1645e85af8d0.jpg)
![hapus-beberapa-laporan](https://cloud.githubusercontent.com/assets/249563/18511796/6e19d8f2-7ab8-11e6-834b-6ac9b5585b02.jpg)
![hapus-satu-laporan](https://cloud.githubusercontent.com/assets/249563/18511797/6e1e1048-7ab8-11e6-8ab2-9b3289b7f30c.jpg)
![tindak-lanjuti-laporan](https://cloud.githubusercontent.com/assets/249563/18511799/6e1e7722-7ab8-11e6-8e34-cde8d9d7afd1.jpg)
![laman-laporan-masuk](https://cloud.githubusercontent.com/assets/249563/18511798/6e1e3b90-7ab8-11e6-81ac-8b39eb5e7b7a.jpg)
![hapus-pengguna-layanan-mandiri](https://cloud.githubusercontent.com/assets/249563/18511801/6e5e136e-7ab8-11e6-9f28-6ae8823f02b7.jpg)
![tambah-pengguna-layanan-mandiri](https://cloud.githubusercontent.com/assets/249563/18511800/6e5d560e-7ab8-11e6-8a5b-77c395fbed31.jpg)

**Comment by eddieridwan** [comment]
Komentar
![memilah-komentar](https://cloud.githubusercontent.com/assets/249563/18632480/32217ea4-7eaa-11e6-969a-7ff4328e637d.jpg)
![mencari-komentar](https://cloud.githubusercontent.com/assets/249563/18632477/321d8fba-7eaa-11e6-8e25-6f5046e508a3.jpg)
![hapus-beberapa-komentar](https://cloud.githubusercontent.com/assets/249563/18632478/321f0b88-7eaa-11e6-9a71-bc3c59987b7b.jpg)
![hapus-satu-komentar](https://cloud.githubusercontent.com/assets/249563/18632479/32216c70-7eaa-11e6-862f-1abd7ddc0e45.jpg)
![form-mengubah-komentar](https://cloud.githubusercontent.com/assets/249563/18632481/32237c9a-7eaa-11e6-8d91-8ae364d5fdac.jpg)
![tombol-mengubah-komentar](https://cloud.githubusercontent.com/assets/249563/18632482/32264bf0-7eaa-11e6-8f46-e83263e55feb.jpg)
![aktifkan-komentar](https://cloud.githubusercontent.com/assets/249563/18632483/324c831a-7eaa-11e6-84e8-3c3f39014282.jpg)
![form-komentar-artikel](https://cloud.githubusercontent.com/assets/249563/18632484/324f543c-7eaa-11e6-975b-eef2185b5c98.jpg)
![laman-komentar](https://cloud.githubusercontent.com/assets/249563/18632485/325172f8-7eaa-11e6-993b-cef00f885e7b.jpg)

**Comment by eddieridwan** [comment]
Onlinekan SID

![ubah-setting-akses-database](https://cloud.githubusercontent.com/assets/249563/18671668/8b874992-7f77-11e6-94e7-d280334736df.jpg)
![pakai-code-editor](https://cloud.githubusercontent.com/assets/249563/18671664/8b815406-7f77-11e6-9f1f-97657753b9cc.jpg)
![folder-desa](https://cloud.githubusercontent.com/assets/249563/18671665/8b8553d0-7f77-11e6-91da-be1e6c84e4ef.jpg)
![extract-script-opensid](https://cloud.githubusercontent.com/assets/249563/18671666/8b85c892-7f77-11e6-870f-c91e04da79c3.jpg)
![unggah-script-opensid](https://cloud.githubusercontent.com/assets/249563/18671667/8b863fb6-7f77-11e6-8d21-f8eec06c5113.jpg)
![fitur-file-manager](https://cloud.githubusercontent.com/assets/249563/18671669/8b8f4cf0-7f77-11e6-9bba-334c7ea5e2ce.jpg)
![impor-file-backup](https://cloud.githubusercontent.com/assets/249563/18671671/8bb34cc2-7f77-11e6-9c3b-fbf0f58f9e70.jpg)
![phpmyadmin-di-cpanel](https://cloud.githubusercontent.com/assets/249563/18671672/8bb87a6c-7f77-11e6-98ae-1b0be8750301.jpg)
![beri-user-hak-akses](https://cloud.githubusercontent.com/assets/249563/18671673/8bbb2bd6-7f77-11e6-8bfe-be18fc29249c.jpg)
![tambahkan-user-ke-database](https://cloud.githubusercontent.com/assets/249563/18671674/8bbb7762-7f77-11e6-9739-ca1fb4c3ddfc.jpg)
![buat-user-database](https://cloud.githubusercontent.com/assets/249563/18671676/8bc5e058-7f77-11e6-8efa-7e0336561f86.jpg)
![buat-database](https://cloud.githubusercontent.com/assets/249563/18671675/8bc5a2d2-7f77-11e6-9234-92036e62d237.jpg)
![fitur-mysql](https://cloud.githubusercontent.com/assets/249563/18671678/8bea3732-7f77-11e6-87d6-61cc7d916a41.jpg)
![fitur-tambah-alias](https://cloud.githubusercontent.com/assets/249563/18671677/8bea1f5e-7f77-11e6-9780-4987c20cb19b.jpg)
![tambah-domain-alias](https://cloud.githubusercontent.com/assets/249563/18671679/8befe736-7f77-11e6-8976-716e4b072f1d.jpg)

**Comment by buchary** [comment]
![backup](https://cloud.githubusercontent.com/assets/20512335/18682889/9188fd9e-7fa0-11e6-81ec-28bd22149109.png)

**Comment by buchary** [comment]
![restore](https://cloud.githubusercontent.com/assets/20512335/18683687/d52dfbc8-7fa3-11e6-9d1e-0cf055724621.png)

**Comment by buchary** [comment]
![restore2](https://cloud.githubusercontent.com/assets/20512335/18684813/2a5b0b3c-7fa8-11e6-9cc2-2bda92cfc560.png)

**Comment by eddieridwan** [comment]
Menu administrasi
![menu-administrasi](https://cloud.githubusercontent.com/assets/249563/18900041/6adf1dec-8570-11e6-978b-3e0633dd75da.jpg)
![tombol-statistik](https://cloud.githubusercontent.com/assets/249563/18900332/f8403912-8572-11e6-92a8-26612f4e8c5a.jpg)

**Comment by eddieridwan** [comment]
Widget
![ubah-urutan-widget](https://cloud.githubusercontent.com/assets/249563/18904524/fd5379dc-8590-11e6-9560-50ee9a190bd8.jpg)
![tombol-ubah-widget](https://cloud.githubusercontent.com/assets/249563/18904523/fd51be12-8590-11e6-8606-37f23bcf8298.jpg)
![hapus-satu-widget](https://cloud.githubusercontent.com/assets/249563/18904527/fd5862d0-8590-11e6-983a-3f993bc23f95.jpg)
![aktifkan-widget](https://cloud.githubusercontent.com/assets/249563/18904525/fd561dea-8590-11e6-9bbd-20254c0512be.jpg)
![tombol-tambah-widget](https://cloud.githubusercontent.com/assets/249563/18904526/fd58589e-8590-11e6-8695-7f8531f54f17.jpg)
![laman-widget](https://cloud.githubusercontent.com/assets/249563/18904528/fd5e31ba-8590-11e6-8a42-987c844fce60.jpg)
![memilah-widget](https://cloud.githubusercontent.com/assets/249563/18905185/8d948fc4-8594-11e6-8a1b-11c71cddb38b.jpg)
![cari-widget](https://cloud.githubusercontent.com/assets/249563/18905187/8d981734-8594-11e6-9f86-076f0d5b45e5.jpg)
![hapus-beberapa-widget](https://cloud.githubusercontent.com/assets/249563/18905186/8d972c84-8594-11e6-8acc-201bcdb47e0d.jpg)

**Comment by eddieridwan** [comment]
Surat
![hapus-surat-keluar](https://cloud.githubusercontent.com/assets/249563/18911444/b9c1f4f4-85af-11e6-8c0f-68e36d2f6756.jpg)
![unduh-salinan-surat](https://cloud.githubusercontent.com/assets/249563/18911445/b9c3513c-85af-11e6-960f-ce2b5c0c25e4.jpg)
