### ISSUE TITLE
JENIS KOLOM NIK PADA HASIL EXPORT EXEL PENDUDUK

### ISSUE THREAD

**Issue by Jhiban-Khang** [eddieridwan/OpenSID#71]
DATA YANG DIHASILKAN PADA KOLOM NIK, TIDAK SECARA DEFAULT TEXT SEHINGGA TAMPAT ANEH WALAU DATA PADA SAAT DI KLIK SUDAH BENAR, MUNGKIN MASALH DEFAULT NUMBER

**Comment by eddieridwan** [comment]
Di bawah ini contoh hasil export excel penduduk. Kolom NIK tampil sebagai text, terbaca biasa. Anda mengalami masalah di OpenSID versi berapa?
[Penduduk (2).xls.zip](https://github.com/eddieridwan/OpenSID/files/387471/Penduduk.2.xls.zip)

**Comment by eddieridwan** [comment]
Anggap issue ini sudah tidak bermasalah lagi.
