### ISSUE TITLE
Bug: halaman tdk ditemukan waktu melapor pada layanan mandiri

### ISSUE THREAD

**Issue by eddieridwan** [eddieridwan/OpenSID#84]
Langkah:
1. di modul Admin, daftarkan seorang penduduk untuk Laporan > Layanan mandiri.
2. di modul Web, login sebagai penduduk tersebut di widget Layanan Mandiri.
3. di fungsi Laporan, isi form laporan dan kirim

Ada error halaman tdk ditemukan.

**Comment by aziztoo** [comment]
MOHON BIMBINGANNYA UNTUK MEMPERDALAM SID

**Comment by eddieridwan** [comment]
Sudah di-commit.
