### ISSUE TITLE
Notifikasi data berhasil  direstore

### ISSUE THREAD

**Issue by suhadrian** [eddieridwan/OpenSID#87]
setelah data berhasil direstore maka akan tampak seperti gambar berikut

![tampilan data direstor](https://cloud.githubusercontent.com/assets/20695005/17686639/7ca41e3c-6398-11e6-8b72-8b717e8e91be.png).

bagaimana caranya pada saat data berhasil direstor hanya menampilkan notifikasi berhasil bukan seperti gamabar diatas, terimakasih

**Comment by eddieridwan** [comment]
Perubahan yang dilakukan menampilkan script sql hanya apabila ditemukan error.

Sdh di-commit.
