### ISSUE TITLE
Bug: Tabel penduduk ada duplikat apabila penduduk pindah kembali lagi

### ISSUE THREAD

**Issue by eddieridwan** [eddieridwan/OpenSID#98]
Langkah yang diikuti:

1. di modul Administrasi, pergi ke laman Penduduk (klik Penduduk > Penduduk)
1. ubah status dasar seorang penduduk, misalnya 'Pindah', dengan catatan 'Pindah ke desa lain'
1. klik tombol Log Penduduk untuk pergi ke laman Log Penduduk. Penduduk yang berubah status dasarnya akan tampil di situ
1. edit status dasar penduduk tersebut kembali menjadi 'Hidup', untuk menunjukkan penduduk itu telah kembali ke desa, dengan catatan 'Kembali ke desa'
1. kembali ke laman Penduduk

Di laman Penduduk, penduduk yang kembali itu ditampilkan dua kali.

**Comment by afri18** [comment]
senelum ditambahkan memang dah seperti itu bung eddie, itu problem yang belum terpecahkan, jangan kan pidah datang lagi, kadang pindah dalam satu desa aja penduduk jadi muncul dua

**Comment by eddieridwan** [comment]
Ok, untuk penampilan duplikat di laman Penduduk sudah ketemu solusinya. Solusi ini akan juga menangani yang mati terus hidup lagi. Sedang di-tes, nanti kalau sdh ok akan di-commit. Untuk masalah terkait lainnya, lebih baik buat issue terpisah.

**Comment by afri18** [comment]
sebenarnya banyak bung, cuma satupersatu aja, ada juga issue/usulan ke cri, cuma lom ada jawaban, masih terkait data, saya perhatikan ternyata bung eddie sangat mampu dalam bahasa pemograman nanti saya  usulkan, tapi ma'af script nya hanya yg penting aja yg saya pakai

**Comment by eddieridwan** [comment]
Oke, solusi untuk issue ini sudah di-commit. Bisa di-unduh dari branch master di https://github.com/eddieridwan/OpenSID
